### ISSUE TITLE
Quiescing fails on Ubuntu 14.04 (with 4.4 kernel)

### ISSUE THREAD

**Issue by tmuncks** [vmware/open-vm-tools#101]
9.4.0, 9.4.6 and 10.0.0.7 and displays the same error on this VM.

The VM has NFS mounts and I initially though this would be the issue, but that does not appear to be the case however. I have been unsuccessful in getting meaningful debug-information from the quiescing process, so please let me know how to enable that.

This is what I'm getting (entire log from blank after open-vm-tools restart):
[Jul 16 20:47:04.457] [ message] [vmsvc] Log caching is enabled with maxCacheEntries=4096.
[Jul 16 20:47:04.457] [ message] [vmsvc] Core dump limit set to -1
[Jul 16 20:47:04.461] [ message] [vmsvc] Log caching is enabled with maxCacheEntries=4096.
[Jul 16 20:47:04.462] [ message] [vmsvc] Core dump limit set to -1
[Jul 16 20:47:04.462] [ message] [vmtoolsd] Tools Version: 10.0.7.52125 (build-3227872)
[Jul 16 20:47:04.462] [ warning] [GLib-GObject] Attempt to add property ToolsCoreService::tcs-app-ctx after class was initialised
[Jul 16 20:47:04.462] [ warning] [GLib-GObject] Attempt to add property ToolsCoreService::tcs-prop-thread-pool after class was initialised
[Jul 16 20:47:04.464] [ message] [vmtoolsd] Plugin 'hgfsServer' initialized.
[Jul 16 20:47:04.464] [ message] [vmtoolsd] Plugin 'vix' initialized.
[Jul 16 20:47:04.464] [ message] [vmtoolsd] Plugin 'deployPkg' initialized.
[Jul 16 20:47:04.466] [ message] [vmtoolsd] Plugin 'grabbitmqProxy' initialized.
[Jul 16 20:47:04.466] [ message] [vmtoolsd] Plugin 'guestInfo' initialized.
[Jul 16 20:47:04.466] [ message] [vmtoolsd] Plugin 'powerops' initialized.
[Jul 16 20:47:04.466] [ message] [vmtoolsd] Plugin 'timeSync' initialized.
[Jul 16 20:47:04.466] [ message] [vmtoolsd] Plugin 'vmbackup' initialized.
[Jul 16 20:47:04.467] [ message] [vix] VixTools_ProcessVixCommand: command 62
[Jul 16 20:47:04.522] [ message] [vix] ToolsDaemonTcloReceiveVixCommand: additionalError = 17
[Jul 16 20:47:04.531] [ message] [vix] VixTools_ProcessVixCommand: command 62
[Jul 16 20:47:04.531] [ message] [vix] ToolsDaemonTcloReceiveVixCommand: additionalError = 17
[Jul 16 20:47:12.488] [ warning] [vmbackup] Error freezing filesystems.

Also, the snapshot appears to error out just after reaching 40 or (at a single occasion) 50%

This is the only line that's repeated by retrying the snapshot:
[Jul 16 20:47:12.488] [ warning] [vmbackup] Error freezing filesystems.

Please help me enable proper debug logging so we can get this resolved :-)

/Thomas

**Comment by tmuncks** [comment]
Of course. Got debug logging working just as I posted this issue:

[Jul 16 21:00:34.656] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:00:34.857] [   debug] [vmsvc] RpcIn: received 5 bytes, content:"ping\00"
[Jul 16 21:00:34.857] [   debug] [vmsvc] RpcIn: sending 3 bytes
[Jul 16 21:00:35.108] [   debug] [vmsvc] RpcIn: received 16 bytes, content:"vmbackup.start 1"
[Jul 16 21:00:35.108] [   debug] [vmbackup] *** VmBackupStart
[Jul 16 21:00:35.108] [   debug] [vmbackup] Using quiesceApps = 1, quiesceFS = 1, allowHWProvider = 1, execScripts = 1, scriptArg = , timeout = 0, enableNullDriver = 1, forceQuiesce = 0
[Jul 16 21:00:35.108] [   debug] [vmbackup] Quiescing volumes: (null)
[Jul 16 21:00:35.108] [   debug] [vmbackup] *** VmBackup_SendEvent
[Jul 16 21:00:35.108] [   debug] [vmbackup] Sending vmbackup event: vmbackup.eventSet reset 0 
[Jul 16 21:00:35.108] [   debug] [vmsvc] RpcChannel: Sending: 27 bytes
[Jul 16 21:00:35.108] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:00:35.108] [   debug] [vmbackup] *** VmBackupStartScripts
[Jul 16 21:00:35.108] [   debug] [vmbackup] Trying to run scripts from /etc/vmware-tools/backupScripts.d
[Jul 16 21:00:35.108] [   debug] [vmsvc] RpcIn: sending 3 bytes
[Jul 16 21:00:36.109] [   debug] [vmbackup] *** VmBackupAsyncCallback
[Jul 16 21:00:36.109] [   debug] [vmbackup] VmBackupAsyncCallback: checking VmBackupOnFreeze
[Jul 16 21:00:36.109] [   debug] [vmbackup] Async request 'VmBackupOnFreeze' completed
[Jul 16 21:00:36.109] [   debug] [vmbackup] *** VmBackupEnableSyncWait
[Jul 16 21:00:36.109] [    info] [guestinfo] Poll loop for stats-interval disabled.
[Jul 16 21:00:36.109] [    info] [guestinfo] Poll loop for poll-interval disabled.
[Jul 16 21:00:36.109] [   debug] [vmbackup] Submitted backup start task.
[Jul 16 21:00:36.109] [   debug] [vmbackup] *** VmBackupSyncDriverStart
[Jul 16 21:00:36.110] [   debug] [vmsvc] SyncDriver: Skipping remote filesystem, name=10.60.251.77:/virtual/www, mntpt=/virtual/www.
[Jul 16 21:00:36.110] [   debug] [vmsvc] SyncDriver: Calling backend 0.
[Jul 16 21:00:36.110] [   debug] [vmsvc] SyncDriver: Freezing /:/proc:/sys:/sys/fs/cgroup:/sys/fs/fuse/connections:/sys/kernel/debug:/sys/kernel/security:/dev:/dev/pts:/run:/run/lock:/run/shm:/run/user:/sys/fs/pstore:/var/lib/ureadahead/debugfs/tracing:/run/rpc_pipefs using Linux ioctls...
[Jul 16 21:00:36.110] [   debug] [vmsvc] SyncDriver: opening path '/'.
[Jul 16 21:00:36.110] [   debug] [vmsvc] SyncDriver: freezing path '/'.
[Jul 16 21:00:36.152] [   debug] [vmsvc] SyncDriver: successfully froze '/'.
[Jul 16 21:00:36.152] [   debug] [vmsvc] SyncDriver: opening path '/proc'.
[Jul 16 21:00:36.152] [   debug] [vmsvc] SyncDriver: freezing path '/proc'.
[Jul 16 21:00:36.152] [   debug] [vmsvc] SyncDriver: freeze on '/proc' returned: 95 (Operation not supported)
[Jul 16 21:00:36.152] [   debug] [vmsvc] SyncDriver: opening path '/sys'.
[Jul 16 21:00:36.152] [   debug] [vmsvc] SyncDriver: freezing path '/sys'.
[Jul 16 21:00:36.152] [   debug] [vmsvc] SyncDriver: freeze on '/sys' returned: 95 (Operation not supported)
[Jul 16 21:00:36.152] [   debug] [vmsvc] SyncDriver: opening path '/sys/fs/cgroup'.
[Jul 16 21:00:36.152] [   debug] [vmsvc] SyncDriver: freezing path '/sys/fs/cgroup'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/sys/fs/cgroup' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/sys/fs/fuse/connections'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/sys/fs/fuse/connections'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/sys/fs/fuse/connections' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/sys/kernel/debug'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/sys/kernel/debug'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/sys/kernel/debug' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/sys/kernel/security'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/sys/kernel/security'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/sys/kernel/security' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/dev'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/dev'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/dev' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/dev/pts'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/dev/pts'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/dev/pts' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/run'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/run'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/run' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/run/lock'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/run/lock'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/run/lock' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/run/shm'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/run/shm'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/run/shm' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/run/user'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/run/user'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/run/user' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/sys/fs/pstore'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freezing path '/sys/fs/pstore'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: freeze on '/sys/fs/pstore' returned: 95 (Operation not supported)
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: opening path '/var/lib/ureadahead/debugfs/tracing'.
[Jul 16 21:00:36.153] [   debug] [vmsvc] SyncDriver: failed to open '/var/lib/ureadahead/debugfs/tracing': 2 (No such file or directory)
[Jul 16 21:00:36.153] [ warning] [vmbackup] Error freezing filesystems.
[Jul 16 21:00:37.110] [   debug] [vmbackup] *** VmBackupAsyncCallback
[Jul 16 21:00:37.110] [   debug] [vmbackup] Async request 'VmBackupSyncDriverStart' completed
[Jul 16 21:00:37.110] [   debug] [vmbackup] *** VmBackupSyncDriverReadyForSnapshot
[Jul 16 21:00:37.609] [   debug] [vmbackup] *** VmBackupKeepAliveCallback
[Jul 16 21:00:37.609] [   debug] [vmbackup] *** VmBackup_SendEvent
[Jul 16 21:00:37.609] [   debug] [vmbackup] Sending vmbackup event: vmbackup.eventSet req.keepAlive 0 
[Jul 16 21:00:37.609] [   debug] [vmsvc] RpcChannel: Sending: 35 bytes
[Jul 16 21:00:37.609] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:00:38.111] [   debug] [vmbackup] *** VmBackupAsyncCallback
[Jul 16 21:00:38.111] [   debug] [vmbackup] *** VmBackupEnableSync
[Jul 16 21:00:38.111] [    info] [guestinfo] New value for stats-interval is 20s.
[Jul 16 21:00:38.111] [    info] [guestinfo] New value for poll-interval is 30s.
[Jul 16 21:00:38.112] [   debug] [vmsvc] Flushed 62 log messages from cache after resuming log IO.
[Jul 16 21:00:38.112] [   debug] [vmbackup] *** VmBackup_SendEvent
[Jul 16 21:00:38.112] [   debug] [vmbackup] Sending vmbackup event: vmbackup.eventSet req.error 3 Error when enabling the sync provider.
[Jul 16 21:00:38.112] [   debug] [vmsvc] RpcChannel: Sending: 69 bytes
[Jul 16 21:00:38.116] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:00:39.117] [   debug] [vmbackup] *** VmBackupAsyncCallback
[Jul 16 21:00:39.117] [   debug] [vmbackup] *** VmBackupStartScripts
[Jul 16 21:00:39.117] [   debug] [vmbackup] Trying to run scripts from /etc/vmware-tools/backupScripts.d
[Jul 16 21:00:39.759] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:00:40.118] [   debug] [vmbackup] *** VmBackupAsyncCallback
[Jul 16 21:00:40.118] [   debug] [vmbackup] VmBackupAsyncCallback: checking VmBackupOnFreezeFail
[Jul 16 21:00:40.118] [   debug] [vmbackup] Async request 'VmBackupOnFreezeFail' completed
[Jul 16 21:00:40.118] [   debug] [vmbackup] *** VmBackupFinalize
[Jul 16 21:00:40.118] [   debug] [vmbackup] *** VmBackup_SendEvent
[Jul 16 21:00:40.118] [   debug] [vmbackup] Sending vmbackup event: vmbackup.eventSet req.done 0 
[Jul 16 21:00:40.118] [   debug] [vmsvc] RpcChannel: Sending: 30 bytes
[Jul 16 21:00:40.119] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:00:44.866] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:00:48.875] [   debug] [vmsvc] RpcIn: received 24 bytes, content:"Set_Option broadcastIP 1"
[Jul 16 21:00:48.875] [   debug] [vmsvc] RpcChannel: Sending: 35 bytes
[Jul 16 21:00:48.879] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:00:48.879] [   debug] [vmsvc] RpcIn: sending 3 bytes
[Jul 16 21:00:49.831] [   debug] [vmsvc] RpcIn: received 5 bytes, content:"ping\00"
[Jul 16 21:00:49.832] [   debug] [vmsvc] RpcIn: sending 3 bytes
[Jul 16 21:00:49.902] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:00:54.997] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:00:58.112] [   debug] [guestinfo] Entered guest info stats gather.
[Jul 16 21:00:58.112] [   debug] [guestinfo] Entered update vmdb: 8.
[Jul 16 21:00:58.112] [   debug] [guestinfo] Sending GuestMemInfo message.
[Jul 16 21:00:58.112] [   debug] [vmsvc] RpcChannel: Sending: 354 bytes
[Jul 16 21:00:58.112] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:00:58.112] [   debug] [guestinfo] GuestMemInfo sent successfully.
[Jul 16 21:00:58.112] [   debug] [guestinfo] Returning after updating guest information: 8
[Jul 16 21:01:00.098] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:01:04.899] [   debug] [vmsvc] RpcIn: received 5 bytes, content:"ping\00"
[Jul 16 21:01:04.899] [   debug] [vmsvc] RpcIn: sending 3 bytes
[Jul 16 21:01:05.150] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:01:08.113] [   debug] [guestinfo] Entered guest info gather.
[Jul 16 21:01:08.113] [   debug] [guestinfo] Entered update vmdb: 4.
[Jul 16 21:01:08.113] [   debug] [guestinfo] Value unchanged for infotype 4.
[Jul 16 21:01:08.113] [   debug] [guestinfo] Returning after updating guest information: 4
[Jul 16 21:01:08.113] [   debug] [guestinfo] Entered update vmdb: 5.
[Jul 16 21:01:08.113] [   debug] [guestinfo] Value unchanged for infotype 5.
[Jul 16 21:01:08.113] [   debug] [guestinfo] Returning after updating guest information: 5
[Jul 16 21:01:08.113] [   debug] [guestinfo] Entered update vmdb: 6.
[Jul 16 21:01:08.113] [   debug] [guestinfo] Value unchanged for infotype 6.
[Jul 16 21:01:08.113] [   debug] [guestinfo] Returning after updating guest information: 6
[Jul 16 21:01:08.113] [   debug] [guestinfo] Entered update vmdb: 3.
[Jul 16 21:01:08.113] [   debug] [guestinfo] Free space changed
[Jul 16 21:01:08.113] [   debug] [guestinfo] sizeof request is 138
[Jul 16 21:01:08.113] [   debug] [vmsvc] RpcChannel: Sending: 138 bytes
[Jul 16 21:01:08.114] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:01:08.114] [   debug] [guestinfo] Updated disk info information
[Jul 16 21:01:08.114] [   debug] [guestinfo] Returning after updating guest information: 3
[Jul 16 21:01:08.114] [   debug] [guestinfo] Entered update vmdb: 1.
[Jul 16 21:01:08.114] [   debug] [guestinfo] Value unchanged for infotype 1.
[Jul 16 21:01:08.114] [   debug] [guestinfo] Returning after updating guest information: 1
[Jul 16 21:01:08.114] [   debug] [guestinfo] Nic info not changed.
[Jul 16 21:01:08.114] [   debug] [guestinfo] Setting guest uptime to '100402321'
[Jul 16 21:01:08.114] [   debug] [guestinfo] Entered update vmdb: 7.
[Jul 16 21:01:08.114] [   debug] [vmsvc] RpcChannel: Sending: 26 bytes
[Jul 16 21:01:08.114] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:01:08.115] [   debug] [guestinfo] Returning after updating guest information: 7
[Jul 16 21:01:10.159] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:01:15.260] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:01:18.112] [   debug] [guestinfo] Entered guest info stats gather.
[Jul 16 21:01:18.113] [   debug] [guestinfo] Entered update vmdb: 8.
[Jul 16 21:01:18.113] [   debug] [guestinfo] Sending GuestMemInfo message.
[Jul 16 21:01:18.113] [   debug] [vmsvc] RpcChannel: Sending: 354 bytes
[Jul 16 21:01:18.113] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:01:18.113] [   debug] [guestinfo] GuestMemInfo sent successfully.
[Jul 16 21:01:18.113] [   debug] [guestinfo] Returning after updating guest information: 8
[Jul 16 21:01:18.958] [   debug] [vmsvc] RpcIn: received 24 bytes, content:"Set_Option broadcastIP 1"
[Jul 16 21:01:18.959] [   debug] [vmsvc] RpcChannel: Sending: 35 bytes
[Jul 16 21:01:18.962] [   debug] [vmsvc] RpcChannel: Recved 0 bytes
[Jul 16 21:01:18.962] [   debug] [vmsvc] RpcIn: sending 3 bytes
[Jul 16 21:01:19.814] [   debug] [vmsvc] RpcIn: received 5 bytes, content:"ping\00"
[Jul 16 21:01:19.814] [   debug] [vmsvc] RpcIn: sending 3 bytes
[Jul 16 21:01:20.276] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:01:25.382] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:01:30.392] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll
[Jul 16 21:01:34.902] [   debug] [vmsvc] RpcIn: received 5 bytes, content:"ping\00"
[Jul 16 21:01:34.902] [   debug] [vmsvc] RpcIn: sending 3 bytes
[Jul 16 21:01:35.454] [   debug] [vmsvc] RpcIn: received 0 bytes, empty TCLO poll

It appears to me like we're trying to freeze special filesystems such as /proc and /sys which is probably not even supposed to work.

"/", which is the only real, local filsystem, freezes correctly

Any hints as to why this is happening? And what to do about it?

**Comment by tmuncks** [comment]
Sorry,

Looking through the sync driver code, it's clear that the "not supported" errors are ignored and that the real cause of confusion is /var/lib/ureadahead/debugfs/tracing that does not exist. This mountpoint sometimes occurs on Ubuntu due to an ureadahead related race, and simply disabling ureadahead should solve the problem. Quiesced snapshots work fine after this nonexisting mountpoint is gone.

So this is not really an open-vm-tools issue, but ENOENT could arguably be added to list of ioctl errorcodes to ignore (we'll never need to quiesce a non-existing mountpoint).

I can easily work around this issue locally, though.

/Thomas

**Comment by tmuncks** [comment]
For reference, this is the ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/mountall/+bug/499773

**Comment by m0ps** [comment]
Does anybody has workaround?

**Comment by tmuncks** [comment]
Disabling ureadahead should solve the problem for you and is not really useful in a virtual environment anyway. In fact, Ubuntu 16.04 disables ureadahead on boot if it detects it's a virtual machine.

**Comment by m0ps** [comment]
@tmuncks thx, disabling ureadahead solved this issue.
`echo manual | sudo tee /etc/init/ureadahead.override`

**Comment by Dragao75** [comment]
@tmuncks @m0ps 
I have this issue as well, although it seems random.. 
I have disabled ureadahead like m0ps said but I still am unable the create a quiesced snapshot. 
Should the machine be rebooted ?

**Comment by m0ps** [comment]
@Dragao75 
`sudo service ureadahead stop`

**Comment by Dragao75** [comment]
@m0ps don't have that services.... hmm

**Comment by m0ps** [comment]
@Dragao75 so... it looks like you have another issue.

**Comment by tmuncks** [comment]
What's the output of the "mount" command

**Comment by Dragao75** [comment]
This is the output
`proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
none on /sys/firmware/efi/efivars type efivarfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
/dev/sda2 on /boot type ext2 (rw)
/dev/mapper/fileserver--vg-data on /data type ext4 (rw,errors=remount-ro,acl,user_xattr)
/dev/sda1 on /boot/efi type vfat (rw)
/data/AVROTROS/ICT/FrontOffice/Salto/TOPdeskFoto on /export/fotomap type none (rw,bind)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
nfsd on /proc/fs/nfsd type nfsd (rw)
`

**Comment by tmuncks** [comment]
No problems that I know of in this, but if Quiescing fails on this machine, I'd try to unmount:
/data/AVROTROS/ICT/FrontOffice/Salto/TOPdeskFoto on /export/fotomap type none (rw,bind)
See if that makes a difference.

**Comment by Dragao75** [comment]
In my /etc/mtab I do see this line:
tracefs on /var/lib/ureadahead/debugfs/tracing type tracefs (rw,relatime)
When I remove this line quiescing succeeds...

**Comment by tmuncks** [comment]
Right - the ureadahead race condition can leave this hanging in mtab. Thought for sure you'd rebooted earlier, but I'm glad you got it working.

**Comment by Dragao75** [comment]
Yes, sorry for the miscommunication.. I was trying to do this without a reboot. :) 

O well, good intel for others 👍

**Comment by ravindravmw** [comment]
Thanks @tmuncks for root causing this issue. Appreciate your help on it!

Workaround fix to ignore bad mount points will be coming in next release.

**Comment by clamport** [comment]
Apologies for opening a stale thread, but can you advise me on how to enable that debug logging @tmuncks ?

**Comment by lemke1458** [comment]
Here's a KB article detailing setting up Tools logging.

https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1007873

**Comment by ravindravmw** [comment]
FWIW, fix has been included in https://github.com/vmware/open-vm-tools/releases/tag/stable-10.1.5 release.
