### ISSUE TITLE
VMware workstation thinks the version is old

### ISSUE THREAD

**Issue by timmyL17** [vmware/open-vm-tools#108]
I have VMware Workstation 12.5 installed on Windows 10. I setup an Archlinux guest and installed the open-vm-tools from the archlinux repository. However, VMware thinks I have an older version of the guest tools installed. In the display settings, Accelerate 3D graphics is grayed out with the message "You must update Tools to enable 3D acceleration in this virtual machine."

**Comment by suhrab** [comment]
open-vm-tools are outdated. But you can install vm tools carried by your vmware workstation 12.5 installation. https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1022525

**Comment by oliverkurth** [comment]
@timmyL17 , can you please tell which version of open-vm-tools you have installed in the vm? You can check with the command "vmtoolsd -v".

Please make sure that vmtoolsd is actually running and enabled - the service is not enabled be default in Archlinux. Check if it's running with:

systemctl status vmtoolsd

If it's not running and/or enabled, start/enable it with:

systemctl start vmtoolsd
systemctl enable vmtoolsd

The advice by @suhrab would install VMware Tools in the vm, not open-vm-tools, and you would need to uninstall open-vm-tools first. This may not be what you want, and is probably not necessary.

**Comment by timmyL17** [comment]
@oliverkurth Thanks. I think I forgot to enable vmtoolsd. Now it is enabled and running. The version is

VMware Tools daemon, version 10.0.7.52125 (build-3227872)

Most things seem to work now, except automatic screen resizing when I change the vm window size. I can live without it, but it would be nice if there's an easy way to get it to work.

**Comment by oliverkurth** [comment]
I am glad you have it working!

For screen resizing, you need the resolutionset plugin working. I am not too familiar with Archlinux - but it looks like the open-vm-tools package includes the plugin, but has some optional dependencies, see https://www.archlinux.org/packages/community/x86_64/open-vm-tools 

...
gtkmm (optional) - DnD/CP plugin
libxtst (optional) - DnD/CP, resolution set plugins
netctl (optional) - suspend-resume network state
networkmanager (optional) - suspend-resume network state
...

So try installing libxtst.

Does copy/paste work for you?

**Comment by akuropka** [comment]
Actually I have the same problem with the outdated notice on 12.5 but vmtoolsd is running in my case. 
![screenshot - 02 10 2016 08_01_30_ver001](https://cloud.githubusercontent.com/assets/22570574/19019012/804162c2-8876-11e6-9c61-ff9e65bb9165.jpg)

**Comment by timmyL17** [comment]
@oliverkurth Copy/paste works. I have all the optional dependencies installed, but automatic resizing still doesn't kick in. Not that big of a deal.

**Comment by timmyL17** [comment]
And I'm also still getting the outdated notice, even with vmtoolsd running. But most things seem to work even with the notice.

**Comment by akuropka** [comment]
Yeah, that outdated notice is basically just a cosmetic issue. Everything works as before... (I use copy/paste and the mouse hovering inside/outside vm)

**Comment by stanguturi** [comment]
> I have VMware Workstation 12.5 installed on Windows 10.
Workstation 12.5 is bundled with tools 10.0.10.

The open-vm-tools version that is installed inside the guest is 10.0.7 which is older than the tools version available with 12.5 workstation. Hence, the 'outdated' message appears. This is expected. You can upgrade the open-vm-tools version inside the guest.
