### ISSUE TITLE
Cycle multiple monitors failing

### ISSUE THREAD

**Issue by Massimo-B** [vmware/open-vm-tools#11]
Hi,

trying to use "Cycle multiple monitors" from VMware-Workstation 11 results in 

> "..cannot use multiple monitors..virtual machine must have up-to-date VMware Tools installed and running"

However using the official tools with the same VM and Host works and has working multi-screen (with some glitches).

Using official tools is very distribution-related and not maintainable on Gentoo, so I would prefer the open-vm-tools.

Using the multiscreen by using the script vmware-user-suid-wrapper and "Cycle multiple monitors" in the workstation" is a requirement.

**Comment by oliverkurth** [comment]
Hi Massimo,

can you please briefly describe how you built and/or installed open-vm-tools, and most important, which version? Specifically, which configure options did you use, if you built it yourself.

Thanks

**Comment by Massimo-B** [comment]
Hi Oliver,

thanks for taking care.
Just to be sure, what is the central location of open-vm-tools, as I found this other tracker: http://sourceforge.net/p/open-vm-tools/tracker ?

I build and install open-vm-tools on Gentoo using an inofficial ebuild from: https://bugs.gentoo.org/show_bug.cgi?id=544182
I'll try to attach the buildlog here...

**Comment by Massimo-B** [comment]
As I can't attach log files here, please take a look at the build log:
https://bpaste.net/show/b90cc3d90135

**Comment by ravindravmw** [comment]
> what is the central location of open-vm-tools, as I found this other tracker: http://sourceforge.net/p/open-vm-tools/tracker ?

We have been moving to github and we are almost here except for download and mailing lists still being  on sourceforge. Please use github for opening/tracking new issues. We will eventually get out of sourceforge tracker once the existing trackers are resolved.

> As I can't attach log files here, please take a look at the build log:
https://bpaste.net/show/b90cc3d90135
The only warning I see in the log is, # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE". You could either ignore it or suppress it by exporting CFLAGS=-D_DEFAULT_SOURCE before running configure script.

**Comment by Massimo-B** [comment]
Thank you for clarifying about github. Maybe this should be mentioned in the index for not misleading if this could be a branch or clone...

Does that mean, "Cycle multiple monitors" in general is supported by open-vm-tools?

This warning doesn't have any impact on this issue, you think?
I guess the only issue is the version check of VMware Workstation. I'm not sure what version it is expecting and what version open-vm-tools should return to match?

**Comment by Massimo-B** [comment]
I noticed setting xinerama for the ebuild does enable multimon on configure.
Here is the new build.log: https://bpaste.net/show/59fdc1174ca1
I rebuilt like that, restarted the tools, but still the same issue.

**Comment by Massimo-B** [comment]
Sorry, I have to correct:
After rebooting the system, the multimon configured tools are working now with cycling monitors.

However when I was using some old closed vmware-tools I had some issues with multiscreen. This was the reason to look for an update so I got to the open-vm-tools:
#14, #15
