### ISSUE TITLE
Error building open-vm-tools with clang

### ISSUE THREAD

**Issue by slacka** [vmware/open-vm-tools#111]
When you try to build open-vm-tools with clang you get the following error:
`hashMap.c:165:1: error: unused function 'CheckSanity'`

The full log can be found here:
http://clang.debian.net/logs/2016-08-30/open-vm-tools_10.0.7-3227872-4.1_unstable_clang.log

**Comment by oliverkurth** [comment]
Thanks for reporting. This issue will be fixed in the next upcoming release.
