### ISSUE TITLE
10.1.0 - XERCES library not found

### ISSUE THREAD

**Issue by hooolden** [vmware/open-vm-tools#117]
Hello - 

I am trying to compile 10.1.0 on a RHEL 7.3 machine and I'm running into the following error message when running the configure script: 

    configure: error: Cannot find XERCES library. Please configure without XERCES (using --without-xerces-c), or install the XERCES libraries and devel package(s).

I do have the only package with xerces in the name I can find installed: 

    
    [root@ls0002 open-vm-tools]# yum list installed | grep xer
    xerces-c.x86_64                    3.1.1-8.el7_2           @rhel-x86_64-server-7

I've also copied the file to /usr/lib and /usr/local/lib as I recall seeing the compiler might only look there. 

Am I missing something? Also, is there an ETA of when this update is going to be in the RHEL repository?  I doubt I'm going to be able to push all the needed packages (compilers etc) to all of my RHEL 7.x servers.  I need the loopback issue fixed though as it's causing us some grief.

**Comment by oliverkurth** [comment]
Holden,

you need to install the xerces-c-devel package as well. Here is a complete list of packages that need to be installed, if you build with

./configure --without-kernel-modules 

yum -y install \
  autoconf \
  automake \
  libtool \
  gcc-c++ \
  doxygen \
  fuse-devel \
  glib2-devel \
  gtk2-devel \
  gtkmm24-devel \
  libdnet-devel \
  libicu-devel \
  libmspack-devel \
  libX11-devel \
  libXext-devel \
  libXi-devel \
  libXinerama-devel \
  libXrandr-devel \
  libXrender-devel \
  libXtst-devel \
  openssl-devel \
  pam-devel \
  procps-devel \
  xerces-c-devel \
  xml-security-c-devel

Alternatively, you could also build with

./configure --without-kernel-modules --disable-vgauth

Which disables vgauth, and xerces and xml-security will not be needed.

As a 3rd alternative, you can install xmlsec1-devel (and you won't need xerces and xml-security) and build with

./configure --without-kernel-modules --enable-xmlsec1

**Comment by hooolden** [comment]
If all else fails.. look at your satellite settings.  I feel silly.  Thanks for posting the list of packages I need.

**Comment by oliverkurth** [comment]
Thanks, Holden. I assume this means it works now, so I will close this issue. Feel free to reopen if this is still a problem.
