### ISSUE TITLE
Open-VM-Tools not working on CentOS 7 (3.10)

### ISSUE THREAD

**Issue by jtjones1028** [vmware/open-vm-tools#119]
Just ran `sudo yum -y install open-vm-tools` and I've enabled shared folders within VMware Workstation 12.5, however, I can't seem to mount the HGFS

If I try manually mounting the filesystem `mount -t vmhgfs .host:/shared_location /mnt/hgfs/Repo` - I receive the following error: `mount: unknown filesystem type 'vmhgfs'`

If I run `vmware-hgfsclient` the output shows my shared_location.  If appears that the vmhgfs driver either wasn't installed or the module wasn't loaded.

Any help would be greatly appreciated.  I'm about tired of beating my head against the desk..

-Cheers!

**Comment by lousybrit** [comment]
You just ran the open-vm-tools install which will have the vmhgfs-fuse option which is generally expected to run on Linux kernels 4.0 and newer.
You can try it on 3.10 kernels if you have the FUSE package installed.
Just use the following:
Check the folder exists and if not use as root
mkdir /mnt/hgfs
/usr/bin/vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other

The allow_other option will allow non-root users to access the mount.
Then underneath the /mnt/hgfs should be the Repo folder and your host files.

If you want to use the kernel mode client then you will have to install the VMware Tools package on top of the open-vm-tools which will install the Shared Folders with the kernel mode client i.e., vmhgfs.ko kernel mode client and it will do the usual
mount -t vmhgfs .host:/ /mnt/hgfs 
for you and you will see that Repo folder under  /mnt/hgfs as normal.

Note if you go with the vmhgfs-fuse option then disabling and enabling the Shared Folders feature from the UI will be an issue, so I would just leave the feature enabled. Adding or removing shares is fine though.

Hope this helps
Steve

**Comment by jtjones1028** [comment]
@lousybrit - Thanks for the info!  So, I updated the Kernel to `4.8.11-1.el7.elrepo.x86_64` and I'm still having  similar issues.  I'm not seeing vmhgfs-fuse installed anywhere.

Am I missing a step somewhere?  Thanks again for the information guys.

**Comment by lousybrit** [comment]
I didn't intend for you to upgrade the OS at all.

What version of open-vm-tools are you running?
It might not have the vmhgfs-fuse client if it is older than 10.0.0.
You can extract the version using
/usr/bin/vmware-toolbox-cmd -v

If it is older then you could install the tools that come with Workstation.
It will have everything you need for the Shared Folders feature and anything else.
If the open-vm-tools is older you can remove it first and get everything from the VMware Tools ISO that comes with Workstation.

Just go to the UI and select VM menu option and  "Install VMware Tools..."
It will try to mount the Linux version of the tools ISO into the CD-ROM and from there you view and copy the files as done in the steps below:

1. Install prerequisites :
# yum install perl gcc make kernel-headers kernel-devel -y

2. Mount the CD-ROM if not automatically done.
# cd to that folder where the mount of the CD-ROM is located.

# ls
manifest.txt     VMwareTools-X.X.X-BuildNumber.tar.gz  vmware-tools-upgrader-64
run_upgrader.sh  vmware-tools-upgrader-32
# cp -p VMwareTools-9.4.0-1280544.tar.gz /tmp
3. Go to /tmp directory and extract the vmware tools package :
# cd /tmp
# tar xzvf VMwareTools-X.X.X-BuildNumber.tar.gz
4. Go to extracted folder, vmware-tools-distrib :
# cd vmware-tools-distrib
# ls
bin  doc  etc  FILES  INSTALL  installer  lib  vmware-install.pl
5. Run vmware-install.pl to start installation :
# ./vmware-install.pl

The default will install the Shared Folders client and feature over the installed open-vm-tools.

**Comment by jtjones1028** [comment]
Thanks again for the feedback.

So I reverted back to 3.10 and installed vmware-tools.  All is good now.

So, out of curiosity, can you explain why open-vm-tools doesn't seem to play well with CentOS?  Additionally, how could i upgrade the OS and keep the tools?

Thanks

**Comment by lousybrit** [comment]
Typically, once users have installed the tools they just take the system updates as they are made available by the distributor.
If that entails some system (and I mean kernel) updates, then after rebooting the system, for the Shared Folders feature, the vmhgfs kernel driver will require rebuilding and reinstalling. To do this you will need to run:
/usr/bin/vmware-tools-config.pl
which will allow you to regenerate the driver component. After that completes the Shared Folders feature will be up and running once more.

If no kernel changes occur (or you don't use the Shared Folders feature) you will not need to do this.

Lastly, if you update to a kernel version that is much newer i.e., kernel 4.x using a custom build for example, then you will find that with the newer release of tools installed that vmhgfs-fuse will be used instead of the kernel mode client.
A df or mount command will show you that.

Steve

**Comment by jtjones1028** [comment]
@lousybrit - Thanks for the information Steve.  Appreciate the help.

**Comment by christianbueno1** [comment]
> You just ran the open-vm-tools install which will have the vmhgfs-fuse option which is generally expected to run on Linux kernels 4.0 and newer.
> You can try it on 3.10 kernels if you have the FUSE package installed.
> Just use the following:
> Check the folder exists and if not use as root
> mkdir /mnt/hgfs
> /usr/bin/vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other
> 
> The allow_other option will allow non-root users to access the mount.
> Then underneath the /mnt/hgfs should be the Repo folder and your host files.
> 
> If you want to use the kernel mode client then you will have to install the VMware Tools package on top of the open-vm-tools which will install the Shared Folders with the kernel mode client i.e., vmhgfs.ko kernel mode client and it will do the usual
> mount -t vmhgfs .host:/ /mnt/hgfs
> for you and you will see that Repo folder under /mnt/hgfs as normal.
> 
> Note if you go with the vmhgfs-fuse option then disabling and enabling the Shared Folders feature from the UI will be an issue, so I would just leave the feature enabled. Adding or removing shares is fine though.
> 
> Hope this helps
> Steve

Hello pals, Is there a rule to know when we have new or alternative commands, or how would we realize about that tiny issue, but very very important.

**Comment by lousybrit** [comment]
Hi there

The tools release notes should contain documentation about the vmhgfs fuse client and Linux version. 
I see you found it.

However, the newest versions of tools will allow the fuse client to work on kernel 3.10 and newer.
If you run
**/usr/bin/vmhgfs-fuse --enabled**

It will report whether the vmhgfs-fuse will be supported on that version or not.
If it is it will report something like
**0 - HGFS FUSE client enabled**
If the above is the result then you know the fuse client is used if not, then the kernel vmhgfs driver is required and the old mount command is used.

Steve
