### ISSUE TITLE
Mount masks directory doesn't exist error

### ISSUE THREAD

**Issue by abraithwaite** [vmware/open-vm-tools#12]
In the hgfsmounter, if the destination directory doesn't exist, then it masks the error.
https://github.com/vmware/open-vm-tools/blob/stable-9.4.x/open-vm-tools/hgfsmounter/hgfsmounter.c#L1052-L1055

You should probably use `perror(3)` instead.

Edit: It looks like it's fixed in 9.10 branch.  Can it be backported to 9.4 as well so debian jessie can get the fix?

**Comment by bzed** [comment]
Please also open a bug with a good explanation in the Debian BTS - adding a tested patch would be appreciated (I don't need a release to fix bugs in Debian).

I'll backport 9.10 for jessie as soon as #16 is fixed.

**Comment by abraithwaite** [comment]
:+1: I already mentioned it in the thread for 9.10.  I'm not sure it makes sense to patch the 9.4 package for Debian though, since it's not really broken without the patch; it's just a usability thing.

**Comment by stanguturi** [comment]
> Edit: It looks like it's fixed in 9.10 branch. Can it be backported to 9.4 as well so debian jessie can get the fix?

> 👍 I already mentioned it in the thread for 9.10. I'm not sure it makes sense to patch the 9.4 package for Debian though, since it's not really broken without the patch; it's just a usability thing.

Based on the above comments, closing this issue.
