### ISSUE TITLE
Open-vm-tools on Atomic Host

### ISSUE THREAD

**Issue by snobear** [vmware/open-vm-tools#121]
Hi,

We are running CentOS 7 Atomic Host in VMware vSphere and need open-vm-tools installed.  Has anyone had experience and perhaps some notes on getting it installed with `rpm-ostree`?  I'm going to work on setting up an rpm-ostree repo and building my own image with open-vm-tools installed, but was hoping to start a conversation and avoid any pitfalls.  There is not much solid info out there about running Atomic Host with VMware.

Alternatively, are there any OVF templates out there for CentOS 7 Atomic?  I've not found any.

**Comment by snobear** [comment]
I was able to a custom Atomic Host with `open-vm-tools` installed that is guest customizable.  For anyone interested here are the steps:

https://github.com/imsweb/centos7-atomic-custom

**Comment by robertwolf83** [comment]
Just running **rpm-ostree pkg-add open-vm-tools** worked for my needs.

**Comment by snobear** [comment]
@robertwolf83 that is way simpler. I was not aware of [package layering](http://www.projectatomic.io/blog/2016/08/new-centos-atomic-host-with-package-layering-support/).

And you are able to enable the `vmtoolsd` service on boot?

**Comment by robertwolf83** [comment]
yes,` systemctl enable vmtoolsd` works as expected

But the pkg-add command is broken in the current version of centos atomic release.
I had to roll back to previous with rpm-ostree rollback, install packages and upgrade again

RedHat is aware of it, but the fix did not make it into the centos release yet:
https://bugzilla.redhat.com/show_bug.cgi?id=1399770

**Comment by dav1x** [comment]
@snobear I did some work containerizing and turning into a system container:
https://developers.redhat.com/blog/2017/03/23/containerizing-open-vm-tools-part-1-the-dockerfile-and-constructing-a-systemd-unit-file/
