### ISSUE TITLE
vmware-toolbox-cmd can make changes as regular user

### ISSUE THREAD

**Issue by jhgit** [vmware/open-vm-tools#124]
Is it intentional that you can make changes with vmware-toolbox-cmd as a regular user on a guest host?  Example:

vmware-toolbox-cmd timesync enable  (or disable)

**Comment by ravindravmw** [comment]
It is not intentional, it is historical for compatibility reasons.

You could make this operation privileged by setting following in your VM's config file (vm_name.vmx file):

guest_rpc.rpci.auth.cmd.vmx.set_option = "TRUE"

**Comment by stanguturi** [comment]
VMX option provided by @ravindravmw in the previous comment should disallow toolbox-cmd from making *timesync* changes when invoked by a regular user.
