### ISSUE TITLE
debian 9 (stretch) customizing NIC uses wrong interface name

### ISSUE THREAD

**Issue by gregster85** [vmware/open-vm-tools#130]
Hi,

ESXi 6.0
Debian 9 stretch/sid
open-vm-tools 10.1.0-4449150-2
guestOS other3xlinux-64
The net-tools package is installed to have the ifconfig binary.

When customizing the NIC, the wrong adapter name is parsed and instead of network interface "eth0", it configures "ether".

From toolsDeployPkg.log:

INFO: Customizing NICS ...
DEBUG: Command: 'modprobe pcnet32 2> /dev/null'
DEBUG: Result:
DEBUG: Exit Code: 0
DEBUG: Command: '/sbin/ifconfig eth0 2> /dev/null'
DEBUG: Result: eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:50:56:98:1b:c5  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

DEBUG: Exit Code: 0
INFO: Customizing NICS. { NIC1 }
INFO: Customizing NIC NIC1
DEBUG: Command: '/sbin/ifconfig -a'
DEBUG: Result: eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:50:56:98:1b:c5  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

DEBUG: Exit Code: 0
INFO: NIC suffix = ether

**Comment by oliverkurth** [comment]
@gregster85 , could you run the ifconfig command, and copy the output? I know, it's right there in the debug output, but maybe we are missing something. It looks different to what I see in my machine.

**Comment by gregster85** [comment]
root@debian:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask 255.255.255.224  broadcast x.x.x.x
        inet6 fe80::20c:29ff:fedb:6da1  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:db:6d:a1  txqueuelen 1000  (Ethernet)
        RX packets 1666675  bytes 120657343 (115.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 103310  bytes 13086058 (12.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by oliverkurth** [comment]
Thank you. This looks like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820212 . Can you try upgrading the net-tools package to 1.60+git20161116.90da8a0-1 or later?

**Comment by gregster85** [comment]
It's already that version.
net-tools 1.60+git20161116.90da8a0-1
# ifconfig --version
net-tools 2.10-alpha

Reading from that bug report, I don't think they changed the formatting.
They just included an article with a statement that it has changed.
* Add debian/NEWS warning about changing output in net-tools commands.
     Closing bugs that reported problems in 3rd-party scripts arising from these
     changes.

**Comment by oliverkurth** [comment]
Thanks, Greg. I have created an internal bug about this.

**Comment by bzed** [comment]
net-tools is also pretty much deprecated. the only useful way to get information about interfaces is using the ip from iproute2.

**Comment by msteenhu** [comment]
An update if this will get fixed anytime soon?

**Comment by bzed** [comment]
@msteenhu does this still fail with the version from unstable? Looking at the code it is using ip, not ifconfig. So it should work... Please make sure iproute2 is installed. I'll add that as a dependency.

**Comment by gregster85** [comment]
@bzed I installed the package from unstable but it still seems to use ifconfig instead of ip, which causes the wrong interface to be configured, "ether" instead of "eth0".
The package iproute2 is installed.

iproute2 4.9.0-1
open-vm-tools 2:10.1.5-5055683-1

Attached is the full output of the toolsDeployPkg.log

[toolsDeployPkg.txt](https://github.com/vmware/open-vm-tools/files/816558/toolsDeployPkg.txt)

**Comment by msteenhu** [comment]
@bzed I reach same conclusions as Greg. My company relies on VMWare and Debian so it is obviously important for us that our hypervisor supports the latest version.
If we can't use guest customization we have to look for alternatives. I didn't spend time in debugging the Perl scripts myself. It is on my todo to look into it. Maybe I can help with a PR.

**Comment by bzed** [comment]
Looking ath the toolsDeployPkg.txt it does not seem that the script is part of open-vm-tools. Also I was unable to find code where ifconfig would be called instead of ip.

**Comment by msteenhu** [comment]
We use the vcenter api using pyvmomi. So i guess vcenter injects a script. Apparently using cloud-init according to the log. Key seems to be this line:
Launching deployment /bin/bash /tmp/.vmware/linux/deploy/scripts/customize.sh /tmp/.vmware/linux/deploy/cust.cfg.

**Comment by msteenhu** [comment]
So guess this bug can be closed/rejected here. According to this document from VMware: http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf
Guest customization on Debian is not even supported :-)

**Comment by bzed** [comment]
@msteenhu I *think* is should work with the current open-vm-tools. Never tested, though.

**Comment by gregster85** [comment]
It's the scripts that are part of the package "Deploying /tmp/vmware-root/189dd580/imc3634.tmp".
The file /tmp/.vmware/linux/deploy/scripts/Customization.pm contains the ifconfig commands.

Copyright 2014 VMware, Inc.  All rights reserved.
Customization.pm
This module implements a framework for OS customization.

Are these scripts deployed by the open-vm-tools package, or how does this work?

**Comment by msteenhu** [comment]
As mentioned before, open-vm-tools is not to blame for this VMWare issue.
In the mean time we could locate the Perl scripts on our vcenter servers and could confirm that this scripts limit the VMWare support for guest customization. Good news is that you can edit them yourself!

**Comment by eLvErDe** [comment]
Hi,

For the record, I had the same issue coming from net-tools update that changed ifconfig output format.
It was a blocker for me so I dig into VMWare crap and managed to patch their broken parser to something better.

The file was at **C:\Program Files\VMware\vCenter Server\vpxd\imgcust\linux\imgcust-scripts\Customization.pm** on vCenter server and there's nothing to reload after modifying. Everytime you create a VM with customization this file is copied from the vCenter to the server directly inside the virtual machine filesystem.

```diff
--- Customization.pm.orig	2017-07-27 20:21:04.259828942 +0200
+++ Customization.pm.new	2017-07-27 20:21:35.559476473 +0200
@@ -756,17 +756,17 @@
    if (! defined $ifcfgResult) {
       $ifcfgResult = Utils::ExecuteCommand('/sbin/ifconfig -a');
    }
+  
+   my @interfaces = split/\n\n/, $ifcfgResult;
 
-   my $result = undef;
-
-   my $macAddressValid = ($macAddress =~ /^([0-9a-f]{2}:){5}[0-9a-f]{2}$/i);
-
-   if ($macAddressValid &&
-      ($ifcfgResult =~ /^\s*(\w+?)(:\w*)?\s+.*?$macAddress/mi)) {
-      $result = $1;
+   foreach my $interface (@interfaces) {
+      if ($interface =~ /$macAddress/) {
+	      print($interface);
+          if ($interface =~ m/^(\w+)(:|\s)/) {
+              return $1;
+          }
+      }
    }
-
-   return $result;
 }
 
 sub GetInterfaceByMacAddressIPAddrShow
```

Not heavily tested but I've been able to deploy two machines with it and the method seem to work fine on a machine with legacy net-tools.

Regards, Adam.

**Comment by val0x00ff** [comment]
@eLvErDe I don't have such file on my vsphere server or client. Any way to get around this problem? I've exactly the same problem as mentioned above. 

Any assistance much appreciated!

**Comment by TolianIPB** [comment]
If you edit **C:\Program Files\VMware\vCenter Server\vpxd\imgcust\linux\imgcust-scripts\Customization.pm** such as upper it will stop Customize older version of Linux.
Here is my way:

```
sub GetInterfaceByMacAddress
{
   # This function is same as GetInterfaceByMacAddress but uses
   # '/sbin/ip addr show' instead of/sbin/ifconfig

   my ($self, $macAddress, $ipAddrResult) = @_;
   my $result = undef;
   if (! defined $ipAddrResult) {
      my $ipPath = Utils::GetIpPath();
      if ( defined $ipPath){
         $ipAddrResult = Utils::ExecuteCommand("$ipPath addr show");
      } else {
         WARN("Path to 'ip addr' not found.");
      }
   }

   my $macAddressValid = ($macAddress =~ /^([0-9a-f]{2}:){5}[0-9a-f]{2}$/i);

   if ($macAddressValid && ($ipAddrResult =~
      /^\d+:\s([^\s.:]+):\s[^\n]+[^\n]+\s+link\/\w+\s+$macAddress/mi)) {
      $result = $1;
   }

   return $result;
}
```

**Comment by shibumi** [comment]
This is still a problem on CentOS7. It customizes the /etc/sysconfig/network-scripts/ interface files with an interface called `ether` that will not match any interface.

**Comment by TolianIPB** [comment]
```
sub GetInterfaceByMacAddress
...
```
See upper.
Is work OK with CentOS7 customization.

**Comment by rongz609** [comment]
> This is still a problem on CentOS7. It customizes the /etc/sysconfig/network-scripts/ interface files with an interface called `ether` that will not match any interface.

Do you still have that problem on CentOS7?
What the version of vsphere are you using now?

**Comment by rongz609** [comment]
> @eLvErDe I don't have such file on my vsphere server or client. Any way to get around this problem? I've exactly the same problem as mentioned above.
> 
> Any assistance much appreciated!
Do you use Windows vCenter or appliances vCenter  (VCSA)?
The path @eLvErDe mentioned (C:\Program Files\VMware\vCenter Server\vpxd\...)  is actually the default vCenter installing path in Windows.  If you used another path to install vCenter in your Windows, you may need to find that file under the path you installed vCenter.
And if you are using VCSA, you can ssh to your vCenter server, and modify /lib/vmware-vpx/imgcust/linux/imgcust-scripts/Customization.pm as @eLvErDe mentioned.
I thinks @TolianIPB 's method is also OK to work around this issue.

**Comment by rongz609** [comment]
> @eLvErDe I don't have such file on my vsphere server or client. Any way to get around this problem? I've exactly the same problem as mentioned above.
> 
> Any assistance much appreciated!

Do you use Windows vCenter or appliances vCenter (VCSA)?
The path @eLvErDe mentioned (C:\Program Files\VMware\vCenter Server\vpxd...) is actually the default vCenter installing path in Windows. If you used another path to install vCenter in your Windows, you may need to find that file under the path you installed vCenter.
And if you are using VCSA, you can ssh to your vCenter server, and modify /lib/vmware-vpx/imgcust/linux/imgcust-scripts/Customization.pm as @eLvErDe mentioned.
I thinks @TolianIPB 's method is also OK to work around this issue.

**Comment by rongz609** [comment]
> It's the scripts that are part of the package "Deploying /tmp/vmware-root/189dd580/imc3634.tmp".
> The file /tmp/.vmware/linux/deploy/scripts/Customization.pm contains the ifconfig commands.
> 
> Copyright 2014 VMware, Inc. All rights reserved.
> Customization.pm
> This module implements a framework for OS customization.
> 
> Are these scripts deployed by the open-vm-tools package, or how does this work?

Those scripts will be packed and transferred from vCenter into guest OS to execute GuestOS customization.  And they will be deleted in Guest OS after customization completed.
And those scripts are stored in vCenter Server. If you are using Windows vCenter, you can find those scripts under your vCenter installing path (e.g. C:\Program Files\VMware\vCenter Server\vpxd\imgcust\linux\imgcust-scripts\)
If you are using VCSA, it is /lib/vmware-vpx/imgcust/linux/imgcust-scripts/.
You can modify Customization.pm as @TolianIPB mentioned as a work around method to solve your issue.

**Comment by rongz609** [comment]
@gstorme This issue has been fixed in ESXi6.5 and later versions, you can work around it by the solution proposed by @TolianIPB , and you can refer to my comment to find the script file which needs to be modified.

**Comment by TolianIPB** [comment]
In ESXi6.7 VMware fix it by changing /etc/networking to /etc/netplan method of network setup for new releases of Debian and Ubuntu.

**Comment by jasonarieger** [comment]
Hi. I just deployed the latest VCSA 6.7 (U1b) (VMware-VCSA-all-6.7.0-11726888.iso ). I compared the sub GetInterfaceByMacAddress {} function with that of a 65. VCSA, and the function is the same. So it appears to me that VMware did not fix the issue in 6.7. :(

**Comment by ryancbutler** [comment]
For anyone on an older version of vCenter VCSA (6.0.0.30500) the file can be found at /**usr/lib/vmware-vpx/imgcust/linux/imgcust-scripts/Customization.pm**

**Comment by maartenschalekamp** [comment]
> @rongz609 @TolianIPB Hi. I just deployed the latest VCSA 6.7 (U1b) (VMware-VCSA-all-6.7.0-11726888.iso ). I compared the sub GetInterfaceByMacAddress {} function with that of a 65. VCSA, and the function is the same. So it appears to me that VMware did not fix the issue in 6.7. :( Please advise.

Seems like they added another customization file `UbuntuCustomization.pm` and its loaded from `Customize.pl`. I have actually that them to older vCenter server, updated the `Customize.pl` file and now its running like a dream.

**Comment by bykvaadm** [comment]
The workaround, that i've found for me was to install on debian10 old net-tools, i.e. 1.60-26ubuntu1. It's all about parsing of ifconfig output, and yes, it changed. So, as u need to install infconfig to make customization working, install older version. Also, u need to setup:
1) guest os - ubuntu
2) fix unit file https://kb.vmware.com/articleview?docid=56409
3) symlink on dhcp https://kb.vmware.com/s/article/2051469

that's all, needed to make customization work properly. tested on debian10, vsphere 6.5u2

**Comment by AristarXXX** [comment]
> 1.60-26ubuntu1

Thanks for the solution. I did not change guest os type to Ubuntu , but i downgrade net-tools to 1.60-26ubuntu1 and made symlink on dhcp.
