### ISSUE TITLE
Too many partitions warning

### ISSUE THREAD

**Issue by blackknight36** [vmware/open-vm-tools#132]
On servers with a large number of mount points open-vm-tools logs a warning message stating "Too many partitions".  For example:

`Jan 13 16:15:29 server.example.com vmsvc[748]: [ warning] [guestinfo] Too many partitions.
Jan 13 16:15:29 server.example.com vmsvc[748]: [ warning] [guestinfo] Failed to update VMDB`

This particular server has 356 entries in /proc/mounts which is higher than the UCHAR_MAX limit for a uint8 variable.  partitionCount is defined as uint8 however this should be increased to uint16 to avoid false warning messages.

**Comment by ravindravmw** [comment]
Thanks for reporting, this definitely needs fixing.

Also, what version of open-vm-tools are you using? open-vm-tools 10.0.0 and later wouldn't log to system log, so you will not see the message unless you go looking for it.

Assuming you are not worried about the functionality loss this causes, is bumping log level an option for you? You can bump the log level by creating /etc/vmware-tools/tools.conf in the guest with following contents:

# Start
[logging]
guestinfo.level=critical
# End

**Comment by blackknight36** [comment]
Thanks for the help.

It looks like the issue was occuring with open-vm-tools version 9.10 which is what's provided on CentOS 7.2.  I've upgraded the server to CentOS 7.3 with open-vm-tools 10.0.5 and the message is no longer appearing in our logs.

We're using open-vm-tools 10.0.5 which is what's included by default in CentOS 7.

`Jan 13 16:24:01 00fs-cent7 yum[8237]: Erased: open-vm-tools-9.10.2-5.el7_2.x86_64
Jan 13 16:48:45 00fs-cent7 yum[2470]: Installed: open-vm-tools-10.0.5-2.el7.x86_64`
