### ISSUE TITLE
Add snmp informations / extend snmp MIB

### ISSUE THREAD

**Issue by rockyluke** [vmware/open-vm-tools#133]
One useful information delivered by Dell OMSA is that the guest OS (Windows & Linux) is running on VMware with : SNMPv2-SMI::enterprises.674.10892.1.300.10.1.9.1 = STRING: "VMware Virtual Platform". It's really useful for tools like Cacti, Nagios, Observium or LibreNMS.

Maybe it will be a good idea to extend one MIB to display information on the guest OS.

Actually for Dell OMSA, we need to add one line to snmpd.conf.

```conf
# http://en.community.dell.com/techcenter/systems-management/f/4494/t/19425042
smuxpeer .1.3.6.1.4.1.674.10892.1
```

Thank you.

**Comment by ravindravmw** [comment]
Thanks for the report. Could you please provide more details about why you think this is related to open-vm-tools? What needs to added/fixed in open-vm-tools for this?

**Comment by rockyluke** [comment]
It's just an idea but I'll try to explain it correctly :)

Actually when you run OMSA on a physical (Dell indeed) server you can have the hardware model (like Dell PowerEdge R300) and the funny part is when you have OMSA installed on a VMware virtual server (why in hell would I do that ? because we migrate physical to virtual with your tool and OMSA stay installed indeed) you don't have model but instead you have "VMware Virtual Platform".

Now I'm looking for the best way to have this information without OMSA installed on VM with SNMP so maybe it's possible for you to add some informations (extend MIB or something else) accessible through SNMP.

Many thanks for this amazing tool, you've done a great job.

**Comment by ravindravmw** [comment]
> Many thanks for this amazing tool, you've done a great job.

I believe you are referring to P2V Converter http://www.vmware.com/products/converter.html, right? If yes, that's not related open-vm-tools.

**Comment by rockyluke** [comment]
I really talk about open-vm-tools who is really useful in Linux to fetch all information in vCenter.

The converter is the tools we use. Now in my VM I have (thanks to OMSA) the information that it's a VMware Virtual Machine. I'm looking for the best way to have the same information without OMSA (no need in a VM) and was thinking that open-vm-tools can provide information(s) the same way than OMSA. If I snmpwalk my VM I can't be 100% sure it's a VM.

If you have better idea only with SNMP I take it :)

Thanks.
