### ISSUE TITLE
Compile Fail open-vm-tools-10.1.0-4449150 in WiperIsDiskDevice

### ISSUE THREAD

**Issue by reubenfarrelly** [vmware/open-vm-tools#134]
I'm currently trying to compile open-vm-tools on a Gentoo x86_64 system and it is failing to compile - as below.

I have also tested this with a tar.gz of open-vm-tools - thus avoiding anything packaging or OS specific, but I'm seeing the failure in the exact same place.

libtool: link: x86_64-pc-linux-gnu-gcc -shared  .libs/libvmtools_la-i18n.o .libs/libvmtools_la-monotonicTimer.o .libs/libvmtools_la-signalSource.o .libs/libvmtools_la-vmtools.o .libs/libvmtools_la-vmtoolsConfig.o .libs/libvmtools_la-vmtoolsLog.o .libs/libvmtools_la-vmxLogger.o .libs/libvmtools_la-guestSDKLog.o .libs/libvmtools_la-stub-log.o  -Wl,--whole-archive ../lib/lock/.libs/libLock.a ../lib/backdoor/.libs/libBackdoor.a ../lib/asyncsocket/.libs/libAsyncSocket.a ../lib/sslDirect/.libs/libSslDirect.a ../lib/pollGtk/.libs/libPollGtk.a ../lib/poll/.libs/libPoll.a ../lib/dataMap/.libs/libDataMap.a ../lib/hashMap/.libs/libHashMap.a ../lib/dict/.libs/libDict.a ../lib/dynxdr/.libs/libDynxdr.a ../lib/err/.libs/libErr.a ../lib/file/.libs/libFile.a ../lib/glibUtils/.libs/libGlibUtils.a ../lib/guestApp/.libs/libGuestApp.a ../lib/guestRpc/.libs/libGuestRpc.a ../lib/message/.libs/libMessage.a ../lib/netUtil/.libs/libNetUtil.a ../lib/nicInfo/.libs/libNicInfo.a ../lib/panic/.libs/libPanic.a ../lib/procMgr/.libs/libProcMgr.a ../lib/rpcChannel/.libs/libRpcChannel.a ../lib/rpcIn/.libs/libRpcIn.a ../lib/rpcOut/.libs/libRpcOut.a ../lib/rpcVmx/.libs/libRpcVmx.a ../lib/string/.libs/libString.a ../lib/syncDriver/.libs/libSyncDriver.a ../lib/system/.libs/libSystem.a ../lib/stubs/.libs/libStubsCS.a ../lib/unicode/.libs/libUnicode.a ../lib/user/.libs/libUser.a ../lib/vmCheck/.libs/libVmCheck.a ../lib/vmSignal/.libs/libVmSignal.a ../lib/wiper/.libs/libWiper.a ../lib/misc/.libs/libMisc.a ../lib/slashProc/.libs/libSlashProc.a -Wl,--no-whole-archive  -ldnet -ldl -lrt -lcrypt -lpthread -lglib-2.0  -Wl,-z -Wl,defs -Wl,-lc   -Wl,-soname -Wl,libvmtools.so.0 -o .libs/libvmtools.so.0.0.0
../lib/wiper/.libs/libWiper.a(wiperPosix.o): In function `WiperIsDiskDevice':
/tmp/open-vm-tools-10.1.0-4449150/open-vm-tools/lib/wiper/wiperPosix.c:319: undefined reference to `major'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:418: libvmtools.la] Error 1
make[1]: Leaving directory '/tmp/open-vm-tools-10.1.0-4449150/open-vm-tools/libvmtools'
make: *** [Makefile:389: all-recursive] Error 1
supercell open-vm-tools #

Compiled with:

./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/open-vm-tools-10.1.0-r1 --htmldir=/usr/share/doc/open-vm-tools-10.1.0-r1/html --libdir=/usr/lib64 --disable-deploypkg --disable-static --disable-tests --with-procps --with-dnet --disable-docs --disable-grabbitmqproxy --disable-vgauth --disable-multimon --without-icu --with-pam --with-pic --without-gtk2 --without-gtkmm --without-gtk3 --without-gtkmm3 --without-x --without-kernel-modules --without-root-privileges --with-kernel-release=4.9.7-gentoo

The system is very up to date and has gcc-6.3.0, glibc-2.24  and other very up to date packages.  If this is not a syntax error in the open-vm-tools, please let me know what other packages could be contributing to this.

**Comment by oliverkurth** [comment]
major() is defined in sys/types.h, see https://linux.die.net/man/3/major.

Could you please try adding the line
#include <sys/types.h>
at the beginning of the file lib/wiper/wiperPosix.c, and try again?

**Comment by reubenfarrelly** [comment]
That fixed it - after that addition open-vm-tools compiled right the way through to completion.

**Comment by oliverkurth** [comment]
Thanks @reubenfarrelly. I filed an internal bug for this issue.

**Comment by reubenfarrelly** [comment]
It turns out that the problem is actually due to a change in a recent release of glibc.  For me glibc-2.24 compiles, but with glibc-2.25 open-vm-tools does not.

Release notes for glibc-2.25 state:

-------

* The inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated.
  This means that in a future release, the macros “major”, “minor”, and
  “makedev” will only be available from <sys/sysmacros.h>.

  These macros are not part of POSIX nor XSI, and their names frequently
  collide with user code; see for instance glibc bug 19239 and Red Hat
  bug 130601.  <stdlib.h> includes <sys/types.h> under _GNU_SOURCE, and
  C++ code presently cannot avoid being compiled under _GNU_SOURCE,
  exacerbating the problem.

-------

I suspect that this change in glibc behaviour is actually the root cause of the problem and the include of <sys/types.h> as suggested earlier in the thread might not be the correct fix going forward.  We may need to instead include <sys/sysmacros.h> .

Reuben

**Comment by oliverkurth** [comment]
That is interesting, good to know. Thank you for this additional information!

**Comment by biship** [comment]
I added #include sys/sysmacros.h to wiperPosix.c and it compiled for me (opensuse tumbleweed x86_64).

**Comment by oliverkurth** [comment]
Fixed with https://github.com/vmware/open-vm-tools/commit/4c20c27ee1b3d0c88ee5d6e41b88a5c94432dbcc
