### ISSUE TITLE
Licensing/copyright issues: open-vm-tools/lib/string/convertutf.c

### ISSUE THREAD

**Issue by bzed** [vmware/open-vm-tools#148]
According to the Debian Free Software Guidelines, the file is not redistributable. Please see the bug against ghostscript for details: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823100
As it seems the code was even removed by the unicode consortium as being buggy and broken.
http://unicode.org/forum/viewtopic.php?f=9&t=90

Please migrate to libicu or something similar.

**Comment by oliverkurth** [comment]
Fixed with commit 42ac2a1eca59453870d8f09b83948f3c04c559c3 in the devel branch.
