### ISSUE TITLE
CentOS 7.2 64-bit detected as CentOS 4/5 or later (64-bit)

### ISSUE THREAD

**Issue by claudiu-matei** [vmware/open-vm-tools#149]
I have installed open-vm-tools-10.0.5-4.el7_3.x86_64 on CentOS Linux release 7.2.1511.
The VM's Guest OS setting is "CentOS 7 (64- bit)"
The reported guest OS version in vSphere Client 6.0.0 is "CentOS 4/5 or later (64-bit)".
For this reason, I am getting a warning in the embedded HTML5 client reading that the VM GuestOS setting does not correspond to the detected version

**Comment by lemke1458** [comment]
See https://github.com/vmware/open-vm-tools/issues/135

**Comment by johnwvmw** [comment]
Thanks David


John

________________________________

**Comment by claudiu-matei** [comment]
Thank you!
