### ISSUE TITLE
Multiple monitors and copy/paste does not work (Debian 9.0, Linux 4.9.0)

### ISSUE THREAD

**Issue by fsch2** [vmware/open-vm-tools#157]
Hi there,

I have open-vm-tools, open-vm-tools-desktop and open-vm-tools-dkms installed in the packaged version of my OS: open-vm-tools (2:10.1.5-5055683-3)

Still the **multiple monitors** feature and the **copy/paste** feature does not work. The symptoms in the first case: When I click the button to cycle multiple monitors, the software says, that I need to have up-to-date VM Tools installed.

My specs:
- Debian Stretch 9.0
- Linux 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux
- open-vm-tools (2:10.1.5-5055683-3)
- Host: VMware Workstation Player 12 on Windows 7

What can I do to further diagnose/fix the problem?

**Comment by oliverkurth** [comment]
First, please check if there is a user process of vmtoolsd running, it should look similar to this (one process running with '-n vmusr'):

```
~> ps awx | grep vmtoo
 1177 ?        Sl     4:09 /usr/bin/vmtoolsd
 2292 ?        Sl     3:58 /usr/bin/vmtoolsd -n vmusr
 6417 pts/0    S+     0:00 grep --color=auto vmtoo

```
If this is not the case, start it with `vmware-user-suid-wrapper`. It should have been started automatically by the desktop environment though. Are you using gnome, KDE or another desktop environment?

Does automatic screen resolution set work?

To further debug, you can enable debugging with these settings in /etc/vmware-tools/tools.conf, and attach the generated log file:

```
# Enable new "vmusr" service logging to a file.
vmusr.level = debug
vmusr.handler = file
vmusr.data = /tmp/vmware-vmusr.${USER}.log
```

You can also attach the file vmware.log, which should be in the same folder where your VM is.

Also, you don't need the open-vm-tools-dkms package - all kernel modules are either part of the Linux kernel, or have been replaced with fuse. I don't think this is the cause of your issue, but you can try uninstalling that package.

**Comment by fsch2** [comment]
Automatic screen resolutions works correctly.

I did not have the user process and was not able to start it because of the error:
> vmware-user: could not open /proc/fs/vmblock/dev

The I purged open-vm-tools-dev and -dkms from my system and -- finally -- both multiple monitors and copy/paste works flawlessly. Thanks a lot for the hints!

BTW, I use XFCE as a desktop environment.

**Comment by oliverkurth** [comment]
Thanks @fsch2 for feedback!

The error `vmware-user: could not open /proc/fs/vmblock/dev` can be ignored. It will start the vmtoolsd user process in the background. I think that this really fixed the problem.

I noticed that the Debian package open-vm-tools-desktop has a `Recommends:` for open-vm-tools-dkms, this may be the reason why you had it installed. I just tested installing it, and it just builds a driver for vmxnet, (which is deprecated). I don't see how that would cause these issues.

**Comment by oliverkurth** [comment]
> The error vmware-user: could not open /proc/fs/vmblock/dev can be ignored. It will start the vmtoolsd user process in the background. I think that this really fixed the problem.

Sorry, that's not completely true. Drag and drop won't work (but copy/paste and resolution settings do).

This fixes it - looks like there is a bug in the Debian package:

```
sudo systemctl start run-vmblock\\x2dfuse.mount
sudo systemctl enable run-vmblock\\x2dfuse.mount
```

**Comment by fsch2** [comment]
Thanks for taking the time to investigate! 😄
