### ISSUE TITLE
Error building open-vm-tools 10.1.5 with Mac OS

### ISSUE THREAD

**Issue by youngsoldier** [vmware/open-vm-tools#161]
Got the latest release from https://github.com/vmware/open-vm-tools/releases.
My Mac info: uname -a
Darwin 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

First, got the error:
`Making all in backdoor
 cd ../.. && /bin/sh ./config.status lib/backdoor/Makefile depfiles
config.status: creating lib/backdoor/Makefile
config.status: executing depfiles commands
/bin/sh ../../libtool --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"2016.09.29\" -DPACKAGE_STRING=\"open-vm-tools\ 2016.09.29\" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"2016.09.29\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DHAVE_DLOPEN=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_PROCPS=1 -DNO_DNET=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -DNO_XSM=1 -DNO_XCOMPOSITE=1 -DNO_MULTIMON=1 -I.   -I/Users/charles/Downloads/open-vm-tools-10.1.0-4449150/lib/include -I/Users/charles/Downloads/open-vm-tools-10.1.0-4449150/lib/include  -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -DNO_ICU -DVMX86_TOOLS  -g -O2 -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-const-variable -MT backdoorGcc32.lo -MD -MP -MF .deps/backdoorGcc32.Tpo -c -o backdoorGcc32.lo backdoorGcc32.c
libtool: compile:  gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"2016.09.29\" "-DPACKAGE_STRING=\"open-vm-tools 2016.09.29\"" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"2016.09.29\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DHAVE_DLOPEN=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_PROCPS=1 -DNO_DNET=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -DNO_XSM=1 -DNO_XCOMPOSITE=1 -DNO_MULTIMON=1 -I. -I/Users/charles/Downloads/open-vm-tools-10.1.0-4449150/lib/include -I/Users/charles/Downloads/open-vm-tools-10.1.0-4449150/lib/include -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -DNO_ICU -DVMX86_TOOLS -g -O2 -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-const-variable -MT backdoorGcc32.lo -MD -MP -MF .deps/backdoorGcc32.Tpo -c backdoorGcc32.c  -fno-common -DPIC -o .libs/backdoorGcc32.o
backdoorGcc32.c:86:9: error: instruction requires: Not 64-bit mode
        "pushl %%ebx"           "\n\t"
        ^
<inline asm>:1:2: note: instantiated into assembly here
        pushl %ebx
        ^
backdoorGcc32.c:86:36: error: instruction requires: Not 64-bit mode
        "pushl %%ebx"           "\n\t"
                                   ^
<inline asm>:2:2: note: instantiated into assembly here
        pushl %eax
        ^
backdoorGcc32.c:101:36: error: instruction requires: Not 64-bit mode
        "movl %%ebx,  4(%%eax)" "\n\t"
                                   ^
<inline asm>:16:2: note: instantiated into assembly here
        popl          (%eax)
        ^
backdoorGcc32.c:102:36: error: instruction requires: Not 64-bit mode
        "popl          (%%eax)" "\n\t"
                                   ^
<inline asm>:17:2: note: instantiated into assembly here
        popl %ebx
        ^
backdoorGcc32.c:146:9: error: instruction requires: Not 64-bit mode
        "pushl %%ebx"           "\n\t"
        ^
<inline asm>:1:2: note: instantiated into assembly here
        pushl %ebx
        ^
backdoorGcc32.c:146:36: error: instruction requires: Not 64-bit mode
        "pushl %%ebx"           "\n\t"
                                   ^
<inline asm>:2:2: note: instantiated into assembly here
        pushl %ebp
        ^
backdoorGcc32.c:148:36: error: instruction requires: Not 64-bit mode
        "pushl %%ebp"           "\n\t"
                                   ^
<inline asm>:3:2: note: instantiated into assembly here
        pushl %eax
        ^
backdoorGcc32.c:166:36: error: instruction requires: Not 64-bit mode
        "movl %%ebx,  4(%%eax)" "\n\t"
                                   ^
<inline asm>:20:2: note: instantiated into assembly here
        popl          (%eax)
        ^
backdoorGcc32.c:167:36: error: instruction requires: Not 64-bit mode
        "popl          (%%eax)" "\n\t"
                                   ^
<inline asm>:21:2: note: instantiated into assembly here
        popl %ebp
        ^
backdoorGcc32.c:169:36: error: instruction requires: Not 64-bit mode
        "popl %%ebp"            "\n\t"
                                   ^
<inline asm>:22:2: note: instantiated into assembly here
        popl %ebx
        ^
backdoorGcc32.c:195:9: error: instruction requires: Not 64-bit mode
        "pushl %%ebx"           "\n\t"
        ^
<inline asm>:1:2: note: instantiated into assembly here
        pushl %ebx
        ^
backdoorGcc32.c:195:36: error: instruction requires: Not 64-bit mode
        "pushl %%ebx"           "\n\t"
                                   ^
<inline asm>:2:2: note: instantiated into assembly here
        pushl %ebp
        ^
backdoorGcc32.c:197:36: error: instruction requires: Not 64-bit mode
        "pushl %%ebp"           "\n\t"
                                   ^
<inline asm>:3:2: note: instantiated into assembly here
        pushl %eax
        ^
backdoorGcc32.c:215:36: error: instruction requires: Not 64-bit mode
        "movl %%ebx,  4(%%eax)" "\n\t"
                                   ^
<inline asm>:20:2: note: instantiated into assembly here
        popl          (%eax)
        ^
backdoorGcc32.c:216:36: error: instruction requires: Not 64-bit mode
        "popl          (%%eax)" "\n\t"
                                   ^
<inline asm>:21:2: note: instantiated into assembly here
        popl %ebp
        ^
backdoorGcc32.c:218:36: error: instruction requires: Not 64-bit mode
        "popl %%ebp"            "\n\t"
                                   ^
<inline asm>:22:2: note: instantiated into assembly here
        popl %ebx
        ^
16 errors generated.
make[2]: *** [backdoorGcc32.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1`

And I try to delete '32' related codes in  backdoorGcc32.c. It works!
Then there is the error:
`fileIOPosix.c:56:10: fatal error: 'sysSocket.h' file not found`
<img width="805" alt="syssocket not found" src="https://cloud.githubusercontent.com/assets/2947938/25422095/3405c448-2a92-11e7-9274-322f0af58234.png">

**Comment by youngsoldier** [comment]
If possible, change the header from "sysSocket.h" to #include <socket.h>, it continues successfully.


BUT, another error :(
`libtool: link: ( cd ".libs" && rm -f "libHgfsHelper.la" && ln -s "../libHgfsHelper.la" "libHgfsHelper.la" )
Making all in hgfsServer
/bin/sh ../../libtool --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.1.5\" -DPACKAGE_STRING=\"open-vm-tools\ 10.1.5\" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.1.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DHAVE_DLOPEN=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_PROCPS=1 -DNO_DNET=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -DNO_XSM=1 -DNO_XCOMPOSITE=1 -DNO_MULTIMON=1 -I.   -I/Users/charles/Downloads/open-vm-tools-10.1.5-5055683/lib/include -I/Users/charles/Downloads/open-vm-tools-10.1.5-5055683/lib/include  -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -DNO_ICU -DVMX86_TOOLS -DVMTOOLS_USE_GLIB -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/Cellar/pcre/8.40/include -g -O2 -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-const-variable -MT hgfsServer.lo -MD -MP -MF .deps/hgfsServer.Tpo -c -o hgfsServer.lo hgfsServer.c
libtool: compile:  gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.1.5\" "-DPACKAGE_STRING=\"open-vm-tools 10.1.5\"" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.1.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DX_DISPLAY_MISSING=1 -DHAVE_DLOPEN=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_PROCPS=1 -DNO_DNET=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -DNO_XSM=1 -DNO_XCOMPOSITE=1 -DNO_MULTIMON=1 -I. -I/Users/charles/Downloads/open-vm-tools-10.1.5-5055683/lib/include -I/Users/charles/Downloads/open-vm-tools-10.1.5-5055683/lib/include -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -DNO_ICU -DVMX86_TOOLS -DVMTOOLS_USE_GLIB -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/Cellar/pcre/8.40/include -g -O2 -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-const-variable -MT hgfsServer.lo -MD -MP -MF .deps/hgfsServer.Tpo -c hgfsServer.c  -fno-common -DPIC -o .libs/hgfsServer.o
hgfsServer.c:6226:44: error: taking address of packed member 'actualSize' of class or structure 'HgfsReplyReadV3' may
      result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
                                          &reply->actualSize);
                                           ^~~~~~~~~~~~~~~~~
hgfsServer.c:6247:57: error: taking address of packed member 'actualSize' of class or structure 'HgfsReplyRead' may
      result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
                                       reply->payload, &reply->actualSize);
                                                        ^~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [hgfsServer.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
`

**Comment by jfarwell-vmware** [comment]
Hi youngsoldier,

Building open-vm-tools for macOS is not supported, and in fact I'm not sure if anyone has ever tried before, so I'm not sure how feasible it is. That said, I'll try to provide some assistance:

1. Replacing sysSocket.h with <socket.h> is the correct workaround, yes.

2. We have not seen this warning before, and we don't entirely understand it because although that structure is packed, the 'actualSize' member is preceded only by a uint32 and an enum (which should also be 32-bits) and thus should be 64-bit aligned. What compiler are you using and what architecture are you building for? The code in question has really only been tested using Apple's clang toolchain from Xcode 7.x and for x86_64. If you are building for a different architecture then the warning may be viable. Otherwise, if you are building with a toolchain that is not Apple's clang, or you are building with a newer version it's possible your compiler is simply being stricter, but I do not believe that the particular line in question is a problem, so you can hopefully pass -Wno-address-of-packed-member to work around it.

**Comment by stanguturi** [comment]
> -c hgfsServer.c -fno-common -DPIC -o .libs/hgfsServer.o hgfsServer.c:6226:44: error: taking address of packed member 'actualSize' of class or structure 'HgfsReplyReadV3' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member] &reply->actualSize); ^~~~~~~~~~~~~~~~~ hgfsServer.c:6247:57: error: taking address of packed member 'actualSize' of class or structure 'HgfsReplyRead' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member] reply->payload, &reply->actualSize); ^~~~~~~~~~~~~~~~~ 2 errors generated. make[2]: *** [hgfsServer.lo] Error 1 make[1]: *** [all-recursive] Error 1 make: *** [all-recursive] Error 1

The above issue was fixed in c68172e in devel branch.

Anyway, building open-vm-tools for macOS is not supported and also never tried/tested. Closing the issue.
