### ISSUE TITLE
With Large Receive Offload (LRO) enabled under FreeBSD 11 virtual machine as a router, outgoing speed of forwarded traffic becomes 500 times slower with VMXNET3 on HP Proliant G8/G9 (Broadcom BCM5719 enthernet controller chipset)!!

### ISSUE THREAD

**Issue by maximmasiutin** [vmware/open-vm-tools#166]
Thank you for the excellent open-vm-tools package!

With Large Receive Offload (LRO) enabled under FreeBSD 11 virtual machine as a router, outgoing speed of forwarded traffic becomes 500 times slower with VMXNET3 on HP Proliant G8/G9 (Broadcom BCM5719 enthernet controller chipset)!!

We are using it with pfSense (under FreeBSD 11) virtual appliances (virtual machine) under VMWare ESXi hosts on HP Proliant G8/G9 servers, all virtual machines have 1-2 VMXNET3 adapters.

We have tried pfSense version from 2.3.0-RELEASE to 2.4.0-BETA (built on Fri May 26 19:15:04 CDT 2017), Open-VM-Tools package 10.1.0,1, FreeBSD 11.0-RELEASE-p10.

We have tried VMWare ESXi version from 6.0 to 6.5.0 with all Hewlett-Packard drivers (highest version of ESXi that we’ve used is HPE Customized Image ESXi 6.5.0 version 650.9.6.5.27 released on May 2017 and based on ESXi 6.5.0 Vmkernel Release Build 5146846).

Regardless of the pfSense version or the VMWare version, on FreeBSD 11.0-RELEASE-p10, if I un-check an option in pfSense to “Disable hardware large receive offload” (to enable hardware large receive offload) – the virtual machines that are routed via pfSense (FreeBSD) have very low upload speed (about 1/500th of their normal speed) or drop connections. To get their speed back to normal, I have to check this option ON.

Other hardware offload options do not have problems – i have them unchecked to enable hardware offload of checksums and TCP segmentation.

The Broadcom BCM5719 chipset, that supports Large Receive Offload (LRO) is quite cheap and ubiquitous, released in 2013. VMWare has added support of hardware LRO to VMXNET3 also in 2013. In Windows, LRO is supported since Windows Server 2012 and Windows 8 (since 2012). FreeBSD supports it from version 8 (since 2009).

There is Open-VM-Tools 10.1.5 version already available at https://github.com/vmware/open-vm-tools/ , maybe it fixes the issue with Large Receive Offload (LRO) under FreeBSD with VMXNET3?

I saw some forum messages where people discourage using VMXNET3 adapter, in favour of E1000 adapter, quote from https://forum.pfsense.org/index.php?topic=98309.0  :  „We saw much better performance from the E1000 than VMXnet2 and 3”.

There is a VMWare blog on the benefits of LRO for Linux and Windows – see https://blogs.vmware.com/performance/2015/06/vmxnet3-lro.html According to this blog entry, LRO saves valuable CPU cycles, and is also very beneficial in VM-VM local traffic where VMs are located in the same host, communicating with each other through a virtual switch.

I suspect that the problem is somewhere in the open-vm-tools-nox11 package - may it includes not fully compatible or not fully stable VMWare drivers for VMXNET3 -- because Windows machines from our servers connected to Internet either directly or via pfSense have LRO enabled and don’t have performance degradation.

There is definitely an incompatibility issues in open-vm-tools on VMXNET3 under FreeBSD with Large Receive Offload (LRO)! Other hadware TCP offload are working properlly, because VMXNET3 under Windows makes LRO correctly!

**Comment by oliverkurth** [comment]
Thanks @maximmasiutin for reporting!

We filed a bug at FreeBSD for this issue, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219672 . Feel free to add to the discussion there. We also filed an internal bug.

It seems that this may be a misconfiguration. LRO is not recommended to be used with pfSense, if used as a router, see https://doc.pfsense.org/index.php/Advanced_Setup :+1: 

> LRO works by aggregating multiple incoming packets from a single stream into a larger buffer before they are passed higher up the networking stack, thus reducing the number of packets to be processed. LRO should not be used on machines acting as routers as it breaks the end-to-end principle and can significantly impact performance. pfSense is most frequently used as a router or an equivalent.

**Comment by maximmasiutin** [comment]
Hello Oliver,

Thank you very much, there was indeed a misconfiguration. pfSense do not recommend using hardware LRO ans TSO if it used as a router, they only recommend hardware offload for end-points.

However, the speed did drop very sharp, from around 80 megabits to 0.5 megabits, and the connections sometimes were dropped. That's why I have concluded that there also might have been a bug; the misconfiguration alone could not have such a huge consequence.


-- 
Maxim Masiutin
Director
Ritlabs, SRL

**Comment by rduffner** [comment]
Can you ask the pfsense-guys about this?

**Comment by maximmasiutin** [comment]
Hello Rainer,

Wednesday, May 31, 2017, 9:39:03 PM, you wrote:

> Can you ask the pfsense-guys about this?

OK, will do!

-- 
Maxim Masiutin
Director
Ritlabs, SRL

**Comment by rduffner** [comment]
Thank you!

**Comment by maximmasiutin** [comment]
pfSense guys have provided the information, I have posted it to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219672 (not sure if you are subscribed to receive updates to that entry)

**Comment by oliverkurth** [comment]
We can close this issue here, it seems to have been properly answered by Mark Peek in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219672#c3 . I'll copy it here:

> From my testing this is not a bug and everything is working as designed. I am seeing a large decrease in performance when LRO is turned on and using pfSense as a gateway. This is due to the originating packets having the IP DF (don’t fragment) flag set which then gets combined into larger packets via LRO. When this (larger) packet needs to be fragmented to match the other NIC the FreeBSD kernel sees the DF flag, drops the packet, and then sends back an ICMP “unreachable - need to frag” message to the sender. The reason it works at all is due to other traffic which disallows the LRO to occur and some packets get forwarded.
> 
> One test I did was turning LRO on and using scp to put a file onto the pfSense appliance which resulted in good performance (not seeing the same drop in performance). I would be interested if you 1) see good performance with LRO turned on and scp a large file to the appliance and 2) see ICMP "need to frag" with LRO turned on and scp to a machine on the remote side.
> 
> Since the pfSense appliance is being used as a gateway you should leave LRO turned off.

Thanks all!
