### ISSUE TITLE
open-vm-tools 10.1.5 build kernel modules with linux-4.9.31

### ISSUE THREAD

**Issue by CaptWiggum** [vmware/open-vm-tools#168]
On CentOS7 we build our own vanilla linux kernel from upstream 4.9.x.

For past kernels (pre 4.9) we could build the open-vm-tools modules and install them into our kernel build tree, like so:
$ autoreconf -i
$ ./configure --with-linuxdir=/home/admin/WORK/os/PACKAGES/kernel49/WORK/kernel49-root/lib/modules/4.9.31-1.el7.x86_64 --with-kernel-release=4.9.31-1.el7.x86_64 --with-kernel-modules --without-icu --without-dnet --without-x --without-xerces
$ make -C modules all
$ make -C modules DEPMOD=: MODULES_DIR=/home/admin/WORK/os/PACKAGES/kernel49/WORK/kernel49-root/lib/modules/4.9.31-1.el7.x86_64/kernel install-exec-hook

Now with 4.9.x kernel, the configure succeeds, but the "make -C modules all" just says "make: Nothing to be done for all"

I notice in the kernel build tree, there are no module Kconfig nor sub-dirs for any of the open-vm-tools modules. Do I need to create these in the kernel build tree?

**Comment by CaptWiggum** [comment]
Actually, I looked back at our build of open-vm-tools modules for linux 3.18

The kernel build tree is very similar. I.e. it does not contain a Kconfig nor sub-dirs for the modules that are found in open-vm-tools. Yet the process I note above in the first post works perfectly to build the modules for linux 3.18.x.

So then, why does the same process for kernel 4.9.x say "Nothing to be done" 
and the open-vm-tools makefile does not attempt to build any modules at all?

**Comment by oliverkurth** [comment]
What modules are you missing from the 4.9 kernel tree? All VMware modules are part of the kernel or are obsolete. For linux kernel 4.0 and greater, modules are not built any longer by default - this is why you see nothing being built at all. We are going to remove kernel modules for Linux completely in future versions of open-vm-tools.

**Comment by CaptWiggum** [comment]
Thank you very much for the reply.

I understand what you are saying. The only module I really miss is vmhgfs.ko. Is that no longer supported?

On the 3.18.x kernel, both open-vm-tools 10.0.5 and 10.1.5 builds vmhgfs.ko (but no other modules). But on 4.9.x kernel, it does not build any modules. Should it at least build vmhgfs.ko?

**Comment by oliverkurth** [comment]
For Linux >= 4.0, the vmhgfs kernel module is replaced by vmhgfs over fuse. You can use the vmhgfs-fuse command to mount shares.

**Comment by CaptWiggum** [comment]
Thank you very much! That explains it. Problem solved.

**Comment by oliverkurth** [comment]
Glad that I could help!
