### ISSUE TITLE
how to disable /var/log/vmware-vmsvc.log 

### ISSUE THREAD

**Issue by 400thecat** [vmware/open-vm-tools#177]
I am using open-vm-tools 2:10.1.5 in Debian Stretch. 

open-vm-tools creates a log file in /var/log/vmware-vmsvc.log, which grows out of proportions.

I looked in /etc/vmware-tools/ how to disable, but found no configuration options to disable logging. Specifically, the file tools.conf is empty. Even when I add following two lines, it still has no effect:

    [logging]
    log=false

How can I disable logging entirely, and get rid of /var/log/vmware-vmsvc.log ?

**Comment by epavser** [comment]
Probably you can toggle this one?

https://github.com/vmware/open-vm-tools/blob/e0a7b4e98bd6d6af06d31212dfdc82610d37e4d3/open-vm-tools/lib/include/vmware/tools/log.h#L113

**Comment by oliverkurth** [comment]
@epavser is right, this setting in tools.conf works:
```
[logging]
vmsvc.level = none
```
But I am wondering why the log "grows out of proportions". Maybe there is an issue that needs attention in the log file? How much does it grow per, say, an hour?

**Comment by oliverkurth** [comment]
@400thecat do you have any more information on this issue, see my last comment? If not I will close this issue.

**Comment by stanguturi** [comment]
Setting the vmsvc.log option to none (as mentioned previous comments) solves the issue. Closing this issue.
