### ISSUE TITLE
Build doesn't seem to create any binaries

### ISSUE THREAD

**Issue by bselack** [vmware/open-vm-tools#179]
Following the build for open-vm-tools (because I need the 10.1.x series, I followed https://github.com/vmware/open-vm-tools/wiki

And it seems to build, but I get nothing installed. Particularly trying the get vmhgfs-fuse.

I don't do a lot of building on linux, but the build itself seemed to be fine. Am I missing a step to get any of the binaries?

**Comment by oliverkurth** [comment]
Which distribution and version is this? Can you attach log files? You can do for example:

```
autoreconf -i 2>&1 | tee autoreconf.out
./configure --without-kernel-modules 2>&1 | tee configure.out
make 2>&1 | tee make.out
sudo make install 2>&1 | tee install.out
```
and then attach the *.out files.

How did you determine that there are no binaries installed? By default, binaries will be installed to `/usr/local`, so did you look into `/usr/local/bin` ?

Also, after installing, you may have to call `sudo ldconfig` (I need to add that to the wiki).

**Comment by bselack** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

.out files attached.

Looked in usual places, had moved vmhgfs-fuse to vmhgfs-fuse.bak.

User locate (after updated) and only found the renamed one

Thanks.

[out_logs.zip](https://github.com/vmware/open-vm-tools/files/1154034/out_logs.zip)

**Comment by bselack** [comment]
Contents of /urs/local/bin

vmtoolsd
vmware-checkvm
vmware-guestproxycerttool
vmware-hgfsclient
vmware-namespace-cmd
vmware-rpctool
vmware-toolbox-cmd
vmware-user-suid-wrapper
vmware-vgauth-cmd
vmware-xferlogs

Maybe I'm expecting something different ... was using vmhgfs-fuse

**Comment by oliverkurth** [comment]
Here is the problem, from configure.out:

```
checking for fuse (via pkg-config)... no
configure: WARNING: Fuse is missing, vmblock-fuse/vmhgfs-fuse will be disabled.
```
On Ubuntu, you can install the fuse development files with `apt-get install install libfuse-dev`.

**Comment by bselack** [comment]
Thanks so much! That was the issue. Missed it because of the warning.

Also this now fixes the issue I was having with git clone to a shared dircetory. Appreciate the help and all your work.
