### ISSUE TITLE
 error: ‘struct net_device’ has no member named ‘do_ioctl’

### ISSUE THREAD

**Issue by teliot** [vmware/open-vm-tools#18]
mv -f .deps/xferlogs.Tpo .deps/xferlogs.Po
/bin/sh ../libtool --tag=CXX   --mode=link g++  -g -O2   -o vmware-xferlogs xferlogs.o /root/open-vm-tools/open-vm-tools-9.10.0-2476743/libvmtools/libvmtools.la -lglib-2.0  -L/usr/lib64 -licui18n -licuuc -licudata
libtool: link: g++ -g -O2 -o .libs/vmware-xferlogs xferlogs.o  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/libvmtools/.libs/libvmtools.so -L/usr/lib64 -ldnet -ldl -lrt -lcrypt -lpthread -lssl -lcrypto -lglib-2.0 -licui18n -licuuc -licudata
make[1]: Leaving directory '/root/open-vm-tools/open-vm-tools-9.10.0-2476743/xferlogs'
Making all in modules
make[1]: Entering directory '/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules'
make VM_UNAME=3.18.11-gentoo MV=mv RM=rm      \
   OVT_SOURCE_DIR=/root/open-vm-tools/open-vm-tools-9.10.0-2476743                 \
   MODULEBUILDDIR=/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux        \
    -C "/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet"
make[2]: Entering directory '/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet'
Using kernel build system.
make -C /lib/modules/3.18.11-gentoo/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR=/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux modules
make[3]: Entering directory '/usr/src/linux-3.18.11-gentoo'
make[3]: Warning: File '.vmlinux.cmd' has modification time 2450903 s in the future
make[4]: Warning: File 'include/config/auto.conf' has modification time 2450395 s in the future
  CC [M]  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet/vmxnet.o
In file included from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet/vmxnet.c:54:0:
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/lib/include/vm_device_version.h:56:0: warning: "PCI_VENDOR_ID_VMWARE" redefined [enabled by default]
 #define PCI_VENDOR_ID_VMWARE                    0x15AD
 ^
In file included from include/linux/pci.h:34:0,
                 from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/shared/compat_pci.h:27,
                 from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet/vmxnet.c:31:
include/linux/pci_ids.h:2248:0: note: this is the location of the previous definition
 #define PCI_VENDOR_ID_VMWARE  0x15ad
 ^
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet/vmxnet.c: In function ‘vmxnet_probe_device’:
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet/vmxnet.c:1148:7: error: ‘struct net_device’ has no member named ‘do_ioctl’
    dev->do_ioctl = vmxnet_ioctl;
       ^
scripts/Makefile.build:263: recipe for target '/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet/vmxnet.o' failed
make[4]: **\* [/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet/vmxnet.o] Error 1
Makefile:1381: recipe for target '_module_/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet' failed
make[3]: **\* [_module_/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet] Error 2
make[3]: Leaving directory '/usr/src/linux-3.18.11-gentoo'
Makefile:120: recipe for target 'vmxnet.ko' failed
make[2]: **\* [vmxnet.ko] Error 2
make[2]: Leaving directory '/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmxnet'
Makefile:500: recipe for target 'vmxnet' failed
make[1]: **\* [vmxnet] Error 2
make[1]: Leaving directory '/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules'
Makefile:361: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1
localhost open-vm-tools-9.10.0-2476743 #

will look at https://github.com/davispuh/open-vm-tools/commit/08836a47c56b47b658025e41a20027c5d915f836.patch and https://github.com/rasa/vmware-tools-patches for a fix for now.

**Comment by oliverkurth** [comment]
Hi teliot,
what is the environment on which you are trying to build, like distribution, kernel version, gcc version? Also, for this particular error, there is a good chance that VMware specific drivers are already included in your kernel, so you do not need to build all kernel modules, except vmhgfs. Try configuring with --without-kernel-modules.

**Comment by teliot** [comment]
editing out vmxnet in ./configure did the trick. --without-kernel-modules would have worked as well.

**Comment by teliot** [comment]
distro is gentoo



localhost open-vm-tools-9.10.0-2476743 # emerge --info
Portage 2.2.18 (python 2.7.9-final-0, default/linux/amd64/13.0, gcc-4.8.4, glibc-2.20-r2, 3.18.11-gentoo x86_64)
=================================================================
System uname: Linux-3.18.11-gentoo-x86_64-Intel-R-_Core-TM-_i7_CPU_Q_840_@_1.87GHz-with-gentoo-2.2
KiB Mem:     2053344 total,   1143264 free
KiB Swap:    8387580 total,   8387580 free
Timestamp of repository gentoo: Thu, 07 May 2015 02:30:01 +0000
sh bash 4.2_p53
ld GNU ld (Gentoo 2.24 p1.4) 2.24
app-shells/bash:          4.2_p53::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.9-r1::gentoo, 3.3.5-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.13.11::gentoo
sys-apps/sandbox:         2.6-r1::gentoo
sys-devel/autoconf:       2.69::gentoo
sys-devel/automake:       1.13.4::gentoo
sys-devel/binutils:       2.24-r3::gentoo
sys-devel/gcc:            4.8.4::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 3.18::gentoo (virtual/os-headers)
sys-libs/glibc:           2.20-r2::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe -D_DEFAULT_SOURCE"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=native -O2 -pipe -D_DEFAULT_SOURCE"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j5"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
USE="acl amd64 berkdb bindist bzip2 cli cracklib crypt cxx dri fortran gdbm iconv ipv6 mmx mmxext modules multilib ncurses nls nptl openmp pam pcre readline session sse sse2 ssl tcpd unicode zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_3" RUBY_TARGETS="ruby19 ruby20" USERLAND="GNU" VIDEO_CARDS="fbdev glint intel mach64 mga nouveau nv r128 radeon savage sis tdfx trident vesa via vmware dummy v4l" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CPPFLAGS, CTARGET, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

localhost open-vm-tools-9.10.0-2476743 #

**Comment by stanguturi** [comment]
> editing out vmxnet in ./configure did the trick. --without-kernel-modules would have worked as well.

Thanks for trying out '--without-kernel-modules' option. Closing.
