### ISSUE TITLE
post and pre freeze script are not executed in centos6

### ISSUE THREAD

**Issue by grocanar** [vmware/open-vm-tools#180]
Hi
i m trying to execute free and post free script while backing up
i have open-vm-tools 10.1.5 installed on a centos6 machine through epel

[root@srvigxprd002 sbin]# ls -l /usr/sbin/post-thaw-script
-rwxr-xr-x 1 root root 495 18 juil. 11:03 /usr/sbin/post-thaw-script
[root@srvigxprd002 sbin]# ls -l /usr/sbin/pre-freeze-script
-rwxr-xr-x 1 root root 1476 18 juil. 11:03 /usr/sbin/pre-freeze-script

but these script are not launched

i have created the tools.conf file with the following content 
[logging]
log = true

vmtoolsd.level = debug
vmtoolsd.handler = file
vmtoolsd.data = /var/log/vmtoolsd.log

vmsvc.level = debug
vmsvc.handler = file
vmsvc.data = /var/log/vmsvc.log

but i don't see any reference of creating or removing of snapshot in the logs as i can see the creation or removing in the veeam console. 
and he scripts are not runned 

how can i solve that?

**Comment by jonathanvmw** [comment]
What version of ESXi are you running?

Have you tried generating a quiesced snapshot through the vSphere client?

**Comment by grocanar** [comment]
VMware ESXi, 6.0.0, 5050593

i just try and it fails. 
on the esx i have the message
The guest OS has reported an error during quiescing

**Comment by grocanar** [comment]
Well aftger some work there s no issue
the queisce snapshot through the vspehre client didn't work because i meesed the tools.conf file.
now it work
and the quieced snapshot wasn't launch during veeam backup because it conflicts with the application processing.
sorry for the distrubance.
