### ISSUE TITLE
How to reconfigure after a kernel update

### ISSUE THREAD

**Issue by medihack** [vmware/open-vm-tools#187]
After a kernel update of an Ubuntu 16.04 guest VMware recommends me to update the VMware tools. The guest already has `open-vm-tools installed` (by Easy Install). I read somewhere that I have to execute `vmware-config-tools.pl` script. Unfortunately, that script is not part of `open-vm-tools`. So how do I reconfigure? Or do I have uninstall `open-vm-tools` and reinstall them again? I tried that, but after the next reboot I get the message again that I should update the VMware tools.

**Comment by oliverkurth** [comment]
If you have open-vm-tools installed you should be fine, there is no need to run that script.

vware-config-tools.pl is part of VMware Tools, which is another, older way to install tools in a VM, and no longer recommended for Ubuntu >= 14.04.

To better understand the problem, I need some more information:
- how are you using VMware (Fusion, Workstation or vSphere?) and which versions?
- which version of open-vm-tools do you have installed (you can find out for example with `vmtoolsd -v`)
- which version of the kernel did you run before, and which did you upgrade to?

It is possible that Workstation/Fusion recommends to upgrade VMware Tools although open-vm-tools are installed, but this can be ignored. It is a known issue.

**Comment by medihack** [comment]
You are right that it is just a confusing warning. The open-vm-tools seems to work correctly under Ubuntu 16.04.2 guest. Just the shared folder feature does not work (maybe that's intentional). Maybe just link this issue to the other known issue (could not find it). Sorry for bothering :-/ Nice job and thank you!
