### ISSUE TITLE
configure unconditionally sets -Werror

### ISSUE THREAD

**Issue by fenrus75** [vmware/open-vm-tools#192]
-Werror is evil for downstream consumers (distros like me) because gcc and other compilers vary warnings all the time. usually configure uses a maintainer-mode to enable -Werror, but does not enable it unconditional (which forces distros to patch it out again)

**Comment by oliverkurth** [comment]
Thank you for your suggestion. I filed an internal bug to discuss this.

But I am curious - where does the build fail with warnings? Can you attach logs and give details about the envionment to reproduce?

**Comment by fenrus75** [comment]
mv -f .deps/libNicInfo_la-nicInfo.Tpo .deps/libNicInfo_la-nicInfo.Plo
nicInfoPosix.c:990:1: error: 'ValidateConvertAddress' defined but not used [-Werror=unused-function]
 ValidateConvertAddress(const struct sockaddr *addr)  // IN:
 ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors


for example

**Comment by stanguturi** [comment]
> mv -f .deps/libNicInfo_la-nicInfo.Tpo .deps/libNicInfo_la-nicInfo.Plo
> nicInfoPosix.c:990:1: error: 'ValidateConvertAddress' defined but not used [-Werror=unused-function]
> ValidateConvertAddress(const struct sockaddr *addr) // IN:
> ^~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> 
> for example

Please check the changes done in 009def580b00040fa6e6c07cb5743e60973973f5 With those changes, the above warning/error should not happen.

**Comment by stanguturi** [comment]
Thanks for reporting this issue. There are few reasons to have -WError option by default.

* Compilers have additional options to allow individual warning types to be tolerated.  It should be up to consumers to decide.
* Greatly helps us keep our code clean. If we suppress it, we will be less likely to get the timely feedback we need when a new GCC version comes out. There will be higher chances of warnings being ignored and code becoming less up-to-date with newer compilers.

Also, with the commit 009def5, there shouldn't be any warnings. With that, I am closing this issue as 'wont fix'.
