### ISSUE TITLE
the code should not #error on configurations allows

### ISSUE THREAD

**Issue by fenrus75** [vmware/open-vm-tools#193]
for anything where "configure" succeeds, the code should not #error on. This should be a general guiding principle; if you need something or a combination of things, configure should catch this and throw an error, not deep into compile time with an #error

**Comment by oliverkurth** [comment]
Thank you. Did you see this for other issues than #195?

**Comment by oliverkurth** [comment]
This should be resolved with 009def580b00040fa6e6c07cb5743e60973973f5 (see issue #195).
