### ISSUE TITLE
--disable-gtk2 does not make configure look for gtk3

### ISSUE THREAD

**Issue by fenrus75** [vmware/open-vm-tools#194]
I had the dev headers/etc for gtk3 installed, but not for gtk2. --disable-gtk2 makes configure pass, but the build fails with errors (glib.h not found) as well as various #error cases..... 
if only configure had looked for gtk3 without being forced to specify --enable-gtk3.

**Comment by oliverkurth** [comment]
Thanks for reporting - using '--enable-gtk3' is the correct way to configure for gtk3. We should probably make using gtk3 the default anyway. I filed an internal bug to address this.

**Comment by oliverkurth** [comment]
This is resolved with e373c1ca328f78581d915940bd7e98abdb76a089
