### ISSUE TITLE
--without-dnet is a lie

### ISSUE THREAD

**Issue by fenrus75** [vmware/open-vm-tools#195]
configure suggests passing --without-dnet if you do not have or want dnet (I don't have nor want it), but this is a lie. later the code #error's out for this case requiring nasty patches.

**Comment by oliverkurth** [comment]
Thanks for reporting. I filed an internal bug for this.

Note that building without dnet will disable reporting of network information from the guest.

**Comment by oliverkurth** [comment]
This is actually a dup of issue #178 . Closing this one, let's keep the discussion in the older one.

**Comment by oliverkurth** [comment]
Fixed with commit 009def580b00040fa6e6c07cb5743e60973973f5
