### ISSUE TITLE
configure suggests --without-xerces-c but the option is called --without-xerces

### ISSUE THREAD

**Issue by fenrus75** [vmware/open-vm-tools#196]
--without-xerces-c doesn't exist...

**Comment by oliverkurth** [comment]
Thanks again for reporting. Output of the error message would have been helpful, but looks like the issue is here in configure.ac in line 561:

[AC_VMW_LIB_ERROR([XERCES], [xerces-c])])

It should be just "xcerces".

**Comment by stanguturi** [comment]
> --without-xerces-c doesn't exist...

Fixed it in commit f36f5da9f0a1134325495872f8853e01cadf51ad
