### ISSUE TITLE
generic_file_aio_read and generic_file_aio_write deleted from the kernel

### ISSUE THREAD

**Issue by yegortimoshenko** [vmware/open-vm-tools#2]
Hi VMware!

`generic_file_aio_read` and `generic_file_aio_write` were deleted from the kernel as for stable version 3.16.2, see https://github.com/torvalds/linux/commit/ed978a811ec528dbe40243605c3afab55892f722 and https://github.com/torvalds/linux/commit/6abd232274fd652e4a57f486d14e52ffee6f72e9

These calls should be changed so vmhgfs kernel module could be compiled for the newest kernel:

[modules/linux/vmhgfs/file.c#L688](https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/modules/linux/vmhgfs/file.c#L688) and [modules/linux/vmhgfs/file.c#L743](https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/modules/linux/vmhgfs/file.c#L743)

New iter_ functions in `mm/filemap.c` have been added, see https://github.com/torvalds/linux/commits/master/mm/filemap.c for 07 May 2014, reading diffs for this day should help.

When done, please close the ticket.
If I patch it, I'll send you a PR. Thanks!

**Comment by catalinus** [comment]
It is now July 2015 and it seems that the above vmware tools bug still seems to be present, am I missing something?

**Comment by ravindravmw** [comment]
Which code did you use? Did you try with https://github.com/vmware/open-vm-tools/tree/stable-9.10.2?

**Comment by catalinus** [comment]
https://github.com/vmware/open-vm-tools/tree/stable-9.10.2 still seems to contain in modules\linux\vmhgfs\file.c a call to generic_file_aio_write() which I understand is no longer part of the newer kernels, am I still missing something?

**Comment by yegortimoshenko** [comment]
Technically it has been fixed in https://github.com/vmware/open-vm-tools/commit/b23378e336a7b0ecc7a4584c9a5f185b40e1ef5a v9.10.0 released on Mar 19, 2015, so I am closing this issue.

It is a disappointment that such a small issue took half a year to get fixed (or released, it doesn't matter).

**Comment by rh-github-2015** [comment]
2015-11 and a freshly updated Player pulls VMwareTools-9.6.5-270074 which still compiles the old buggy code, plus the patch above fails on these tools with a  'struct dentry' has no member named 'd_alias' where inode.c uses the hlist macros... So, not half a year but 13 months NOT to get fixed.

**Comment by dyno** [comment]
try 9.10.3 or 10.0.5 it definitely got fixed in the newer release.
-dyno

On Tue, Nov 24, 2015 at 7:50 AM, rh-github-2015 <notifications@github.com>
wrote:

> 2015-11 and a freshly updated Player pulls VMwareTools-9.6.5-270074 which
> still compiles the old buggy code, plus the patch above fails on these
> tools with a 'struct dentry' has no member named 'd_alias' where inode.c
> uses the hlist macros... So, not half a year but 13 months NOT to get fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vmware/open-vm-tools/issues/2#issuecomment-159310420>.
>



-- 
reality, with all its ambiguities, does the job just fine.
