### ISSUE TITLE
‘struct dentry

### ISSUE THREAD

**Issue by teliot** [vmware/open-vm-tools#20]
make
.
.
.
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/shared/kernelStubsSal.h:111:8: warning: "_SAL_VERSION" is not defined [-Wundef]
 #elif  _SAL_VERSION == 10
        ^
  CC [M]  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/file.o
  CC [M]  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/transport.o
  CC [M]  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/module.o
  CC [M]  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/super.o
  CC [M]  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/bdhandler.o
  CC [M]  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/fsutil.o
  CC [M]  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/page.o
  CC [M]  /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.o
In file included from include/linux/list.h:8:0,
                 from include/linux/preempt.h:10,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from include/linux/pagemap.h:7,
                 from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:29:
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c: In function ‘HgfsPermission’:
include/linux/kernel.h:796:27: error: ‘struct dentry’ has no member named ‘d_alias’
  const typeof( ((type _)0)->member ) *__mptr = (ptr); \
                           ^
include/linux/list.h:688:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:699:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:709:13: note: in expansion of macro ‘hlist_entry_safe’
  for (pos = hlist_entry_safe((head)->first, typeof(_(pos)), member);\
             ^
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:1915:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
include/linux/kernel.h:796:48: warning: initialization from incompatible pointer type [enabled by default]
  const typeof( ((type _)0)->member ) *__mptr = (ptr); \
                                                ^
include/linux/list.h:688:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:699:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:709:13: note: in expansion of macro ‘hlist_entry_safe’
  for (pos = hlist_entry_safe((head)->first, typeof(_(pos)), member);\
             ^
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:1915:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/compiler-gcc.h:106:0,
                 from include/linux/compiler.h:54,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from ./include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/shared/driver-config.h:71,
                 from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:26:
include/linux/compiler-gcc4.h:14:34: error: ‘struct dentry’ has no member named ‘d_alias’
 #define __compiler_offsetof(a,b) __builtin_offsetof(a,b)
                                  ^
include/linux/stddef.h:17:31: note: in expansion of macro ‘__compiler_offsetof’
 #define offsetof(TYPE,MEMBER) __compiler_offsetof(TYPE,MEMBER)
                               ^
include/linux/kernel.h:797:29: note: in expansion of macro ‘offsetof’
  (type _)( (char *)__mptr - offsetof(type,member) );})
                             ^
include/linux/list.h:688:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:699:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:709:13: note: in expansion of macro ‘hlist_entry_safe’
  for (pos = hlist_entry_safe((head)->first, typeof(_(pos)), member);\
             ^
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:1915:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/preempt.h:10:0,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from include/linux/pagemap.h:7,
                 from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:29:
include/linux/list.h:711:35: error: ‘struct dentry’ has no member named ‘d_alias’
       pos = hlist_entry_safe((pos)->member.next, typeof(_(pos)), member))
                                   ^
include/linux/list.h:698:12: note: in definition of macro ‘hlist_entry_safe’
  ({ typeof(ptr) ____ptr = (ptr); \
            ^
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:1915:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
include/linux/list.h:711:35: error: ‘struct dentry’ has no member named ‘d_alias’
       pos = hlist_entry_safe((pos)->member.next, typeof(_(pos)), member))
                                   ^
include/linux/list.h:698:28: note: in definition of macro ‘hlist_entry_safe’
  ({ typeof(ptr) ____ptr = (ptr); \
                            ^
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:1915:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/list.h:8:0,
                 from include/linux/preempt.h:10,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from include/linux/pagemap.h:7,
                 from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:29:
include/linux/kernel.h:796:27: error: ‘struct dentry’ has no member named ‘d_alias’
  const typeof( ((type _)0)->member ) *__mptr = (ptr); \
                           ^
include/linux/list.h:688:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:699:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:711:13: note: in expansion of macro ‘hlist_entry_safe’
       pos = hlist_entry_safe((pos)->member.next, typeof(_(pos)), member))
             ^
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:1915:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
include/linux/kernel.h:796:48: warning: initialization makes pointer from integer without a cast [enabled by default]
  const typeof( ((type _)0)->member ) *__mptr = (ptr); \
                                                ^
include/linux/list.h:688:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:699:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:711:13: note: in expansion of macro ‘hlist_entry_safe’
       pos = hlist_entry_safe((pos)->member.next, typeof(_(pos)), member))
             ^
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:1915:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/compiler-gcc.h:106:0,
                 from include/linux/compiler.h:54,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from ./include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/shared/driver-config.h:71,
                 from /root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:26:
include/linux/compiler-gcc4.h:14:34: error: ‘struct dentry’ has no member named ‘d_alias’
 #define __compiler_offsetof(a,b) __builtin_offsetof(a,b)
                                  ^
include/linux/stddef.h:17:31: note: in expansion of macro ‘__compiler_offsetof’
 #define offsetof(TYPE,MEMBER) __compiler_offsetof(TYPE,MEMBER)
                               ^
include/linux/kernel.h:797:29: note: in expansion of macro ‘offsetof’
  (type _)( (char *)__mptr - offsetof(type,member) );})
                             ^
include/linux/list.h:688:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:699:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:711:13: note: in expansion of macro ‘hlist_entry_safe’
       pos = hlist_entry_safe((pos)->member.next, typeof(_(pos)), member))
             ^
/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.c:1915:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
scripts/Makefile.build:257: recipe for target '/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.o' failed
make[4]: **\* [/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs/inode.o] Error 1
Makefile:1381: recipe for target '_module_/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs' failed
make[3]: **\* [_module_/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs] Error 2
make[3]: Leaving directory '/usr/src/linux-3.18.11-gentoo'
Makefile:120: recipe for target 'vmhgfs.ko' failed
make[2]: **\* [vmhgfs.ko] Error 2
make[2]: Leaving directory '/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules/linux/vmhgfs'
Makefile:500: recipe for target 'vmhgfs' failed
make[1]: **\* [vmhgfs] Error 2
make[1]: Leaving directory '/root/open-vm-tools/open-vm-tools-9.10.0-2476743/modules'
Makefile:361: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1
localhost open-vm-tools-9.10.0-2476743 #

**Comment by teliot** [comment]
had to configure --without-kernel-modules to get around error

**Comment by bzed** [comment]
The vmware-tools guys are stuck at some really old kernel version unfortunately.
You could give the patches from Arch Linux a try: https://github.com/davispuh/open-vm-tools-dkms - should make the kernel modules build if you need them.

If not, there is https://github.com/rasa/vmware-tools-patches ....

**Comment by stanguturi** [comment]
> had to configure --without-kernel-modules to get around error

As mentioned in the readme document, following are the steps to compile open-vm-tools

autoreconf -i
./configure --without-kernel-modules
make
sudo make install
sudo ldconfig

Using '--without-kernel-modules option fixed the issue. Closing.
