### ISSUE TITLE
Drag and drop not working from host to guest with Lubuntu

### ISSUE THREAD

**Issue by rafaeldamasceno** [vmware/open-vm-tools#202]
As the title indicates, I can't get drag and drop from host to guest to properly work. I've tried using both Lubuntu 17.04 and 16.04.3 LTS, and they both misbehave. I'm using open-vm-tools and open-vm-tools-desktop 2:10.1.5-5055683-1ubuntu1.1. As for the host, I'm using Windows 10, 64-bit  (Build 16299) 10.0.16299 and VMware® Workstation 14 Player 14.0.0 build-6661328.

At this point, I'm not sure of what is the culprit, LXDE or PCManFM. However, what surprises me the most is copy/paste works and dragging from guest to host also works just fine.

When hovering the VM with the file, it seems to be working just fine (drop indicator is normal). However, this is the message that I'm presented with when dropping on guest:

```
Error when getting information for file “/tmp/VMwareDnD/wz5c5i/caffeine.exe”: No such file or directory
```

My guess is that the files were deleted before copying to the drop directory or not properly copied to the VM (which is weird considering copy/paste works).

I'm not sure if there's something you can do as Lubuntu is probably not officially supported and this seems to work fine using Ubuntu 17.04, but it would be great if someone could indicate a workaround for this issue.

P.S.: I've somehow got it working by using Workstation 12 Player to create and install the guests and then updating to Workstation 14 Player. I'm not sure why it worked and I didn't reproduce it because I've  since deleted the machines and downgrading is too much of a hassle. Using VMware Tools 10.1.15 build-6627299, the behaviour is consistent with open-vm-tools. However, instead of dropping and then getting the /tmp/ error, the cursor changes and indicates that I can't drop at all. I'm not sure of how relevant this is.

**Comment by eleses** [comment]
the tools don't seem to work at all in Lubuntu 20. The systemd status shows them as up, but nothing whatsoever works, not even the ballooning memory driver (which needs no graphics etc.)

**Comment by oliverkurth** [comment]
@eleses , from https://github.com/vmware/open-vm-tools/issues/303#issuecomment-645071265 it looks like your issue is resolved?

@rafaeldamasceno , I am going to close this issue since there are no relevant updates for 2.5 years, and we (and Ubuntu) have released many new versions since then.

We have a kb article that describes how to get drag and drop working at https://kb.vmware.com/s/article/74671 , however we expect it to be working out of the box for Ubuntu. Note that it does not work with Wayland.

**Comment by eleses** [comment]
@oliverkurth yes, it's resolved. I suspect the problem was that merely restarting the vmware daemon (as https://kb.vmware.com/s/article/1007873) said to do) after editing those files was not enough to load all the proper kernel modules, but a reboot fixed that.
