### ISSUE TITLE
open-vm-tools does not auto resize the display on Fedora 27

### ISSUE THREAD

**Issue by lvii** [vmware/open-vm-tools#204]
I have installed `open-vm-tools` and `open-vm-tools-desktop` in Fedora 27 :

```
[root@fedora ~]# uname -a
Linux fedora 4.13.5-300.fc27.x86_64 #1 SMP Thu Oct 5 16:57:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[root@fedora ~]# rpm -qa|grep open-vm
open-vm-tools-10.1.10-3.fc27.x86_64
open-vm-tools-desktop-10.1.10-3.fc27.x86_64
```

`vmtoolsd` service was auto start on boot :

```
[root@fedora ~]# systemctl status vmtoolsd.service
● vmtoolsd.service - Service for virtual machines hosted on VMware
   Loaded: loaded (/usr/lib/systemd/system/vmtoolsd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-10-24 13:32:13 CST; 1min 4s ago
     Docs: http://github.com/vmware/open-vm-tools
 Main PID: 373 (vmtoolsd)
    Tasks: 1 (limit: 19660)
   CGroup: /system.slice/vmtoolsd.service
           └─373 /usr/bin/vmtoolsd

Oct 24 13:32:13 fedora systemd[1]: Started Service for virtual machines hosted on VMware.
```

I have to **restart** `vmtoolsd` service manually, VM could auto fit the screen.

Running `vmware-user-suid-wrapper &` with this error :

```
$ vmware-user-suid-wrapper &
[1] 1017 vmware-user: could not open /proc/fs/vmblock/dev
[1]+  Done            vmware-user-suid-wrapper
```

**Comment by ralves-uu** [comment]
Same problem on Arch linux (kernel 4.13.11)

**Comment by Bigsy** [comment]
Same problem here after I upgraded my arch install to 4.13, although I guess kernel version maybe unreleased. For me vmtoolsd.service is started fine and I can simply run `vmware-user-suid-wrapper &` and resize+copypaste start working again, maybe this isn't being on session start anymore, if it was?

**Comment by stefcl** [comment]
@Bigsy 
I am using archlinux too, I noticed that the launcher here:

`/etc/xdg/autostart/vmware-user.desktop`

is a symlink pointing to 

`/usr/share/applications/vmware-user.desktop`

which does not exist.

Creating the file manually with the content below :

```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Exec=/usr/bin/vmware-user-suid-wrapper
Name=VMware User Agent
# KDE bug 190522: KDE does not autostart items with NoDisplay=true...
# NoDisplay=true
X-KDE-autostart-phase=1
```
should restore the autostart feature.

**Comment by zbindenren** [comment]
@Bigsy thanks, had the same problem on arch.

**Comment by king-gu** [comment]
> 我已经安装`open-vm-tools`，并`open-vm-tools-desktop`在Fedora的27：
> 
> ```
> [root@fedora ~]# uname -a
> Linux fedora 4.13.5-300.fc27.x86_64 #1 SMP Thu Oct 5 16:57:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> 
> [root@fedora ~]# rpm -qa|grep open-vm
> open-vm-tools-10.1.10-3.fc27.x86_64
> open-vm-tools-desktop-10.1.10-3.fc27.x86_64
> ```
> `vmtoolsd` 服务是在启动时自动启动：
> 
> ```
> [root@fedora ~]# systemctl status vmtoolsd.service
> ● vmtoolsd.service - Service for virtual machines hosted on VMware
>    Loaded: loaded (/usr/lib/systemd/system/vmtoolsd.service; enabled; vendor preset: enabled)
>    Active: active (running) since Tue 2017-10-24 13:32:13 CST; 1min 4s ago
>      Docs: http://github.com/vmware/open-vm-tools
>  Main PID: 373 (vmtoolsd)
>     Tasks: 1 (limit: 19660)
>    CGroup: /system.slice/vmtoolsd.service
>            └─373 /usr/bin/vmtoolsd
> 
> Oct 24 13:32:13 fedora systemd[1]: Started Service for virtual machines hosted on VMware.
> ```
> 我必须手动**重启** `vmtoolsd`服务，VM可以自动适应屏幕。
> 
> 运行`vmware-user-suid-wrapper &`此错误：
> 
> ```
> $ vmware-user-suid-wrapper &
> [1] 1017 vmware-user: could not open /proc/fs/vmblock/dev
> [1]+  Done            vmware-user-suid-wrapper
> ```
 vmware-user-suid-wrapper &
[1] 3605
[1]  + 3605 done       vmware-user-suid-wrapper                                                    
vmware-user: could not open /proc/fs/vmblock/dev
/usr/bin/vmtoolsd: error while loading shared libraries: libicui18n.so.62: cannot open shared object file: No such file or directory



why

**Comment by king-gu** [comment]
> @Bigsy
> 我也在使用archlinux，我注意到这里的启动器：
> 
> `/etc/xdg/autostart/vmware-user.desktop`
> 
> 是指向的符号链接
> 
> `/usr/share/applications/vmware-user.desktop`
> 
> 哪个不存在。
> 
> 使用以下内容手动创建文件：
> 
> ```
> [Desktop Entry]
> Type=Application
> Encoding=UTF-8
> Exec=/usr/bin/vmware-user-suid-wrapper
> Name=VMware User Agent
> # KDE bug 190522: KDE does not autostart items with NoDisplay=true...
> # NoDisplay=true
> X-KDE-autostart-phase=1
> ```
> 应该恢复自动启动功能。
zsh: bad pattern: [Desktop


why

**Comment by king-gu** [comment]
> 我已经安装`open-vm-tools`，并`open-vm-tools-desktop`在Fedora的27：
> 
> ```
> [root@fedora ~]# uname -a
> Linux fedora 4.13.5-300.fc27.x86_64 #1 SMP Thu Oct 5 16:57:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> 
> [root@fedora ~]# rpm -qa|grep open-vm
> open-vm-tools-10.1.10-3.fc27.x86_64
> open-vm-tools-desktop-10.1.10-3.fc27.x86_64
> ```
> `vmtoolsd` 服务是在启动时自动启动：
> 
> ```
> [root@fedora ~]# systemctl status vmtoolsd.service
> ● vmtoolsd.service - Service for virtual machines hosted on VMware
>    Loaded: loaded (/usr/lib/systemd/system/vmtoolsd.service; enabled; vendor preset: enabled)
>    Active: active (running) since Tue 2017-10-24 13:32:13 CST; 1min 4s ago
>      Docs: http://github.com/vmware/open-vm-tools
>  Main PID: 373 (vmtoolsd)
>     Tasks: 1 (limit: 19660)
>    CGroup: /system.slice/vmtoolsd.service
>            └─373 /usr/bin/vmtoolsd
> 
> Oct 24 13:32:13 fedora systemd[1]: Started Service for virtual machines hosted on VMware.
> ```
> 我必须手动**重启** `vmtoolsd`服务，VM可以自动适应屏幕。
> 
> 运行`vmware-user-suid-wrapper &`此错误：
> 
> ```
> $ vmware-user-suid-wrapper &
> [1] 1017 vmware-user: could not open /proc/fs/vmblock/dev
> [1]+  Done            vmware-user-suid-wrapper
> ```

`vmtoolsd.service - Open Virtual Machine Tools (VMware Tools)
   Loaded: loaded (/usr/lib/systemd/system/vmtoolsd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-11-05 16:25:46 CST; 1h 57min ago
  Process: 338 ExecStart=/usr/bin/vmtoolsd (code=exited, status=127)
 Main PID: 338 (code=exited, status=127)

11月 05 16:25:45 Manjaro systemd[1]: Started Open Virtual Machine Tools (VMware Tools).
11月 05 16:25:46 Manjaro vmtoolsd[338]: /usr/bin/vmtoolsd: error while loading shared libraries: l>
11月 05 16:25:46 Manjaro systemd[1]: vmtoolsd.service: Main process exited, code=exited, status=12>
11月 05 16:25:46 Manjaro systemd[1]: vmtoolsd.service: Failed with result 'exit-code'.
lines 1-10/10 (END)
`

why

**Comment by acuteaura** [comment]
> Same problem on Fedora 33, VMware Workstation 16.

Switch to an X based session, it does not work in Wayland.

**Comment by lousybrit** [comment]
Have you checked recent comments and updates in
https://github.com/vmware/open-vm-tools/issues/491

Thanks!

**Comment by msdisatis** [comment]
I have gnome installed, and of course I am running a x-session.

**Comment by johnwvmw** [comment]
I believe that this issue is fixed in currently supported Fedora releases with open-vm-tools 11.3.0 or later.
