### ISSUE TITLE
Question: How to start open-vm-tools-desktop?

### ISSUE THREAD

**Issue by Mannshoch** [vmware/open-vm-tools#205]
Ubuntu 17.10 - description of open-vm-tools-desktop:
Open VMware Tools for virtual machines hosted on VMware **(GUI)**

`man` or `--help` do not provide any useful information about the terminal tools.

**Comment by shuaiwangVM** [comment]
Hi Mannshoch,

open-vm-tools-desktop was automatic started  when you logged into you GUI.
please refer to file:
cat /etc/xdg/autostart/vmware-user.desktop
[Desktop Entry]
Type=Application
Encoding=UTF-8
Exec=/usr/bin/vmware-user-suid-wrapper
Name=VMware User Agent
# KDE bug 190522: KDE does not autostart items with NoDisplay=true...
# NoDisplay=true
X-KDE-autostart-phase=1

Thanks.
Shuai

**Comment by stanguturi** [comment]
> open-vm-tools-desktop was automatic started when you logged into you GUI.

Thanks for the comment. Closing this issue.
