### ISSUE TITLE
"No value found" when use vmware-rpctool

### ISSUE THREAD

**Issue by YurovRuslan** [vmware/open-vm-tools#209]
Hi!

I use Debian on ESXi 6.5 with installed `open-vm-tools`.
To be honest, it has read-only FS so I install `open-vm-tools` before starting GuestOS.
So when I want to see `ovfEnv` I write:
```
# vmware-rpctool 'info-get guestinfo.ovfEnv'
No value found

# apt search open-vm-tools
Sorting... Done
Full Text Search... Done
open-vm-tools/unknown 2:10.0.7-3227872-1 amd64
  Open VMware Tools for virtual machines hosted on VMware (CLI)
```
On host:
```
2017-11-30T11:54:35.875Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox-dnd timed out.                        
2017-11-30T11:55:07.524Z| vcpu-0| I125: Tools: Running status rpc handler: 0 => 1.                                       
2017-11-30T11:55:07.524Z| vcpu-0| I125: Tools: Changing running status: 0 => 1.
2017-11-30T11:55:27.524Z| vcpu-0| I125: Tools: Tools heartbeat timeout.    
2017-11-30T11:55:27.524Z| vcpu-0| I125: Tools: Running status rpc handler: 1 => 0.           
2017-11-30T11:55:27.524Z| vcpu-0| I125: Tools: Changing running status: 1 => 0. 
```

There is no vApp on ESXi as I can see.

What can I do wrong?!

**Comment by shuaiwangVM** [comment]
Hi YurovRuslan,

How did you set the value for guestinfo.ovfEnv?
you can set the value by vmware-rpctool 'info-set guestinfo.ovfEnv your-value' or add an entry in vmx file first.

Thanks.
Shuai

**Comment by stanguturi** [comment]
> I use Debian on ESXi 6.5 with installed `open-vm-tools`.
> To be honest, it has read-only FS so I install `open-vm-tools` before starting GuestOS.
> So when I want to see `ovfEnv` I write:

The guestinfo variable i.e. 'guestinfo.ovfenv' is not available by default for every VM that is deployed/created. The information needs to be *explicitly* specified by the vSphere administrator during the VM provisioning process. The 'guestinfo.ovfenv' option is a simple way that vSphere administrators use while provisioning to transport certain metadata information specific to the VM. Please check the following few blogs that explain various use cases of guestinfo.ovfenv.

* https://www.virtuallyghetto.com/2019/02/building-your-own-virtual-appliances-using-ovf-properties-part-1.html
* https://www.virtuallyghetto.com/2012/06/ovf-runtime-environment.html

**Comment by wayne-joneser** [comment]
I found a trick to make the ovf variable available in vmware workstation. It should work for esxi too. 
1. First you'll need the XML content from a vSphere environment. Paste that XML into the "Description" field in vmware workstation. 
2. Edit the vmx file. There is a new line called "Annotation" in the file and the XML will be properly formatted in that line. Copy and paste the line. 
3. Change the field value on the new line from annotation to guestinfo.ovfenv and the XML variable will be populated in the VM.
