### ISSUE TITLE
Fedora 27

### ISSUE THREAD

**Issue by josimp** [vmware/open-vm-tools#211]
When installing Fedora 27 does the installer detect that I am in a virtual machine and automatically include open-vmtools?  I have installed a fedora 27 server on a device and it took up about 3 gigs.  When I create a virtual machine and try to install the same configuration it is telling me that there is not enough room.  I would ask the general Fedora forum but I suspect that this is the issue.  Thanks.

**Comment by stanguturi** [comment]
> When installing Fedora 27 does the installer detect that I am in a virtual machine and automatically include open-vmtools?

Yes. I have just tried with Fedora 33 in a VM managed by ESXi 6.7 Update 1. The open-vm-tools package was installed/included by default in the VM.
