### ISSUE TITLE
Scrolling issues in Google Chrome

### ISSUE THREAD

**Issue by martinbdz** [vmware/open-vm-tools#213]
Scrolling while moving the mouse does not work in all chrome-related applications (browser itself, Visual Studio Code, Atom, ...) which leads to a really bad experience inside the vm. This is happening in both VMWare Workstation Pro and Virtualbox, but not on the host system itself. I am using Ubuntu 17.10 as the guest system and Ubuntu 16.04 as the host.
There is a workaround described in this thread: https://bbs.archlinux.org/viewtopic.php?id=223470 (starting chrome with "--disable-high-precision-scrolling"), but this does not solve the real issue.

**Comment by stanguturi** [comment]
This doesn't seem to be an issue with open-vm-tools. You can post the issue in the chrome user community/forum for some inputs.
