### ISSUE TITLE
configuration file reference

### ISSUE THREAD

**Issue by msplival** [vmware/open-vm-tools#215]
Hi.

Is there a list of options one can put inside the conf file? (The conf file being the one supplied to vmtoolsd via the --config option)

Regards,

Mario

**Comment by oliverkurth** [comment]
Unfortunately no, we don't have any yet. We do have plans though to provide a template configuration file that lists them.

**Comment by stanguturi** [comment]
Check https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/tools.conf 

Check commit e385c90808d527bce41259796badba094ad62a77

As @oliverkurth mentioned in the previous update, a template for tools configuration file has been provided. It has all the information about the available configuration options. Please check it out.

Thanks
