### ISSUE TITLE
vmxnet: module build breaks with kernel 4.15

### ISSUE THREAD

**Issue by cpaelzer** [vmware/open-vm-tools#217]
Hi,
Ubuntu runs tests to build the kernel module for vmxnet which fails with kernel 4.15  - I'm on 10.1.15.
There are more details on [launchpad](https://bugs.launchpad.net/ubuntu/+source/open-vm-tools/+bug/1737753)

But the TL;DR of the break is at this [make log](https://launchpadlibrarian.net/348959120/make.log)

Those are the top 3 I see immediately.

```
In file included from /var/lib/dkms/open-vm-tools/10.1.15/build/vmxnet/vmxnet.c:54:0:
/var/lib/dkms/open-vm-tools/10.1.15/build/vmxnet/./shared/vm_device_version.h:56:0: warning: "PCI_VENDOR_ID_VMWARE" redefined
```
 
```
In file included from /var/lib/dkms/open-vm-tools/10.1.15/build/vmxnet/./shared/eth_public.h:50:0,
                 from /var/lib/dkms/open-vm-tools/10.1.15/build/vmxnet/vmxnet.c:57:
/var/lib/dkms/open-vm-tools/10.1.15/build/vmxnet/./shared/vm_basic_defs.h:778:0: warning: "DO_ONCE" redefined
```

```
    compat_init_timer_deferrable(&lp->linkCheckTimer);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/open-vm-tools/10.1.15/build/vmxnet/vmxnet.c:1166:22: error: â€˜struct timer_listâ€™ has no member named â€˜dataâ€
```

**Comment by ravindravmw** [comment]
@cpaelzer is there any reason you are trying to build vmxnet driver on kernel 4.15? This driver is not supported for kernel version >= 3.3, see https://kb.vmware.com/s/article/1001805. Also, we have disabled it's build on newer kernels, see https://github.com/vmware/open-vm-tools/blob/stable-10.1.x/open-vm-tools/configure.ac#L1251.

**Comment by cpaelzer** [comment]
@ravindravmw - essentially at least the lack of knowledge I'd guess.
Your reply is great to resolve that, so I beg your pardon and want to thank you.

This package currently in Ubuntu is a sync from Debian (so they are the same in both) and I just saw the issue when the new kernel was proposed and thought to report.

The module is carried in both as "Open VMware Tools vmxnet kernel module (deprecated) [...] You should only install this package if you know that you need the legacy vnxnet module. " for quite a while now for some compat. I think the time has come to actually drop it.

But that might be again my lack of domain knowledge, so I'll open a bug in the packaging for it and let one decide that touched/used it more often.

Thank you, and by that closing this issue.
