### ISSUE TITLE
Autofit does not work in Arch Linux on 10.2.0 (regression from 10.1.15)

### ISSUE THREAD

**Issue by tbodt** [vmware/open-vm-tools#222]
I recently upgraded open-vm-tools from 10.1.15 to 10.2.0 on my Arch VM. Autofit stopped working, though copy/paste and drag/drop still worked. After downgrading to 10.1.15 autofit worked again.

The output of `lsof -p $(pgrep vmtoolsd) | grep resolution` was empty with 10.2.0, but shows libresolutionSet.so on 10.1.15.

**Comment by thomashvmw** [comment]
Did you completely power off the VM (contrary to just rebooting?) after upgrading to 10.2.0?

**Comment by tbodt** [comment]
No, why would that make a difference?

**Comment by thomashvmw** [comment]
Because there is a flaw in vmware VMX that doesn't reset the channel on which resolution change events are sent on VM reboot. A complete power off is needed, since 10.2.x uses a different channel than 10.1.x

**Comment by tbodt** [comment]
Ok, I reinstalled 10.2.0 and powered off and restarted the VM, and autofit still doesn't work.

**Comment by thomashvmw** [comment]
Theodore, could you perhaps post the vmware.log from the host, the Xorg.log from the guest and also enable open-vm-tools logging like below, and then post the resulting log files?

Thanks,
Thomas


https://kb.vmware.com/s/article/1007873

Using the example a bit down on the page:

[logging]
log = true

# Enable VMware Tools service logging to a file.
vmtoolsd.level = debug
vmtoolsd.handler = file
vmtoolsd.data = /tmp/vmtoold.log

# Enable "vmsvc" service logging to a file.
vmsvc.level = debug
vmsvc.handler = file
vmsvc.data = /tmp/vmsvc.log

# Enable new "vmusr" service logging to a file.
vmusr.level = debug
vmusr.handler = file
vmusr.data = /tmp/vmusr.${USER}.log

# Enable the "vmvss" snapshot service logging to a file.
vmvss.level = debug
vmvss.handler = file
vmvss.data = /tmp/vmvss.log

**Comment by jmcabo** [comment]
I have the same problem with my Arch guest: Autofit doesn't work and the screen resolution starts at 800x600 unless set manually. 

Version of open-vm-tools is:

$ pacman -Qs open-vm-tools
     local/open-vm-tools 6:10.2.0-1

**Comment by helmi77** [comment]
I just noticed that my `vmtoolsd.service` unit was disabled. Reenabling and starting it resolved the issue for me.

**Comment by jmcabo** [comment]
Oh my god it works! Thanks helmi77!!!
I did the following:

      systemctl enable vmtoolsd
      systemctl start vmtoolsd

and it worked right away. No reboot required.

Thanks!

**Comment by tbodt** [comment]
@thomashvmw vmtoolsd.log says this:

```
[Apr 04 11:05:08.296] [    info] [vmtoolsd] Plugin 'libresolutionSet.so' didn't provide deployment data, unloading.
```

What does it mean? Also where do I find the host log file?

**Comment by tbodt** [comment]
OK, I found vmware.log. I've posted it in a gist: https://gist.github.com/tbodt/686f1a55f54ddab106cb00f3a655d3c0

**Comment by tbodt** [comment]
https://github.com/vmware/open-vm-tools/commit/dec55c31e7dcdbb747647123ad60cc2cde4e0635 is probably the culprit.

**Comment by tbodt** [comment]
So why isn't libresolutionKMS loading?

**Comment by tbodt** [comment]
Oh, because that's the system-wide vmtoolsd wasn't running 🤦‍♂️
