### ISSUE TITLE
Fails to build with new ICU version

### ISSUE THREAD

**Issue by bzed** [vmware/open-vm-tools#224]
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879804

open-vm-tools ftbfs with icu from Debian experimental, not shipping the icu-config
binary anymore.  The autoconf tests should use pkg-config as a fallback.

hecking for g++... g++
checking for icu-config... no
configure: error: ICU library not found. Please configure without ICU (using
--without-icu) or install ICU - http://www.icu-project.org
	tail -v -n \+0 config.log

**Comment by oliverkurth** [comment]
It's probably safe to build without using icu. I suggest to build with the `--without-icu` option.

**Comment by oliverkurth** [comment]
This issue is fixed in the devel branch with https://github.com/vmware/open-vm-tools/commit/13df0e2fc2f68aeab0380761eb0c5ab129730710 . It will be in the stable-10.2.x soon.

**Comment by stanguturi** [comment]
> This issue is fixed in the devel branch with 13df0e2 . It will be in the stable-10.2.x soon.

Fix already submitted. Closing.
