### ISSUE TITLE
per-session user-owned vmtoolsd segfaults afer upgrade to 2:10.2.0-1

### ISSUE THREAD

**Issue by bzed** [vmware/open-vm-tools#226]
forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887755

After upgrade to open-vm-tools[-desktop] 2:10.2.0-1 in Sid, the
per-session user-owned vmtoolsd process segfaults in libgdk while
logging into a Wayland GNOME session. The problem does not occur
for an Xorg GNOME session.

This problem appears to be identical to the known problem reported
in Red Hat Bug 1526952 and (my) SUSE Bug 1073760. Note that in
openSUSE Tumbleweed the problem occurred for open-vm-tools-desktop
10.1.15 as well as 10.2.0, so it might not simply be a bug introduced
with your upgrade. Note that Fedora have released a workaround, and my
understanding is that VMware are working on a permanent fix involving
rework of the plugins to handle Wayland.

For an Xorg session:
lovelld@ron5sid:~$ ps -ef | grep vmtoolsd
root        417      1  0 10:30 ?        00:00:02 /usr/bin/vmtoolsd
lovelld    3442      1  0 10:41 tty2     00:00:02 /usr/bin/vmtoolsd -n vmusr --blockFd 3
lovelld    4087   3847  0 11:04 pts/2    00:00:00 grep -d skip --color=auto vmtoolsd

For a Wayland session, the process running as me (with the -n vmusr option) is
not present, and the journal shows it segfaults in libgdk. See the Red Hat
and SUSE bugs for further details, including stack traces.

**Comment by oliverkurth** [comment]
Can you please check if this patch fixes the issue: http://pkgs.fedoraproject.org/cgit/rpms/open-vm-tools.git/tree/wayland-crash.patch

**Comment by oliverkurth** [comment]
Also this change: https://github.com/vmware/open-vm-tools/commit/c5bc784da611ee929e0da7c20a410e03e6540613

**Comment by ceesco53** [comment]
@oliverkurth I can confirm these patches against 10.2.0 resolved my vmtoolsd segfault under Arch Linux.  I have two vmtoolsd running fine under wayland.  I don't mean to hijack this thread and can open a new ticket if needed.  With these patches I'm still experiencing bug #222

**Comment by vith** [comment]
Thanks, that worked for me too. I opened an issue at the Arch Linux tracker (https://bugs.archlinux.org/task/57425) to see if they're willing to apply the patch. I attached a PKGBUILD to my report there in case anyone else wants to just apply the patch locally in the meantime.

**Comment by vith** [comment]
For Arch Linux users, the patch is included in `community/open-vm-tools` as of `6:10.2.0-2`: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/open-vm-tools&id=d4d618f4d9b911a0d9e8cd07a0c8d8a8ebd8ff7d

**Comment by stanguturi** [comment]
> Also this change: [c5bc784](https://github.com/vmware/open-vm-tools/commit/c5bc784da611ee929e0da7c20a410e03e6540613)

Thanks Oliver. c5bc784da611ee929e0da7c20a410e03e6540613 fixed the issue. Closing.
