### ISSUE TITLE
deploy can not get template file

### ISSUE THREAD

**Issue by mtx99** [vmware/open-vm-tools#227]
I am trying to rewrite openvmtools deploy plugin,  when I get "deployPkg.begin"  from exsi,  I send "OK /tmp/vmware-root/XXXX/" to exsi , and then  I can not get the deploy file from exsi. Why ？  Who can help me ?I don't know where can find the message  protocol of vmtools between exsi and guest os ??

exsi version :VMware ESX  version=5.5.0 build=build-1331820
guest os :  debain

**Comment by mtx99** [comment]
After check the Hgfs plugin is needed 。

**Comment by stanguturi** [comment]
> After check the Hgfs plugin is needed 。

Yes. HgfsServer plugin is needed for the files to get copied into the guest from the underlying layers.
