### ISSUE TITLE
open-vm-tools on Fedora 22 isn't fitting guest or autofit

### ISSUE THREAD

**Issue by darlingm** [vmware/open-vm-tools#23]
On a fresh Fedora 22 install running kde-plasma and kernel 4.0.4-301.fc22:

* `sudo dnf install open-vm-tools` (dnf is Fedora 22's replacement to yum)
* reboot
* `dmesg | grep vm` shows "systemd[1]: Detected virtualization VMware."; "[drm] Initialized vmwgfx 2.6.1 20140704 for 0000:00:0f.0 on minor 0"; "vmw_vmci 0000:00:00.7: Found VMCI PCI device at 0x11080, irq 16"; "vmw_vmci 0000:00:07.7: Using capabilities 0xc"; and "VMCI host device registered (name=vmci, major=10, minor=58)".
* `ps -ax | grep vm` shows "/usr/bin/vmtoolsd".
* VMware Workstation->View->Fit Guest Now is grayed out

Is there more configuration that I have to do?  Or, after rebooting after a successful repo install, should autofit and fitting guest be working?

If I install the VMware Tools included in VMware Workstation, it creates a new initrd boot image, starts VMware-tools via systemctl, and tells me to run /usr/bin/vmware-user, log out, restart my x session.  Running /usr/bin/vmware-user fits guest without me asking for it.

What extra steps do I need to take, to use open-vm-tools?  The only features I'm interested in is auto-fitting guest, and automatically handling resizing to fit.  Do I need to install a new initrd image?  If so, what are the steps?  Do I need to run the comparable version of `/usr/bin/vmware-user` (as open-vm-tools doesn't install one?)

**Comment by darlingm** [comment]
BTW Fedora 22's dnf repository is v9.10.0-4.fc22

You can download the tar file open-vm-tools' `/usr/bin/vm-support` generated at: http://www.filedropper.com/vm-2015-05-261858tar

(I added "addGrubFile /boot/grub2/grub2.cfg" and "addGrubFile /etc/default/grub" to the script, because the three locations built into it were guessing other locations.)

**Comment by ravindravmw** [comment]
Have you tried installing open-vm-tools-desktop package, followed by a logout and log back in?

**Comment by darlingm** [comment]
Nope, had no idea that package existed!  That did the trick.  Thanks for the fast response.

I see now that if I had read the links to vmware.com, I would have known about the package.  Might be helpful to someone else skipping the links to make a mention in the github readme about the separate package.  (Maybe in the Is open-vm-tools available with Linux distributions? section)

**Comment by WiWa** [comment]
@ravindravmw Thanks!

**Comment by AnRkey** [comment]
@ravindravmw Thanks, that worked on Debian 8.3 with Mate too ;-)

**Comment by ravindravmw** [comment]
> Might be helpful to someone else skipping the links to make a mention in the github readme about the separate package. (Maybe in the Is open-vm-tools available with Linux distributions? section)

I have updated the section on master branch.

**Comment by rsh015** [comment]
installing open-vm-tools-desktop solved my issue as well with Debian 8.7 KDE
