### ISSUE TITLE
updating and upgrading on ubuntu xenial64 vagrant box 

### ISSUE THREAD

**Issue by icf20** [vmware/open-vm-tools#232]
hello i am doing some testing on this box https://app.vagrantup.com/ubuntu/boxes/xenial64

```
The following packages will be upgraded:
  open-vm-tools
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 432 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 open-vm-tools amd64 2:10.0.7-3227872-5ubuntu1~16.04.2 [432 kB]
Fetched 432 kB in 0s (1,518 kB/s)     
(Reading database ... 54004 files and directories currently installed.)
Preparing to unpack .../open-vm-tools_2%3a10.0.7-3227872-5ubuntu1~16.04.2_amd64.deb ...
```
1 for some odd reason ubuntu dont pack the latest version on their box 

2 running the system update and upgrade show that this is the only package to update

3 proceeding with the upgrade will break the package and no update can be done

**Comment by oliverkurth** [comment]
Thanks for reporting - please look at https://github.com/vmware/open-vm-tools/issues/229 , which is essentially the same issue.

**Comment by icf20** [comment]
so the best bet is to holdback the package with `sudo apt-mark hold open-vm-tools` ?

**Comment by oliverkurth** [comment]
Sorry, I think I am missing something. Can you please show the steps you did before you got the output you posted above, and what happens when you proceed with the upgrade?

**Comment by icf20** [comment]
> Sorry, I think I am missing something. Can you please show the steps you did before you got the output you posted above

sure

https://github.com/Yenthe666/InstallScript/pull/74#issuecomment-367948670

the script has a system update u dont need to run the script 


> what happens when you proceed with the upgrade?

ssh session dies at 5% and is irresponsive, open-vm-tools remain broken and can be fixed or reinstalled

**Comment by oliverkurth** [comment]
Sorry, this does not seem to be a problem with open-vm-tools, but with the script you are trying to run or a dependency problem with the other packages being installed.

**Comment by icf20** [comment]
are you sure because that happens even if i dont run the script  like i said above

**Comment by oliverkurth** [comment]
It looks like the script has installed a packages (like wkhtmltox-0.12.1_linux-trusty-amd64.deb), and this may have dependencies that conflict with open-vm-tools. So you would get this problem as long as that remains installed. If you are getting the errors in a fresh VM where the script never was executed, then it is a problem with the open-vm-tools package (and you should report that with Ubuntu). You didn't send the whole output with the errors you are getting though, so I can only guess.

**Comment by icf20** [comment]
> If you are getting the errors in a fresh VM where the script never was executed, then it is a problem with the open-vm-tools package



by the way if u look closer on the first post there is a update of the package
```
The following packages will be upgraded:
  open-vm-tools

```

`Preparing to unpack .../open-vm-tools_2%3a10.0.7-3227872-5ubuntu1~16.04.2_amd64.deb`

between that post and the post above( the image) ubuntu updated their vagrant box, the image is a reinstall 


https://app.vagrantup.com/ubuntu/boxes/xenial64
```
v20180223.0.0 currently released version
This version was created about 6 hours ago.
```
