### ISSUE TITLE
Can't Install open-vm-tools-desktop on Ubuntu 16.04

### ISSUE THREAD

**Issue by henrysia** [vmware/open-vm-tools#233]
Everything worked fine until last week when I was prompted to reboot my VM due to an update.
After rebooting, my Ubuntu resolution reverted back to 800x600 and copying and pasting between my OSX and Ubuntu stopped working.
I tried reinstalling the VM tools, but I got the following error:

```
henry@ubuntu:~$ sudo apt-get install --reinstall open-vm-tools open-vm-tools-desktop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 21 not upgraded.
Need to get 0 B/639 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 290671 files and directories currently installed.)
Preparing to unpack .../open-vm-tools_2%3a10.0.7-3227872-5ubuntu1~16.04.2_i386.deb ...
Unpacking open-vm-tools (2:10.0.7-3227872-5ubuntu1~16.04.2) over (2:10.0.7-3227872-5ubuntu1~16.04.2) ...
Preparing to unpack .../open-vm-tools-desktop_2%3a10.0.7-3227872-5ubuntu1~16.04.2_i386.deb ...
Unpacking open-vm-tools-desktop (2:10.0.7-3227872-5ubuntu1~16.04.2) over (2:10.0.7-3227872-5ubuntu1~16.04.2) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up open-vm-tools (2:10.0.7-3227872-5ubuntu1~16.04.2) ...
Setting up open-vm-tools-desktop (2:10.0.7-3227872-5ubuntu1~16.04.2) ...
Failed to get unit file state for run-vmblockx2dfuse.mount: No such file or directory
run-vmblock\x2dfuse.mount is a disabled or a static unit, not starting it.
Processing triggers for libc-bin (2.23-0ubuntu10) ...
henry@ubuntu:~$ uname -a
Linux ubuntu 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:26:51 UTC 2018 i686 i686 i686 GNU/Linux
henry@ubuntu:~$
```

Any help would be greatly appreciated. Thank you.

**Comment by stanguturi** [comment]
> Setting up open-vm-tools-desktop (2:10.0.7-3227872-5ubuntu1~16.04.2) ...
> Failed to get unit file state for run-vmblockx2dfuse.mount: No such file or directory
> run-vmblock\x2dfuse.mount is a disabled or a static unit, not starting it.
> Processing triggers for libc-bin (2.23-0ubuntu10) ...

Please check comments in  #207 for few steps to get this resolved.

**Comment by stanguturi** [comment]
> Please check comments in #207 for few steps to get this resolved.

Here are the links to the comments.

https://github.com/vmware/open-vm-tools/issues/207#issuecomment-354152823
https://github.com/vmware/open-vm-tools/issues/207#issuecomment-354903782
https://github.com/vmware/open-vm-tools/issues/207#issuecomment-357113151

Thanks
Sankar.
