### ISSUE TITLE
README should be reviewed

### ISSUE THREAD

**Issue by Decstasy** [vmware/open-vm-tools#239]
Hello,

the link http://open-vm-tools.sourceforge.net/ in open-vm-tools/README shows just a page with the content:
> We're moving!
> Come visit us on github. 

From Apr 17, 2015 linked here: https://github.com/vmware/open-vm-tools/blob/8c0cc53753b93fe7230ba339e898e1c15a067a05/open-vm-tools/README#L3

I can also imagine, that the minimum OS version for each module is also outdated: https://github.com/vmware/open-vm-tools/blob/8c0cc53753b93fe7230ba339e898e1c15a067a05/open-vm-tools/README#L71

There is more than once this dead link and the testing OS versions are very old: https://github.com/vmware/open-vm-tools/blob/8c0cc53753b93fe7230ba339e898e1c15a067a05/open-vm-tools/README#L109

The whole readme should be reviewed. I would really appreciate an update.

Thanks and best regards,
Dennis

**Comment by lemke1458** [comment]
Thanks, I've opened an internal bug to clean up the README.

**Comment by stanguturi** [comment]
We have updated the README. Please check d5c0bcea04aae65484ba3c2756b64acf6f6388d0
