### ISSUE TITLE
open-vm-tools doesn't allow for customizing OSes hostname

### ISSUE THREAD

**Issue by tedivm** [vmware/open-vm-tools#24]
In ESXI I can create custom settings to apply custom settings- the main one being "change hostname to vm name". This is extremely useful for puppet templates.

This works fine on my image that uses vmware tools, but creating an image with open-vm-tools fails to handle the hostname change.

**Comment by ravindravmw** [comment]
What's the version of open-vm-tools and what OS version are you using?

**Comment by tedivm** [comment]
Ubuntu 14.01 LTS, and I'm using the version packaged with apt (which appears to be 9.4.0 with patches applied).

**Comment by jantman** [comment]
@tedivm my understanding is that open-vm-tools < 9.10 requires the deploypkg plugin from VMWare in order to do guest customizations. See http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2075048

**Comment by ravindravmw** [comment]
@jantman yes, you are absolutely right!

**Comment by tedivm** [comment]
Awesome, good to know.
