### ISSUE TITLE
ip address of ubuntu vm is not populated on esxi ui 6.5.0 (Build 4887370)

### ISSUE THREAD

**Issue by Sheshagiri** [vmware/open-vm-tools#241]
Hi, IP Address of Ubuntu-16.04 is not populated in the General Information of the vm in vSphere Client with version 6.5.0 (Build 4887370).
<img width="484" alt="screen shot 2018-03-23 at 2 58 24 pm" src="https://user-images.githubusercontent.com/2954796/37821829-b3d8449e-2eaa-11e8-8552-1abd83d5df91.png">

I enabled debug logs as mentioned in https://github.com/vmware/open-vm-tools/issues/220, but don't see any errors in there.

```
root@ubuntu:/etc/init.d# /usr/bin/vmtoolsd -v
VMware Tools daemon, version 10.0.7.52125 (build-3227872)
root@ubuntu:/etc/init.d# /usr/bin/vmtoolsd --cmd "info-get guestinfo.ip"
10.73.40.93
root@ubuntu:/etc/init.d# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
root@ubuntu:/etc/init.d# 
```

**Comment by stanguturi** [comment]
A similar issue was reported in https://github.com/vmware/open-vm-tools/issues/462

Please make sure that guestinfo plugin is loaded and running inside the guest. guestinfo plugin is the one that captures the ip address and broadcasts it to the VMware hypervisor.

**Comment by Sheshagiri** [comment]
thank you @stanguturi for having a look at this. I don't have access to this environment anymore. Will keep this in mind though.
