### ISSUE TITLE
how to upgrade open-vm-tools silent in bash script

### ISSUE THREAD

**Issue by FreeEager** [vmware/open-vm-tools#242]
OS: Ubuntu 17.10

when I use the command below in my bash script:
 'sudo apt-get -q -y install open-vm-tools'
 or
 'sudo apt-get update && apt-get upgrade' 

It allways pause at here: 

Setting up open-vm-tools (2:10.1.10-3ubuntu0.1) ...
Configuration file '/etc/vmware-tools/tools.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** tools.conf (Y/I/N/O/D/Z) [default=N] ?  

how to pass this choice step automatically in shell script?

thank you.

**Comment by iKrushYou** [comment]
Did you figure this out?

**Comment by oliverkurth** [comment]
Hi @iKrushYou , this is not a question related to open-vm-tools but for apt. Here is some advice: https://serverfault.com/questions/527789/how-to-automate-changed-config-files-during-apt-get-upgrade-in-ubuntu-12

**Comment by FreeEager** [comment]
> Did you figure this out?

@oliverkurth offers a way which maybe helpful. Somehow, as upgrade open-vm-tools is not necessary for me, I just skipped the upgrade of open-vm-tools by the command below: 

apt-mark hold open-vm-tools
### do your normal update && upgrade work here ###
apt-mark unhold open-vm-tools

**Comment by oliverkurth** [comment]
> > Did you figure this out?
> 
> Hi, @iKrushYou, @oliverkurth offers a way which maybe helpful. Somehow, as upgrade open-vm-tools is not necessary for me, I just skipped the upgrade of open-vm-tools by the command below:
> 
> apt-mark hold open-vm-tools
> <<do your normal update && upgrade work here>>
> apt-mark unhold open-vm-tools

This might work, however this won't address the problem when other packages besides open-vm-tools have configuration changes. You will also miss open-vm-tools updates, which may be important. So I don't recommend this approach.

I am closing this issue because it's not an open-vm-tools issue. It's really about apt.
