### ISSUE TITLE
Vm tools not started - what logs to read

### ISSUE THREAD

**Issue by viktorovichandrej** [vmware/open-vm-tools#244]
Hello,

I was trying to [start vmtools in Centos](https://github.com/vmware/open-vm-tools/issues/243). I was expected it will start at system startup, but it was not happening. 

How to know problem that appears at system vm tools startup? What log files I should see ?

**Comment by stanguturi** [comment]
> I was trying to [start vmtools in Centos](https://github.com/vmware/open-vm-tools/issues/243). I was expected it will start at system startup, but it was not happening.

If you are building and installing 'open-vm-tools' from source, you need to write your own init script specific to the distro. Please check https://src.fedoraproject.org/rpms/open-vm-tools/blob/master/f/vmtoolsd.service for a reference. The init script will take care of starting vmtoolsd at startup. Check https://github.com/vmware/open-vm-tools/issues/320 where a similar issue was asked earlier. 

> How to know problem that appears at system vm tools startup? What log files I should see ?

Please check https://kb.vmware.com/s/article/1007873 for instructions to enable and capture the 'VMware Tools' log files inside the guest OS.
