### ISSUE TITLE
Error -107 cannot open connection! when mounting

### ISSUE THREAD

**Issue by suntong** [vmware/open-vm-tools#248]
As root:

```
$ ls -ld /mnt/hgfs
drwxr-xr-x 2 root root 4096 May  3 13:50 /mnt/hgfs

% mount -t fuse.vmhgfs-fuse .host:/ /mnt/hgfs
Error -107 cannot open connection!

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
```

This is after 

    sudo apt-get -y install open-vm-tools fuse open-vm-tools-desktop

and reboot.

Is it a known issue? THX!

**Comment by suntong** [comment]
Thanks for the response @johnwvmw, here they are:

![image](https://user-images.githubusercontent.com/422244/39768453-5339a3c2-52b7-11e8-85e2-88d231069cad.png)

the current version of open-vm-tools are:

2:10.2.0-3ubuntu3: amd64

for both open-vm-tools and open-vm-tools-desktop

Note that

For the same host, if using the old Ubuntu 17.04, then the share _works fine_. The open-vm-tools and open-vm-tools-desktop there that I'm using are:

```
 open-vm-tools_2:10.1.5-5055683-1ubuntu1.1
 open-vm-tools-desktop_2:10.1.5-5055683-1ubuntu1.1
```

**Comment by lousybrit** [comment]
Hi there,

I am the main owner for the Shared Folders feature.

We haven't done a great job documenting this change but you have run into the change from using a kernel client driver to a FUSE file system driver.

You should change your mount command format:
mount -t fuse.vmhgfs-fuse .host:/ /mnt/hgfs

to  the FUSE mount
/usr/bin/vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other

If you run the above as root either sudo or su you should have the mount appear as before for all users.

Let me know if this still doesn't work for you but it should.
Thanks

Steve

**Comment by suntong** [comment]
Thanks @lousybrit, 

I gave it a try, but got the same thing:

```
root@vm:~# /usr/bin/vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other
Error -107 cannot open connection!

root@vm:~# /usr/bin/vmhgfs-fuse -d .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other
Error -107 cannot open connection!
```

I.e. the `-o debug` didn't give much helpful info either. 

Anything else that I can try?

**Comment by lousybrit** [comment]
Are you sure you have the feature enabled?
I only get this error if the settings for the Shared Folders feature are disabled.
For Workstation Menu VM -> Settings -> Options tab -> Shared Folders.
Modify the setting for "Disabled" to "Always Enabled"
Hit OK button.

The Shared Folders should automatically mount for you. So recheck the mount in the guest after this.

Can verify with the VM config file with the extension ".vmx " with the following line
isolation.tools.hgfs.disable = "TRUE"

If it is not the above, then somethiing odd is set up in your Linxu environment.

Steve

**Comment by suntong** [comment]
Oh, I'm so~~~ sorry. I turned it on, and checked it before, I swear. 

Yeah, it's working now. Thanks a lot everyone, sorry for bothering you.

**Comment by suntong** [comment]
>The Shared Folders should automatically mount for you. . .
Can verify with the VM config file with the extension ".vmx " with the following line
isolation.tools.hgfs.disable = "TRUE"

I don't quite get above -- I've rechecked the settings for the Shared Folders feature, AOK. However,

- My VM config has: `isolation.tools.hgfs.disable = "FALSE"`. Why need to disable it to make things work?
- The Shared Folders is automatically mount for me. The mount in the guest does not seems to have it. 

```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=1408180k,nr_inodes=352045,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=287136k,mode=755)
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=24,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15928)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
vmware-vmblock on /run/vmblock-fuse type fuse.vmware-vmblock (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other)
tmpfs on /run/user/9999 type tmpfs (rw,nosuid,nodev,relatime,size=287132k,mode=700,uid=xxx,gid=xxy)
```

**Comment by lousybrit** [comment]
The vmx file setting I mentioned, if set to "TRUE" would indicate that the feature is in fact disabled. I mentioned it only for verification for the Shared Folders feature state.
If the disable setting is set to FALSE as you mention then the feature is enabled. It is reverse logic just to be confusing. Sorry.
You don't change the .vmx file setting manually unless your VM is powered off and you don't want to or can't use the UI. The UI is the preferred and expected way to enable/disable the feature and add/remove shares and modify their properties.

You stated that it was working. However, now you add that if you use the UI and disable and enable the shared folders feature, it now doesn't work at all? Or do you mean that the mount doesn't appear and be listed by running "mount" in a terminal shell after the UI enabled the feature? 

Steve

**Comment by suntong** [comment]
> You have the VM up and running, from the UI disable Shared Folders hit OK, go back to the UI enable Shared Folders and hit OK. You don't see any error dialog messages pop up? 

Yep. 

> In the Ubuntu VM mount does not list the /mnt/hgfs 

_Now_ it is there, and in my `mount` and `df` output as well. Thinking that I might have mounted it manually previously, so I remove the mount and tried above steps again. and the `/mnt/hgfs` is mounted properly again. 

So, what was the problem? 

The Shared Folders is not automatically mounted when system initially booted up. 

- reboot the VM 
- login after reboot 
- do  `mount` and `df`
- the  `/mnt/hgfs` is not in the output (not mounted)

Repeat the steps you mentioned above, the `/mnt/hgfs` is mounted properly again. 

I first thought I don't have that  `/mnt/hgfs` entry in my `/etc/fstab`, but then realized that your above steps don't need it there either. 

Again, just want to be clear, not a big deal to me at all.

**Comment by lousybrit** [comment]
For automatic mount on boot, you can save yourself from having to go through the UI steps by adding an entry to fstab. I have the following:
vmhgfs-fuse /mnt/hgfs fuse defaults,allow_other 0 0

**Comment by prusswan** [comment]
I had an old line for automounting `/mnt/hgfs`, but after some update in 16.04 it just stopped working, and dropping the system to emergency mode on every boot. The current entry from @lousybrit fixed that.

**Comment by erbaker** [comment]
Sorry to necro an old topic; however I've stumbled upon shared folders and vmhgfs-fuse causes segfaults when trying to mount. 
`sudo /usr/bin/vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other`

I believe VMWare may have also been changed, as I don't have an option to "always allow" file sharing, nothing is mounted by default. 

![image](https://user-images.githubusercontent.com/245716/49670645-f45b6180-fa2a-11e8-895d-82588f6da91c.png)

**Comment by zoneyang** [comment]
I have set isolation.tools.hgfs.disable = "FALSE", but the follow code doesn't work for me.
`vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other`
and return：
`Error -107 cannot open connection!`

my settting in vmx is：
`
isolation.tools.hgfs.disable = "FALSE"
sharedFolder0.present = "TRUE"
sharedFolder0.enabled = "TRUE"
sharedFolder0.readAccess = "TRUE"
sharedFolder0.writeAccess = "TRUE"
sharedFolder0.hostPath = "E:\work"
sharedFolder0.guestName = "work"
sharedFolder0.expiration = "never"
sharedFolder.maxNum = "1"
`

**Comment by zoneyang** [comment]
> For automatic mount on boot, you can save yourself from having to go through the UI steps by adding an entry to fstab. I have the following:
> vmhgfs-fuse /mnt/hgfs fuse defaults,allow_other 0 0



> Hi there,
> 
> I am the main owner for the Shared Folders feature.
> 
> We haven't done a great job documenting this change but you have run into the change from using a kernel client driver to a FUSE file system driver.
> 
> You should change your mount command format:
> mount -t fuse.vmhgfs-fuse .host:/ /mnt/hgfs
> 
> to the FUSE mount
> /usr/bin/vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other
> 
> If you run the above as root either sudo or su you should have the mount appear as before for all users.
> 
> Let me know if this still doesn't work for you but it should.
> Thanks
> 
> Steve

could you help me?

**Comment by suntong** [comment]
Please read the previous answer(s) before asking questions, especially, 

> Are you sure you have the feature enabled?
I only get this error if the settings for the Shared Folders feature are disabled.
For Workstation Menu VM -> Settings -> Options tab -> Shared Folders.
Modify the setting for "Disabled" to "Always Enabled"
Hit OK button.

**Comment by zoneyang** [comment]
> Please read the previous answer(s) before asking questions, especially,
> 
> > Are you sure you have the feature enabled?
> > I only get this error if the settings for the Shared Folders feature are disabled.
> > For Workstation Menu VM -> Settings -> Options tab -> Shared Folders.
> > Modify the setting for "Disabled" to "Always Enabled"
> > Hit OK button.

Yes, I have tried, but the problem also came out.

**Comment by lousybrit** [comment]
If you see

Error -107 cannot open connection!

Then this means that the server is not responding.
So, a question or more:
- DId you edit the vmx file directly?
- Did you have the VM powered off when you did this? Or suspended at a minimum.
- Why not simply use the UI and shared folders setting to do this? That way you can do this with the VM powered on and running.
- If you edited the setting while the VM was running, the setting will be not read and lost. The VMX settings will be read only on the VM start up either power on or resume. 
- If you do not have an entry in the fstab for the Linux VM modifying the Shared Folders setting from off to on with a FUSE client can go unnoticed and the mount might not be created. This is a known issue we are fixing. So use a fstab entry if you want consistency of Shared Folder mounts that persist across system reboot.

Here is the text from the other thread about fstab and shared folder mounts:
There are 2 ways to specify the Shared Folders mounts persistently in /etc/fstab
Below there are both samples /etc/fstab line to mount a FUSE vmhgfs export.

Method 1: Specifying the file system

<file system> <mount point> <type> <options> <dump> <pass>

Replace <file system> with vmhgfs-fuse.
Replace <mount point> with the local file system on which the exported directory is mounted, which default replacement is to use /mnt/hgfs
Replace <type> with fuse.
e.g.
vmhgfs-fuse	/mnt/hgfs	fuse	defaults,allow_other	0	0

Method 2: Specifying the remote server and share

<server>:</remote/export> </local/directory> <fuse-type> <options> <dump> <pass>
Replace <server> with the hostname .host the shared folders name of the host server exporting the hosts file system.
Replace </remote/export> with the path to the exported directory which defaults to/or you can use the /share-name-you-created.
Replace </local/directory> with the local file system on which the exported directory is mounted, which defaults to /mnt/hgfs.
Replace <fuse-type> with fuse.vmhgfs-fuse.
Eg.
.host:/	/mnt/hgfs	fuse.vmhgfs-fuse	defaults,allow_other	0	0

Final diagnositic test to run from a terminal window:
/usr/bin/vmware-hgfsclient
What does it report? If the shared folder you have added is not shown or nothing is shown the host server is likely not enabled.

Hope that helps.
Steve

**Comment by tbl0605** [comment]
This syntax also worked for me:
vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other

*BUT* I first had to be sure that /mnt/hgfs was totally empty (I created a directory /mnt/hgfs/myshare for my tests) or my Ubuntu system booted into recovery mode without more explanation.
I just wanted to share that ;)

Thierry.

**Comment by babuilyas** [comment]
Try this 
sudo vmhgfs-fuse -o nonempty -o allow_other -o uid=? .host:/SUM /usr/sap/R3P/SUM
? = numeric id for user account. can be get by command "id" or "getent passwd"

**Comment by tbl0605** [comment]
> Try this
> sudo vmhgfs-fuse -o nonempty -o allow_other -o uid=? .host:/SUM /usr/sap/R3P/SUM
> ? = numeric id for user account. can be get by command "id" or "getent passwd"

Thank you @babuilyas, your command worked well, I didn't know about the "nonempty" parameter.
Now in my /etc/fstab file, I've added following line and everything seems ok:

vmhgfs-fuse /mnt/hgfs fuse defaults,nonempty,allow_other 0 0

**Comment by zxweed** [comment]
Have the same problem, fixed by reinstall **open-vm-tools**

**Comment by sashokbg** [comment]
We were just having the same issue "Error -107 cannot open connection!" when running the bellow command and rebooting the windows host machine fixed the problem.

_/usr/bin/vmhgfs-fuse .host:/Downloads /mnt/shared -o subtype=vmhgfs-fuse,allow_other_

Too bad we lost a couple of hours for nothing.

Here is a summary of some checks to go through (mostly covered in above comments):
- check your sharing is active in machine settings
- run _vmtoolsd --version_ to make sure vmtools is installed in guest
- run _ps aux | grep "vmtoolsd"_ to make sure it is running in guest
- run _/usr/bin/vmware-hgfsclient_ in guest to see that shares are visible
- make sure _isolation.tools.hgfs.disable=FALSE_ in vmx file on host
- reboot host <-- this one worked

**Comment by eleses** [comment]
This seems to be an undocumented 'feature' but with WS 17.5.2 if there's a vmdk error on startup (that I had to fix with `vmware-vdiskmanager.exe -R`) then your VM will have its sharing automagically turned off in options after the fix. Some kind of 'safe mode' for the VM gets triggered, I guess.
