### ISSUE TITLE
vixTools.c:2291: possible missing break ?

### ISSUE THREAD

**Issue by dcb314** [vmware/open-vm-tools#25]
[vixTools.c:2291] -> [vixTools.c:2293]: (warning) Variable 'err' is reassigned a value before the old one has been used. 'break;' missing?

   case VGAUTH_E_COMM:
      err = VIX_E_FAIL;
   case VGAUTH_E_NOTIMPLEMENTED:
      err = VIX_E_NOT_SUPPORTED;
      break;

**Comment by ravindravmw** [comment]
Yes, that's a bug. Thanks for reporting.

**Comment by stanguturi** [comment]
Fixed in ebed1074323950b03d25b31c54741eaa128c3e0c. Closing.
