### ISSUE TITLE
Centos 7 guest customization broken with multiple search domains

### ISSUE THREAD

**Issue by lschweiss-wustl** [vmware/open-vm-tools#251]
If more than one DNS search domain is specified, the DOMAIN= line in /etc/sysconfig/network-scripts/ifcfc-{adapter} must be quoted.

If the content is not quoted Network Manager will not set the search line in /etc/resolv.conf.

**Comment by pengzhencao** [comment]
Thanks for pointing this out.
We've also found this issue during our internal test and we've already fixed it internally.
It will be fixed once we merge our fix into future open-vm-tools releases

**Comment by pengzhencao** [comment]
Sorry. The fix is in our perl customization engine which is delivered within VMware vCenter.
It has been fixed in vspher6.5 update2 and will be in next vsphere6.0 patch/udpate release.
So what version/build number of vCenter are you using?

**Comment by den-is** [comment]
same here, description in reference by *vancluever*
esxi 6.5, vcenter 6.7
open-vm-tools v10.1.10-3.el7

**Comment by pengzhencao** [comment]
It will be fixed in vsphere6.7 next patch/udpate release.
@den-is , if you need this fix ASAP, maybe you could use vcenter6.5 update2 since you are using esxi6.5 and we've release vsphere6.5 update2
https://docs.vmware.com/en/VMware-vSphere/6.5/rn/vsphere-vcenter-server-65u2-release-notes.html

**Comment by Boran** [comment]
Could you please provide a diff for the "perl customization engine" in vCenter, so that the fix can be manually applied to existing v6.5 installations?

**Comment by rabbitt** [comment]
@Boran  I haven't upgraded myself yet, but after looking at the code, this should probably work:

```patch
--- /usr/lib/vmware-vpx/imgcust/linux/imgcust-scripts/RHEL6Customization.pm.orig	2019-04-25 09:44:42.073517397 -0400
+++ /usr/lib/vmware-vpx/imgcust/linux/imgcust-scripts/RHEL6Customization.pm	2019-04-25 09:45:32.938106291 -0400
@@ -94,7 +94,7 @@
    # Set up dns suffix search list
    my $dnsSuffixes = $self->{_customizationConfig}->GetDNSSuffixes();
    if ($dnsSuffixes && @$dnsSuffixes) {
-      push(@content, "DOMAIN=" . join(' ', @$dnsSuffixes) . "\n");
+      push(@content, 'DOMAIN="' . join(' ', @$dnsSuffixes) . "\"\n");
    }

    # Set up the rest of the fields.
```

**Comment by stanguturi** [comment]
> It will be fixed in vsphere6.7 next patch/udpate release.
> @den-is , if you need this fix ASAP, maybe you could use vcenter6.5 update2 since you are using esxi6.5 and we've release vsphere6.5 update2
> https://docs.vmware.com/en/VMware-vSphere/6.5/rn/vsphere-vcenter-server-65u2-release-notes.html

Fixed in the latest vSphere releases as mentioned above. Closing.
