### ISSUE TITLE
open-vm-tools 10.x for Ubuntu 14.x?

### ISSUE THREAD

**Issue by jauling** [vmware/open-vm-tools#255]
I'm unable to find a reputable source to install open-vm-tools 10.x onto our Ubuntu 14.04.5 LTS servers. The latest open-vm-tools for this Ubuntu distro version looks to be 9.4?

AFAIK, I must be running open-vm-tools 10.x in order to upgrade my VM hardware to version 9 or higher, which is a prerequisite to mitigate spectre/meltdown (variant 1 & 2).

**Comment by stanguturi** [comment]
> I'm unable to find a reputable source to install open-vm-tools 10.x onto our Ubuntu 14.04.5 LTS 
servers. The latest open-vm-tools for this Ubuntu distro version looks to be 9.4?

Yes. As per https://packages.ubuntu.com/search?keywords=open-vm-tools, 9.4 is the latest OVT version available for Ubuntu 14.04.

> AFAIK, I must be running open-vm-tools 10.x in order to upgrade my VM hardware to version 9 or higher, which is a prerequisite to mitigate spectre/meltdown (variant 1 & 2).

Please check https://kb.vmware.com/s/article/1003746, Hardware version 9 corresponds to ESXi 5.1. Please check https://packages.vmware.com/tools/versions for one-to-one mapping between VMware Tools and ESXi versions. The tools 9.4 should be sufficient for upgrading the VM hardware version to 9.

For other higher VM hardware versions, if you want to install the tools 10.x, you can
* Build the OVT from source and install it or
* Download the explicit version of tools from https://my.vmware.com/web/vmware/downloads and install in the guest or
* Uninstall the OVT tools in the guest. Mount the Tools Linux ISO bundled with ESXi and install.

Thanks
