### ISSUE TITLE
New Interface Config File Created Instead of the Correct One Being Customized

### ISSUE THREAD

**Issue by alexgaganashvili** [vmware/open-vm-tools#256]
Hi,

I'm using Terraform v0.11.7.
It won't customize the network interface on a VM. Instead of customizing ens192, it creates a new interface configuration file /etc/sysconfig/network-scripts/ifcfg-ether and tries to customize it.
The OS is Fedora Atomic 28.

Thanks
Alex

**Comment by pengzhencao** [comment]
Unfortuanately, VMware does not officially support customization for Fedora/Fedora Atomic 28, we've only tested and verified some RHEL Atomic OS could work.
Maybe you could try to run customization with open-vm-tools+cloud-init,  after install/config cloud-init through Atomic's package management tool, add the following ‘disable_vmware_customization: false’ to "/etc/cloud/cloud.cfg". Then run customization.  But this is not our officially supported OS and there is NO guarantee if it works.
Guest OS Customization Support Matrix:
https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf

**Comment by stanguturi** [comment]
> Unfortuanately, VMware does not officially support customization for Fedora/Fedora Atomic 28, we've only tested and verified some RHEL Atomic OS could work.

Thanks @pengzhencao Closing as per the previous comment.

**Comment by alexgaganashvili** [comment]
I see fedora here:

https://github.com/vmware/open-vm-tools/blob/1f128736f9975b7afa9e342ec52575f57bf63d13/open-vm-tools/lib/misc/hostinfoPosix.c#L191


Here's how it worked for us eventually:
https://github.com/ansible/ansible/issues/37198#issuecomment-452784692
