### ISSUE TITLE
Suspend guest and shutdown guest do not work on Fedora 28 guest / Windows 10 host / VMware Workstation Pro 14.1.2 build-8497320 / open-vm-tools 10.2.5-2

### ISSUE THREAD

**Issue by hermidalc** [vmware/open-vm-tools#258]
The suspend guest and shutdown guest buttons and keyboard shortcuts do not work on Fedora 28 guest.  Everything worked with Fedora 27 before upgrade.

**Comment by jonathanvmw** [comment]
Thank you for reporting the problem.  A bug has been filed internally for your report.

What version of open-vm-tools was running on Fedora 27 before the upgrade?

**Comment by hermidalc** [comment]
Hi @jonathanvmw - all software versions were identical on Fedora 27.  Within Fedora 27 guest in the Software GNOME app I simply clicked to upgrade the system to 28 and after it rebooted and completed the upgrade I saw that the VMware suspend guest and shutdown guest buttons and keyboard shortcuts stopped working.

**Comment by hph86** [comment]
I can confirm this behavior as well (Host: Win 10 1803, 17134.112, Guest: Fedora 28, open-vm-tools-10.2.5-2.fc28). Both, F27 and F28 have been on the same version since 2 months (see [here](https://bodhi.fedoraproject.org/updates/FEDORA-2018-7ea12a5bc4) and [here](https://bodhi.fedoraproject.org/updates/FEDORA-2018-c97904a30a)).

On my system, SELinux is set to "Enforcing" (which is Fedora's default). When I hit the pause button of VMware, the following entry shows up in journalctl:

```
Jun 26 10:00:42 xxxxxx audit[807]: USER_AVC pid=807 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.77 spid=1026 tpid=2556 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:system_r:vmtools_unconfined_t:s0 tclass=dbus permissive=0
                                    exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=? terminal=?'
```

I created an exemption for this and everything works fine again.

```
cat | audit2allow -M fix-f28-open-vm-tools
sudo semodule -i fix-f28-open-vm-tools.pp
```

Therefore, I believe this issue is not caused by open-vm-tools. It should probably be handed over to the Fedora Bug Tracker.

**Comment by hermidalc** [comment]
Hi @hph86 - could you post the details of the exception you created? Sorry I’m not well acquainted with selinux

**Comment by hph86** [comment]
@hermidalc The error message that I quoted above appears in ``journalctl``` (just run the command ```journalctl```). Copy that error message and paste it into ```cat | audit2allow -M fix-f28-open-vm-tools``` (run the command, then paste, then CTRL-D). You should find the file ```fix-f28-open-vm-tools.pp``` in your CWD. Then run ```sudo semodule -i fix-f28-open-vm-tools.pp``` to load the newly created policy. It would be great, if you could confirm if this solves your problem as well. It would indicate that your problem originated from the same root cause as mine did.

**Comment by hermidalc** [comment]
Hi @hph86 and @jonathanvmw - hph86's description of problem is correct and solution works for me too.

**Comment by hph86** [comment]
Just for reference, someone has filed a similar bug at the Red Hat/Fedora bug tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1598346

**Comment by EgoAleSum** [comment]
I have the same issue. Suspending a FC28 doesn't work.

**Comment by hermidalc** [comment]
BTW @jonathanvmw @oliverkurth @thomashvmw - open-vm-tools 10.3.0 just installed yesterday via Fedora Updates.  So far everything works great on my Fedora 28 guest VM and I used functionality heavily yesterday.

**Comment by oliverkurth** [comment]
Thx @hermidalc - this sounds like the issue is resolved. Feel free to reopen if that is not the case.
