### ISSUE TITLE
AC_VMW_CHECK_LIB troubles

### ISSUE THREAD

**Issue by vapier** [vmware/open-vm-tools#26]
the current AC_VMW_CHECK_LIB currently only works for native builds and fails badly when trying to cross-compile due to:
- it hardcodes "pkg-config" instead of standard PKG_CHECK_MODULES ... at the very least, it should utilize AC_CHECK_TOOL and respect the $PKG_CONFIG env var
- it should use AC_CHECK_TOOL instead of AC_PATH_PROG to look for the fallback xxx-config scripts

**Comment by oliverkurth** [comment]
Thanks for reporting this issue. I filed an internal bug for this, and we will investigate.

**Comment by stanguturi** [comment]
Fixed in cecbaf6b16f5fd1ecbfe4419310352353b047ba2
