### ISSUE TITLE
Guest Network Customization - systemd-networkd

### ISSUE THREAD

**Issue by shibumi** [vmware/open-vm-tools#267]
Hello everybody,
systemd-networkd has replaced the deprecated if-up/if-down scripts.
It would be nice if you could support systemd-networkd for network customization.
In Ubuntu 18.04 there is already no if-up/if-down scripts on default. They use systemd-networkd with netplan as abstraction layer on their server images.

I suggest you support systemd-networkd instead of if-up/if-down scripts. You could also use some sort of autodetection ( if ubuntu_version < 18.04; then ifup/ifdown; else systemd-networkd)

**Comment by PengpengSun** [comment]
Hi Shibumi,

Yes, You are right. Guest customization supports netplan from ESXi 6.7 and ESXi 6.5 Update2.

Best regards,
Pengpeng

**Comment by shibumi** [comment]
Just out of interest. Doesn't netplan produce just more work? You could easily stick on systemd-networkd instead of netplan. I don't think redhat will adopt netplan and since then you would need to support netplan and systemd-networkd and one of the deprecated solutions.

**Comment by hangrao** [comment]
@oliverkurth

**Comment by PengpengSun** [comment]
Yes, Guest customization supports netplan (on Ubuntu18.04 server only). 
For Ubuntu18.04 Desktop and other distros, ex redhat, they does NOT adopt netplan.

**Comment by AlekseyPalshin** [comment]
Hello everybody. I am using _Ubuntu 18.04.1 LTS_ and _open-vm-tools 2:10.3.0-0ubuntu1~18.04.2_ over vCD 9.1(based _vSphere 6.7_)
Open-vm-tools attempts to configure interfaces via /etc/network/interfaces
Netplan configuration is /etc/netplan/*.yaml
Where can i go wrong?

**Comment by shibumi** [comment]
@PengpengSun can you please specify the version of open-vm-tools that supports netplan? Because it looks like that people with ubuntu 18.04.1 LTS version still has issues with it. I had sadly no time yet to get some logs in my vmware environment.

**Comment by PengpengSun** [comment]
@AlekseyPalshin May I have the /var/log/vmware-imc/toolsDeployPkg.log from the Ubuntu 18.04.1 LTS?

**Comment by PengpengSun** [comment]
@shibumi The netplan supporting fix is on vCenter side(6.5U2 or 6.7).

**Comment by hangrao** [comment]
@shibumi How is the customization going on your Ubuntu 18.04 VMs? As Pengpeng mentioned, netplan support has been added since 6.5 U2. Please kindly let us know if you still encounter any issue.

And you might already know that there's a KB about Ubuntu 18.04 customization. Just FYI:
https://kb.vmware.com/s/article/54986

**Comment by stanguturi** [comment]
> @shibumi How is the customization going on your Ubuntu 18.04 VMs? As Pengpeng mentioned, netplan support has been added since 6.5 U2. Please kindly let us know if you still encounter any issue.
> 
> And you might already know that there's a KB about Ubuntu 18.04 customization. Just FYI:
> https://kb.vmware.com/s/article/54986

Closing this issue. Please reopen if the issue still exists with ESXi 6.5U2 and 6.7.
