### ISSUE TITLE
Customization of VM from template fails for Ubuntu 18.04

### ISSUE THREAD

**Issue by gsrigo** [vmware/open-vm-tools#269]
I have verified that deploying from a template, sometimes VM inconsistently fail and they do not generate any log file with the possible cause. The guest VM is created, however it does not assign the hostname, it only gets the template hostname. On the logs, there is no indication why the hostname assignment failed

**On the vSphere Client I can see a description with the following:
"An error occurred while customizing VM <vmname>. For details reference the log file <No Log> in the guest OS."

Possible Causes:
" customization of the target operating system is not supported"** 

However, by checking the website and vmware, it seems like Ubuntu 18.04 is supported. Our systems have version build 5318200. On the guest OS, open-vm-tools is at version "VMware Tools daemon, version 10.2.0.1608 (build-7253323)"

**Comment by stanguturi** [comment]
> However, by checking the website and vmware, it seems like Ubuntu 18.04 is supported. Our systems have version build 5318200. On the guest OS, open-vm-tools is at version "VMware Tools daemon, version 10.2.0.1608 (build-7253323)"

build 5318200 corresponds to VMware vCenter version 6.0 update 3b. The guest customization support for Ubuntu 18.04 was added only from vCenter 6.5 Update 2. Check https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf for the details. Please reopen this bug if you encounter any issue even after upgrading the vCenter.
