### ISSUE TITLE
Centos7 - vmtools start failed

### ISSUE THREAD

**Issue by kstst** [vmware/open-vm-tools#275]
Is this a known issue?

Package open-vm-tools-10.1.10-3.el7_5.1.x86_64 already installed and latest version

root@centos7-vm vmtoolsd.service.requires]# systemctl status vmtoolsd
● vmtoolsd.service - Service for virtual machines hosted on VMware
   Loaded: loaded (/usr/lib/systemd/system/vmtoolsd.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Thu 2018-07-26 17:58:52 EDT; 8s ago
           ConditionVirtualization=vmware was not met
     Docs: http://github.com/vmware/open-vm-tools
[root@centos7-vm vmtoolsd.service.requires]# cd /etc
[root@centos7-vm etc]# grep -R ConditionVirtualization
systemd/system/multi-user.target.wants/vmtoolsd.service:ConditionVirtualization=vmware
systemd/system/default.target.wants/systemd-readahead-replay.service:ConditionVirtualization=no
systemd/system/default.target.wants/systemd-readahead-collect.service:ConditionVirtualization=no
systemd/system/basic.target.wants/microcode.service:ConditionVirtualization=false
systemd/system/basic.target.wants/rhel-dmesg.service:ConditionVirtualization=!container
systemd/system/vmtoolsd.service.requires/vgauthd.service:ConditionVirtualization=vmware

4.7.4-1.el7.elrepo.x86_64
Windows 10, 64-bit  (Build 17134) 10.0.17134
VMware® Workstation 12 Player
12.5.9 build-7535481

**Comment by zhoumgh** [comment]
What is the result of 'vmware-checkvm -p' and 'vmware-checkvm -h' commands?

**Comment by kstst** [comment]
[root@centos7-vm etc]# vmware-checkvm -p
Not running in a virtual machine.
[root@centos7-vm etc]# vmware-checkvm -h
Not running in a virtual machine.
[root@centos7-vm etc]#

**Comment by zhoumgh** [comment]
This means that VMware Tools has not detected VMware Hypervisor. Could you run this command on host side VM folder?

grep -e "virtualHW" -e "monitor_control" vmware.log

**Comment by kstst** [comment]
2018-07-26T17:44:14.304-04:00| vmx| I125: DICT         virtualHW.version = "12"
2018-07-26T17:44:14.304-04:00| vmx| I125: DICT virtualHW.productCompatibility = "hosted"

**Comment by kstst** [comment]
I am not using any Windows VMs.
There is currently a Centos7 VM running with the issue and a Fedora28 running with no issues on the Windows 10 host.

**Comment by zhoumgh** [comment]
Fedora28 seems to have newer OVT:
vmware-toolbox-cmd -v
10.2.0.1608 (build-7253323)

Could you try upgrade OVT or build it yourself?

**Comment by kstst** [comment]
I like most users would prefer to use the yum command to keep packages updated. Is there a way to verify if the Centos 7 package is broken? Do you have a way to test? 

I will try to upgrade and see what happens..

**Comment by zhoumgh** [comment]
I just created a new CentOS 7.5 VM:

# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)

# uname -r
3.10.0-862.el7.x86_64

# vmware-toolbox-cmd -v
10.1.10.63510 (build-6082533

# systemctl status vmtoolsd
...
   Active: active (running) since ...
...

vmtoolsd is running.

Did you upgrade kernel version to 4.7.4-1.el7.elrepo.x86_64?

**Comment by kstst** [comment]
I am closing this due to the realization that I am running a development kernel. The kernel works with vmtools until you select the boot option enabling Xen hypervisor, which prevents vmtoolsd from starting. 

It would be nice if the error provided more detail into the cause.
ConditionVirtualization=vmware was not met

Thanks for the help identifying this!
