### ISSUE TITLE
OVT VM (Guest Managed vmwate tool - 2147483647) is not pingable when migrated to ESX6.5

### ISSUE THREAD

**Issue by Sardar28g** [vmware/open-vm-tools#276]
OVT VM (Guest Managed vmwate tool - 2147483647) is not pingable when migrated to ESX6.5

**Comment by ravindravmw** [comment]
Could you please check if the guest has IP address and if guest can reach out to other machines?

I'm also thinking it might not be related to open-vm-tools and you might want to open a case with VMware support to take this up further because it might require analysis from the vSphere side.

**Comment by stanguturi** [comment]
> Could you please check if the guest has IP address and if guest can reach out to other machines?
> 
> I'm also thinking it might not be related to open-vm-tools and you might want to open a case with VMware support to take this up further because it might require analysis from the vSphere side.

Please follow the instructions mentioned above and open a case with VMware support. Not really an issue with open-vm-tools. Closing the issue.
