### ISSUE TITLE
Virtual Machine's time is sync up with ESXi host when start the vmtoolsd service although the 'timesync' is disabled

### ISSUE THREAD

**Issue by lidothui** [vmware/open-vm-tools#277]
Virtual Machine's time is sync up with ESXi host when start the vmtoolsd service although the 'timesync' is disabled.
1. Disable the timesync on virtual machine: /usr/bin/vmware-toolbox-cmd timesync disable
2. Start vmtoolsd service: service vmtoolsd start
Behavior: The virtual machine's time was sync up with ESXi host immediately.
I think I have disabled the timesync, and should not sync up the time of virtual machine with ESXi host when start the vmtoolsd service.

**Comment by lidothui** [comment]
The version I used is open-vm-tools 9.4.6

**Comment by ravindravmw** [comment]
> Disable the timesync on virtual machine: /usr/bin/vmware-toolbox-cmd timesync disable

This may not be enough. You might want to read about this here:

1. VMware KB - https://kb.vmware.com/kb/1189
2. VMware Blog - https://blogs.vmware.com/apps/2016/01/completely-disable-time-synchronization-for-your-vm.html

**Comment by stanguturi** [comment]
> This may not be enough. You might want to read about this here:
> 
> 1. VMware KB - https://kb.vmware.com/kb/1189
> 2. VMware Blog - https://blogs.vmware.com/apps/2016/01/completely-disable-time-synchronization-for-your-vm.html

All the options mentioned in the above KB articles need to be set to FALSE to *completely disable* the time synchronization inside the guest VM. Please reopen if you encounter the issue even after ALL the settings are set to FALSE.
