### ISSUE TITLE
Fedora 27/28 guest networking stops working after VM start from suspend (Windows 10 host)

### ISSUE THREAD

**Issue by hermidalc** [vmware/open-vm-tools#278]
Hi - this is an issue I've had I since Fedora 27 VM and open-vm-tools 10.1.x I believe.

After starting my Fedora 27 or 28 VM after a suspend, many times there is no networking.  The GNOME desktop Network Manager widget on the upper righthand corner is gone as well.  When I do an ifconfig I see the ens33 interface.  Not sure what is going on or how to troubleshoot it more.  I always just reboot the VM and then everything is working again.

**Comment by ravindravmw** [comment]
Is your VM running on ESXi host or Workstation or Fusion? Could you please collect /var/log/vmware-network.log from your VM when you reproduce this issue?

**Comment by hermidalc** [comment]
Hi @ravindravmw for now I'm closing the issue.  I've tested long enough and it hasn't returned. Looks like 14.1.3 fixed it or one of the latest updates on the Fedora 28 side.

**Comment by ravindravmw** [comment]
Thanks for the update. Please collect the logs I requested earlier if you see this again.

**Comment by cicku** [comment]
I have to add a comment here as I'm experiencing the same problem. I have to manually restart the NM using systemctl.

Guest is Fedora 28 with latest updates installed. Host is VMware 14 Pro.
