### ISSUE TITLE
Limited set of environment variables

### ISSUE THREAD

**Issue by lucdekens** [vmware/open-vm-tools#279]
When I start a process in the guest OS through the StartProgramInGuest method, I only seem to get a very limited set of environment variables.
I know I can add environment variables when calling StartProgramInGuest, but shouldn't I be seeing the same set of environment variables as when I connect to guest OS through a SSH session for example?

**Comment by lucdekens** [comment]
I noticed this in Photon 2.0 with open-vm-tools.x86_64 10.1.10-1.ph2

**Comment by lemke1458** [comment]
An interactive login runs all the various shell setup files, StartProgram doesn't attempt to do this.

**Comment by lucdekens** [comment]
I understand about the shell files, but what about the system files?
For example /etc/sysconfig/proxy

**Comment by lemke1458** [comment]
No.

Shell setup is very distro (and shell) specific, which is another reason we don't try, and instead expose a way to pass env variables, as well as an API to query them.

**Comment by lucdekens** [comment]
Ok, thanks.
So I'll read in the file and add the variables to the StartProgramInGuest call.
