### ISSUE TITLE
Support XFS filesystem?

### ISSUE THREAD

**Issue by hitsumabushi** [vmware/open-vm-tools#28]
XFS filesystem is a popular file system and used as default on RHEL7/CentOS7.
However, an open-vm-tools doesn't support XFS.

Will open-vm-tools support XFS at an early date?

I want to get partition sizes with vsphere API or mob.

**Comment by ravindravmw** [comment]
It is coming in next update of open-vm-tools i.e. version 9.10.x.

**Comment by hitsumabushi** [comment]
Sound great! Thanks!

And, I'm sorry for my stupid question.  The answer is already written on the new branch.
https://github.com/vmware/open-vm-tools/blob/stable-9.10.x/open-vm-tools/ChangeLog#L368
