### ISSUE TITLE
vmware-user.desktop is not installed

### ISSUE THREAD

**Issue by Optiligence** [vmware/open-vm-tools#285]
/usr/share/applications/vmware-user.desktop is not installed
/etc/xdg/autostart/vmware-user.desktop is a dead link

therefore i.e. copy and paste is not working automatically

**Comment by stevenxxiu** [comment]
Just encountered this issue, using the file from https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/vmware-user-suid-wrapper/vmware-user.desktop.in and replacing `_bindir_` with `/usr/bin` fixes it in vmware & arch linux guest.

**Comment by stanguturi** [comment]
The solution provided by @stevenxxiu in the previous comment should work.  Please reopen if you still have any issues.

Also, please check the following URLs where a similar issue was reported and resolved:
* https://github.com/vmware/open-vm-tools/issues/205#issuecomment-350645977
* https://github.com/vmware/open-vm-tools/issues/147#issuecomment-285771917
* https://github.com/vmware/open-vm-tools/issues/270#issuecomment-418334025

Thanks

**Comment by Optiligence** [comment]
that doesn’t seem like a solution but a workaround to me
i workarounded this myself, but i reported it here so the build system gets fixed in that regard

fyi i don’t have the option to reopen this

**Comment by Optiligence** [comment]
but as it turns out, the current arch package does indeed seem to work correctly (configure options i guess)
