### ISSUE TITLE
Cannot install in newly-released pfsense 2.2.3

### ISSUE THREAD

**Issue by kevindd992002** [vmware/open-vm-tools#29]
I just installed pfsense 2.2.3 on my vmware esxi 6.0 host, but when I try to install open-vm-tools I get different errors for each different installation attempt. The errors are:

1.) ERROR: Failed to read PBI header! Possible corrupt PBI, or wrong PBI version for this OS.

2.) Verifying Checksum...SKIP_ARCHLINES: 67
 Archive checksum: ab39b91f1552b5d702703668d976c15daa3fba706c6388c82c57a07157546b4f
 Saved checksum: 6ce8ce1af97f35fceff5f46bd829d9440f7b050453343f81fabd5ed39fc0b86f
 ERROR: /tmp/apkg_open-vm-tools-1280544_9-amd64.pbi failed checksum, the archive may be corrupt.
of open-vm-tools-1280544_9-amd64 failed!

Hoping for your help. Thanks.

**Comment by oliverkurth** [comment]
Hi Kevin,
this looks very much like an issue with the .pbi file. You should contact the maintainers of the the pbi package file, of of pfsense.

**Comment by kevindd992002** [comment]
Thanks, Oliver. Does that mean the version of open-vm-tools now does support the freebsd os version included in pfsense 2.2.3?

**Comment by oliverkurth** [comment]
It looks like pfsense 2.2.3 uses FreeBSD 10.1 (I am not familiar with pfsense, but I gather that from https://en.wikipedia.org/wiki/PfSense). Build 1280544 (version 9.4.0) is an older version of open-vm-tools. For FreeBSD 10.1 I would recommend the latest release 9.10.2, see https://github.com/vmware/open-vm-tools/releases/tag/stable-9.10.2.

However, the issue that you report does not seem to be related to the software that is in the package at all. Rather, it looks like a corrupted file, maybe caused by an incomplete download, or maybe it was already corrupted in the first place. I cannot help you with that. I would recommend trying to download the package again, and then contact the support for pfsense.

**Comment by kevindd992002** [comment]
I understand. I'll look into manually installing 9.10.2 then. Thanks.

**Comment by kevindd992002** [comment]
Do you happen to know how to install this package manually in pfsense? Sorry, I'm a Windows guy.

**Comment by kevindd992002** [comment]
Anyone?

**Comment by oliverkurth** [comment]
Sorry for the late reply...

You should contact support at pfsense, they seem to host a defective package. This is most likely the easiest route and promises better results.

But if that doesn't work, you can try building it yourself, but I am not sure if that works. pfsense is based on FreeBSD 10, but I don't know how much it is modified. Follow these instructions:

Download the tarball from https://github.com/vmware/open-vm-tools/archive/stable-9.10.2.tar.gz

Prerequisites: install gcc48 with the command
pkg install gcc

Install build dependencies with 'pkg install': glib libdnet libXinerama libXrandr gtk2 gtkmm24

Instructions for building:

autoreconf -i --force
env CC=gcc48 CFLAGS=-Wl,-rpath=/usr/local/lib/gcc48 CPPFLAGS="-I/usr/local/include/" LIBS="-L/usr/local/lib" ./configure --without-kernel-modules --without-xmlsecurity --without-icu --disable-vgauth --disable-grabbitmqproxy --disable-deploypkg
make

as root:
make install

**Comment by stanguturi** [comment]
> But if that doesn't work, you can try building it yourself, but I am not sure if that works. pfsense is based on FreeBSD 10, but I don't know how much it is modified. Follow these instructions:
> 
> Download the tarball from https://github.com/vmware/open-vm-tools/archive/stable-9.10.2.tar.gz

Thanks @oliverkurth for the inputs. Closing this old issue. 

@kevindd992002 Please reopen if you still encounter any issues with the above instructions.
