### ISSUE TITLE
Missing Error Check in function SSL_CTX_set_cipher_list()

### ISSUE THREAD

**Issue by lc3412** [vmware/open-vm-tools#291]
Hi,
Function SSL_CTX_set_cipher_list() returns 1 if any cipher selected and 0 on complete failure. However, function SSL_CTX_set_cipher_list() in open-vm-tools/open-vm-tools/lib/sslDirect/sslDirect.c didn't check the return value is 0 or not. See the following code:

line: 890
![screenshot from 2018-09-18 15-13-51](https://user-images.githubusercontent.com/19151593/45670534-974fbe00-bb55-11e8-941d-2e035a2a161c.png)

================================================================================

The specification about function SSL_CTX_set_cipher_list（） 
Ref:  https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_cipher_list.html

It‘s essential to check up. We find the return value of this call been checked in openssl project with the version of openssl 1.1.2. Such as in openssl/apps folder

apps/ciphers.c
Ref: https://github.com/openssl/openssl/blob/master/apps/ciphers.c
line: 201
![screenshot from 2018-09-18 15-23-02](https://user-images.githubusercontent.com/19151593/45670955-c581cd80-bb56-11e8-9eb6-e906fbf85159.png)

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by stanguturi** [comment]
Fixed in 6bd31f83d7ee03570b9972a0de2d61e82b04ba5c in devel branch.
