### ISSUE TITLE
Missing Error Check in function X509_STORE_CTX_get_current_cert()

### ISSUE THREAD

**Issue by lc3412** [vmware/open-vm-tools#292]
Hi,
Function X509_STORE_CTX_get_current_cert() returns the certificate which caused the error or NULL if no certificate is relevant to the error. However, the function X509_STORE_CTX_get_current_cert() in  open-vm-tools/open-vm-tools/vgauth/common/certverify.c  didn't check the return value is NULL or not, before passing the return value as an argument to the function X509_get_subject_name(). See the following details.

line: 136, 145
![screenshot from 2018-09-18 15-39-36](https://user-images.githubusercontent.com/19151593/45671940-6d989600-bb59-11e8-97c4-33327b6a11c0.png)

================================================================================

We find the definition of the function X509_get_subject_name()  in openssl project with the version of openssl 1.1.2.  Function X509_get_subject_name() doesn't check the argument which is the return value of function X509_STORE_CTX_get_current_cert() is NULL or not before using it.

Ref: https://github.com/openssl/openssl/blob/master/crypto/x509/x509_cmp.c

![screenshot from 2018-09-18 16-04-00](https://user-images.githubusercontent.com/19151593/45673163-91111000-bb5c-11e8-8d65-d868492816bc.png)

=================================================================================

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2.
Such as in openssl/apps folder

apps/verify.c
Ref: https://github.com/openssl/openssl/blob/master/apps/verify.c
line 275, 280
![screenshot from 2018-09-18 16-06-09](https://user-images.githubusercontent.com/19151593/45673275-d5041500-bb5c-11e8-8fa7-a386fb66b0f7.png)
![screenshot from 2018-09-18 16-06-26](https://user-images.githubusercontent.com/19151593/45673283-d8979c00-bb5c-11e8-8eb7-5a51abe5cd73.png)

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by lemke1458** [comment]
Thanks for the report.  An internal bug has been filed to fix this.

**Comment by stanguturi** [comment]
The issue was fixed in commit 7560aab8a6be1be166d0e37c08f46ba0196d0a16 in devel branch. Closing this issue.
