### ISSUE TITLE
Buffer for /etc/os-release too small

### ISSUE THREAD

**Issue by rawtaz** [vmware/open-vm-tools#293]
In summary, on a NixOS 18.03 (latest version) system with `open-vm-tools` installed, the guest tools service fails to start with the following error messages in `/var/log/vmware-vmsvc.log`:
~~~
[Sep 11 14:50:09.578] [ warning] [vmsvc] HostinfoReadDistroFile: input buffer too small
[Sep 11 14:50:09.578] [ warning] [vmsvc] HostinfoOSData: Error: no distro file found
[Sep 11 14:50:09.578] [ warning] [guestinfo] Failed to get OS info.
~~~

After some debugging, I've come to the conclusion that the contents of the file `/etc/os-release` is too large to fit in the buffer `vmsvc` uses when reading and parsing the file. The file contents is:

~~~
NAME=NixOS
ID=nixos
VERSION="18.03.133192.45f52f765cd (Impala)"
VERSION_CODENAME=impala
VERSION_ID="18.03.133192.45f52f765cd"
PRETTY_NAME="NixOS 18.03.133192.45f52f765cd (Impala)"
HOME_URL="https://nixos.org/"
SUPPORT_URL="https://nixos.org/nixos/support.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
~~~

Please see https://github.com/NixOS/nixpkgs/issues/46527 for a more complete description, but in short it would be great it the buffer could be a bit larger, to accomodate files like this. After all, it's just temporary memory usage.

**Comment by lemke1458** [comment]
Thanks for reporting this, an internal bug has been filed.

**Comment by lemke1458** [comment]
Also, can you tell me what version of open-vm-tools is shipped by NixOS 18.03 ?  Current Tools uses 1k for the buffer, which should be  enough given your example, but we may have recently boosted it.

**Comment by lemke1458** [comment]
Actually, I think this is already fixed in the latest.

https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/lib/misc/hostinfoPosix.c#L154

changed from 255 to 1024

**Comment by rawtaz** [comment]
@lemke1458 It's version 10.1.10 for open-vm-tools and `vmware-checkvm` tells me "VMware software version 6 (good)" in case that's relevant.

Indeed, the buffer seems to be 1k big, and what's weird is that `stat` on the file reports 318 bytes, so I don't really see what's going on (I just concluded that by making the file smaller, the service started fine).

Oh, right, might be that I have the old code with 255 bytes buffer size then.. Can you tell me which version this was changed in?

**Comment by lemke1458** [comment]
It was after 10.1.10.  Looks like this change

https://github.com/vmware/open-vm-tools/commit/ce769ae4aa3a14810b418c044629f2d9dcb72a37#diff-1e473968c2d6786d3660ce7ffcba43a0

From that tag, looks like 10.3.0

**Comment by Mic92** [comment]
@rawtaz feel free to send a pull request for an upgrade.

**Comment by rawtaz** [comment]
@lemke1458 Thank you very much for such a swift reply. I think we can close this for now as it's probably just a matter of using a newer version. Sorry for taking you time!

**Comment by lemke1458** [comment]
Glad to help.  Please let us know if I misread the code and this doesn't fix it.

**Comment by rawtaz** [comment]
@lemke1458 On a somewhat related note, do you think you could poke someone to take a look at https://github.com/vmware/open-vm-tools/pull/35? Seems like a small patch, and NixOS is still going strong :)

**Comment by lemke1458** [comment]
That patch isn't going to really solve it.  It'll get the right data down to the VMX, but there's work required at multiple layers.  The hostinfo data is also reported to vSphere, and vSphere will need to be changed to understand it.

I've filed a bug requesting NixOS support.
