### ISSUE TITLE
Enable the Releases "tab" in this GitHub repo

### ISSUE THREAD

**Issue by rawtaz** [vmware/open-vm-tools#294]
It would be nice to be able to see the releases and versions that have been made for this software in a more streamlined way than checking tags, as well as be able to more easily download the releases as .tar.gz files and similar by clicking a link.

Could you please enable the Releases tab/view in the GitHub web UI for this repo?

**Comment by ravindravmw** [comment]
It is here - https://github.com/vmware/open-vm-tools/releases. Are you not able to access it?

**Comment by rawtaz** [comment]
@ravindravmw I'm an idiot, sorry. The releases are only shown when you're on the Code "tab" of course.. I wasn't. So sorry to take your time.
