### ISSUE TITLE
Add support for Systemd in network scripts

### ISSUE THREAD

**Issue by c4milo** [vmware/open-vm-tools#3]

**Comment by bzed** [comment]
Feel free to take the systemd files from debian: https://github.com/bzed/pkg-open-vm-tools/tree/master/debian/ - the service/unit files are in the debian folder, also you'll need the .mount file from the debian/local folder.

**Comment by ravindravmw** [comment]
Fixed in https://github.com/vmware/open-vm-tools/releases/tag/stable-9.10.0.
