### ISSUE TITLE
Ubuntu 18.04 NIC=ether when trying to use static IP

### ISSUE THREAD

**Issue by sayantandas** [vmware/open-vm-tools#304]
Hi all,

Here is my setup 
OS Template: Ubuntu 18.04.1
vSphere Client version 6.5.0.13000
vCenter Server 6.5 Update 1e  build 7515524
cloud init installed : Yes
 open-vm-tools : 2:10.3.0-0ubuntu1~18.04.2
deploying through: ansible using vmware_guest

I have removed netplan and installed network manager.  

When I try to clone this VM , I see in the vmware deploy logs that its picking up NIC=ether. Ideally it should be ens160. 

I see the same issue faced in #172 

Troubleshooting:

Did the following to workaround tmp dir issue:
1). Edit tmp.conf under /usr/lib/tmpfiles.d/
2). comment out line 11 by adding '#' in front of this line.

**Comment by sayantandas** [comment]
I believe this is happening primarily due to the fact that open-vm-tools is picking up the wrong ethernet info from ifconfig. can it use ip command instead?

**Comment by stanguturi** [comment]
> OS Template: Ubuntu 18.04.1
> vSphere Client version 6.5.0.13000
> vCenter Server 6.5 Update 1e build 7515524

Please check https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf for the guest customization support matrix.

The guest customization for "Ubuntu 18.04" guest is supported only from vCenter server version 6.5 Update 2 only. Please update your vCenter version. (6.5 update 2 information is available at https://docs.vmware.com/en/VMware-vSphere/6.5/rn/vsphere-vcenter-server-65u2-release-notes.html)

If you still encounter the issue with 6.5U2, then please reopen this issue.

Thanks
Sankar.

**Comment by PixiBixi** [comment]
Have this issue for a long time too and found a fix on github : https://github.com/vmware/open-vm-tools/issues/172#issuecomment-318447043 !
