### ISSUE TITLE
Open VM Tools crashes when running Invoke-Script

### ISSUE THREAD

**Issue by Ttech** [vmware/open-vm-tools#305]
On Alpine Linux 3.8 with open-vm-tools 10.1.15.65452 build 6677369
When you run Invoke-Script with PowerCLI the script fails to run and Open VM Tools crashes.

PowerCLI returns:
Invoke-VMScript : 11/24/2018 12:52:25 PM	Invoke-VMScript		A general system error occurred: vix error codes = (3016, 0).
	
At line:1 char:7
+ $es = Invoke-VMScript -vm $vmc -ScriptText "root.sh" -GuestCred ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-VMScript], SystemError
    + FullyQualifiedErrorId : Client20_VmGuestServiceImpl_RunScriptInGuest_ViError,VMware.VimAutomation.ViCore.Cmdlets.Commands 
   .InvokeVmScript
 

Open VM Tools returns:
[vmsvc] FileGetUserName: sysconf(_SC_GETPW_R_SIZE_MAX) failed.
[vmsvc] File_GetSafeTmpDir: FileGetUserName failed, using numberic ID as username instead

**Comment by lemke1458** [comment]
Can you post the complete vmtoolsd log covering the crash?  It looks like vmtoolsd is expecting a sysconf variable that isn't set, and something isn't handling that properly.

Also, did you build open-vm-tools, and if so did you use some non-default options?  And how is it being started (systemd?)

**Comment by lemke1458** [comment]
After a bit more digging, we think this is a repro of https://github.com/vmware/open-vm-tools/issues/236

If so, open-vm-tools version 10.3.x should include a fix.

**Comment by oliverkurth** [comment]
This is fixed with cdf0406dc669f2284e1e810ac5820f123d46a50e and e9463abdc0d56d0612237faf01a5736c9998b499 . It will be part of the next release.
