### ISSUE TITLE
RHEL8 guest cannot properly reboot after Guest OS Customization

### ISSUE THREAD

**Issue by foofoo-2** [vmware/open-vm-tools#306]
Hi everyone,

I'm facing a small issue while trying to deploy and customize a brand new RHEL8 (Beta) template that we created internally: the customization process seems to successfully complete up to the point where the system should be rebooted. At this point, the systems hangs until someone logs into the VM console and hits a key. As soon as a key is pressed, the system properly reboots and it is then reachable via SSH.

The only useful information found in `/var/log/vmware-imc/toolsDeployPkg.log` is the following one:
```
...
[2018-11-27T06:17:42.576Z] [    info] Launching cleanup.

[2018-11-27T06:17:42.576Z] [   debug] Command to exec : /bin/rm

[2018-11-27T06:17:42.576Z] [    info] sizeof ProcessInternal is 56

[2018-11-27T06:17:42.577Z] [    info] Returning, pending output from stdout
[2018-11-27T06:17:42.577Z] [    info] Returning, pending output from stderr
[2018-11-27T06:17:42.677Z] [    info] Process exited normally after 0 seconds, returned 0
[2018-11-27T06:17:42.677Z] [    info] No more output from stdout
[2018-11-27T06:17:42.677Z] [    info] No more output from stderr
[2018-11-27T06:17:42.677Z] [    info] Customization command output:

[2018-11-27T06:17:42.677Z] [    info] sSkipReboot: false, forceSkipReboot false

[2018-11-27T06:17:42.678Z] [   debug] Ran DeployPkg_DeployPackageFromFile successfully
[2018-11-27T06:17:42.678Z] [   debug] ## Closing log
[2018-11-27T06:17:42.679Z] [    info] Rebooting

[2018-11-27T06:17:42.679Z] [   debug] Command to exec : /sbin/telinit

[2018-11-27T06:17:42.679Z] [    info] sizeof ProcessInternal is 56

[2018-11-27T06:17:42.680Z] [    info] Returning, pending output from stdout
[2018-11-27T06:17:42.680Z] [    info] Returning, pending output from stderr
[2018-11-27T06:17:42.768Z] [   error] Process exited abnormally after 0 sec, uncaught signal 15
[2018-11-27T06:17:42.768Z] [    info] No more output from stdout
[2018-11-27T06:17:42.768Z] [    info] No more output from stderr
[2018-11-27T06:17:42.768Z] [    info] Customization command output:

[2018-11-27T06:17:42.768Z] [   error] Customization command failed with exitcode: 127, stderr:

[2018-11-27T06:17:43.768Z] [   error] telinit returned error 127
```

I've seen this code snippet that could be related to that issue:
* https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/libDeployPkg/linuxDeployment.c#L1290-L1297

Some more information about our infrastructure:
```
# VMware vSphere Version 6.5.0

[root@rhel8-test ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.0 Beta (Ootpa)

[root@rhel8-test ~]# rpm -q open-vm-tools
open-vm-tools-10.3.0-1.el8.x86_64

[root@rhel8-test ~]# vmtoolsd --version
VMware Tools daemon, version 10.3.0.5330 (build-8931395)
```

Does anyone of you have an idea how we could solve or work around this issue?

Thanks in advance for your help!

(If you need additional information, feel free to ask)

**Comment by PengpengSun** [comment]
@foofoo-2 
Hi Oliver,

From the toolsDeployPkg.log, it shows the '/sbin/telinit 6' cmd called once, and it's used to reboot VM, the [error]s at the last lines are expected.
I tried to reproduce it on a RHEL8(beta) VM which has the same open-vm-tools version, it rebooted automatically.
Can you please run '/sbin/telinit 6' directly on the RHEL8 VM which you keep seeing this issue, Let's see if it can reboot your VM immediately. 

Thanks,
Pengpeng

**Comment by foofoo-2** [comment]
Hi @PengpengSun,

Thanks for your answer.

I tried to issue a {{/sbin/telinit 6}} on the VM and it restarted immediately. So apparently, something is blocking the reboot after the Guest OS Customization process. Unfortunately, I cannot see which process because, as mentioned in the bug description, as soon as I access the VM console and hit a key, the VM restarts.

Do you have an idea what could cause this issue to happen?

Thanks in advance for your help!

**Comment by PengpengSun** [comment]
Hi @foofoo-2 ,

Are you still seeing this issue? 
Here I can NOT reproduce this issue from my RHEL8 beta VM. The VM can reboot after Guest OS Customization process as we are also testing this beta version internally.
Would you please have a try on another RHEL8 beta VM?

Thanks,
Pengpeng

**Comment by foofoo-2** [comment]
Hi @PengpengSun,

The last time I tried the issue was still present. I am going to try again tomorrow and let you know the outcome.

What version of the different components are you using?
* vCenter
* open-vm-tools
* etc...

Thanks!

**Comment by PengpengSun** [comment]
Hi @foofoo-2 ,

Have you tried it again?

I used the same vCenter version with you:  version 6.5.0, build 4602587
and open-vm-tools version is same:  version 10.3.0.5330 (build-8931395)
The RHEL8 beta was installed as Workstation.

Thanks,
Pengpeng

**Comment by foofoo-2** [comment]
Hi @PengpengSun,

Sorry, I was quite busy on Friday. Going to try it again today and let you know.

Thanks!

**Comment by foofoo-2** [comment]
Hi @PengpengSun,

I did a quick test today afternoon and I encountered the same issue as described in my bug report. What kind of information would be helpful for you to troubleshoot this problem?

Thanks!

**Comment by PengpengSun** [comment]
Hi @foofoo-2 ,

I tried a default 'Server' install today, and only installed 'perl' at local repository from the RHEL8 beta ISO.
Then did VM clone and customization, the cloned VM was rebooted and customized correctly.

According to your toolsDeployPkg.log, 'perl' and 'open-vm-tools' are both installed and running, there are no other dependencies/packages needed for customization to work on RHEL8.

Would you mind let me know what's Software Selection you selected during install the "stripped-down" server.  If I can reproduce the issue, there should be some clues in system logs.

Thanks,
Pengpeng

**Comment by foofoo-2** [comment]
Hi @PengpengSun,

Sure, here is the package selection we are using as part of our kickstart process:
```
#
# Packages to be installed
#

%packages
@core

# Include Perl
perl

# General tools
yum-rhn-plugin
curl
expect
mailx
wget
sed

# Packages not to be installed
-telnet*
-aic*-firmware*
-alsa-*
-bfa-firmware
-iwl*firmware
-libertas*-firmware
-postfix
-ql*-firmware
-iprutils
```

Do you know if the `open-vm-tools` package comes as part of the `@core` group? Because I'm a bit surprised not to find it in the list.

Thanks!

**Comment by PengpengSun** [comment]
Hi @foofoo-2 ,

By running 'yum list installed | grep open-vm-tools' on my RHEL8 beta VM, it tells open-vm-tools comes from @AppStream. 
So both 'perl' and 'open-vm-tools' are available from your VM, customization took effect and triggered 'telinit 6' to try to reboot VM.  Could you please attached /var/log/boot.log and /var/log/message log files from the VM that you reproduced this issue? Try to see what's blocked the reboot process.

Thanks,
Pengpeng

**Comment by foofoo-2** [comment]
Hi @PengpengSun,

As requested, here the two log files taken from a freshly deployed RHEL8 VM that was affected by this issue.
* [boot.log](https://github.com/vmware/open-vm-tools/files/2861346/boot.log)
* [messages](https://github.com/vmware/open-vm-tools/files/2861347/messages.log)

Thanks in advance for your help!

**Comment by PengpengSun** [comment]
Hi @foofoo-2 ,

Thanks for the log files.
I does NOT find any issues from the /var/log/messages, I can see Login Service started twice, this is expected. The first time is power-on, the second time is reboot.

At the first time , the hostname is 'localhost', timestamp is 17:39:57:
```
Feb 13 17:39:57 localhost systemd[1]: Starting Login Service...
Feb 13 17:39:57 localhost systemd-logind[939]: New seat seat0.
Feb 13 17:39:57 localhost systemd[1]: Started Getty on tty1.
Feb 13 17:39:57 localhost systemd[1]: Reached target Login Prompts.
Feb 13 17:39:57 localhost systemd-logind[939]: Watching system buttons on /dev/input/event0 (Power Button)
Feb 13 17:39:57 localhost systemd-logind[939]: Watching system buttons on /dev/input/event1 (AT Translated Set 2 keyboard)
Feb 13 17:39:57 localhost systemd[1]: Started Login Service.
```
At the second time, the hostname is customized to 'rhel8-test', timestamp is 17:41:02:
```
Feb 13 17:41:02 rhel8-test systemd[1]: Starting Login Service...
Feb 13 17:41:02 rhel8-test systemd-logind[944]: New seat seat0.
Feb 13 17:41:02 rhel8-test systemd-logind[944]: Watching system buttons on /dev/input/event0 (Power Button)
Feb 13 17:41:02 rhel8-test systemd-logind[944]: Watching system buttons on /dev/input/event1 (AT Translated Set 2 keyboard)
Feb 13 17:41:02 rhel8-test systemd[1]: Started Login Service.
```

Between these 2 times, no user logged and timestamps are close. root user logged after the second time:
`Feb 13 17:46:19 rhel8-test systemd-logind[944]: New session 1 of user root.`

From the original post, you mentioned "`At this point, the systems hangs until someone logs into the VM console and hits a key. As soon as a key is pressed, the system properly reboots and it is then reachable via SSH.`"
Some quick questions on this:
1.  "someone logs into the VM console and hits a key",  at this time,  no user logged, just hit a key,  right?
2.  "the systems hangs", how long did you wait until you found it hung?

Thanks,
Pengpeng

**Comment by foofoo-2** [comment]
Hi @PengpengSun,

Thanks for your analysis. Here are my comments:

1. Yes, that's correct. No user was logged in. In order to "trigger" the reboot, I had to open the VMware console and to hit a key. After this action, the reboot happened almost immediately
2. In the case presented in my previous post, I only waited one minute or so. But during previous tests, I deployed a couple of VMs and let the customization run for more thant 8 hours. And in the end no machine rebooted without manual intervention on the console :-(

Thanks!

**Comment by foofoo-2** [comment]
Hi @PengpengSun,

FYI, I was able to "fix" the issue by creating a fresh new RHEL8 template on one of our new ESXi servers (
6.7.0, Build 9484548) and by fixing the `guest_os_type` to `rhel7-64`. This way, the customization process goes through and the VM properly reboots afterwards.

I'm now going to close this issue for the moment.

Thanks again for your help and your time spent on trying to reproduce this issue!

**Comment by PengpengSun** [comment]
Hi @foofoo-2 ,

I'm glad to know you fix the issue, I was trying to run a kickstart setup but have not done.
btw: which `guest_os_type` you chose before?

Best regards,
Pengpeng

**Comment by foofoo-2** [comment]
Hi @PengpengSun,

Sorry for my late answer.

If I remember correctly I tried with `rhel8-64` and `other-64`.

Thanks and Best Regards!

**Comment by PengpengSun** [comment]
Thanks a lot @foofoo-2 !

**Comment by PengpengSun** [comment]
@millad90s could you please share the `/var/log/vmware-imc/toolsDeployPkg.log` file in centos7 VM? You can share the whole file or the last part of it where `/sbin/telinit` command was executed.
And which vSphere version are you using, there are some workaround I share which depends on your vSphere version.

**Comment by amithkotu** [comment]
I can replicate the same issue when using RHEL 7.9 template. Using vSphere Client version 6.7.0.
Here is the /var/log/vmware-imc/toolsDeployPkg.log from the vm:

[2021-08-24T01:24:52.661Z] [    info] sSkipReboot: 'false', forceSkipReboot 'false'.

[2021-08-24T01:24:52.662Z] [   debug] Ran DeployPkg_DeployPackageFromFile successfully
[2021-08-24T01:24:52.662Z] [   debug] ## Closing log
[2021-08-24T01:24:52.662Z] [    info] Trigger reboot.

[2021-08-24T01:24:52.662Z] [   debug] Command to exec : '/sbin/telinit'.

[2021-08-24T01:24:52.662Z] [    info] sizeof ProcessInternal is 56

[2021-08-24T01:24:52.662Z] [    info] Returning, pending output from stdout
[2021-08-24T01:24:52.662Z] [    info] Returning, pending output from stderr
[2021-08-24T01:24:52.695Z] [   error] Process exited abnormally after 0 sec, uncaught signal 15
[2021-08-24T01:24:52.695Z] [    info] No more output from stdout
[2021-08-24T01:24:52.695Z] [    info] No more output from stderr
[2021-08-24T01:24:52.695Z] [    info] Customization command output: ''.

[2021-08-24T01:24:52.695Z] [   error] Customization command failed with exitcode: 127, stderr: ''.

[2021-08-24T01:24:52.739Z] [   error] Failed to reboot, telinit returned error 127.

**Comment by PengpengSun** [comment]
Hi @amithkotu ,

We've found this issue could reproduce on Linux where '/sbin/telinit' is a soft-link to '/usr/bin/systemctl' or '/bin/systemctl'. I believe this is the case for both RHEL 7.9 and RHEL 8.0.

This issue has been fixed in the next open-vm-tools release, before that you can workaround it.
 
If you can upgrade your vCenter version to 7.0, the post customization script will be available. You can use it to execute a reboot VM script automatically after customization script finished. See details at https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-9A5093A5-C54F-4502-941B-3F9C0F573A39.html and https://kb.vmware.com/s/article/74880
If you want to keep using vCenter version 6.7,  VM template has to be modified. You can create a systemd service to launch a script to reboot VM. I can share detailed steps if you prefer this way, but my suggestion is upgrade vCenter server to 7.0 and use post customization script.

Best regards,
Pengpeng

**Comment by amithkotu** [comment]
Thanks for the info @PengpengSun. We are replicating a customer environment for this case and hence have to stay on the vmware version specified. In the meantime if you can provide the instructions for the workaround that will be helpful.

Regards,
Amith

**Comment by amithkotu** [comment]
I can see similar behavior when using RHEL 7.8 template. So looks like we have this issue for RHEL 7.x on vSphere Client version 6.7.0.

**Comment by PengpengSun** [comment]
@amithkotu Right, please modify VM template as below steps in case you want to keep the current vCenter server version:
1. Create file /etc/systemd/system/rebootvm.service with below content
```
[Unit]
Description=Reboot VM if uncaught signal 15
[Service]
Type=simple
ExecStart=timeout 180s /rebootvm.sh
[Install]
WantedBy=multi-user.target
```
2. Create a shell script at /rebootvm.sh with below content
```
#!/bin/bash

goscLogFile=/var/log/vmware-imc/toolsDeployPkg.log
while true; do
    isRebootFailed=$(grep -E 'Failed to reboot' "$goscLogFile")
    if [ ! -z "$isRebootFailed" ]; then
	isUncaughtSignal15=$(grep -E 'uncaught signal 15' "$goscLogFile")
        if [ ! -z "$isUncaughtSignal15" ]; then
	    systemctl disable rebootvm.service
	    rm -rf /etc/systemd/system/rebootvm.service
	    systemctl reboot
	fi
    fi
    sleep 1
done
```
3. Delete file /var/log/vmware-imc/toolsDeployPkg.log if it exists
4. enable rebootvm.service with below commands
```
$(sudo) chmod +x /rebootvm.sh
$(sudo) systemctl enable rebootvm.service 
```

Then you can save VM to be new template, the rebootvm.service should help to reboot vm if this issue reproduces.
