### ISSUE TITLE
Solaris 11.4 Mouse not working within VMRC and Webview.

### ISSUE THREAD

**Issue by boredgames16** [vmware/open-vm-tools#307]
Running Solaris 11.4 VM with ESXI host running 6.5 U2 and latest VMware tools. When connecting to the VM with VMRC or the Web View, I get no mouse movement but I do get keyboard control. This worked fine in Solaris 11.3 with the same ESXI version. 

The fix from the shortcut no longer works.
https://kb.vmware.com/s/article/2040498

**Comment by lemke1458** [comment]
Thanks for the report, a bug has been filed.

**Comment by oliverkurth** [comment]
@boredgames16 this is also reported here: https://www.oracle.com/webfolder/community/oracle_sun_technologies/4181372.html

It seems to be a issue with Solaris, and they are working on a fix.

**Comment by thomashvmw** [comment]
This is now tracked as Solaris bugs
29397885 (Xorg hangs)
15742739 (The kb issue mentioned in the bug report)
Fixes are available at Oracle. Solaris customers who need fixes sooner than the May 2019 timeframe can call into Solaris support to request interim versions (or escalate the bugs to get the fixes out sooner).

**Comment by alanc** [comment]
The fixes for those Solaris bugs shipped in Solaris 11.4.9 .5.0 (Solaris 11.4 SRU 9).  The Xorg side also went upstream to Xorg in <https://gitlab.freedesktop.org/xorg/xserver/merge_requests/126>.

**Comment by johnwvmw** [comment]
Solaris customers can upgrade to 11.4.9 and things should work out of the box.  This was released in May-June 2019.

Closing this issue.
