### ISSUE TITLE
leak when mtab information get(linux)

### ISSUE THREAD

**Issue by a10222012** [vmware/open-vm-tools#308]
A mem-leak of vmtools running in linux.
The VmHWM will be more than 100MB when the vm-tools has been running for weeks.

I strings the gcore-files and rank it(by using cmd: strings core.343 | uniq -cd | sort -nr > string.sort), the strings repeated mostly is like /etc/mtab. I suspect that there is mem-leak in mtab-information get, but I can not find the bug.

The result i got is as follows:
481293 none
481289 rw,relatime
120325 ext4
120324 hugetlbfs
120323 rootfs
120322 ramfs
  88351 rw,relatime,data=ordered
  60230 /mnt/sda1
  60166 /etc/home
  60165 tmpfs
  60165 /proc
  60165 devpts
  60164 sysfs
  60164 proc
  60164 /dev/shm
  60163 /sys
  60163 /etc/coredump
  60162 /etc/huge
  60162 /dev/pts
  60161 /tmp/ramdisk
  60161 /sys/kernel/debug
  60161 streamfs
  60161 rw,relatime,mode=600,ptmxmode=000
  60161 /mnth
  60161 /dev/sdb1
  60161 /dev/sda1

**Comment by lemke1458** [comment]
What version of open-vm-tools is this?  What Linux distribution?

**Comment by a10222012** [comment]
vmtools version is 10.1.0.57774
running linux is customized base on kernel 3.10.20-rt14+

**Comment by a10222012** [comment]
i find the mem-leak point.
The static parameter "sm" is memset to zero, every time, at Interface Posix_Getmntent() in file misc/posixPosix.c.
The latest version has fixed the bug already, My vm-tools' version is to old. The issues can be closed
thanks all
