### ISSUE TITLE
open-vm-tools requires the legacy version of fuse, not the much more current one

### ISSUE THREAD

**Issue by fenrus75** [vmware/open-vm-tools#314]
.... obviously not a good thing to demand stale old software

**Comment by lousybrit** [comment]
Last checked we use 2.9.4 fuse which was not that old.

Specifically what versions of the vmhgfs-fuse and tools are you using? Some context here would be beneficial.

Thanks
Steve

**Comment by fenrus75** [comment]
eh fuse is at https://github.com/libfuse/libfuse/releases/download/fuse-3.4.1/fuse-3.4.1.tar.xz  3.4 not 2.9

this is all latest release (open-vm-tools-10.3.5-10430147.tar.gz)

**Comment by lousybrit** [comment]
FYI VMware tools do not install FUSE or modify the version installed by the Linux maintainers.
The fuse client will use whatever version is installed on the system.
For Ubuntu 16.04 FUSE is 2.9.4
For Ubuntu 18,04 FUSE is 2.9.7
For Ubuntu 18.10 FUSE is 2.9.8

Just because the latest version on github has moved forward doesn't mean the Linux maintainers will immediately start using it. They will pick up the version that makes sense for them. If you want to find out why they have not moved it beyond 2.9.8 you need to ask them. I would hazard a guess is that they require some soak time before accepting new versions.

Steve

**Comment by fenrus75** [comment]
https://packages.ubuntu.com/search?keywords=fuse3

Ubuntu is moving as well

**Comment by lousybrit** [comment]
Ok, great, thanks for filling me in!
So is there something in our vmhgfs-fuse that won't work if you move the package forward? Is the 10.3.5 open-vm-tools vmhgfs-fuse client broken when you do?
I was not aware that there was an issue but I have not checked myself to see what changes have gone in that would break backwards compatibility.

Steve

**Comment by fenrus75** [comment]
the key hurdle is that the .pc file got renamed to fuse3.pc (likely to
allow temporary coexistence)...

also they added quite a few things to allow higher performance with newer
kernels but I don't think that breaks existing code

**Comment by lousybrit** [comment]
Ok thanks. I think it seems like it should work as it stands.
However, our FUSE client has to work with many versions of Linux which will have a wide variety of FUSE versions. We might be able to query the version installed and make some runtime configuration additions to take advantage of newer versions.
I will take a look into something like that.

Steve

**Comment by oliverkurth** [comment]
I filed an internal bug for this.

**Comment by jonathanunderwood** [comment]
> I filed an internal bug for this.

Really? That's terrible transparency for an open source project. Do better, please.

**Comment by mikepurvis** [comment]
The issue which I am facing here is that `open-vm-tools` doesn't depend on `libfuse2`, it depends on `fuse`, and in Ubuntu 20.04, `fuse` and `fuse3` are mutually exclusive. This isn't the only package contributing to this issue, but it's definitely part of the reason that it's been a challenge moving on:

```
dpkg: fuse: dependency problems, but removing anyway as you requested:
 xdg-desktop-portal depends on fuse; however:
  Package fuse is to be removed.
 open-vm-tools-desktop depends on fuse.
 ntfs-3g depends on fuse.
 gvfs-fuse depends on fuse.
 fuseiso depends on fuse.
```

**Comment by johnwvmw** [comment]
The fix to build open-vm-tools with either _fuse_ or _fuse3_ has been committed to the _devel_ branch - https://github.com/vmware/open-vm-tools/commit/97917fce5828ef0efdae59d7bb6e4dd7f0caeae0
