### ISSUE TITLE
open-vm-tools docs

### ISSUE THREAD

**Issue by izenk** [vmware/open-vm-tools#315]
Hi,
Is there any docs describe cloud-init and open-vm-tools interaction?
I can see in vmware-vmsvc.log that there are some, but can't understand the logic and possible configurations.

**Comment by PengpengSun** [comment]
@izenk 
Would you please let me know which Linux distro you are using? There is no general docs but one for Ubuntu18.04 Live Server, see **Set cloud-init as the customization engine** in https://kb.vmware.com/s/article/54986

Generally, below steps are needed for cloud-init and open-vm-tools interaction:
1. cloud-init version is > 18.2
2. add **disable_vmware_customization: false** to /etc/cloud/cloud.cfg

Related code:
https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/libDeployPkg/linuxDeployment.c#L1062
https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/libDeployPkg/linuxDeploymentUtilities.c#L45

**Comment by izenk** [comment]
@PengpengSun thanks, finally found what I want, but really its not clear from the beginning how to get it work in a right way.
