### ISSUE TITLE
libDeployPkg uses /tmp which is not safe during boot

### ISSUE THREAD

**Issue by cpaelzer** [vmware/open-vm-tools#318]
Looking at source code for[ linuxDeployment.c](https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/libDeployPkg/linuxDeployment.c#L69) and also looking at some logs, I'm pretty sure that the imc-customization path is using /tmp to create files. That is not safe during systemd boot as the tmpfiles cleaner may remove your files at any point.

The [paste](http://paste.ubuntu.com/p/MDvVSQwsTB/) here has some of the confusing bits in the log.

Maybe those are normal/expected, but it really isnt' safe to use /tmp during boot.

For examples of such problems see
[ bug 1727876](https://bugs.launchpad.net/bugs/1727876)
[ bug 1707222](https://bugs.launchpad.net/bugs/1707222)

Ultimately, cloud-init started using /run/cloud-init rather than mktemp to avoid this, myabe you'd want to consider a similar solution for open-vm-tools?

Disclaimer: this is mostly a copy&paste of the great bug report on Launchpad by Scott Moser.

**Comment by PengpengSun** [comment]
Thanks @cpaelzer and Scott for this. We has started using /var/run or /run to create files from next VMTools release.

Here is a [paste](https://paste.ubuntu.com/p/3XTYyJqBTN/) from log with updated VMTools.

**Comment by stanguturi** [comment]
> Thanks @cpaelzer and Scott for this. We have started using /var/run or /run to create files from next VMTools release.

Fixed in 640bd4f9c012b201ad1d45a131dad2e804f53766. Closing this issue.
