### ISSUE TITLE
make install, initscripts?

### ISSUE THREAD

**Issue by iddq** [vmware/open-vm-tools#320]
Hello,

make install doesn't install any initscript, how could we install it?

Thanks

**Comment by vmwzhangv** [comment]
You need write your own init script or systemd unit file.

Use the following as a reference to do so.
https://src.fedoraproject.org/rpms/open-vm-tools/blob/master/f/vmtoolsd.service

**Comment by stanguturi** [comment]
> You need write your own init script or systemd unit file.
> 
> Use the following as a reference to do so.
> https://src.fedoraproject.org/rpms/open-vm-tools/blob/master/f/vmtoolsd.service

User needs to write the own init script specific to the distro. Please check the above link for the reference. Closing the issue.
