### ISSUE TITLE
DOCs for open-vm-tools

### ISSUE THREAD

**Issue by izenk** [vmware/open-vm-tools#323]
Hi.
Are there any documentation related to [Plugins](https://github.com/vmware/open-vm-tools/tree/master/open-vm-tools/services/plugins) in terms "how to use". Because everything can be found is related to "how to install" only.
For example "deploypkg" plugin - all docs say that new version of open vm tools includes deploypkg and no need to install it separately. But there is no info how to use deploypkg (configuration, command line syntax) - even no info if open vm tools with plugins can be used from command line in general.
Or for example "grabbitmqProxy" plugin - what is it for? I couldn't find any info.

**Comment by lemke1458** [comment]
Plugins are a part of vmtoolsd.

There's no documentation because they are an internal implementation detail.  Various plugins handle various vSphere APIs.

deployPkg is a part of Guest Customization.
grabbitmqProxy is an internal plugin to set up message bus communication used by other parts of vSphere.

vix handles guest operations.  power handles soft power ops.

**Comment by stanguturi** [comment]
Check the following few URLs. They should provide good documentation about different modules in 'VMware Tools'.

*[Introduction to VMware Tools](https://docs.vmware.com/en/VMware-Tools/10.3.0/com.vmware.vsphere.vmwaretools.doc/GUID-28C39A00-743B-4222-B697-6632E94A8E72.html)
*[VMware Tools](https://docs.vmware.com/en/VMware-Tools/index.html)
*[VMware Tools Services](https://docs.vmware.com/en/VMware-Tools/10.3.0/com.vmware.vsphere.vmwaretools.doc/GUID-0BD592B1-A300-4C09-808A-BB447FAE2C2A.html) - This has information about each plugin.
*[VMware Tools User Service](https://docs.vmware.com/en/VMware-Tools/10.3.0/com.vmware.vsphere.vmwaretools.doc/GUID-FB7FA658-7622-4680-BD9F-7A6670C12794.html)
