### ISSUE TITLE
Systemd 237-3ubuntu10.15 breaks auto screen sizing on Ubuntu 18.04.2LTS

### ISSUE THREAD

**Issue by isaki** [vmware/open-vm-tools#324]
Upgrading Ubuntu 18.04.2 LTS to systemd 237-3ubuntu10.15 (there was also a udev upgrade), my Ubuntu 18 guest no longer dynamically resizes its window to match the full screen resolution under Fusion 11 (retina resolution disabled).

Running `sudo systemctl restart open-vm-tools` will cause the VM to update its resolution appropriately.

Checking the systemd unit files, it looks like open-vm-tools only depends on cloud-init.

```
$ cat /etc/systemd/system/multi-user.target.wants/open-vm-tools.service 
[Unit]
Description=Service for virtual machines hosted on VMware
Documentation=http://open-vm-tools.sourceforge.net/about.php
ConditionVirtualization=vmware
DefaultDependencies=no
Before=cloud-init-local.service

[Service]
ExecStart=/usr/bin/vmtoolsd
TimeoutStopSec=5

[Install]
WantedBy=multi-user.target
```

Which is not even installed by default on the desktop Ubuntu 18.04LTS (it is on server).

I installed the `open-vm-tools-desktop` package as I wanted all the niceties that come with that, if it matters.

**Comment by oliverkurth** [comment]
This seems to be the same issue, see https://github.com/vmware/open-vm-tools/issues/253#issuecomment-417456984

**Comment by stanguturi** [comment]
> This seems to be the same issue, see [#253 (comment)](https://github.com/vmware/open-vm-tools/issues/253#issuecomment-417456984)

Please check the fix mentioned by @oliverkurth Closing this issue.
