### ISSUE TITLE
Host OS detection should support os-release file 

### ISSUE THREAD

**Issue by wmertens** [vmware/open-vm-tools#33]
See http://0pointer.de/public/systemd-man/os-release.html

This removes the need for supporting a bunch of hardcoded OSes (https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/lib/misc/hostinfoPosix.c#L174-L215) and would allow e.g. [NixOS](https://github.com/NixOS/nixpkgs/blob/bb9aff2f0c0f8a9d4726c33ca1db88aa5322dc62/nixos/modules/misc/version.nix#L83-L91) to be supported without code changes.

**Comment by wmertens** [comment]
Ping, is this issue something that should indeed be implemented or will that never happen?

**Comment by copumpkin** [comment]
@oliverkurth sorry to ping you like this, but how do we get this issue more attention from people who can do something about it?

**Comment by stanguturi** [comment]
A lot of changes were made to the 'host information detection' code. The latest code should support os-release file. Please check the latest code. Check ce060ca498defdf08da4fac899dc623328d47a5d for some background.
