### ISSUE TITLE
ftbfs with GCC-9

### ISSUE THREAD

**Issue by bzed** [vmware/open-vm-tools#330]
Hi,

open-vm-tools fails to build in a test rebuild on at least amd64 with
gcc-9/g++-9, but succeeds to build with gcc-8/g++-8.

The full build log can be found at:
http://people.debian.org/~doko/logs/gcc9-20190321/open-vm-tools_10.3.5-8_unstable_gcc9.log
The last lines of the build log are at the end of this report.

To build with GCC 9, either set CC=gcc-9 CXX=g++-9 explicitly,
or install the gcc, g++, gfortran, ... packages from experimental.

  apt-get -t=experimental install g++ 

Common build failures are new warnings resulting in build failures with
-Werror turned on, or new/dropped symbols in Debian symbols files.
For other C/C++ related build failures see the porting guide at
http://gcc.gnu.org/gcc-9/porting_to.html

GCC 9 also passes the linker option --as-needed by default; typical
build issues are passing libraries before object files to the linker,
or underlinking of convenience libraries built from the same source.

```
hgfsServer.c: In function 'HgfsServerRead':
hgfsServer.c:6541:43: error: taking address of packed member of 'struct HgfsReplyReadV3' may result in an unaligned pointer value [-Werror=address-of-packed-member]
 6541 |                                           &reply->actualSize);
      |                                           ^~~~~~~~~~~~~~~~~~
hgfsServer.c:6562:56: error: taking address of packed member of 'struct HgfsReplyRead' may result in an unaligned pointer value [-Werror=address-of-packed-member]
 6562 |                                        reply->payload, &reply->actualSize);
      |                                                        ^~~~~~~~~~~~~~~~~~
```

Debian bug report: http://bugs.debian.org/925794

**Comment by ravindravmw** [comment]
We are in the process of releasing a patch in devel branch. It seems you are building open-vm-tools 10.3.5. So, you should be able to use the patch we published for Fedora - https://src.fedoraproject.org/rpms/open-vm-tools/blob/master/f/gcc9-warnings.patch.

**Comment by ravindravmw** [comment]
Found the commit from the devel branch as well. It is here - https://github.com/vmware/open-vm-tools/commit/c68172ef7f2d4f116078e2aba82986a8cab0b16e. This patch may not apply well to open-vm-tools 10.3.5 as devel branch has moved forward.

**Comment by bzed** [comment]
@ravindravmw thanks for your reply! We are not in a hurry here as gcc9 will not be released with Debian buster. But if you are interested, I can always upload devel versions of open-vm-tools to Debian experimental.

**Comment by ravindravmw** [comment]
@bzed we are fine either way. The change I pointed is just code restructuring change to make it compile with gcc9. You don't need to take it unless you move to gcc9. Hopefully, we will have a stable release by that time. If required earlier, you can always pick the patch.

**Comment by ravindravmw** [comment]
I must clarify that Fedora patch I mentioned earlier should apply smoothly on open-vm-tools 10.3.x versions.

**Comment by stanguturi** [comment]
> ```
> hgfsServer.c: In function 'HgfsServerRead':
> hgfsServer.c:6541:43: error: taking address of packed member of 'struct HgfsReplyReadV3' may result in an unaligned pointer value [-Werror=address-of-packed-member]
>  6541 |                                           &reply->actualSize);
>       |                                           ^~~~~~~~~~~~~~~~~~
> hgfsServer.c:6562:56: error: taking address of packed member of 'struct HgfsReplyRead' may result in an unaligned pointer value [-Werror=address-of-packed-member]
>  6562 |                                        reply->payload, &reply->actualSize);
>       |                                                        ^~~~~~~~~~~~~~~~~~
> ```
> 
> 
> Debian bug report: http://bugs.debian.org/925794

As Ravindra mentioned earlier in one of the comments, the issue reported above was fixed in commit  c68172ef7f2d4f116078e2aba82986a8cab0b16e Closing this issue.

**Comment by bzed** [comment]
@stanguturi is there an ETA for a release that ships the GCC9 patch?

**Comment by stanguturi** [comment]
> @stanguturi is there an ETA for a release that ships the GCC9 patch?

The fix was already submitted in devel branch. The fix should be available in the next MAJOR release. I don't know about any specific ETA.
