### ISSUE TITLE
vmhgfs-fuse doesn't correctly set _PC_NAME_MAX

### ISSUE THREAD

**Issue by jonathanunderwood** [vmware/open-vm-tools#337]
Host filesystems mounted in a linux (Fedora 29) guest with vmhgfs-fuse have _PC_NAME_MAX set to 0, as can be seen with `getconf _POSIX_NAME_MAX <path to mounted file or dir>`.

This means that nautilus in the guest can't rename a file or directory to a name with more than a single character.

See: https://gitlab.gnome.org/GNOME/nautilus/issues/1011

Related: 
https://github.com/cryptomator/cryptomator/issues/770
https://linux.die.net/man/3/pathconf

**Comment by jonathanunderwood** [comment]
The problem lies here where the struct is not properly filled out: 

https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/vmhgfs-fuse/filesystem.c

**Comment by jonathanunderwood** [comment]
Please see the nautilus bug referenced above for more detail.

**Comment by lousybrit** [comment]
Thanks for reporting. We do have a bug outstanding for this issue. As has been pointed out above too.

Steve

**Comment by stanguturi** [comment]
The issue was fixed in 7b096ae277428efd8f550c1bbb35e98bb0cdf565 in the devel branch.

**Comment by obeobe** [comment]
@stanguturi this happens to me with VMWare Workstation Pro 16, using Ubuntu 20.04 as host and Pop OS 20.04 as guest.

```
user@pop-os:~ $ getconf _POSIX_NAME_MAX /mnt/hgfs/xfer
0
```

Is there a fix or a workaround? It effectively prevents me from using Nautilus on the guest.
