### ISSUE TITLE
CentOS 7.6 not correctly recognized on ESXi 6.7U2

### ISSUE THREAD

**Issue by jozefizso** [vmware/open-vm-tools#341]
We have ESXi 6.7 Update 2 host with a CentOS 7.6 virtual machine with *open-vm-tools* installed. The VM is set with virtual hardware level 14 and Guest OS is CentOS 7.

ESXi issues warning that the OS is CentOS 6 and not CentOS 7. This is incorrect.

> The configured guest OS (CentOS 7 (64-bit)) for this virtual machine does not match the guest that is currently running (CentOS 6 (64-bit)). You should specify the correct guest OS to allow for guest-specific optimizations.

```
ESXi 6.7.0 Update 2 (Build 13006603)
CentOS 7.6.1810-x86_64
open-vm-tools 10.2.5 build 8068406
```

The OS version for CentOS 7 should be reported correctly.

**Comment by lemke1458** [comment]
This looks like a dup of issue 311.

**Comment by jozefizso** [comment]
Yes, this is caused by incorrect CentOS version detection as reported in #311 

There's no open-vm-tools 10.3.10 release available as RPM for CentOS though.

**Comment by lemke1458** [comment]
It was reported it to Redhat, but they currently have plans to fix it:

https://bugzilla.redhat.com/show_bug.cgi?id=1672087

**Comment by tonyskapunk** [comment]
fwiw in CentOS 7 there is 10.3.10 available now: http://mirror.centos.org/centos/7/os/x86_64/Packages/open-vm-tools-10.3.0-2.el7.x86_64.rpm

**Comment by stanguturi** [comment]
For CentOS 7, 11.0.5 is available http://mirror.centos.org/centos/7/os/x86_64/Packages/open-vm-tools-11.0.5-3.el7.x86_64.rpm which has the fix. Closing.
