### ISSUE TITLE
Invoke-VMScript fails with authentication error

### ISSUE THREAD

**Issue by f-ree** [vmware/open-vm-tools#345]
The command Invoke-VMScript produces the error "Failed to authenticate with the guest operating system using the supplied credentials". The credentials are 100% right, the operating system of the VM is Ubuntu 18.04. 

The logfile /var/log/vmware-vmsvc.log has the following entry:
   [2019-06-17T14:12:24.131Z] [ message] [vix] VixTools_ProcessVixCommand: command 181
   [2019-06-17T14:12:26.030Z] [ warning] [VCGA] PAM error: Authentication failure (7), mapped to VGAuth error 12
   [2019-06-17T14:12:26.032Z] [ warning] [vix] VixToolsImpersonateUser: impersonation failed (3050)
   [2019-06-17T14:12:26.032Z] [ message] [vix] VixToolsCreateTempFileInt: opcode 181 returning 3050
   [2019-06-17T14:12:26.032Z] [ message] [vix] ToolsDaemonTcloReceiveVixCommand: command 181, additionalError = 4294967294

What's wrong?

Thanks for the help

**Comment by lemke1458** [comment]
Its possibly a pam configuration issue, or the account has some limitations.
Does the account being used have a real shell, and support interactive logins?

The contents of /etc/pam.d/vmtoolsd could tell us more.

**Comment by f-ree** [comment]
Yes, the user is pointed to /bin/bash (etc/passwd) and I can login via SSH with this account.

The content of /etc/pam.d/vmtoolsd:
# PAM configuration for vmtoolsd
@include common-auth
account     required    pam_shells.so
@include common-account

Here are the valid login shells from /etc/shells:
/bin/sh
/bin/bash
/bin/rbash
/bin/dash
/usr/bin/tmux
/usr/bin/screen

Is it correct, that libpam.so is not linked with the binary /usr/bin/vmtoolsd?
The output of the command ldd /usr/bin/vmtoolsd does not show the library...

**Comment by lemke1458** [comment]
Can you get Invoke-VMScript to work with any guest user?
Is this open-vm-tools from the Ubuntu 18.04 distro, or were there any upgrades/changes/etc?

libpam.so is used by vmtoolsd; its dynamically loaded.

**Comment by lemke1458** [comment]
I tried to repro, using 18.04 with open-vm-tools with no issues.  Tried both root and a local normal account ('vmware'), and guestOps authenticate fine.

/etc/passwd entries
root:x:0:0:root:/root:/bin/bash
vmware:x:1000:1000:Virtual User:/home/vmware:/bin/bash

'apt list open-vm-tools' shows
open-vm-tools/bionic-updates 2:10.3.10-1~ubuntu0.18.04.1 amd64 [upgradable from: 2:10.2.0-3ubuntu3]

os-release is
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by f-ree** [comment]
were you able to execute successfull the Invoke-VMScript (e.g. Invoke-VMscript -ScriptText "ls -l" -VM <NameofVM> -GuestUser root -GuestPassword <pw>) or what do you mean exactly with "...authenticate fine"?

**Comment by lemke1458** [comment]
I successfully used guest operations, all of which require guest authentication.  Your issue is that the authentication fails, and it works fine for me.

Note that if you are using powercli and providing the password on a command line, be sure that the shell isn't modifying your password.  A common user error is not properly quoting or escaping a password with special characters in it, eg something like "pa$$word" on a Linux shell will turn into 'pa<PID>word'.

**Comment by f-ree** [comment]
Sorry for my late response, I was out of the office. 
The quotation of the password was the problem.
Thanks a lot four yoour help.
