### ISSUE TITLE
[guestinfo] GetDiskInfo: ERROR: Partition name buffer too small

### ISSUE THREAD

**Issue by Jcpetrucci** [vmware/open-vm-tools#346]
CentOS Linux release 7.6.1810 (Core)
$ vmware-toolbox-cmd -v
10.2.5.3619 (build-8068406)

I am encountering the error `[guestinfo] GetDiskInfo: ERROR: Partition name buffer too small` in my /var/log/vmware-vmsvc.log.  I don't fully understand what test is being done @ https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/services/plugins/guestInfo/diskInfo.c#L121, however looking at the contents of /proc/$(pidof vmtoolsd)/mounts I see that there are many lines which have very long (many character) mount points, due to a user running Kubernetes.  

I believe that the test above is comparing the character length of each mount point to "partNameSize" which is an unsigned int, and I suspect that these particular mount points in use may be too long for an unsigned int, however I am just speculating.  If anyone can break down for me what the test is looking for, I can validate if my mount points conform.

**Comment by lemke1458** [comment]
You're correct.  The partition name needs to fit into a buffer of partitionNameSize (100).  And that code gets mad if its too long.

We should probably just truncate it, and we need to think about the log level as well -- debug is probably a better idea if Kubernetes is going to make very long partition names.

The end result (beyond filling a logfille) is that this partition won't show up when you look at the GuestInfo for this VM via a vSphere API.

**Comment by Jcpetrucci** [comment]
Thanks @lemke1458 - I can confirm that I have mount points longer than 100 characters due to Kubernetes.  Truncating the names sounds good, or perhaps just skip ones longer than 100 characters and move on to the next mount point.  Currently, any single mount point that is too long results in no data for any of the mount points.

**Comment by lemke1458** [comment]
Ouch -- yeah I misread that.  That's a much nastier than I thought.

So if you want to hack things, change the g_warning() to a g_debug() and 'goto out' to a continue probably works (not tested yet).

We'll have a better fix in an upcoming release.

**Comment by oliverkurth** [comment]
Issue is fixed in the devel branch.
