### ISSUE TITLE
Why the content of file "/etc/vmware-tools/GuestProxyData/server/key.pem" is Clear text key？

### ISSUE THREAD

**Issue by RisingooSun** [vmware/open-vm-tools#349]
Hi guys

After I installed open-vm-tool, I found the content of file "/etc/vmware-tools/GuestProxyData/server/key.pem" is clear text key. Well known，using clear text key is not safe. So, I want to know the reason why the developers use clear text key here.

Thank you

**Comment by jonathanvmw** [comment]
@RisingooSun 

guestproxycerttool, the program that generates and reads this key, is deprecated.  It's being removed from VMTools 11.

**Comment by xiaominlxm** [comment]
Hi，the Clear text key in the file /etc/vmware-tools/GuestProxyData/server/key.pem has removed now？ from what version？

**Comment by xiaominlxm** [comment]
In addition，if i change the “encrypt_key” from “no” to “yes”，if it can  generate the encrypted content？

Thank you

**Comment by dsouders** [comment]
As previously noted, guestproxycerttool is deprecated and has been removed.

https://github.com/vmware/open-vm-tools/blob/stable-11.0.x/open-vm-tools/ChangeLog:

commit 49eb56393323c9344d10313d104bf20630813578
Author: Oliver Kurth <okurth@vmware.com>
Date:   Tue Dec 18 13:19:45 2018 -0800

    Remove grabbitmqproxy and certtool from tar installer, OSPs and open-vm-tools.

**Comment by xiaominlxm** [comment]
@dsouders 
Thank you for your quick answer. If I use old version before 11.0.x version，Can I  change the “encrypt_key” from “no” to “yes” to generate the  encrypted content？

**Comment by dsouders** [comment]
@xiaominlxm 

There is no "encrypt_key" option to the cert_tool command.  Note cert_tool was part of Common Agent Framework (CAF), which was a forward looking feature that was never actually used.
