### ISSUE TITLE
RecordRoutingInfo: Unable to collect IPv6 routing table.

### ISSUE THREAD

**Issue by takenek** [vmware/open-vm-tools#351]
Hello
I just upgrade my Debian 9 to 10 and i get problem.
ii  open-vm-tools                        2:10.3.10-1                 amd64        Open VMware Tools for virtual machines hosted on VMware (CLI)

In file /var/log/vmware-vmsvc.log i got spam about IPv6 route:
[2019-07-14T16:46:05.233Z] [ warning] [vmsvc] SlashProcNet_GetRoute6: open(/proc/net/ipv6_route): no such file or directory
[2019-07-14T16:46:05.233Z] [ warning] [vmsvc] RecordRoutingInfo: Unable to collect IPv6 routing table.

And yes this is true i disable IPv6 because i don`t use it on server - but maybe there is option to disable this spam in log?

Best Regards
TaKeN

**Comment by oliverkurth** [comment]
You should be able to suppress IPv6 route gathering by setting:
```
[guestinfo]
max-ipv6-routes=0
```
in `/etc/vmware-tools/tools.conf`. Create that file if it does not exist.

**Comment by takenek** [comment]
Working perfect.

Thanks @oliverkurth
