### ISSUE TITLE
Kali Linux 2019.3 screen resize is not working

### ISSUE THREAD

**Issue by raulsiles** [vmware/open-vm-tools#355]
I'm running Kali Linux 2019.3 inside a VM using VMware Workstation 15 Pro (15.1.0) in Windows 10. All components, including Windows, VMware and Kali Linux are fully updated up to today. This Kali Linux VM has been upgraded from previous 2017 versions.

I've followed the official Kali Linux instructions to install VMware Tools (open-vm-tools) in a guest VM: https://docs.kali.org/general-use/install-vmware-tools-kali-guest

NOTE: All commands are executed as root using "sudo".

After rebooting I've reinstalled both open-vm-tools (v2:10.3.10-1) and open-vm-tools-desktop (v2:10.3.10-1):
```
# apt -y --reinstall install open-vm-tools-desktop fuse
# apt -y --reinstall install open-vm-tools
# vmtoolsd -v
VMware Tools daemon, version 10.3.10.10540 (build-12406962)
```

Other packages such as "open-vm-tools-dkms" or "open-vm-tools-dev" are not installed.

**Copy and paste is working fine** from host to guest (and vice versa) but **screen resize is not working**.

I've also enabled in VMware Workstation all Autofit options:
- Edit-Preferences-Display: Autofit --> Autofit window and Autofit guest
- Edit-Preferences-Display: Full screen --> Autofit guest
- VM - Settings - Display: Display scaling --> Stretch mode & Keep aspect ratio stretch
- View - Autosize: Autofit Guest (& Autofit Window)

BTW, modern Kali Linux versions use X11, not Wayland:
```
# echo $XDG_SESSION_TYPE
x11
```

The kernel version in use is 4.19:
```
# uname -a
Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux
```

If I run the open-vm-tools-desktop wrapper I got a vmblock error:
```
# /usr/bin/vmware-user-suid-wrapper
vmware-user: could not open /proc/fs/vmblock/dev
...
```

I've fixed this vmblock error (related to "/usr/bin/vmware-user-suid-wrapper") by executing:
```
# systemctl start run-vmblock\\x2dfuse.mount
# systemctl enable run-vmblock\\x2dfuse.mount
```

When the Kali Linux VM boots up, the two expected vmtoolsd processes are running:
```
# ps -ef | grep vmtool
root       536     1  0 13:41 ?        00:00:00 /usr/bin/vmtoolsd
root      1359     1  0 13:42 tty2     00:00:00 /usr/bin/vmtoolsd -n vmusr --blockFd 3
```

However, the "vmtoolsd -n vmusr" process does not have the "libresolutionSet.so" plugin:
```
# lsof -p 1359 | grep -i plugin
vmtoolsd 1359 root  mem       REG                8,1   362440  394567 /usr/lib/open-vm-tools/plugins/vmusr/libdndcp.so
vmtoolsd 1359 root  mem       REG                8,1   135000  264958 /usr/lib/open-vm-tools/plugins/common/libvix.so
vmtoolsd 1359 root  mem       REG                8,1    14536  264954 /usr/lib/open-vm-tools/plugins/common/libhgfsServer.so
vmtoolsd 1359 root  mem       REG                8,1    23568  393582 /usr/lib/open-vm-tools/plugins/vmusr/libdesktopEvents.so
```

The plugin file does exist, but it is not loaded by "vmtoolsd -n vmusr":
```
# ls -l /usr/lib/open-vm-tools/plugins/vmusr/libresolutionSet.so
-rw-r--r-- 1 root root 35752 Mar 29 11:58 /usr/lib/open-vm-tools/plugins/vmusr/libresolutionSet.so
```

VMware Workstation assigns 128 MB of RAM to the video card, based on vmware.log file, so this should not be the reason not to load the plugin:
```
...
2019-07-20T10:38:48.911+02:00| vmx| I125: SVGA: SVGA_REG_MEMORY_SIZE=939524096
2019-07-20T10:38:48.911+02:00| vmx| I125: SVGA: SVGA_REG_VRAM_SIZE=134217728
...
```

I've also tried to delay the startup of open-vm-tools during the boot process after the Display Manager, as mentioned in issue #253 , without success, by adding the following line to the "/lib/systemd/system/open-vm-tools.service" file under the "[Unit]" section, and rebooting:
```
After=display-manager.service
```

In Kali Linux the file mentioned in issue #214 under "/etc" does not exist, "/etc/systemd/system/multi-user.target.wants/open-vm-tools.service", although the contents are similar to the contents of the file previously mentioned under "/lib". In this case, the suggestion is to delay the startup after the GDM service:
```
After=gdm.service
```

This option, using the file under "/lib", didn't work for me either.

BTW, it seems the right file for "open-vm-tools" in Kali Linux is the one under "/lib", not the one under "/etc":
```
# apt-file list open-vm-tools
...
open-vm-tools: /etc/vmware-tools/*
open-vm-tools: /lib/systemd/system/open-vm-tools.service
...
```

Following the advice also in issue #214 , I removed the previous two "After" directives to delay the startup of the service (as they didn't work in my case) and tried adding the following directive under the "[Service]" section, before the "ExecStart" directive, in the same "/lib/systemd/system/open-vm-tools.service" file:
```
ExecStartPre=-/sbin/modprobe vmwgfx
ExecStart=/usr/bin/vmtoolsd
```

This didn't work either. I rebooted the VM after every change. The related Kali Linux report for a similar issue is https://bugs.kali.org/view.php?id=5051, supposedly fixed in Kali Linux 2019.1.

Issue #265 mentions autofit does not work if resolutionKMS is enabled. In this Kali Linux VM, resolutionkMS seems to be enabled based on the output from the following log file:
```
# less /var/log/vmware-vmsvc.log
...
[2019-08-03T11:41:32.340Z] [ message] [vmsvc] Log caching is enabled with maxCacheEntries=4096.
[2019-08-03T11:41:32.341Z] [ message] [vmsvc] Core dump limit set to -1
[2019-08-03T11:41:32.341Z] [ message] [vmtoolsd] Tools Version: 10.3.10.10540 (build-12406962)
[2019-08-03T11:41:32.488Z] [ message] [vmtoolsd] Plugin 'hgfsServer' initialized.
[2019-08-03T11:41:32.488Z] [ message] [vix] QueryVGAuthConfig: vgauth usage is: 1
[2019-08-03T11:41:32.488Z] [ message] [vmtoolsd] Plugin 'vix' initialized.
[2019-08-03T11:41:32.488Z] [ message] [vmtoolsd] Plugin 'deployPkg' initialized.
[2019-08-03T11:41:32.850Z] [ message] [vmtoolsd] Plugin 'grabbitmqProxy' initialized.
[2019-08-03T11:41:32.850Z] [ message] [vmtoolsd] Plugin 'guestInfo' initialized.
[2019-08-03T11:41:32.850Z] [ message] [vmtoolsd] Plugin 'powerops' initialized.
[2019-08-03T11:41:32.856Z] [ message] [resolutionCommon] resolutionCheckForKMS: dlopen succeeded.
[2019-08-03T11:41:32.859Z] [ message] [resolutionCommon] resolutionCheckForKMS: System support available for resolutionKMS.
[2019-08-03T11:41:32.859Z] [ message] [vmtoolsd] Plugin 'resolutionKMS' initialized.
[2019-08-03T11:41:32.860Z] [ message] [vmtoolsd] Plugin 'timeSync' initialized.
[2019-08-03T11:41:32.860Z] [ message] [vmtoolsd] Plugin 'vmbackup' initialized.
[2019-08-03T11:41:32.863Z] [ message] [vix] VixTools_ProcessVixCommand: command 62
[2019-08-03T11:41:33.109Z] [ message] [vix] VixTools_ProcessVixCommand: command 62
[2019-08-03T11:41:33.109Z] [ message] [vix] ToolsDaemonTcloReceiveVixCommand: command 62, additionalError = 17
...
```

What can be done to force "vmtoolsd -n vmusr" to load the "libresolutionSet.so" plugin and be able to properly resize the VM screen?

**Comment by johnwvmw** [comment]
The latest official Kali Linux that I can find is Kali-2019.2.

I presume that you may be using one of the weekly builds.

I have installed Kali-2019.2 and like an earlier Kali-2019s.-1a, I am having no problems resizing my WS windows and the Kali desktop is resized.

I have both the Autofit windows and Autofit guest selected in my WS display preferences.

Using the same open-vm-tools packages that you are using.

  open-vm-tools-desktop/now 2:10.3.10-1 amd64 [installed,upgradable to: 2:10.3.10-2]
  open-vm-tools/now 2:10.3.10-1 amd64 [installed,upgradable to: 2:10.3.10-2]

# uname -a
Linux kali-2019 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux


On recent versions of open-vm-tools the preference is to use the libresolutionKMS.so plugin in the vmtoolsd vmsvc daemon process for display resolution.  I believe it depends on the presence of the vmwgfx kernel module.  The vmusr libresolutionSet.so would only be loaded if the KMS plugin can not be loaded.

  # ps -ef | grep tools
  root        473      1  0 14:13 ?        00:00:02 /usr/bin/vmtoolsd
  root       3281      1  0 14:25 tty2     00:00:01 /usr/bin/vmtoolsd -n vmusr --blockFd 3

  # lsof -p 473 | grep plugins
   ...
  vmtoolsd 473 root  mem       REG                8,1    23000 395948 /usr/lib/open-vm-tools/plugins/vmsvc/libresolutionKMS.so

I was able to reproduce what you are reporting when I enabled the "Stretch mode" option in the VM's Display settings?

Do you get the results that you expect if you disable the "Stretch mode" option?

Hopefully you have a snapshot of the VM before all the systemd file "tweaks".  It should work just as is.    The vmwgfx module is loaded by /lib/systemd/system/open-vm-tools.service.d/desktop.conf.

**Comment by raulsiles** [comment]
I was using Kali Linux 2019.3, not a weekly build, as this was the latest version available via operating system updates. Based on the "uname -a" output, we do not have the same kernel version.

No matter what option I select in VMware Workstation "View - Stretch Guest" menu: Keep Aspect Ratio Stretch, or Free Stretch, the result is the same and I cannot auto resize the guest screen. 

I have disabled in VMware "VM - Settings - Display: Display scaling" --> Stretch mode. I have proceeded to update today the operating system to the latest SW updates. After rebooting, with "Stretch mode" disable and the latest updates, it didn't work right after booting, but it worked after executing the following command:
```
# /usr/bin/vmware-user-suid-wrapper

# uname -a
Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux

# ps -ef | grep vmtool
root       564     1  0 13:31 ?        00:00:00 /usr/bin/vmtoolsd
root      1301     1  1 13:32 tty2     00:00:00 /usr/bin/vmtoolsd -n vmusr --blockFd 3
root      1478  1455  0 13:32 pts/0    00:00:00 grep vmtool

# lsof -p 1301 | grep plugin
vmtoolsd 1301 root  mem       REG                8,1   362440  265671 /usr/lib/open-vm-tools/plugins/vmusr/libdndcp.so
vmtoolsd 1301 root  mem       REG                8,1   135000  268986 /usr/lib/open-vm-tools/plugins/common/libvix.so
vmtoolsd 1301 root  mem       REG                8,1    14536  265668 /usr/lib/open-vm-tools/plugins/common/libhgfsServer.so
vmtoolsd 1301 root  mem       REG                8,1    23568  265670 /usr/lib/open-vm-tools/plugins/vmusr/libdesktopEvents.so
# lsof -p 564 | grep plugin
vmtoolsd 564 root  mem       REG                8,1    43736  268993 /usr/lib/open-vm-tools/plugins/vmsvc/libvmbackup.so
vmtoolsd 564 root  mem       REG                8,1   135000  268986 /usr/lib/open-vm-tools/plugins/common/libvix.so
vmtoolsd 564 root  mem       REG                8,1    22792  268992 /usr/lib/open-vm-tools/plugins/vmsvc/libtimeSync.so
vmtoolsd 564 root  mem       REG                8,1    23000  268991 /usr/lib/open-vm-tools/plugins/vmsvc/libresolutionKMS.so
vmtoolsd 564 root  mem       REG                8,1    36616  268989 /usr/lib/open-vm-tools/plugins/vmsvc/libguestInfo.so
vmtoolsd 564 root  mem       REG                8,1    31272  268988 /usr/lib/open-vm-tools/plugins/vmsvc/libgrabbitmqProxy.so
vmtoolsd 564 root  mem       REG                8,1    14712  268990 /usr/lib/open-vm-tools/plugins/vmsvc/libpowerOps.so
vmtoolsd 564 root  mem       REG                8,1    14536  265668 /usr/lib/open-vm-tools/plugins/common/libhgfsServer.so
vmtoolsd 564 root  mem       REG                8,1    14696  268987 /usr/lib/open-vm-tools/plugins/vmsvc/libdeployPkgPlugin.so

```
