### ISSUE TITLE
Support for appmonitorlib in open-vm-tools

### ISSUE THREAD

**Issue by michaelpq** [vmware/open-vm-tools#36]
This version of open-vm-tools does not include libappmonitorlib.so to be able to perform ping, start and stop actions for individual components in a VM. Are there any plans in this area? It seems to me that the vSphere HA SDK conflicts with the contents of open-vm-tools, which may lead to unexpected failures if both are mixed in a VM, particularly for the deamon vmtoolsd if it finds in a path a library provided by the HA SDK instead of what is available in package open-vm-tools.

**Comment by ravindravmw** [comment]
There is no plan to open source Guest SDK at this point of time.

The Guest SDK tarball uses different paths and one needs to adjust LD_LIBRARY_PATH to use the libraries from Guest SDK, http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.guestsdk.pg.doc/guest_sdk_Install.3.4.html?path=7_7_0_0_2_1#996080. 

Having said this, the conflict is always possible even with VMware Tools if one wants to create it. So, one needs to be careful about not mixing the libraries from Guest SDK with VMware Tools or open-vm-tools.

**Comment by michaelpq** [comment]
OK, thanks for your reply. I am aware of using tricks with LD_LIBRARY_PATH, but honestly that's ugly, and bug prone.

**Comment by ravindravmw** [comment]
I understand the LD_LIBRARY_PATH concerns. I have raised your ask with the group that owns AppMonitorLib for future consideration.

**Comment by nikhail** [comment]
Ravindra, open-vm-tools main readme mentions:
"...
Generation of heartbeat from guests to hosts so VMware's HA solution can determine guests' availability.
..."
Is that no longer true? (I see you response above, but it only mentions topics of open sourcing Guest SDK and coexistence of Guest SDK and open-vm-tools, not the 1st question from Michael.)
Could you please elaborate on above VMware HA support? (The tools autonomously ping to underlying vSphere HA or they do provide user-land API that can be called by an arbitrary app, or the readme is incorrect?)

**Comment by ravindravmw** [comment]
@nikhail The guest heartbeat is different from AppMonitorLib. Guest heartbeat is sent by Toolsd independent of GuestSDK. This is used for VM level protection.

GuestSDK provides AppMonitorLib for arbitrary apps. It is the user-land API you are asking about.
