### ISSUE TITLE
Trouble creating VM with Guest OS Version: VMware ESXi 6.5 or later

### ISSUE THREAD

**Issue by willervinNTS** [vmware/open-vm-tools#360]
I'm trying to configure a new VM with Guest OS Version ESXi 6.5 or later. 
![GuestOS](https://user-images.githubusercontent.com/53794492/63715756-733f3700-c812-11e9-9ebc-b25b7e4dc7c3.PNG)
When creating a new VM on through vSphere I'm able to set the correct version but I'm unable to find it's corresponding guestId needed for the vim.vm.ConfigSpec() param. Here is the only list of guestId's I've been able to find so far: https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html#top

**Comment by williamervinNTS** [comment]
Actually yes that worked this time. I tried that a few days ago and was unsuccessful so I ruled it out. Thank you.
