### ISSUE TITLE
Mismatched Memory Management Routines

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [vmware/open-vm-tools#361]
Argument to free() is the address of the global variable 'gHostClipboardBuf', which is not memory allocated by malloc()
https://github.com/vmware/open-vm-tools/blob/1f128736f9975b7afa9e342ec52575f57bf63d13/open-vm-tools/services/plugins/dndcp/copyPasteCompatX11.c#L623

**Comment by dsouders** [comment]
This should be fixed in the devel branch:

https://github.com/vmware/open-vm-tools/commit/9c30be3448c743e51718480543142bf833ea553a#diff-40da9520c22adf29544653a4d543266f

Please check.  Thanks!
