### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [vmware/open-vm-tools#362]
Memory is allocated
https://github.com/vmware/open-vm-tools/blob/1f128736f9975b7afa9e342ec52575f57bf63d13/open-vm-tools/libDeployPkg/linuxDeployment.c#L446

Potential leak of memory pointed to by 'data'
https://github.com/vmware/open-vm-tools/blob/1f128736f9975b7afa9e342ec52575f57bf63d13/open-vm-tools/libDeployPkg/linuxDeployment.c#L457

**Comment by QiAnXinCodeSafe** [comment]
Memory is allocated
https://github.com/vmware/open-vm-tools/blob/1f128736f9975b7afa9e342ec52575f57bf63d13/open-vm-tools/libDeployPkg/linuxDeployment.c#L1495

Potential leak of memory pointed to by 'args'
https://github.com/vmware/open-vm-tools/blob/1f128736f9975b7afa9e342ec52575f57bf63d13/open-vm-tools/libDeployPkg/linuxDeployment.c#L1505

**Comment by stanguturi** [comment]
These should be fixed in d93219282ff7e89e3f581bf757dfd807c7568452 in devel branch. Please check
