### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [vmware/open-vm-tools#363]
Stream is opened
https://github.com/vmware/open-vm-tools/blob/a4dde45f5e281663efc2e1acbf1bba0dfb5bfce1/open-vm-tools/libDeployPkg/linuxDeployment.c#L851

Opened file never closed
https://github.com/vmware/open-vm-tools/blob/a4dde45f5e281663efc2e1acbf1bba0dfb5bfce1/open-vm-tools/libDeployPkg/linuxDeployment.c#L857

**Comment by dsouders** [comment]
Thank you for reporting this issue.

An internal bug has been filed to address the problem.

**Comment by stanguturi** [comment]
The issue was fixed in 2ffd2913088505d8249fa342b0ee8e5002a69108 on devel branch. It should be available in the next release.
