### ISSUE TITLE
Dereference of null pointer

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [vmware/open-vm-tools#365]
Value assigned to 'entry'
https://github.com/vmware/open-vm-tools/blob/a4dde45f5e281663efc2e1acbf1bba0dfb5bfce1/open-vm-tools/libvmtools/vmtoolsLog.c#L612

Assuming pointer value is null
https://github.com/vmware/open-vm-tools/blob/a4dde45f5e281663efc2e1acbf1bba0dfb5bfce1/open-vm-tools/libvmtools/vmtoolsLog.c#L613

Access to field 'msg' results in a dereference of a null pointer (loaded from variable 'entry')
https://github.com/vmware/open-vm-tools/blob/a4dde45f5e281663efc2e1acbf1bba0dfb5bfce1/open-vm-tools/libvmtools/vmtoolsLog.c#L630

**Comment by dsouders** [comment]
Thank you for reporting this issue.

An internal bug has been filed to address the problem.

**Comment by dsouders** [comment]
This has been fixed on the devel branch.  Please see: https://github.com/vmware/open-vm-tools/commit/4d3607ca69fb031cd1b25c157a396250a867cf3e
