### ISSUE TITLE
Endless Loop

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [vmware/open-vm-tools#366]
https://github.com/vmware/open-vm-tools/blob/a4dde45f5e281663efc2e1acbf1bba0dfb5bfce1/open-vm-tools/vmhgfs-fuse/cache.c#L494

**Comment by dsouders** [comment]
Thank you for reporting this issue.

The infinite loop is intentional.   HgfsPurgeCache() is a garbage collection thread that runs periodically, waking up ever CACHE_PURGE_SLEEP_TIME seconds.  Please refer to the comment at line 475.
