### ISSUE TITLE
Depends on dead-upstream libdnet

### ISSUE THREAD

**Issue by bzed** [vmware/open-vm-tools#368]
libdnet (https://github.com/dugsong/libdnet) hasn't been updated for years and is unmaintained in Debian. You might want to switch to an actively maintained library or take of the development of libdnet.

**Comment by oliverkurth** [comment]
We don't depend on libndnet any more by default, at least on Linux. The only reason we still support it is because of open-vm-tools for FreeBSD.

**Comment by dsouders** [comment]
Thank you for reporting this issue.

There is an existing internal bug to address the problem.

**Comment by bzed** [comment]
> We don't depend on libdnet any more by default, at least on Linux. The only reason we still support it is because of open-vm-tools for FreeBSD.

Thanks - I've missed that. Removed from the build-dependencies in Debian.
