### ISSUE TITLE
undefined reference to 'VMTools_Log' (open-vm-tools 11.0.0)

### ISSUE THREAD

**Issue by MilhouseVH** [vmware/open-vm-tools#370]
Build log part1: http://ix.io/1W6i
Build log part2: http://ix.io/1W6j
(sorry, too big to post as a single log)
```
.libs/libvmbackup_la-scriptOps.o:scriptOps.c:function VmBackupRunNextScript: error: undefined reference to 'VMTools_Log'
.libs/libvmbackup_la-scriptOps.o:scriptOps.c:function VmBackupRunNextScript: error: undefined reference to 'VMTools_Log'
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'libvmbackup.la' with the above command before installing it
make[6]: *** [Makefile:514: install-pluginLTLIBRARIES] Error 1
```

No issues building `open-vm-tools 10.3.10` - this is our [build package](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/sysutils/open-vm-tools/package.mk) - is there something new in 11.0.0 that we are missing? Or is there a missing header somewhere in `open-vm-tools 11.0.0`?

**Comment by oliverkurth** [comment]
We do test various Linux distributions, LibreELEC is not one of them though. I just tried the same configure options that you use in a Ubuntu 18.04 VM, but it builds successfully.

`VMTools_Log()` is in https://github.com/vmware/open-vm-tools/blob/854fde81011f500405c01a46651c41e893b78449/open-vm-tools/libvmtools/vmtoolsLog.c

**Comment by MilhouseVH** [comment]
Thanks. I'm currently building on Ubuntu 16.04, with `gcc-9.2.0` (LibreELEC builds it's own toolchain). I'll check with a colleague and see if they have any ideas (I'm not a C-coder by trade...) - will post back with any updates.

**Comment by MilhouseVH** [comment]
This is proving tricky to reproduce.

I had the original failure on Ubuntu 16.04, but two subsequent clean builds of LibreELEC (with `open-vm-tools-11.0.0`) on Ubuntu 16.04 - identical to the first clean build that failed, with no changes to the build host - have both succeeded, which suggests the failure might be a little... random. Eugh! :frowning_face: 

I'm building with `-j8` (LibreELEC default is to use `-j$(nproc)`) in case this is some sort of concurrency/race issue. Of course it could be an issue/glitch with the LibreELEC build system, and I'm not discounting that either.

I'll close this issue for now, but will post again if the issue continues and I have more details to share (hopefully it was a one off... but from experience things like this rarely are, and are sometimes difficult to pin down!)

BTW should you ever fancy test building `open-vm-tools` for LibreELEC:
```
git clone https://github.com/LibreELEC/LibreELEC.tv.git
cd LibreELEC.tv
scripts/checkdeps # install any missing required dependencies

PROJECT=Generic ARCH=x86_64 scripts/build_mt open-vm-tools >/tmp/build.log
```
It takes about 30 minutes on an 8-core 4GHz Haswell to build `open-vm-tools`, and requires 10GB disk space. If you wish, run `tools/dashboard` to monitor the build progress.

Currently LibreELEC `master` builds `open-vm-tools-10.3.10` (with `gcc-9.2.0`, `glibc-2.30`, `glib-2.61.1`,  `fuse-2.9.9`, kernel `5.3.0`, etc.). You'll need to apply https://github.com/LibreELEC/LibreELEC.tv/pull/3861 to build `open-vm-tools-11.0.0`.

**Comment by MilhouseVH** [comment]
It turns out I might have been a little addled when I posted on Friday...

We have two ways of building LibreELEC, a "clean" build (deleting the entire build directory for the target image, ie. starting from scratch) and an "unclean" build when we rebuild only those packages that have been modified since the previous build.

It seems that the `open-vm-tools` failures I experienced were not from a clean build (these are always successful with 11.0.0) but from an "unclean" build when I simply updated the `open-vm-tools` package from 10.3.10 to 11.0.0 and then rebuilt `open-vm-tools` - these types of builds fail, and reproducibly so.

We think we [have a fix](https://github.com/LibreELEC/LibreELEC.tv/pull/3861#issuecomment-533856696) which involves modifying `services/plugins/vmbackup/Makefile.am` in `open-vm-tools-11.0.0`, and we are now able to reliably build `open-vm-tools-11.0.0` both "clean" and "unclean" (upgrading from 10.3.10) without it becoming confused about missing libraries (or perhaps more likely, finding and using incompatible libraries it finds elsewhere from an existing 10.3.10 install?)

Anyway, this fix is good enough for us. Not sure if this fix means anything to you or if it may be something specific for LibreELEC to carry in future.

**Comment by oliverkurth** [comment]
Thank you for the update, this is very much appreciated!

I will file an internal bug to investigate the problem in `services/plugins/vmbackup/Makefile.am`.

**Comment by MilhouseVH** [comment]
FYI we've modified the fix ([link v2](https://github.com/LibreELEC/LibreELEC.tv/pull/3861#issuecomment-534421035)) - we now delete the old `/usr/lib/libvmtools*` libraries from our toolchain sysroot prior to building the new `open-vm-tools` package, this ensures it's not possible for the new `open-vm-tools-11.0.0` package to link against the older `open-vm-tools-10.3.10` libraries that were installed by the previous build.

Based on this, I suspect that if you were to build and install `open-vm-tools-10.3.10`, and then subsequently build/install `open-vm-tools-11.0.0`, the latter would fail if you were to hit the same issue we are seeing here with LibreELEC when performing an "unclean" build (ie. 11.0.0 linking against the installed 10.3.10 libs).
