### ISSUE TITLE
Freebsd12p10 mounting via fstab not working

### ISSUE THREAD

**Issue by network-shark** [vmware/open-vm-tools#374]
Hello , 

I don't know if the problem is related to open-vm-tools or to freebsd, but I hope we can clarify it. 

Manually mounting the host system or a folder to a freebsd12p10 vm works well. 

`sudo vmhgfs-fuse -o allow_other -o uid=1001 .host:/ /mnt/HostShare`

If I try to use fstab , freebsd gives me a syntax error . I could not found any specific documentation for freebsd . How to mount vmhfgs-fuse via /etc/fstab. It is more try and error and none of my solutions works. 

What I have tried. 

```
# cat /etc/fstab
# Device                Mountpoint      FStype  Options         Dump    Pass#
/dev/da0p2              none    swap    sw              0       0`
#.host:/ /mnt/ vmhgfs-fuse mountprog=/usr/local/bin/vmhgfs-fuse,defaults,allow_other,uid=1000 0 0
#.host:/mech /mnt/mech vmhgfs-fuse allow_other 0 0
#.host:/mech /mnt/mech vmhgfs defaults,ttl=5,uid=1000,gid=1000   0 0
#.host:/mech /mnt/ vmhgfs-fuse defaults,ttl=5,uid=1000,gid=1000   0 0
#.host:/ /mnt/ vmhgfs-fuse mountprog=/usr/local/bin/vmhgfs-fuse,uid=1000,gid=1000,defaults 0 0
#vmhgfs-fuse /mnt/ fuse defaults,allow_other    0    0
#vmhgfs-fuse /mnt/ vmhgfs-fuse mountprog=/usr/local/bin/vmhgfs-fuse, defaults,allow_other    0    0
#.host:/    /mnt/        fuse.vmhgfs-fuse mountprog=/usr/local/bin/vmhgfs-fuse,    defaults,allow_other    0    0
#vmhgfs-fuse /mnt/ vmhgfs-fuse defaults,nonempty,allow_other 0 0
#vmhgfs-fuse .host:/ /mnt/ -o subtype=vmhgfs-fuse,allow_other 0 0
#.host: /mnt/ vmhgfs-fuse mountprog=/usr/local/bin/vmhgfs-fuse,nonempty,allow_other,auto_unmount,defaults 0 0
#.host:/ /mnt/ fuse mountprog=/usr/local/bin/vmhgfs-fuse,defaults,allow_other
#.host://mnt// fuse mountprog=/usr/local/bin/vmhgfs-fuse,defaults,allow_other,uid=1001
.host:/ /mnt/ fuse mountprog=/usr/local/bin/vmhgfs-fuse,defaults,allow_other,uid=1001
```
```
# mount -a
fstab: /etc/fstab:16: Inappropriate file type or format
```
Nothing works . 
Kernel module is loaded.
```
# kldstat
Id Refs Address                Size Name
 1   23 0xffffffff80200000  243d228 kernel
 2    1 0xffffffff8263f000   3a9a10 zfs.ko
 3    2 0xffffffff829e9000     a4f0 opensolaris.ko
 4    1 0xffffffff82c1a000     27b0 vmmemctl.ko
 5    1 0xffffffff82c1d000     23f0 vmxnet.ko
 6    1 0xffffffff82c20000     2ed8 vmblock.ko
 7    1 0xffffffff82c23000     9c08 fuse.ko
 8    1 0xffffffff82c2d000     2678 intpm.ko
 9    1 0xffffffff82c30000      b10 smbus.ko
```
I'm wondering about the following errors .

```
# vmhgfs-fuse -e
failed to open /proc/filesystems 2
failed to open /lib/modules/12.0-RELEASE-p10/modules.dep 2
SysCompatCheck: failed FUSE install checks
vmhgfs-fuse: 2 - HGFS FUSE client needs FUSE environment
```
Failed to open does not sound good to me , but I don't know if these failures are ok or not.

**Comment by johnwvmw** [comment]
@network-shark 

I am setting up a fresh FBSD 12.0 on my WS 15.1 Pro to investigate.   In the mean time can you confirm
- what version of fusion or workstation are you using?
- what Host OS version are you using?
- version of open-vm-tools(-nox11) are you using?  - presumably 10.3.0
- what version of the fusefs-libs package is install on the FBSD 12.0 VM?

One note, the filesystem type should be "vmhgfs-fuse"  - not "fuse".   That would explain the "fstab: /etc/fstab:16: Inappropriate file type or format" error that you are getting on the "mount -a" attempt.

**Comment by network-shark** [comment]
Thank You @johnwvmw 

what version of fusion or workstation are you using?
Vmware Fusion 11.02

what Host OS version are you using?
Mac OS 10.14.6
version of open-vm-tools(-nox11) are you using? - presumably 10.3.0

# pkg info | grep vm
open-vm-tools-nox11-10.3.0_1,2 Open VMware tools for FreeBSD VMware guests

what version of the fusefs-libs package is install on the FBSD 12.0 VM?
# pkg info | grep fuse
fusefs-libs-2.9.9              FUSE allows filesystem implementation in userspace

**Comment by lousybrit** [comment]
Hello,

The command line options and errors you tried here

`
# vmhgfs-fuse -e
failed to open /proc/filesystems 2
failed to open /lib/modules/12.0-RELEASE-p10/modules.dep 2
SysCompatCheck: failed FUSE install checks
vmhgfs-fuse: 2 - HGFS FUSE client needs FUSE environment
`

Will not work in a FreeBSD environment. It is really only meant for Linux currently. 
We need to fix that and have it correctly check and report on the FreeBSD system.

Updating our FUSE client for FreeBSD is on the list of items to address.
Thanks for reporting.
Steve

**Comment by johnwvmw** [comment]
@network-shark 

While the vmhgfs-fuse command will mount the shared folder on FreeBSD, it is not a FreeBSD filesystem mount program.  We need to use the  FreeBSD fusefs mount program here.

In a separate Forum this weekend (https://forums.freebsd.org/threads/vmware-shared-folders.10318/post-442308) _martin has posted this /etc/fstab line.

.host:/        /mnt/hgfs    fusefs  rw,mountprog=/usr/local/bin/vmhgfs-fuse,allow_other,failok 0 0

Please be certain that the fuse kernel module has been loaded - fuse_load="YES" in /boot/loader.conf.

I have tested it and the shared folder is automatically mounted when the VM is rebooted.

**Comment by martin-0** [comment]
Yeah, I had a little fun debugging it yesterday. Basically you do need to specify the fstab.fs_type ( here in example "rw" ) or it fails through parsing loop and ends up in error(EFTYPE).

**Comment by stanguturi** [comment]
> In a separate Forum this weekend (https://forums.freebsd.org/threads/vmware-shared-folders.10318/post-442308) _martin has posted this /etc/fstab line.
> 
> .host:/ /mnt/hgfs fusefs rw,mountprog=/usr/local/bin/vmhgfs-fuse,allow_other,failok 0 0

Thanks @johnwvmw for the pointers.

> Yeah, I had a little fun debugging it yesterday. Basically you do need to specify the fstab.fs_type ( 
here in example "rw" ) or it fails through parsing loop and ends up in error(EFTYPE).

Thanks @martin-0

@network-shark Closing this issue. Please reopen if the approach mentioned above doesn't work.
