### ISSUE TITLE
"configure: error: mspack >= 0.0.20040308alpha is required" in RHEL 6.6

### ISSUE THREAD

**Issue by avinashdjadhao** [vmware/open-vm-tools#38]
I am trying to run ./configure for open-vm-tools in RedHat Enterprise Linux 6.6, but it is giving me this error:

checking for libmspack >= 0.0.20040308alpha (via pkg-config)... no
configure: error: mspack >= 0.0.20040308alpha is required.

**Comment by ravindravmw** [comment]
I don't think RHEL 6.6 ships that library. You would need to build/install it from the source code yourself.

**Comment by avinashdjadhao** [comment]
This is exactly what I am doing. I took the source code and tried to configure it. But while configuring, faced above issue.

**Comment by dyno** [comment]
for RHEL6.6, we actually have rpm built from VMware and hosted at http://packages.vmware.com/tools/esx/latest/rhel6/index.html, it is recommended to use that one, unless you have a specific reason to build it by yourself.

having said that, i've tried to build the open-vm-tools on RHEL6.7 
 
```bash
yum install gcc gcc-c++
 yum install gtk2-devel libXtst-devel gtkmm24-devel pam-devel
# install libdnet from http://libdnet.sourceforge.net/
./configure --enable-deploypkg=no --without-ssl --without-icu
make
```
`--enable-deploypkg=no` basically remove the dependency of libmspack
for more information about deploypkg, check http://kb.vmware.com/kb/2075048

**Comment by ravindravmw** [comment]
Thanks Dyno. I should have asked why one would need to build open-vm-tools for RHEL 6.x when we provide OSPs for it.

I would like to remind that we don't support open-vm-tools on RHEL 6.x officially yet.

> for more information about deploypkg, check http://kb.vmware.com/kb/2075048
I would like to add that open-vm-tools-deploypkg package mentioned in the KB article above is not intended/designed to be used with open-vm-tools 9.10.x.

**Comment by dyno** [comment]
actually,  if you install libmspack from http://www.cabextract.org.uk/libmspack/#download and
```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```
you can remove the `--enable-deploypkg=no` option.

**Comment by nPn-** [comment]
I realize this issue is for RedHat 6.6, but I get the same error with configure open-vmware-tools V10.0 for Ubuntu 14.04.  I also noticed the packages pointed to above have a lots of Ubuntu versions but not 14.04.  What is the recommended way to install V10 on Ubuntu 14.04?  With 9.4 I run in the "Error: cannot mount filesystem: No such device" problem when I try to mount a share from the host

**Comment by dyno** [comment]
for newer version of RHEL(7)/SLES(12)/Ubuntu(14), there is the package open-vm-tools in their repository which is recommended.

**Comment by nPn-** [comment]
Thanks for the reply,  I will keep looking but best I can find is 9.4,  if you know of a link for v10 for 14.04, that would be greatly appreciated!

**Comment by syslogic** [comment]
`yum install libmspack-devel` ...while there is a whole bunch of further dependencies.

**Comment by amkeller** [comment]
Hi, I'm having the same error trying to compile open-vm-tools on lubuntu-17.10.1-desktop-amd64
% error: mspack >= 0.0.20040308alpha is required.

I have automake, autoconf, libtools & gettext installed.
1) what is the error & can you explain the solution for lubuntu 17.10?
2) is there a vm for lubuntu that is already set up for VMWare 10?
TIA

**Comment by ravindravmw** [comment]
@amkeller do you have libmspack-dev package installed? Not sure what package manager is used by lubuntu, but you can get it by running "apt-get install -y libmspack-dev" on Ubuntu. If you can't get a pre-built package for libmspack-dev, you may need to build it from the source code yourself.

**Comment by stanguturi** [comment]
> @amkeller do you have libmspack-dev package installed? Not sure what package manager is used by lubuntu, but you can get it by running "apt-get install -y libmspack-dev" on Ubuntu. If you can't get a pre-built package for libmspack-dev, you may need to build it from the source code yourself.

Installing libmspack-devel package in my VM solved the issue. Please note that we need mspack version atleast 0.0.20040308alpha. Otherwise, please use  --enable-deploypkg=no option to disable the deploypkg plugin. 

Closing this issue. Please reopen if you still have any issues even after installing the proper libmspack.

**Comment by jpie726** [comment]
I was able to install to Kali 2021.1 by using the command `./configure --enable-deploypkg=no --without-ssl && make && make install` after acquiring the following dependencies
```libgtkmm-3.0-dev libgtk-3-dev libgdk-pixbuf-xlib-2.0-dev libxtst-dev libxrandr-dev libxrender-dev libxi-dev libxinerama-dev libxext-dev libx11-dev libglib2.0-data libglib2.0-dev libglib2.0-dev-bin libglib2.0-doc libglib2.0-tests libglib2.0-bin libglib2.0-0```
This method should work with other debian-based distributions, but may require more or less packages to be installed

**Comment by gheescoo** [comment]
search for packages containing "messagepack", "msgpack" or something. install them
