### ISSUE TITLE
open-vm-tools reads reverse logic from cloud.cfg file?

### ISSUE THREAD

**Issue by guo1017138** [vmware/open-vm-tools#380]
There is a line in cloud-init 18.5 config file: /etc/cloud/cloud.cfg
 `disable_vmware_customization: false`
From my understanding, that means I should use vmare customization instead of cloud init.

But in open-vm-tools(10.3.x) source code, line 45-74
https://github.com/vmware/open-vm-tools/blob/stable-10.3.x/open-vm-tools/libDeployPkg/linuxDeploymentUtilities.c 

if it matches “disable_vmware_customization: false”, it will be treated as cloud-init is enabled and VMware tool will delegate customization tasks to cloud-init, then mark customization done.

That should be a wrong logic, do you mean that we should match  “disable_vmware_customization: true”?

**Comment by rongz609** [comment]
"disable_vmware_customization: false" means cloud-init enables GOS customization from open-vm-tools, the meaning of the value is from the view of cloud-init. 
In another words, cloud-init accepts parameters from open-vm-tools if the value of this option is 'false', and doesn't accept them if it's 'true'.

From the view of open-vm-tools, it dispatches customization parameters to either cloud-init or the vmware customization engine (which is a group of scripts). 
Cloud-init has higher priority, which means if cloud-init is available and it enables vmware customization, then open-vm-tools will launch cloud-init to complete the customization.

Hope my explanation can help you understand this setting option.

**Comment by guo1017138** [comment]
@rongz609 , Thank you for the detailed explanation. Now it sounds reasonable.

**Comment by stanguturi** [comment]
Thanks @rongz609 for the explanation. Closing this issue.
