### ISSUE TITLE
vmlinuz boot image crashes after first couple reboots from vmware-toolbox-cmd shrink disk on Fedora guest

### ISSUE THREAD

**Issue by hermidalc** [vmware/open-vm-tools#385]
I've actually had this issue for a long time, so multiple versions of open-vm-tools and Fedora guest OS.  After doing a `sudo vmware-toolbox-cmd shrink disk /home` and then rebooting for the first couple reboots or so I will get notifications from Fedora that the vmlinuz boot image crashed.  It will disappear after a couple reboots or so, but I always worry that one time the VM won't ever come up again.  Why is this happening?  I am shrinking only /home not /boot or /.

**Comment by zhoumgh** [comment]
https://pubs.vmware.com/server1/vm/wwhelp/wwhimpl/common/html/wwhelp.htm?context=vm&file=disks_server.7.14.html

Shrinking a disk is a two-step process. In the first step, called wiping, VMware Tools reclaims all unused portions of disk partitions (such as deleted files) and prepares them for shrinking. This allows for the maximum shrink possible. Wiping takes place in the guest operating system.

The shrink process itself is the second step, and it takes place outside the virtual machine. VMware Server reduces the size of the disk based on the disk space reclaimed by the wipe process. This step occurs after the wipe finishes preparing the disk for shrinking.

Note: The shrink process applies to all virtual disks even if you do not prepare all the virtual disks in a virtual machine for shrinking.


Please check Linux journals why it crashes, you may change system setting accordingly, like:

$ sysctl -w kernel.softlockup_panic=0

**Comment by hermidalc** [comment]
Sorry it took a while until I needed a shrink.  So now I've run it exactly as described in my OP and `vmware-toolbox-cmd` automatically does the two-step process you described.  After rebooting the VM and logging into GNOME you immediately get an ABRT notification at the top of the desktop that the vmlinuz boot image crashed and a few kernel-core unexpected system errors in the ABRT app:

![Screenshot from 2020-02-09 12-01-15](https://user-images.githubusercontent.com/461066/74106332-f4c22180-4b33-11ea-89f1-d65e1a1d540b.png)

It looks by the timestamp of the errors (11:36) that they occurred during the shrink process not during reboot (which was at 11:59).  I apologize I was doing something on another computer while it was shrinking and didn't see if the ABRT notifications appeared on the desktop during the shrink.

Attached is the relevant [journalctl.log](https://github.com/vmware/open-vm-tools/files/4177197/journalctl.log)

I know I don't understand the details of what goes on when doing a shrink in the correct way but the problems the kernel appears to have afterward don't look normal.

**Comment by hermidalc** [comment]
I can confirm that the kernel-core system error occur during the shrink command.  When I shrunk another partition I didn't get a ABRT desktop notification but when I opened the app three new error reports, just like before, were generated.

**Comment by hermidalc** [comment]
This issue doesn't exist anymore in recent versions of Fedora and open-vm-tools
