### ISSUE TITLE
Increasing the disk timeout values for a Linux 2.6 virtual machine

### ISSUE THREAD

**Issue by eworm-de** [vmware/open-vm-tools#39]
VMware has a Knowledge Base article about this:
[Increasing the disk timeout values for a Linux 2.6 virtual machine](http://kb.vmware.com/selfservice/microsites/search.do?cmd=displayKC&externalId=1009465)

open-vm-tools should install a similar udev rule.

**Comment by stanguturi** [comment]
> open-vm-tools should install a similar udev rule.

Addressed in commit f069fff44c6d0b7e210cb13aa7de9b6d1003c17b

Check https://github.com/vmware/open-vm-tools/commits/master/open-vm-tools/udev/99-vmware-scsi-udev.rules for the commit history.
