### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [vmware/open-vm-tools#395]
Memory is allocated
https://github.com/vmware/open-vm-tools/blob/9369f1d77fdd90f50b60b44f1ba8c8da00ef55ca/open-vm-tools/lib/rpcChannel/simpleSocket.c#L533
Potential leak of memory pointed to by 'newBuf '
https://github.com/vmware/open-vm-tools/blob/9369f1d77fdd90f50b60b44f1ba8c8da00ef55ca/open-vm-tools/lib/rpcChannel/simpleSocket.c#L552

**Comment by jonathanvmw** [comment]
Thanks for reporting this issue.  Can you provide any additional background?  For example, was this issue reported by a code analysis tool and if so which one?  Was there any additional analysis provided?

At the moment this looks like a false positive.  If the code reaches line 552, it implies the call to **DataMap_SetString** at line 539 was successful; this would attach to _map_ the storage pointed to by _newBuf_.  The call to **DataMap_Destroy** at line 551 would then free that storage as part of freeing _map_.

**Comment by QiAnXinCodeSafe** [comment]
Hi，Thank you for your quickly feedback, This issue found by our own symbolic-execution-based static analyzer.
