### ISSUE TITLE
after make install, no services or modules are launched

### ISSUE THREAD

**Issue by sarcarx** [vmware/open-vm-tools#4]
Hi,

This is the first time i am using openvm tools, i would like to install them from compiling. I patched the code source from git to match my kernel, and started make install which work perfectly without a mistake, then used ldconfig to resolve library paths. But when i reboot, i cannot find processes of vmtoolsd, nor launched kernel modules, i tried to add vmtoolsd to init.d script but this process doesn't seem to do anything.
For exemple i tried to activate the log feature but without any services, i doubt changing the config file will do anything.
What should i do to use the general features of open-vm-tools ? i am a little lost.

**Comment by oliverkurth** [comment]
Hi sarcarx,
unfortunately there is no startup script in in open-vm-tools. Different Linux distributions use different init systems and init scripts.

Kernel modules are mostly provided by the kernel package, with the exception of vmhgfs. Without an init script, you will need to load that one manually. With vmtoolsd running as root, you should be able to do guest operations, like for example shutting down cleanly, or use vmrun in the host (if you use WS/Fusion). When you run 'vmtoolsd -n vmusr' as a regular user while running a graphical display, you should be able to do copy/paste and drag and drop. Let me know what you expect from tools.

Which Linux distribution are you using? If you use RHEL7, Ubuntu, Debian or SLE 12 it may be easier for you to install the open-vm-tools package from the distribution vendor. But let me know, and I may be able to give more detailed help.

**Comment by sarcarx** [comment]
Hi,

Thanks for answering.
I am working in Ubuntu 14.04, without graphical display, I actually don't need kernel modules or x support.
I have compiled and launched the vmtoolsd program. What i want to achieve is using vmtoolsd with ESXi to monitor a running VM, but without compiling or installing what i don't need (resolution set is not really needed).
I have succeded in installing a without kernel modules and without x version of vmtoolsd, but i will need the guest info part, will it work? What are the sections I need to install to achieve my goal?

**Comment by oliverkurth** [comment]
I think if you are running Ubuntu 14.04, the best way to install open-vm-tools is to use the open-vm-tools package, it should have all you need. The x support is in the package open-vm-tools-desktop, so you don't need to install that. It also doesn't include the kernel modules.

You can enable logging by following these instructions: http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1007873

It's written for the legacy vmware tools, but works for open-vm-tools just as well.

**Comment by sarcarx** [comment]
I have followed the steps you suggested to try and i have the same error, even with the built-in version of vmware-tools : the logging system cannot find the file vmbackup.vmsg in the catalog. But it does responds to a snapshot try. Any idea ?

**Comment by dyno** [comment]
there are several levels of consistency. 
* the normal snapshot with memory will have the full picture of the time when things stop, when resume vm will have all the relevant information to resume running. 
* and if you take the snapshot without memory then all the run time information will lost, you got something called "crash consistency".
* vmbackup is something in between, so that vm knows we are taking a snapshot, it should do some checkpoint, (flush the cache, etc). it's called "application consistency". basically, it tells the vm that a snapshot will take place, donnot write to disk.

**Comment by sarcarx** [comment]
So in theory the only snapshot I should be able to see from the guest, are the one taken with support of vmware tools? (is that what quiesce is?).
I noticed snapshot references in the Vix part of vmware tools, would that allow me to capture the other snapshots event?

**Comment by dyno** [comment]
do you mean VixIOFreeze()?  that is trying to make VIX cooperate with quiesced snapshot so that it won't result in a deadlock. it's a little bit complicated, because tools main process is single-threaded event loop.
1. host tells tools a quiesced snapshot is taking, so freeze disk io.
2. if vix command comes in and trying to access the disk, the command will be waiting for io.
3. because of 2, tools will not be able to response to unfreeze disk io and result deadlock and VM hang. 

other than quiesced snapshot, i don't think tools has any direct involvement in the snapshot process in general. but it will be notified to do some sync operation like sync time, after checkpoint resume (snapshot, migration, etc)

**Comment by sarcarx** [comment]
Ok i got that, I have another question concerning the code, I have explored in order to understand deeper the communication between the host and the guest (Rpc, message and backdoor). From what I understand it all leads to the asm code :
   __asm__ __volatile__(
        "pushq %%rax"           "\n\t"
        "movq 40(%%rax), %%rdi" "\n\t"
        "movq 32(%%rax), %%rsi" "\n\t"
        "movq 24(%%rax), %%rdx" "\n\t"
        "movq 16(%%rax), %%rcx" "\n\t"
        "movq  8(%%rax), %%rbx" "\n\t"
        "movq   (%%rax), %%rax" "\n\t"
        "inl %%dx, %%eax"       "\n\t"  /* NB: There is no inq instruction */
        "xchgq %%rax, (%%rsp)"  "\n\t"
        "movq %%rdi, 40(%%rax)" "\n\t"
        "movq %%rsi, 32(%%rax)" "\n\t"
        "movq %%rdx, 24(%%rax)" "\n\t"
        "movq %%rcx, 16(%%rax)" "\n\t"
        "movq %%rbx,  8(%%rax)" "\n\t"
        "popq          (%%rax)" "\n\t"
      : "=a" (dummy)
      : "0" (myBp)
      : "rcx", "rdx", "rsi", "rdi", "memory"
   );
(without the MacOs part), it looks like a (that should contain the data) is not used, how is this code getting the message we want to send? why isn't the variable "a" used in the code?
If you could explain that to me it would be great.
Also what is triggered on the host part, I understand that inl and xchgq are the magic words but is there a way I can understand the interaction between those and the host?

**Comment by dyno** [comment]
https://sites.google.com/site/chitchatvmback/backdoor has the best explanation.

**Comment by dyno** [comment]
for the guest it's just port-mapped IO, and for the backend implementation on host is just a special device (think VGA device).

**Comment by sarcarx** [comment]
Sorry to bother you but I have another question in mind, When I am using open vmware tools, the message in Vsphere is not vmware tools installed but "3rd-party/Independent", I was wondering, what is the minimum plugin/service/code just to show the independent message, and what makes the difference between 3rd-paty and the official message?

**Comment by dyno** [comment]
"3rd-party/Independent" now is "GuestManaged" in the newer release to clear any confusion. we do support open-vm-tools.
check https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/services/vmtoolsd/toolsRpc.c#L133
```c
#if defined(OPEN_VM_TOOLS)
      version = TOOLS_VERSION_UNMANAGED;
```

IP addresses is from guestInfo plugin. if it is removed, there should be no ip address send to VMware. power off/on the vm and see if the ip address is still there or not.
https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/services/plugins/guestInfo/guestInfoServer.c#L304

**Comment by sarcarx** [comment]
Ok, concerning the IP problem, what I did is that I changed the code from https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/services/vmtoolsd/mainLoop.c#L197.
I simply deleted the line of loading the plugins and added a 
<code>
ToolsCore_DumpPluginInfo(state);
</code>
to check wheter the plugins are loaded and it does print
[ message] [vmtoolsd]    No plugins loaded.
Is there anywhere else in the code of vmtoolsd where the plugins are loaded?

**Comment by sarcarx** [comment]
I tried producing a .deb with open-vm-tools using dpkg -rfakeroot -b, when I install the .deb produced the scripts are not installed but vmtools is and works fine, is there a way to include the scripts install in the .deb ?
