### ISSUE TITLE
upgrade warning again for vmtoolsd.service

### ISSUE THREAD

**Issue by tuxedotje** [vmware/open-vm-tools#405]
At upgrade (dnf upgrade) this comment:
  Running scriptlet: open-vm-tools-11.0.0-4.fc31.x86_64                   17/20 
Warning: The unit file, source configuration file or drop-ins of vmtoolsd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of vgauthd.service changed on disk. Run 'systemctl daemon-reload' to reload units.

on Fedroa 31

**Comment by ravindravmw** [comment]
What package version did you upgrade from? Also, packaging issues are tracked on bugzilla.redhat,com. Could you please create a bug there?

**Comment by stanguturi** [comment]
> What package version did you upgrade from? Also, packaging issues are tracked on bugzilla.redhat,com. Could you please create a bug there?

As @ravindravmw mentioned, please create a bug with redhat. This is not a open-vm-tools issue. Closing. Thanks.
