### ISSUE TITLE
How to get sound from VM

### ISSUE THREAD

**Issue by amittrivedinew** [vmware/open-vm-tools#406]
Hi
We are using VCSA 6.7 with five esxi 6.7 hosts & multiple vms are are running inside the esxi hosts.
I have no Sound card installed on Esxi hosts but we need Sound from VMs. Can we do that? Please let me know if possible. It will highly appreciable for the earliest response.

Thank in advance

**Comment by amittrivedinew** [comment]
Hi
Looking for your kind response

**Comment by amittrivedinew** [comment]
Please Do the needful by providing your inputs to fix the issue

**Comment by oliverkurth** [comment]
Sorry for the late reply. I am trying to find the right team to address this.

**Comment by oliverkurth** [comment]
Relaying an answer from a developer. I hope that helps:

Ah, you should just be able to add the sound card in the UI, and then if you're using our VMRC console, we remote the audio.

If you're not using our consoles, then it depends what you're remoting application/protocol is.  But if it supports audio remoting then presumably it should work.  (I'll bet many remoting applications would work even without the VM having a sound-card to be honest.)

**Comment by amittrivedinew** [comment]
Thanks for you kind response.
I would like to update you that we do not have to use "VMRC" . It will be more appreciable if you could able to suggest application\Protocol that i can use to get the sound from the vm.

**Comment by oliverkurth** [comment]
This is not really an issue related to open-vm-tools. You may get better responses here: https://communities.vmware.com/community/vmtn/content .

**Comment by stanguturi** [comment]
> This is not really an issue related to open-vm-tools. You may get better responses here: https://communities.vmware.com/community/vmtn/content .

Thanks @oliverkurth Please try the channels mentioned above.
