### ISSUE TITLE
configure: error: rpcgen not found

### ISSUE THREAD

**Issue by micchickenburger** [vmware/open-vm-tools#407]
Hello,

I've just compiled LFS 9.1-systemd-rc1, Linux 5.5.3 with glibc 2.31.  The open-vm-tools configure failed because it cannot find `rpcgen`.  After a ton of research I discovered that `rpcgen` is part of the obsolete rpc code in glibc.  It was deprecated in 2012 (2.16) according to [these release notes](https://savannah.gnu.org/forum/forum.php?forum_id=7288):

> New configure option --enable-obsolete-rpc makes the deprecated RPC
  headers and functions available at compile time as they were before 
  version 2.14.  This option will be removed at some time in the future 
  after the TI-RPC library becomes fully sufficient for the needs of 
  existing applications. 

I validated that the missing `rpcgen` program is compiled when that flag is set per [these notes](https://lwn.net/Articles/729774/):

> Sun RPC is deprecated.  The **rpcgen** program, librpcsvc, and Sun RPC headers
  will only be built and installed when the GNU C Library is configured with
  --enable-obsolete-rpc.  This allows alternative RPC implementations, such
  as TIRPC or rpcsvc-proto, to be used.

Note how `TIRPC` replaces `rpcgen` and that open-vm-tools needs that library anyway.  So why is there a requirement for both?  I'd really rather not have to recompile glibc to support this deprecated library...

Thanks :)

**Comment by oliverkurth** [comment]
As you have noted, open-vm-tools links with tirpc. However, we still need the rpcgen binary for building. There is no need for the rpcgen binary for running open-vm-tools.

However, I think I see the problem with LFS - you'd still need to use the flag to build libc so you get the rpcgen binary. I tried to find out if there is a replacement, and it looks like rpcsvc-proto might be an option, see http://www.linuxfromscratch.org/blfs/view/svn/basicnet/rpcsvc-proto.html and https://github.com/thkukuk/rpcsvc-proto . Please let us know if this works for you.

**Comment by stanguturi** [comment]
Please check @oliverkurth suggestions mentioned in the earlier post. Please reopen if it doesn't work. Thanks.

**Comment by micchickenburger** [comment]
Thanks for the advice and apologies for not returning earlier.  I recompiled glibc with this flag, but did not do a `make install`.  Instead I only copied the `rpcgen` binary to `/usr/bin` and the tools were then able to compile successfully.

**Comment by 24unix** [comment]
Just as an info, if some, like me, finds this issue via search:

 rpcsvc-proto is sufficient and build faster than a new glibc.
