### ISSUE TITLE
configure: error: mspack >= 0.0.20040308alpha is required.

### ISSUE THREAD

**Issue by huazai177** [vmware/open-vm-tools#41]
I am trying to run ./configure for open-vm-tools in debian 8.1，but I get the error:
configure: error: mspack >= 0.0.20040308alpha is required.

libmspack0:amd64  and libmspack-dev:amd64 0.5-1 is installed

**Comment by oliverkurth** [comment]
Do you have pkg-config installed?

Try this:
apt-get install pkg-config

**Comment by huazai177** [comment]
thanks, that's work!
