### ISSUE TITLE
/usr/bin/install: cannot create regular file '/usr/local/lib/libvmtools.so.0.0.0': Permission denied

### ISSUE THREAD

**Issue by Coderx7** [vmware/open-vm-tools#410]
I'm trying to install this on ubuntu 18.04 and I',m facing this error :
```
make[2]: Entering directory '/home/hossein/Downloads/open-vm-tools-11.0.5-15389592/lib'
make[3]: Entering directory '/home/hossein/Downloads/open-vm-tools-11.0.5-15389592/lib'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/hossein/Downloads/open-vm-tools-11.0.5-15389592/lib'
make[2]: Leaving directory '/home/hossein/Downloads/open-vm-tools-11.0.5-15389592/lib'
make[1]: Leaving directory '/home/hossein/Downloads/open-vm-tools-11.0.5-15389592/lib'
Making install in libvmtools
make[1]: Entering directory '/home/hossein/Downloads/open-vm-tools-11.0.5-15389592/libvmtools'
make[2]: Entering directory '/home/hossein/Downloads/open-vm-tools-11.0.5-15389592/libvmtools'
test -z "/usr/local/lib" || /bin/mkdir -p "/usr/local/lib"
 /bin/bash ../libtool --mode=install /usr/bin/install -c  'libvmtools.la' '/usr/local/lib/libvmtools.la'
libtool: install: /usr/bin/install -c .libs/libvmtools.so.0.0.0 /usr/local/lib/libvmtools.so.0.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libvmtools.so.0.0.0': Permission denied
Makefile:408: recipe for target 'install-libLTLIBRARIES' failed
make[2]: *** [install-libLTLIBRARIES] Error 1
make[2]: Leaving directory '/home/hossein/Downloads/open-vm-tools-11.0.5-15389592/libvmtools'
Makefile:630: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/hossein/Downloads/open-vm-tools-11.0.5-15389592/libvmtools'
Makefile:398: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

```
I also tried 
```
 sudo ./configure; make; make install
```
to no avail. make clean and starting again didnt help either! 
How should I go about this?

**Comment by johnwvmw** [comment]
Off hand, I would expect that the "sudo" applied only to the "./configure" command.  The make and install are being done as the non-root user and therefore may be prevented from installing into /usr/local/lib  ??

Check the ownership of the .libs/libvmtools.so.0.0.0 being installed.

**Comment by johnwvmw** [comment]
The ./configure and make can be done as any user, but the "make install" should be done as root.

**Comment by johnwvmw** [comment]
Closing this issue.   Please re-open if additional problems arise.

**Comment by johnwvmw** [comment]
Actually, you should not do every stage of an open-vm-tools builds as "root".

The "autoreconf", "./configure" and the "make" should be done as a non-privileged user.  Notice that this is a simple "make" and not a "make install" command.   The "make" will compile the open-vm-tools source.

The "make install" will place the built executables and libraries in a directory tree in the relative position they would or could be installed on the system.   Linux vendors and open-vm-tools maintainers do the "make install" placing the open-vmtools files into a directory from which open-vm-tools packages can be assembled.   This is also done as a "normal" user.  The built open-vm-tools packages can be installed on any system by a system administrator

If the "make install" is to be used to actually install the compiled open-vm-tools onto the system on which it was built, that step must be done as the system administrator.

Only that "make install" need be done as "root" when installing newly built tools onto the same system.

Alternatively, you can place the separate steps into a shell script and execute that script with "sudo".   This is not something that I would recommend, however.
