### ISSUE TITLE
Drag and drop files and copy/paste files not working on Centos 8.1

### ISSUE THREAD

**Issue by jguizarj** [vmware/open-vm-tools#411]
Today I've installed CentOS 8 (build 1911) with Desktop with a GUI installation template.

The first thing I did, was opening the terminal and executing the following command to update the O.S. packages:
`sudo dnf update -y`

The O.S. had already open-vm-tools and open-vm-tools-desktop preinstalled. The actual open-vm-tools version of my O.S. is:
![image](https://user-images.githubusercontent.com/53882278/76564797-ec307400-646e-11ea-8a72-e8bff9eaf8af.png)

Drag and drop funcionallity is not  working at all with files, copy/paste is only working with text, and copying files from guest O.S to host O.S. I'll attach a video showing my problem

[Video](https://youtu.be/Un5Fflmjgfk)

**Comment by oliverkurth** [comment]
We have a kb article that has some instructions, please see https://kb.vmware.com/s/article/74671 .

We are working on fixing this in future packages for RHEL/CentOS.

**Comment by jguizarj** [comment]
It didn't worked :(

I did all the instructions in the kb aricle, now when I execute the command
`sudo systemctl status run-vmblock\\x2dfuse.mount`

I get the output:

>    Loaded: loaded (/etc/systemd/system/run-vmblock\x2dfuse.mount; enabled; vendor preset: disabled)
   Active: active (mounted) since Thu 2020-03-12 15:49:59 CST; 2min 52s ago
    Where: /run/vmblock-fuse
     What: vmware-vmblock
     Docs: https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/vmblock-fuse/design.txt
    Tasks: 3 (limit: 23832)
   Memory: 5.2M
   CGroup: /system.slice/run-vmblock\x2dfuse.mount
           └─965 vmware-vmblock-fuse /run/vmblock-fuse -o rw,subtype=vmware-vmblock,default_permissions,allow_other,dev,suid

**Comment by oliverkurth** [comment]
Hm. The status looks good, so the issue must be somewhere else.

Did you follow all the other steps?
- did you reboot/ log out of X and in again?
- is the setuid bit set for `/usr/bin/vmware-user-suid-wrapper` ?

Note that drag/drop doesn't work with Wayland. So you need to set the session to 'X11' or "classic'.

**Comment by jguizarj** [comment]
It was de gnome session! 

Thank you very much for your assistance! 👍
