### ISSUE TITLE
VMware Player 15.5.2 fails to start newly created vm (aborts in hostinfoPosix.c)

### ISSUE THREAD

**Issue by mamrhein** [vmware/open-vm-tools#415]
VMware Player Error:
VMware Player unrecoverable error: (vmplayer)
VERIFY bora/lib/misc/hostinfoPosix.c:2455

OS: Gentoo (2.6)
Kernel: 5.5.10

**Comment by mamrhein** [comment]
[vmware-vmplayer-7680.log](https://github.com/vmware/open-vm-tools/files/4398413/vmware-vmplayer-7680.log)

**Comment by lemke1458** [comment]
This isn't an open-vm-tools issue; you may have better luck on message boards dealing with Player or Worktation.  I've asked the Player team to take a look.

**Comment by ravindravmw** [comment]
For issues unrelated to open-vm-tools, VMTN (https://communities.vmware.com) or VMware Support would be better resources.

**Comment by stanguturi** [comment]
Please log a bug in the VMTN WS/player community as mentioned above. Not an open-VM-tools issue. Closing. Thanks
