### ISSUE TITLE
Build failure on arm64 for 'open-vm-tools' package

### ISSUE THREAD

**Issue by odidev** [vmware/open-vm-tools#416]
While building open-vm-tools package on arm64 platform, I am facing build failure and there is some incomplete code under 'VM_ARM_64'. May I know why the development for adding arm64 support was stopped in between? Will the changes be accepted for adding arm64 support if I raise PR for the same?

**Comment by stanguturi** [comment]
What is the exact error that you encountered? Can you provide the build log file?

**Comment by stanguturi** [comment]
Which branch are you using to build OVT.

You can use stable-11.1.x branch to build OVT on arm64. If you have the old configure files around, please rerun autoreconf first.

**Comment by stanguturi** [comment]
Today, we have pushed a fix in 32df621461ca3f7f7188763be0f3b269b71b87cb in devel branch. If you building on devel branch, make sure you pull the latest changes. Let us know the results.

**Comment by odidev** [comment]
We were trying to run OVT on Alpine and the version available over there was 11.0.5. Updated the version to 11.1-x in the package and the build was successful. :)

**Comment by stanguturi** [comment]
> We were trying to run OVT on Alpine and the version available over there was 11.0.5. Updated the version to 11.1-x in the package and the build was successful. :)

Thanks for the update. Closing this issue.
