### ISSUE TITLE
3D Graphics Acceleration causes gnome window display issues in Fedora 31

### ISSUE THREAD

**Issue by jdmac87** [vmware/open-vm-tools#417]
**Host:** Windows 10 (1909 build 18363.752)
**Product:** VMWare Workstation 15.5.2 build-15785246
**Guest:** Fedora 31 with latest updates from repositories.
**open-vm-tools:** open-vm-tools-desktop-11.0.5-3.fc31.x86_64

Please note  before continuing, that I have already read through:
- https://bugzilla.redhat.com/show_bug.cgi?id=1803819
- https://github.com/vmware/open-vm-tools/issues/400 3D graphics acceleration causes GNOME window display issues in Fedora 31

I have commented on 1803819 where Thomas Hellström had commented to suggest it is not the same issue.
Therefore I'm logging a new and separate issue as a user of VMWare products to try to remedy my issue as it's now been sometime since it broke and prevents me using the product correctly.

I cannot attempt to revert prior to mesa 19.2 as per suggest on #400 and can't upgrade past it on Fedora 31.
Having said that, even on Fedora 32 beta which uses mesa 20.0 (mesa-dri-drivers-20.0.0-1.fc32.x86_64) the issue is still present.

**Details of issue:**
Whilst 3D graphics acceleration is enabled on my VM and I'm using gnome (wayland) certain applications seem to artifact.

![2020-04-11 00_37_13](https://user-images.githubusercontent.com/16666676/79029606-f6887f80-7b8c-11ea-9800-f31d90f8371d.png)

As per the screenshot, the application in the upper left is Google Chrome and the lower right is JetBrains GoLand (same with most of their IDEs, phpstorm for example).

My native resolution of 2560x1440. However, this is without even making the VM enter full screen mode.

My only 'workaround' is to disable 3D accelerated graphics or use x11.
Both of which graphically perform well under expectations come to be set VMware workstation.

**Comment by jdmac87** [comment]
Only suitable workaround at the moment is for me to go to a kernel older than 5.5 from the Fedora 31 repository.

At time of writing, 5.3.7-301 is the version that has worked for me.

Downloaded a fresh Fedora 32 - VMware acceleration seems to experience the same troubles still during the installer, however after patching everything post-install, I've found kernel 5.6.4 and mesa 20.0.0-4 installed. The problem seems not reproducible there.

My personal plan, if anyone wishes to copy. Continue on Fedora 31 with Kernel 5.3.7 until such time Fedora 32 is released and upgrade then.

Suspect something isn't quite working correctly in Kernel 5.5 (at least under Fedora distro) and VMware 3d acceleration, but I've currently not got availability to be sifting through kernel commits and picking apart how they fit in with open-vm-tools / vmware 3d acceleration.

**Comment by hermidalc** [comment]
Hi @jdmac87 - what's weird is I have the exact same setup as you, latest Windows 10 host, latest VMware Workstation Pro, full updated Fedora 31 guest, open-vm-tools, I'm on the latest kernel 5.5.17 and do not experience display artifacts you are having, with 3D acceleration or without.

The only issue I have is the known one from my #400

Just so it's clear to me, you are experiencing the artifact you've shown above on kernel 5.5.x even with 3D acceleration turned off?

**Comment by jdmac87** [comment]
Hi @hermidalc,

Issue occurs only with **3D Acceleration turned on**.
Three different host systems have shown me the exact same situation.

It's most noticeable if I use JetBrains IDEA basic IDE tools, for example PyCharm.
I've also seen it occur in Google Chrome.

Host #1:
Windows 10 1909 (with retrospective patches kept up to date).
AMD 3900X / 32GB RAM / Nvidia RTX 2080

Host #2 (Laptop):
Windows 10 1909 (with retrospective patches kept up to date).
Intel i7 6700HQ / 16GB RAM / Discrete graphics - Nvidia GTX 965m

Host #3 (Laptop):
Windows 10 1909 (with retrospective patches kept up to date).
Intel i7 8750H / 40GB RAM / Discrete graphics - Nvidia Quadro P1000

My work around has so far worked on Host 1 and 3, with respect to the fact I haven't needed use of Host 2 recently so therefore haven't yet tested.

**Comment by hermidalc** [comment]
Sorry I'm confused, I don't see what the problem is.  Why don't you just keep 3D acceleration turned on, keep latest Fedora 31 kernel 5.5.17, and

1.  `sudo dnf downgrade "mesa-*"`
2.  `sudo echo 'excludepkgs=mesa-*' >> /etc/dnf/dnf.conf`

Wait for Fedora 32 to come out and when it does just remove the excludepkgs line from `/etc/dnf/dnf.conf` and then upgrade Fedora?

**Comment by hermidalc** [comment]
If you are running mesa 19.0.2 (which is the downgrade version available on Fedora below broken 19.2.8) then you should have no problems with 3D acceleration or using latest kernel 5.5.x

**Comment by jdmac87** [comment]
@hermidalc - Not sure what your confusion over what has been explained is, but feel free to ask questions to clarify.

Please note, the oldest mesa available on Fedora 31 repos is from "fedora" and is 19.2.0-1.fc31
There is no 19.0.2 available.

I've also already attempted to downgrade to 19.2.0-1 from 19.2.8-1 and the issue is still present.

**Comment by jdmac87** [comment]
Just to provide detail showing the issue with the 'solution' you've suggested:

![2020-04-21 18_24_20-Window](https://user-images.githubusercontent.com/16666676/79894429-5983dd00-83fd-11ea-9b72-deeafc0b8688.png)

**Comment by jdmac87** [comment]
I think with the soon to be released Fedora 32 (running Kernel 5.6) showing better results, I'm personally just going to stick on Kernel 5.3 on Fedora 31 in the meantime as that seems to work for me. :)

I appreciate your responses though @hermidalc

**Comment by hermidalc** [comment]
@jdmac87 no no it's totally my fault, apologies see I've had 3D acceleration turned off for some time due to #400 (I just didn't bother to downgrade mesa) and when I tested my solution above with latest kernel, 3D acceleration on, and mesa pinned to 19.2.0 I didn't see any artifact issue with Wayland native apps.  But I am now seeing your exact same artifact issue with [Atom](https://atom.io/)which is an XWayland app. Are you seeing this issue only with XWayland apps and not native Wayland apps?

**Comment by jdmac87** [comment]
Ok, that's interesting. Knowing what apps are Wayland Native and XWayland is something I've struggled to find a clear answer on.

How would you confirm if an app is XWayland or native?

**Comment by hermidalc** [comment]
> 
> 
> Ok, that's interesting. Knowing what apps are Wayland Native and XWayland is something I've struggled to find a clear answer on.
> 
> How would you confirm if an app is XWayland or native?
> 
> I suspect they are XWayland apps but then I _thought_ I read somewhere Chrome is now native. I'm unsure without checking though

GNOME apps are definitely native. So if you are seeing the artifact issue with any GNOME apps tell me.  For other apps I've really just Googled and searched if they are XWayland or not.  I just know that Atom is XWayland and it's the only app so far where I can reproduce your artifact issue exactly.

Maybe this works https://medium.com/@bugaevc/how-to-easily-determine-if-an-app-runs-on-xwayland-or-on-wayland-natively-8191b506ab9a

**Comment by hermidalc** [comment]
@jdmac87 do you think it's good to re-open this issue? I can reproduce your exact problem I've tested it enough and it's real.  For me the artifacts appear so far on XWayland app windows but I have to use them for a few minutes before suddenly they appear.

@thomashvmw I've been able to reproduce the graphics issue 

Latest Windows 10 host
Latest Fedora 31 guest, open-vm-tools, and kernel currently at 5.5.17
3D acceleration on
mesa-* pinned to 19.2.0 to avoid #400 
Open and run an XWayland app window (like [Atom](https://atom.io/) and after a few minutes of use the artifact issue suddenly appears and the window is all garbled.

**Comment by thomashvmw** [comment]
This issue has been identified as a bug in a new feature in the mesa svga driver (ARB_buffer_storage) that is only enabled with kernel 5.5 and above. 

The fix is mesa commit 46fdc288fb ("svga, winsys/svga: Fix persistent memory discard maps"). The fix has been backported and released with mesa 20.0.3 and 20.0.4. 

Unfortunately, it doesn't seem, again, like distros maintain mesa branches that has reached EOL. I see that Fedora 32 has mesa 20.0.4.

So workarounds are to use a kernel < 5.4, or Xorg instead of Wayland, or if you're desperate, use the attached rpms which replaces fedora 31's original with patches for #400 and #417

[rpms.zip](https://github.com/vmware/open-vm-tools/files/4512633/rpms.zip)

Instructions: 
Update fedora 31 and verify that you have mesa version 19.2.8-1.fc31
Download and unzip the rpms.zip file in a separate directory
cd to that directory and run "sudo rpm -Uvh *.rpm"

Reboot, and that should do it. If fedora decides to update mesa, then hopefully the fixes would be included and everything should continue to work.

**Comment by hermidalc** [comment]
Thanks @thomashvmw very much for the timely response with the info and detail explanation

**Comment by jdmac87** [comment]
Excellent, thanks for your efforts reproducing @hermidalc.
Thank you @thomashvmw for sharing that detail and rpms.
I'm glad the issues aren't a completely separate case meaning we can tie up the loose ends.

It also makes sense to me that fedora 32 works after pulling latest updates as mesa 20.0.4 is included. However, unless the beta differs when released, the anaconda setup still seems to use older 20.0.x. 

Presuming Fedora 32 gets released on same as beta, then easier to work around that though as just install Fedora 32 without 3d acceleration.

**Comment by hermidalc** [comment]
@thomashvmw @jdmac87 so far so good on Fedora 32 guest with 3D acceleration

**Comment by jdmac87** [comment]
Absolutely, good here. They shipped the iso with mesa-20.0.4 and have also
got 20.0.5 in repos. All seems good.

Thanks.
