### ISSUE TITLE
Open-vm-tools recustomizes VM on VCD reboot

### ISSUE THREAD

**Issue by RuchikaChugh1** [vmware/open-vm-tools#420]
open-vm-tools-10.3.0-2.el7_7.1.x86_64,NFV 1.5 is based on ESXi 6.0 U2, VCD 8.20. VMs are based on RHEL 7.2
Reboot of VMs is done through VCD. After this reboot most of the times ( not everytime) , the customization of VM begins by itself and the custom guest customization scripts do not come into picture. Rather we see, libdeploypackage being called which removes specific guest customization done by our product.

As we can see below, the customization  which our project sets is overwritten.

_2020-04-17T08:57:40.864Z] [    info] Original deployment command: /usr/bin/perl -I/tmp/.vmware/linux/deploy/scripts /tmp/.vmware/linux/deploy/scripts/Customize.pl /tmp/.vmware/linux/deploy/cust.cfg

[2020-04-17T08:57:40.864Z] [    info] Actual deployment command: /usr/bin/perl -I/tmp/.vmware-imgcust-d8uTOpL/scripts /tmp/.vmware-imgcust-d8uTOpL/scripts/Customize.pl /tmp/.vmware-imgcust-d8uTOpL/cust.cfg_
...
...
2020-04-17T08:57:43.490Z] [    info] Customization command output: INFO: Opening file name /tmp/.vmware-imgcust-d8uTOpL/cust.cfg. 
DEBUG: Processing line: '[NETWORK]' 
DEBUG: FOUND CATEGORY = NETWORK 
DEBUG: Processing line: 'NETWORKING = yes' 
DEBUG: ADDED KEY-VAL :: 'NETWORK|NETWORKING' = 'yes' 
DEBUG: Processing line: 'BOOTPROTO = dhcp' 
DEBUG: ADDED KEY-VAL :: 'NETWORK|BOOTPROTO' = 'dhcp' 
DEBUG: Processing line: 'HOSTNAME = SPS-OAME-002' 
DEBUG: ADDED KEY-VAL :: 'NETWORK|HOSTNAME' = 'SPS-OAME-002' 
..
...
DEBUG: Exit Code: 0 
DEBUG: opening file /etc/sysconfig/network. 
DEBUG: Line : NETWORKING=yes
 
DEBUG: Line : NETWORKING_IPV6=yes
 
DEBUG: Line : HOSTNAME=ts8spss-oame-0
 
INFO: GATEWAYDEV not found, created with eth1 
INFO: GATEWAY not found 
INFO: Created with 172.29.49.193 
DEBUG: opening file for writing (/etc/sysconfig/network). 
DEBUG: Command: 'chmod 644 /etc/sysconfig/network' 
DEBUG: Result:  
DEBUG: Exit Code: 0 
DEBUG: Command: 'hostname SPS-OAME-002' 
DEBUG: Result:  
DEBUG: Exit Code: 0 
DEBUG: opening file for writing (/etc/hostname). 
DEBUG: Command: 'chmod 644 /etc/hostname' 
DEBUG: Result:  
DEBUG: Exit Code: 0 
INFO: Customizing NICS ...

**Comment by vmwzhangv** [comment]
Are you saying the customization run by the libdeploypackage was not intended ?  

"the customization which our project sets is overwritten" How did your project set the guest customization before the VM reboot ?

**Comment by RuchikaChugh1** [comment]
> Are you saying the customization run by the libdeploypackage was not intended ?
> 
> "the customization which our project sets is overwritten" How did your project set the guest customization before the VM reboot ?

The lideployPkg customization is NOT intended at reboot of the VM (does not happen always but sometimes, condition is not known) . The first time VM was deployed , a project specific post customization script was used in guest customization of the VM and this ensured correct settings on the VM. However, the VM reboot has overwritten that.

**Comment by vmwzhangv** [comment]
How do you customize the VM ? Are you using a vsphere UI client to do so ?

When customizing a VM through vsphere UI, the VM needs to be powered off and powered back on. The actual customization takes place when the VM is powered back on.

**Comment by RuchikaChugh1** [comment]
The VM customization is done through Vcloud Director, there is a section of Guest Customization in the custom script, this is done when the Vm is first powered on. The script just has to be put in tehre and teh VCD takes care of the rest.  This script is not triggered again during the lifetime of the VM.

**Comment by vmwzhangv** [comment]
This should not happen. A guest customization is expected only run once at the power on time, and clean up.  A secondary reboot should not trigger any re-customization. I shall ping our guest customization teams and ask them to help investigate. Please provide additional logs if you have to show the time sequence of at what time the initial guest customization, at what time guest reboot and at what time the re-customzation.

**Comment by rongz609** [comment]
> open-vm-tools-10.3.0-2.el7_7.1.x86_64,NFV 1.5 is based on ESXi 6.0 U2, VCD 8.20. VMs are based on RHEL 7.2
> Reboot of VMs is done through VCD. After this reboot most of the times ( not everytime) , the customization of VM begins by itself and the custom guest customization scripts do not come into picture. Rather we see, libdeploypackage being called which removes specific guest customization done by our product.
> 
> As we can see below, the customization which our project sets is overwritten.
> 
> _2020-04-17T08:57:40.864Z] [ info] Original deployment command: /usr/bin/perl -I/tmp/.vmware/linux/deploy/scripts /tmp/.vmware/linux/deploy/scripts/Customize.pl /tmp/.vmware/linux/deploy/cust.cfg
> 
> [2020-04-17T08:57:40.864Z] [ info] Actual deployment command: /usr/bin/perl -I/tmp/.vmware-imgcust-d8uTOpL/scripts /tmp/.vmware-imgcust-d8uTOpL/scripts/Customize.pl /tmp/.vmware-imgcust-d8uTOpL/cust.cfg_
> ...
> ...
> 2020-04-17T08:57:43.490Z] [ info] Customization command output: INFO: Opening file name /tmp/.vmware-imgcust-d8uTOpL/cust.cfg.
> DEBUG: Processing line: '[NETWORK]'
> DEBUG: FOUND CATEGORY = NETWORK
> DEBUG: Processing line: 'NETWORKING = yes'
> DEBUG: ADDED KEY-VAL :: 'NETWORK|NETWORKING' = 'yes'
> DEBUG: Processing line: 'BOOTPROTO = dhcp'
> DEBUG: ADDED KEY-VAL :: 'NETWORK|BOOTPROTO' = 'dhcp'
> DEBUG: Processing line: 'HOSTNAME = SPS-OAME-002'
> DEBUG: ADDED KEY-VAL :: 'NETWORK|HOSTNAME' = 'SPS-OAME-002'
> ..
> ...
> DEBUG: Exit Code: 0
> DEBUG: opening file /etc/sysconfig/network.
> DEBUG: Line : NETWORKING=yes
> 
> DEBUG: Line : NETWORKING_IPV6=yes
> 
> DEBUG: Line : HOSTNAME=ts8spss-oame-0
> 
> INFO: GATEWAYDEV not found, created with eth1
> INFO: GATEWAY not found
> INFO: Created with 172.29.49.193
> DEBUG: opening file for writing (/etc/sysconfig/network).
> DEBUG: Command: 'chmod 644 /etc/sysconfig/network'
> DEBUG: Result:
> DEBUG: Exit Code: 0
> DEBUG: Command: 'hostname SPS-OAME-002'
> DEBUG: Result:
> DEBUG: Exit Code: 0
> DEBUG: opening file for writing (/etc/hostname).
> DEBUG: Command: 'chmod 644 /etc/hostname'
> DEBUG: Result:
> DEBUG: Exit Code: 0
> INFO: Customizing NICS ...

According to your description, this issue happens after reboot action sometimes, not every time.
 - After the first power on, can you find the file named ".markerfile-*************" under / ? Please notice there is a point "." in the beginning of the file name.
 - Are the VM's configurations and workflow the same between normal scenarios and issue existing scenarios?
 - Is the log file, that you mentioned before, flushed only in issue existing scenarios? Or is it also flushed in normal scenarios. You can check the log file update timestamp to confirm it.

**Comment by RuchikaChugh1** [comment]
To answer your questions
1.  Yes, there is a size zero file.
2. Yes, we created the Vapp, didn't change anything after the initial custom guest customization script.
3. The log file exists gets rewritten only when the issue is reproduced,otherwise it remains the same as when the VM was created . 
Attached is the log file.
[toolsDeployPkg.log](https://github.com/vmware/open-vm-tools/files/4528424/toolsDeployPkg.log)

**Comment by rongz609** [comment]
> To answer your questions
> 
> 1. Yes, there is a size zero file.
> 2. Yes, we created the Vapp, didn't change anything after the initial custom guest customization script.
> 3. The log file exists gets rewritten only when the issue is reproduced,otherwise it remains the same as when the VM was created .
>    Attached is the log file.
>    [toolsDeployPkg.log](https://github.com/vmware/open-vm-tools/files/4528424/toolsDeployPkg.log)

VCD triggers guest customization on every reboot of the VM in the following manner:
1) If any networking change is done in the VM, for example its IP address changed, IP mode changed etc then VCD marks such a VM as 'needs_customization=true'
2) Any other customization specific changes are done which don't need a full customization to take effect.
But in all these above cases, the customization that VCD tiggers is a partial customization.  That size zero file under '/' is used for indicate whether it should be a partial customization or not. 
According to toolsDeployPkg.log you attached, this was a partial customization. 
So, if nothing has changed in you VM and you also did not accidentally select 'Power on with Forced customization' from VCD UI and API, then VCD should not trigger any customization.
If you still get no idea how to prevent the re-customization, I would recommend you to create a PR so that things can be investigated from VCD side.

**Comment by stanguturi** [comment]
> VCD triggers guest customization on every reboot of the VM in the following manner:
> 
> 1. If any networking change is done in the VM, for example its IP address changed, IP mode changed etc then VCD marks such a VM as 'needs_customization=true'
> 2. Any other customization specific changes are done which don't need a full customization to take effect.
>    But in all these above cases, the customization that VCD tiggers is a partial customization.  That size zero file under '/' is used for indicate whether it should be a partial customization or not.
>    According to toolsDeployPkg.log you attached, this was a partial customization.
>    So, if nothing has changed in you VM and you also did not accidentally select 'Power on with Forced customization' from VCD UI and API, then VCD should not trigger any customization.
>    If you still get no idea how to prevent the re-customization, I would recommend you to create a PR so that things can be investigated from VCD side.

Thanks @rongz609 for the valuable inputs. VCD environment is somehow forcing the customization for the VM reboot. Some of the conditions that @rongz609 mentioned are triggering. Please work with your VCD team. Closing this issue.
