### ISSUE TITLE
Bad gateway customization on Debian 10

### ISSUE THREAD

**Issue by KaliszAd** [vmware/open-vm-tools#423]
I have noticed the customization specification of network configuration is causing an unfortunate default gateway configuration on Debian 10. Instead of using a statement like `gateway <IP | IPv6>` basically a script `up route add -net <default> gw <IP> dev <DEV>` gets configured in `/etc/network/interfaces`.
This is in my view bad for two reasons:

1. [net-tools needs to be installed](https://github.com/nsidc/vagrant-vsphere/issues/290), which is not in the default installation and the whole Linux community is moving to [deprecate net-tools](https://lwn.net/Articles/710533/)
2. why use a script if a simple statement would do just as well, am I missing something important here?

It would be better to utilise the robust Debian configuration options in this case and remove the dependency on net-tools.

**Comment by vmwzhangv** [comment]
Okay, we will file a bug to investigate. Thanks for your comments.

**Comment by vmwzhangv** [comment]
Before filing a bug, I checked our guest customization source code. I think we do set the "gateway <IP>" in /etc/network/interfaces for the primary NIC in the GOSC setting if it is defined. Otherwise,  we set "up route add ..." in /etc/network/interfaces for all NICs.

"up route  add ..." is a supported syntax/statement in /etc/network/interfaces. It is not a CLI from the net-tools package.

**Comment by KaliszAd** [comment]
> Before filing a bug, I checked our guest customization source code. I think we do set the "gateway " in /etc/network/interfaces for the primary NIC in the GOSC setting if it is defined. Otherwise, we set "up route add ..." in /etc/network/interfaces for all NICs.
> 
> "up route add ..." is a supported syntax/statement in /etc/network/interfaces. It is not a CLI from the net-tools package.

In my case on vSphere 6.7 with Debian 10, it went directly for the 'up route add' variant and it didn't work until I installed the net-tools package. No other change was made.
I don't think, it is a coincidence that the route syntax seems to be exactly the same and there is just the 'up' prefix, that signals it is to be run when you set the interface up.

I also fear that setting 'up route add...' on multiple interfaces doesn't lead to a valid or intended configuration. That would only make sense, if all interfaces were in the same network but that is almost never the case (because you could then just e.g. give one interface more addresses).

**Comment by PengpengSun** [comment]
Hi @KaliszAd ,

Debian is not supported by Guest OS Customization, I believe you will find customization task fails with error message "Customization of the guest operating system 'debian10_64Guest' is not supported in this configuration. " if your VM's Guest OS Version is 'Debian GNU/Linux 10(64-bit)'. You can find all supported Linux distroes at https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf

If you are using vSphere 6.7 Update 2 and later version
1.   The first NIC will be set to Primary NIC when you customize it to static IP and gateway <IP>, then only `gateway <IP>`  is configured in `/etc/network/interfaces`, the other NICs' gateway will be ignored.
2.  No primary NIC will be set if you customize the first nic to DHCP and the second, third... NICs to static IP and gateway <IP>, then multiple `up route add default gw <IP>` are configured in `/etc/network/interfaces`.

Back to your findings:

1. net-tools needs to be installed, which is not in the default installation and the whole Linux community is moving to deprecate net-tools

Yes, net-tools needs to be installed, otherwise `up route add default gw <IP>` does NOT work.

2. why use a script if a simple statement would do just as well, am I missing something important here?

It depends on whether there is a Primary NIC.

So net-tools is necessary for Debian "customization" and please check if you want to set a primary NIC.

**Comment by KaliszAd** [comment]
> Hi @KaliszAd ,
> 
> Debian is not supported by Guest OS Customization, I believe you will find customization task fails with error message "Customization of the guest operating system 'debian10_64Guest' is not supported in this configuration. " if your VM's Guest OS Version is 'Debian GNU/Linux 10(64-bit)'. You can find all supported Linux distroes at https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf

This is solved by setting the Guest OS Type to Ubuntu 64bit which in practice is nearly identical. The customization works with this setup.

> If you are using vSphere 6.7 Update 2 and later version
> 
>     1. The first NIC will be set to Primary NIC when you customize it to static IP and gateway , then only `gateway <IP>`  is configured in `/etc/network/interfaces`, the other NICs' gateway will be ignored.
> 
>     2. No primary NIC will be set if you customize the first nic to DHCP and the second, third... NICs to static IP and gateway , then multiple `up route add default gw <IP>` are configured in `/etc/network/interfaces`.

Ok, good to know. Thank you.

> Back to your findings:
> 
>     1. net-tools needs to be installed, which is not in the default installation and the whole Linux community is moving to deprecate net-tools
> 
> 
> Yes, net-tools needs to be installed, otherwise `up route add default gw <IP>` does NOT work.

Yes, that is true. At least, it could be `up ip route add default via <IP>`...

>     1. why use a script if a simple statement would do just as well, am I missing something important here?
> 
> 
> It depends on whether there is a Primary NIC.
> 
> So net-tools is necessary for Debian "customization" and please check if you want to set a primary NIC.

There is only one NIC so I guess, from your description, it should be the "primary" NIC by definition.

**Comment by PengpengSun** [comment]
@KaliszAd 
> There is only one NIC so I guess, from your description, it should be the "primary" NIC by definition.

Yes, it should be ''primary" NIC in such case, only `gateway <IP>`  should be configured in `/etc/network/interfaces` if you are using vCenter 6.7 U2 and above version. Then even without net-tools, it should work.

**Comment by PengpengSun** [comment]
Hi @KaliszAd ,

Can you please confirm if the one NIC Debian10 VM gateway customization works without 'net-tools'?

**Comment by KaliszAd** [comment]
> Hi @KaliszAd ,
> 
> Can you please confirm if the one NIC Debian10 VM gateway customization works without 'net-tools'?

It doesn't from what I can observe in my setup. It doesn't work with the GUI of vsphere and it doesn't work with vagrant-vsphere either. Installing `net-tools` did solve the issue of not having a working gateway for me.

**Comment by PengpengSun** [comment]
> > Hi @KaliszAd ,
> > Can you please confirm if the one NIC Debian10 VM gateway customization works without 'net-tools'?
> 
> It doesn't from what I can observe in my setup. It doesn't work with the GUI of vsphere and it doesn't work with vagrant-vsphere either. Installing `net-tools` did solve the issue of not having a working gateway for me.

What's in the /etc/network/interface? `gateway <IP>` or `up route add default gw <IP>`, and what's your vCenter version?

**Comment by KaliszAd** [comment]
> > > Hi @KaliszAd ,
> > > Can you please confirm if the one NIC Debian10 VM gateway customization works without 'net-tools'?
> > 
> > 
> > It doesn't from what I can observe in my setup. It doesn't work with the GUI of vsphere and it doesn't work with vagrant-vsphere either. Installing `net-tools` did solve the issue of not having a working gateway for me.
> 
> @KaliszAd What's in the /etc/network/interface? `gateway <IP>` or `up route add default gw <IP>`, and what's your vCenter version?

It is the `up route add default gw <IP>` version. I mean I wouldn't have opened the issue, if it was the former, because that would work.
vSphere Client version 6.7.0.20000
I don't know, where I can find out about the exact vCenter Version but in the vSphere Administration under licensing it says VMware vCenter Server 6 Standard. The thing is, the whole thing comes in one package as far as I can tell - it is a Dell/EMC VxRail based system setup by a certified partner. Therefore I don't have much visibility there since I didn't really need to make my hands dirty with setting it all up.

**Comment by PengpengSun** [comment]
> > > > Hi @KaliszAd ,
> > > > Can you please confirm if the one NIC Debian10 VM gateway customization works without 'net-tools'?
> > > 
> > > 
> > > It doesn't from what I can observe in my setup. It doesn't work with the GUI of vsphere and it doesn't work with vagrant-vsphere either. Installing `net-tools` did solve the issue of not having a working gateway for me.
> > 
> > 
> > @KaliszAd What's in the /etc/network/interface? `gateway <IP>` or `up route add default gw <IP>`, and what's your vCenter version?
> 
> It is the `up route add default gw <IP>` version. I mean I wouldn't have opened the issue, if it was the former, because that would work.
> vSphere Client version 6.7.0.20000

It's vCenter 6.7 U1 (6.7.0.20000),  if it can be upgraded to 6.7 U2 (6.7.0.30000) or above version, the first nic (the only nic in your case) will be primary nic, then `gateway <IP>` will be configured in /etc/network/interface.
