### ISSUE TITLE
Customization problem on new Ubuntu release (20.04 / Focal Fossa)

### ISSUE THREAD

**Issue by HammerZ3it** [vmware/open-vm-tools#424]
Hi everyone,

I wanted to prepare my VSphere Templates generated with Packer for the new release of Ubuntu.
So far I have been able to create my template but it seems that there is a problem when I want to deploy a VM from it with ansible module : https://docs.ansible.com/ansible/latest/modules/vmware_guest_module.html

When the VM is powered on, the customization fail with this error : 

`
DEBUG: opening file for writing (/etc/resolv.conf).
ERROR: Fatal error occurred during customization !! Customization halted.
ERROR: Error : No such file or directory:Error writing to file (/etc/resolv.conf). No such file or directory
Customization command failed with exitcode: 252, stderr: 'mv: cannot stat '/etc/network/interface': No such file or directory'.
`
![image](https://user-images.githubusercontent.com/12964578/81204103-0f882300-8fc9-11ea-88f4-e6494b142aaf.png)

The error is normal as it is now netplan use for the new version of Ubuntu (started with 18.04).
Strange things is that customization is working great with Ubuntu 18.04.

Maybe it needs to add a condition to do the same as for Ubuntu 18.04.

Thx in advance.

Regards,

**Comment by ravindravmw** [comment]
@HammerZ3it could you please provide more details about this issue? Also, please check if it is same as issue #421.

**Comment by HammerZ3it** [comment]
My bad I did not put any content on the issue....
It is in fact cloning a vm from a template and it tries to mv /etc/network/interfaces but with netplan it does not exist anymore.
Like I said, it perfectly work with ubuntu 18.04 that uses netplan too.

**Comment by ravindravmw** [comment]
It could still be same issue as #421 due to old VC not being able to recognize the newer Ubuntu version correctly. Please try upgrading your VC to one of the suggested versions (7.0 or a newer patch of 6.7u3) in #421 if not done so already.

**Comment by PengpengSun** [comment]
Hi @HammerZ3it , Ubuntu 20.04 customization is supported from VC 6.7U3g release, please find this release at https://my.vmware.com/web/vmware/info/slug/datacenter_cloud_infrastructure/vmware_vsphere/6_7

**Comment by ravindravmw** [comment]
@HammerZ3it could you please update here if your issue gets resolved with upgrading VC?

**Comment by HammerZ3it** [comment]
@ravindravmw  I can't make the update right now but I'm gonna close this issue and reopen a new one if it does not fix it.

Thanks for you help.

regards,
