### ISSUE TITLE
Unknown ioctl 1976

### ISSUE THREAD

**Issue by thelounge-zz** [vmware/open-vm-tools#425]
https://bugzilla.redhat.com/show_bug.cgi?id=1821892

[root@buildserver:~]$ uname -r
5.6.10-200.fc31.x86_64

[root@buildserver:~]$ rpm -q open-vm-tools
open-vm-tools-11.1.0-2.fc31.20200511.rh.sandybridge.x86_64

May 11 19:01:53 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:01:53 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:01:53 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:01:53 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:01:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:01:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:01:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:01:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:01:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:02:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:02:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:02:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:02:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:02:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:02:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:03:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:03:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:03:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:04:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:04:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:04:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:05:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:05:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:05:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:08:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:08:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:08:24 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:12:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:12:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:12:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:17:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:17:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:17:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:22:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:22:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:22:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:27:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:27:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:27:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:32:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:32:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:32:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:37:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:37:54 buildserver.thelounge.net kernel: Unknown ioctl 1976
May 11 19:37:54 buildserver.thelounge.net kernel: Unknown ioctl 1976

**Comment by dsouders** [comment]
Is vmci/vsock missing?

https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/lib/include/vmci_sockets.h

#  define VMCI_SOCKETS_DEFAULT_DEVICE      "/dev/vsock"
#  define VMCI_SOCKETS_CLASSIC_ESX_DEVICE  "/vmfs/devices/char/vsock/vsock"
#  if defined(__linux__)
#     define VMCI_SOCKETS_VERSION       1972
#     define VMCI_SOCKETS_GET_AF_VALUE  1976
#     define VMCI_SOCKETS_GET_LOCAL_CID 1977
#     define VMCI_SOCKETS_UUID_2_CID    1991

**Comment by thelounge-zz** [comment]
surely blacklisted for *years* because nobody needs that stuff, poero-operations, vmware-ha and backups are working, anything else is useless

**Comment by dsouders** [comment]
vmci/vsock should be installed.  The drivers are used by open-vm-tools to provide a variety of services, including secure RPCs that are needed to manage VMs.

**Comment by thelounge-zz** [comment]
they are not needed for Vmware-HA, Vmware-DataProtection, SHotduwn/Reboot guests and so should not be loaded on setups wehere virtual machines are handeled like a physical machine

all that services are not needed and not wanted in stripped setups and after 12 years i know my setups, better than VMware knows their stuff where your whole network disappears after a bugfix ESXi update without manual internevntion (god knows why a failing secondary onobard NIC kills the whole teaming when the 10 GBE NIC would work just fine and does on a different port for NFS)

On the ESXi command line, run these commands to disable the ntg3 driver and enable the tg3 driver:
# esxcfg-module -d ntg3
# esxcfg-module -e tg3

**Comment by Piraty** [comment]
I hit this as well, no fancy setup in place (no blacklisted modules).

* Host: Windows 10, VMware workstation player 14
* Guest: Linux, open-vm-tools 11.1.0
```
$ uname -srmpo
Linux 5.6.18_1 x86_64 unknown GNU/Linux

$ vmtoolsd --version
VMware Tools daemon, version 11.1.0.19887 (build-16036546)

# lsmod | grep -e vmc -e vsock
vmw_vmci               73728  1 vmw_balloon
vhost_vsock            24576  0
vmw_vsock_virtio_transport_common    32768  1 vhost_vsock
vsock                  40960  2 vmw_vsock_virtio_transport_common,vhost_vsock
vhost                  45056  2 vhost_vsock,vhost_net

# dmesg | tail -n 6
[  709.188437] Unknown ioctl 1976
[  709.289691] Unknown ioctl 1976
[  709.392175] Unknown ioctl 1976
[ 1009.268697] Unknown ioctl 1976
[ 1009.370125] Unknown ioctl 1976
[ 1009.470603] Unknown ioctl 1976
```

**Comment by thelounge-zz** [comment]
[root@master:/etc/modprobe.d]$ cat blacklist-lounge-vm.conf 
blacklist acpi_cpufreq
blacklist acpi_power_meter
blacklist ata_generic
blacklist bluetooth
blacklist cfg80211
blacklist coretemp
blacklist cramfs
blacklist dccp
blacklist drm
blacklist edac_core
blacklist fjes
blacklist floppy
blacklist hfs
blacklist hfsplus
blacklist i2c_piix4
blacklist intel_powerclamp
blacklist intel_rapl
blacklist intel_rapl_common
blacklist intel_rapl_msr
blacklist intel_rapl_perf
blacklist irda
blacklist joydev
blacklist kvm
blacklist kvm_amd
blacklist kvm_intel
blacklist l2tp_core
blacklist l2tp_ip
blacklist l2tp_ip6
blacklist lib80211
blacklist lib80211_crypt_ccmp
blacklist lib80211_crypt_tkip
blacklist lib80211_crypt_wep
blacklist mac80211
blacklist microcode
blacklist mperf
blacklist n_hdlc
blacklist nf_conntrack_proto_dccp
blacklist nf_nat_proto_dccp
blacklist nfc
blacklist nfc_digital
blacklist nfit
blacklist nsc_ircc
blacklist openvswitch
blacklist parport
blacklist parport_pc
blacklist pata_acpi
blacklist pcspkr
blacklist ppdev
blacklist rfkill
blacklist sb_edac
blacklist serio_raw
blacklist snd
blacklist snd_page_alloc
blacklist snd_pcm
blacklist snd_pcsp
blacklist snd_timer
blacklist soundcore
blacklist squashfs
blacklist sunrpc
blacklist tpm
blacklist tpm_tis
blacklist ttm
blacklist udf
blacklist vmw_vsock_vmci_transport
blacklist vmwgfx
blacklist xt_dccp
blacklist vsock_loopback
blacklist vmw_vsock_virtio_transport_common
install acpi_cpufreq /usr/bin/true
install acpi_power_meter /usr/bin/true
install ata_generic /usr/bin/true
install bluetooth /usr/bin/true
install cfg80211 /usr/bin/true
install coretemp /usr/bin/true
install cramfs /usr/bin/true
install dccp /usr/bin/true
install drm /usr/bin/true
install edac_core /usr/bin/true
install fjes /usr/bin/true
install floppy /usr/bin/true
install hfs /usr/bin/true
install hfsplus /usr/bin/true
install i2c_piix4 /usr/bin/true
install intel_powerclamp /usr/bin/true
install intel_rapl /usr/bin/true
install intel_rapl_msr /usr/bin/true
install intel_rapl_common /usr/bin/true
install intel_rapl_perf /usr/bin/true
install irda /usr/bin/true
install joydev /usr/bin/true
install kvm /usr/bin/true
install kvm_amd /usr/bin/true
install kvm_intel /usr/bin/true
install l2tp_core /usr/bin/true
install l2tp_ip /usr/bin/true
install l2tp_ip6 /usr/bin/true
install lib80211 /usr/bin/true
install lib80211_crypt_ccmp /usr/bin/true
install lib80211_crypt_tkip /usr/bin/true
install lib80211_crypt_wep /usr/bin/true
install mac80211 /usr/bin/true
install microcode /usr/bin/true
install mperf /usr/bin/true
install n_hdlc /usr/bin/true
install nf_conntrack_proto_dccp /usr/bin/true
install nf_nat_proto_dccp /usr/bin/true
install nfc /usr/bin/true
install nfc_digital /usr/bin/true
install nfit /usr/bin/true
install nsc_ircc /usr/bin/true
install openvswitch /usr/bin/true
install parport /usr/bin/true
install parport_pc /usr/bin/true
install pata_acpi /usr/bin/true
install pcspkr /usr/bin/true
install ppdev /usr/bin/true
install rfkill /usr/bin/true
install sb_edac /usr/bin/true
install serio_raw /usr/bin/true
install snd /usr/bin/true
install snd_page_alloc /usr/bin/true
install snd_pcm /usr/bin/true
install snd_pcsp /usr/bin/true
install snd_timer /usr/bin/true
install soundcore /usr/bin/true
install squashfs /usr/bin/true
install sunrpc /usr/bin/true
install tpm /usr/bin/true
install tpm_tis /usr/bin/true
install ttm /usr/bin/true
install udf /usr/bin/true
install vmw_vsock_vmci_transport /usr/bin/true
install vmwgfx /usr/bin/true
install xt_dccp /usr/bin/true
install vsock_loopback /usr/bin/true
install vmw_vsock_virtio_transport_common /usr/bin/true
