### ISSUE TITLE
[bug] Unable to copy files from host to guest when Fedora as guest

### ISSUE THREAD

**Issue by suiahae** [vmware/open-vm-tools#427]
Hello VMware Development Team,

I have encountered the problem "Cannot copy files from host to Fedora guest". My laptop running latest Windows 10 Pro 1909 Build 18363.836 and VMware Workstation 15.52 build-15785246 and guest is Fedora 32 with Gnome 3.36.

As we all know, there are two ways to copy the host file to the virtual machine, namely: No.1"drag the file to the virtual machine" and No.2"just copy and paste".

**When i try method No.2**, It said "No such file or directory" as follows
![image](https://user-images.githubusercontent.com/45323123/82723120-15873f00-9cff-11ea-9062-579e1f7c59d9.png)
And the folder(`/tem/VMwareDnD/SmzgBG`) is empty indeed.
![image](https://user-images.githubusercontent.com/45323123/82723167-60a15200-9cff-11ea-9972-955f205cd98f.png)

---
**When i try method No.1**, there will be a transparent program named "vmware-user" running(No icon, like this).
![image](https://user-images.githubusercontent.com/45323123/82723227-ea511f80-9cff-11ea-9548-412cd882438e.png)
Then, if I switch to another interface, the desktop will definitely freeze soon.

~~And I think the reason for "Desktop keeps freezing" is that "vmware-user" cannot exit from "File Copy" because "File Copy" cannot be completed.~~

**Comment by suiahae** [comment]
#176

**Comment by johnwvmw** [comment]
The vmblock enables dragging or copying files between host and guest in a Fusion or Workstation virtual environment.

The service is available as part of the open-vm-tools packages on Fedora, but the service is not enabled by default.   DnD and copy/paste between host and guest is disabled when the VM is on a vSphere host..

For WorkStation hosts, It is simply a matter of enabling and starting the vmblock-fuse service.

  systemctl enable run-vmblock\\x2dfuse.mount

  systemctl start run-vmblock\\x2dfuse.mount

  systemctl status -l run-vmblock\\x2dfuse.mount

Once enabled, the service will be started automatically when the Fedora VM is booted.

**Comment by suiahae** [comment]
> The vmblock enables dragging or copying files between host and guest in a Fusion or Workstation virtual environment.
> 
> The service is available as part of the open-vm-tools packages on Fedora, but the service is not enabled by default. DnD and copy/paste between host and guest is disabled when the VM is on a vSphere host..
> 
> For WorkStation hosts, It is simply a matter of enabling and starting the vmblock-fuse service.
> 
> systemctl enable run-vmblock\x2dfuse.mount
> 
> systemctl start run-vmblock\x2dfuse.mount
> 
> systemctl status -l run-vmblock\x2dfuse.mount
> 
> Once enabled, the service will be started automatically when the Fedora VM is booted.

Thank for your help.
These commands can be allowed by adding "\\" before the "\\" of the command, like this:
```
systemctl enable run-vmblock\\x2dfuse.mount
systemctl start run-vmblock\\x2dfuse.mount
systemctl status -l run-vmblock\\x2dfuse.mount
```

But "dragging or copying files" still cannot run successfully. And the gnome desktop will still freeze 
:(

**Comment by johnwvmw** [comment]
I apologize, I did not take notice that the "//'" was changed to a single "/" when I copied my response to this issue.  I am happy that you caught that.

Please switch from the default Wayland X protocol to X11 protocol. 
When logging onto the desktop, click on the small menu in the lower right corner of the logon screen and select "Gnome on Xorg".   Please lets the tools team know if this resolves the drag-n-drop problems that you have been experiencing.

Switching to X11 protocol may also resolve the desktop freeze.  Please take a look at issue #417  for details.  If the freeze should continue,  please open a separate issue to be used to track that problem.

Thanks

**Comment by suiahae** [comment]
> I apologize, I did not take notice that the "//'" was changed to a single "/" when I copied my response to this issue. I am happy that you caught that.
> 
> Please switch from the default Wayland X protocol to X11 protocol.
> When logging onto the desktop, click on the small menu in the lower right corner of the logon screen and select "Gnome on Xorg". Please lets the tools team know if this resolves the drag-n-drop problems that you have been experiencing.
> 
> Switching to X11 protocol may also resolve the desktop freeze. Please take a look at issue #417 for details. If the freeze should continue, please open a separate issue to be used to track that problem.
> 
> Thanks

It works!! Thank you very much!

**Comment by johnwvmw** [comment]
@suiahae   Thanks for confirming.   Closing this issue for now.   Please feel free to re-open should you encounter other issues with the DnD copy/paste plugin.

**Comment by SinoAHpx** [comment]
> I apologize, I did not take notice that the "//'" was changed to a single "/" when I copied my response to this issue. I am happy that you caught that.
> 
> Please switch from the default Wayland X protocol to X11 protocol. When logging onto the desktop, click on the small menu in the lower right corner of the logon  screen and select " gnome  on Xorg". Please lets the tools team know if this resolves the drag-n-drop problems that you have been experiencing.
> 
> Switching to X11 protocol may also resolve the desktop freeze. Please take a look at issue #417 for details. If the freeze should continue, please open a separate issue to be used to track that problem.
> 
> Thanks

for who's googling this:

just refer to [official documentation](https://docs.fedoraproject.org/en-US/quick-docs/configuring-xorg-as-default-gnome-session/)
