### ISSUE TITLE
"The power-on script did not run successfully in this virtual machine"

### ISSUE THREAD

**Issue by xDEADC0DE** [vmware/open-vm-tools#43]
I've just created a linux image in Workstation 12 (debian-8.2-testing-amd64-netinst).

Once open-vm-tools is installed, I get errors on each power change:
"The VMware Tools power-on script did not run successfully in this virtual machine. If you have configured a custom power-on script in this virtual machine, make sure that it contains no errors. You can also submit a support request to report this issue"

**Comment by ravindravmw** [comment]
What version of open-vm-tools is installed in the VM? What is the contents of /etc/vmware-tools/scripts dir? 'ls -lR /etc/vmware-tools/scripts' would be useful.

**Comment by xDEADC0DE** [comment]
Sorry, I'll add them right away. It's a fresh install, so if there are scripts they are the default ones.

**Comment by xDEADC0DE** [comment]
There's only one folder, "vmware", containing a single script, "network".

according to dpkg -s, it's version 2:9.10.2-2822639-3+b1 of the package.

Thanks!

**Comment by ravindravmw** [comment]
Thanks. What is the exit status of "/etc/vmware-tools/scripts/vmware/network poweron-vm"? You might also want to run it under "bash -x" and capture the output for us to take a look.

**Comment by dyno** [comment]
i run into the same problem with Unbuntu 14.04. please try 
```bash
sudo chmod +x /etc/vmware-tools/*-vm-default
sudo chmod +x /etc/vmware-tools/scripts/vmware/network
```
i think the problem is the `open-vm-tools` upgrade removes the execution bit of the scripts.

**Comment by ravindravmw** [comment]
Thanks Dyno. That's a packaging bug in Ubuntu/Debian.

**Comment by ravindravmw** [comment]
Including @bzed as he maintains the package in Debian.

@xDEADC0DE if changing execution bit fixes it, you might want to raise a tracking issue in Debian system for this.

**Comment by xDEADC0DE** [comment]
Yes, that fixed it! :+1: 

It's an issue with debian, not with the package?

**Comment by vcardillo** [comment]
These files do not exist on my VM.

**Comment by hdave** [comment]
Same here, these files are not found in my Ubuntu 16.04.

**Comment by bzed** [comment]
@hdave @vcardillo which version of the open-vm-tools package are you using?

**Comment by bzed** [comment]
@hdave also please note that Ubuntu is shipping their own fork of my packaging. You might try to open a bug in  launchpad or just use Debian.

**Comment by actionless** [comment]
i just faced the same issue, but in my case the rootcause was different:
i had installed with the package only one script there - `network`, which was relying on Network manager which is not installed/which i am not using

is that script mantained by openvm-tools team or distribution package maintainers?

**Comment by ravindravmw** [comment]
The script itself is part of open-vm-tools, https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/scripts/linux/network. However, it's file permissions/installation path etc are maintained by the packaging.

**Comment by actionless** [comment]
the problem with this script what it is causing the same problem (can't suspend from the first request) as described in the ticket if NetworkManager is not installed.

would you mind a PR which will add to that script a check if NetworkManager appears to be installed/running, and if not -- not trying to communicate to it?

**Comment by ravindravmw** [comment]
The script in open-vm-tools 10.0.x and newer does handle absence of NetworkManager. What is the version of your guest OS and version of open-vm-tools?

**Comment by actionless** [comment]
Arch Linux, community/open-vm-tools 6:10.1.0-2

**Comment by actionless** [comment]
i would recommend to do some check like `which netctl` instead of relying on exit code, because command not found will return bad status code as well

**Comment by ravindravmw** [comment]
What do the file permissions look like for /etc/vmware-tools/scripts/vmware/network in your guest OS?

**Comment by actionless** [comment]
`-rwxr-xr-x root root`

but since the script working after editing i don't think what it's something to do with the permissions...

**Comment by pitosalas** [comment]
I get the same problem as @xDEADC0DE . In my case in am running Ubuntu 16.02 on Vmware Fusion on Mac. I don't even have the directory: ls -lR /etc/vmware-tools/scripts. Any tips?

**Comment by ravindravmw** [comment]
I believe you are using open-vm-tools package provided by Ubuntu. Is the directory missing even in case of fresh install? If yes, it might be a packaging bug in Ubuntu.

**Comment by oliverkurth** [comment]
@pitosalas , do you have the open-vm-tools package installed, or did you build from source? What is the output of the command `dpkg -l open-vm-tools` ? I just checked, the version 10.0.7 that comes with Ubuntu 16.04 does include the directory. You an also check with `dpkg -L open-vm-tools`.

**Comment by pitosalas** [comment]
I am away from that computer for several days, but this I remember from memory: I installed vmware, then ubuntu 16.04, used it for a while, noticed that cut/paste between mac and the vm didn't work, researched it and installed (attempted) vmware-tools. That amounted to mounting a (virtual) cd, copying a shell script to my desktop and running it. I didnt look at the shell script. I remember something going wrong and then me retrying it. When copy/paste still didn't work, I think I read more and tried to install open-vm-tools. Then the next time I shutdown (and also restarted) I would get that error message. HTH

**Comment by pitosalas** [comment]
@oliverkurth Here's the output from those two commands... I don't know what I am looking for though... What do you think?

```
pitosalas@ubuntu:~$ dpkg -l open-vm-tools
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  open-vm-tools  2:10.0.7-322 amd64        Open VMware Tools for virtual mac
pitosalas@ubuntu:~$ dpkg -L open-vm-tools
/.
/etc
/etc/vmware-tools
/etc/vmware-tools/poweron-vm-default
/etc/vmware-tools/scripts
/etc/vmware-tools/scripts/vmware
/etc/vmware-tools/scripts/vmware/network
/etc/vmware-tools/poweroff-vm-default
/etc/vmware-tools/resume-vm-default
/etc/vmware-tools/guestproxy-ssl.conf
/etc/vmware-tools/statechange.subr
/etc/vmware-tools/vm-support
/etc/vmware-tools/suspend-vm-default
/etc/vmware-tools/tools.conf
/etc/init.d
/etc/init.d/open-vm-tools
/etc/pam.d
/etc/pam.d/vmtoolsd
/usr
/usr/bin
/usr/bin/vmware-checkvm
/usr/bin/vmware-rpctool
/usr/bin/vmware-namespace-cmd
/usr/bin/vmware-hgfsclient
/usr/bin/vmware-vmblock-fuse
/usr/bin/vmtoolsd
/usr/bin/vmhgfs-fuse
/usr/bin/vmware-xferlogs
/usr/bin/vmware-guestproxycerttool
/usr/bin/vmware-toolbox-cmd
/usr/sbin
/usr/share
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/vmware-xferlogs.1.gz
/usr/share/man/man1/vmware-checkvm.1.gz
/usr/share/man/man1/vmware-toolbox-cmd.1.gz
/usr/share/man/man9
/usr/share/man/man9/vmxnet.9.gz
/usr/share/man/man3
/usr/share/man/man3/libguestlib.3.gz
/usr/share/man/man3/libvmtools.3.gz
/usr/share/open-vm-tools
/usr/share/open-vm-tools/messages
/usr/share/open-vm-tools/messages/de
/usr/share/open-vm-tools/messages/de/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/de/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/zh_CN
/usr/share/open-vm-tools/messages/zh_CN/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/ko
/usr/share/open-vm-tools/messages/ko/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/ko/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/ja
/usr/share/open-vm-tools/messages/ja/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/ja/vmtoolsd.vmsg
/usr/share/doc
/usr/share/doc/open-vm-tools
/usr/share/doc/open-vm-tools/copyright
/usr/share/doc/open-vm-tools/changelog.Debian.gz
/usr/lib
/usr/lib/libhgfs.so.0.0.0
/usr/lib/open-vm-tools
/usr/lib/open-vm-tools/plugins
/usr/lib/open-vm-tools/plugins/vmsvc
/usr/lib/open-vm-tools/plugins/vmsvc/libdeployPkgPlugin.so
/usr/lib/open-vm-tools/plugins/vmsvc/libtimeSync.so

```

**Comment by oliverkurth** [comment]
@pitosalas the script directory including the network script is part of the package that you have installed, see from the output of you `dpkg -L` command:

```
...
/etc/vmware-tools
/etc/vmware-tools/poweron-vm-default
/etc/vmware-tools/scripts
/etc/vmware-tools/scripts/vmware
/etc/vmware-tools/scripts/vmware/network
...
```

If the directory isn't there, it might be that you have removed the directory yourself. In that case you can reinstall tools with
`sudo apt-get install --reinstall open-vm-tools
`

**Comment by pitosalas** [comment]
I was optimistic, but, I did your process, rebooted the instance, and then got the error message again...


![screen shot 2017-07-31 at 9 17 40 pm](https://user-images.githubusercontent.com/44681/28805121-b100055a-7635-11e7-9298-4102e065d13a.png)

**Comment by pitosalas** [comment]
Any other tips from anyone on my receiving the error: "The VMware Tools resume script did not run successfully in this virtual machine."

**Comment by ravindravmw** [comment]
Looks like we need the debug logs. We need to run the failing script by hand and collect its debug output. Please run and collect the output generated by following commands:

$ bash -x /etc/vmware-tools/scripts/vmware/network suspend-vm; echo $?
$ bash -x /etc/vmware-tools/scripts/vmware/network resume-vm; echo $?

**Comment by brocky27** [comment]
@oliverkurth that worked for me!

**Comment by extratype** [comment]
Same here, https://github.com/vmware/open-vm-tools/issues/43#issuecomment-278123574 as @actionless.

I have installed `networkmanager`. `netctl` works, and both of `$ ./network suspend-vm; echo$?` and `$ ./network resume-vm; echo$?` print 0. But I am getting the error message. Clearly `WakeNetworkManager` returns nonzero. I can't figure out what's happening, so I just forced `$exitCode=0` instead of `$exitCode=$?`. Now the error message is gone.

**Comment by ravindravmw** [comment]
@extratype could you please backup and replace '/etc/vmware-tools/scripts/vmware/network' script in the guest with https://github.com/vmware/open-vm-tools/blob/devel/open-vm-tools/scripts/linux/network? The github version of the script would generate /var/log/vmware-network.log file inside the guest. Either you could analyze the generated log file yourself or share it with us for analysis.

**Comment by extratype** [comment]
@ravindravmw Is there an error in these logs? I guess not, but the error message is still displayed.
```
++ date
+ echo 2017. 11. 06. '(월)' 21:25:45 KST ': Executing '\''/etc/vmware-tools/scripts/vmware/network suspend-vm'\'''
2017. 11. 06. (월) 21:25:45 KST : Executing '/etc/vmware-tools/scripts/vmware/network suspend-vm'
+ echo

++ dirname /etc/vmware-tools/scripts/vmware/network
+ . /etc/vmware-tools/scripts/vmware/../../statechange.subr
+ main suspend-vm
+ exitCode=0
+ activeList=/var/run/vmware-active-nics
+ case "$1" in
+ TranquilizeNetworkManager
++ which dbus-send
+ dbusSend=/usr/sbin/dbus-send
+ rc=0
+ '[' 0 -ne 0 ']'
++ awk '/variant/ {print $3;}'
++ /usr/sbin/dbus-send --system --print-reply --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:org.freedesktop.NetworkManager string:State
+ nm_state=70
+ '[' -z 70 ']'
+ case $nm_state in
+ /usr/sbin/dbus-send --system --print-reply --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager org.freedesktop.NetworkManager.Enable boolean:false
method return time=1509971145.171168 sender=:1.2 -> destination=:1.76 serial=200 reply_serial=2
+ rc=0
+ '[' 0 -eq 0 ']'
+ return 0
+ exitCode=0
+ '[' 0 '!=' 0 ']'
+ return 0
++ date
+ echo 2017. 11. 06. '(월)' 21:25:45 KST ': Finished '\''/etc/vmware-tools/scripts/vmware/network suspend-vm'\'''
2017. 11. 06. (월) 21:25:45 KST : Finished '/etc/vmware-tools/scripts/vmware/network suspend-vm'
```
```
++ date
+ echo 2017. 11. 06. '(월)' 21:25:52 KST ': Executing '\''/etc/vmware-tools/scripts/vmware/network resume-vm'\'''
2017. 11. 06. (월) 21:25:52 KST : Executing '/etc/vmware-tools/scripts/vmware/network resume-vm'
+ echo

++ dirname /etc/vmware-tools/scripts/vmware/network
+ . /etc/vmware-tools/scripts/vmware/../../statechange.subr
+ main resume-vm
+ exitCode=0
+ activeList=/var/run/vmware-active-nics
+ case "$1" in
+ WakeNetworkManager
++ which dbus-send
+ dbusSend=/usr/sbin/dbus-send
+ rc=0
+ '[' 0 = 0 ']'
+ /usr/sbin/dbus-send --system --print-reply --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager org.freedesktop.NetworkManager.Enable boolean:true
method return time=1509971152.202142 sender=:1.2 -> destination=:1.79 serial=247 reply_serial=2
+ rc=0
+ '[' 0 = 0 ']'
+ return 0
+ exitCode=0
+ '[' 0 '!=' 0 ']'
+ return 0
++ date
+ echo 2017. 11. 06. '(월)' 21:25:52 KST ': Finished '\''/etc/vmware-tools/scripts/vmware/network resume-vm'\'''
2017. 11. 06. (월) 21:25:52 KST : Finished '/etc/vmware-tools/scripts/vmware/network resume-vm'
```

**Comment by mageekguy** [comment]
@pitosalas try ` apt-get remove --purge open-vm-tools open-vm-tools-desktop` and `apt-get install --reinstall open-vm-tools` and `apt-get install --reinstall open-vm-tools-desktop`, and reboot the VM.  
Good luck!

**Comment by ravindravmw** [comment]
@extratype I don't see any error in the log. I'd like to double confirm that the log you have captured is the /var/log/vmware-network.log file generated as part of the suspend operation and *not* from a manual run of the script by hand? In order to see what exactly failed, could you please also enable debug logs by specifying following in /etc/vmware-tools/tools.conf inside guest:

[logging]
vmsvc.level=debug

Once you have the settings above, you could wait for 5 seconds or restart vmtoolsd before retrying the suspend/resume. Retry suspend/resume, if issue reproduces collect /var/log/vmware-vmsvc*log.

**Comment by extratype** [comment]
@ravindravmw Updated Arch, the error is gone. Still don't know what happened, but thanks!

**Comment by ravindravmw** [comment]
Sorry @extratype I don't completely follow your message. What do you mean by "Updated Arch"? Could you please make it little clearer?

**Comment by extratype** [comment]
@ravindravmw Oops, I meant Arch Linux, sorry. 100+ packages were updated, including open-vm-tools (6:10.1.10-2 to 6:10.1.15-1). It had been updated recently, though it was released far earlier at GitHub.

**Comment by ravindravmw** [comment]
Thank you @extratype and I'm glad that your issue has been resolved. However, how an update resolved it remains a mystery for me.

If you see a reproduction of this issue again, please collect the logs as I suggested in my comment https://github.com/vmware/open-vm-tools/issues/43#issuecomment-343308089.

**Comment by nickaein** [comment]
@ravindravmw I am having the same issue.

Guest OS Ubuntu 16.04.3
VMware Workstation version: 14.0.0 build-6661328
VMware tools version on Guest: 10.0.7.52125 (build-3227872)


I tried to enable debugging for VMware tools as you suggested [https://github.com/vmware/open-vm-tools/issues/43#issuecomment-343308089](https://github.com/vmware/open-vm-tools/issues/43#issuecomment-343308089), but the `tools.conf` file isn't present. In fact, there is no file present in `/etc/vmware-tools` directory:

```
isaac@ubuntu:~$ find /etc/vmware-tools/
/etc/vmware-tools/
/etc/vmware-tools/scripts
/etc/vmware-tools/scripts/vmware
isaac@ubuntu:~$
```

**Comment by ravindravmw** [comment]
@nickaein we don't ship tools.conf, you have to create it first time. Also, please replace the network script as I mentioned in Oct 30, 2017 comment (#issuecomment-340548257) because the script that is present in open-vm-tools 10.0.7 does not generate enough logs for debugging.

**Comment by nickaein** [comment]
@ravindravmw 

The script `/etc/vmware-tools/scripts/vmware/network` wasn't present. I created it and copied the contents from the source you mentioned at [https://github.com/vmware/open-vm-tools/issues/43#issuecomment-340548257](https://github.com/vmware/open-vm-tools/issues/43#issuecomment-340548257).

Here is the log after enabling `vmsvc.level=debug` in tools.conf: https://pastebin.com/Rt5YTcbp.

**Comment by seetimee** [comment]
> @pitosalas try ` apt-get remove --purge open-vm-tools open-vm-tools-desktop` and `apt-get install --reinstall open-vm-tools` and `apt-get install --reinstall open-vm-tools-desktop`, and reboot the VM. Good luck!

thanks a lot. It worked
