### ISSUE TITLE
Black Screen when using multible monitors. 

### ISSUE THREAD

**Issue by blueForestIcarus** [vmware/open-vm-tools#439]
I can no longer use multiple monitors.  Autofit works for one screen, but If I select "choose a monitor layout" -> "layout <2 or 3>" to use more than one monitor the screen extends, the cursor is visible, but besides that the screen is black.

The guest is seems to still receive input while the screen is black; I can revert to a single monitor layout and any text I typed is there.

The guest is arch Linux.
Kernel: 5.7.2
open-vm-tools: 6:11.0.1
VMware: 15.1.0 Pro

The issue occurs both with 3d acceleration turned on or turned off in VM config.

I'm aware in there is a 11.1 release but saw nothing relating to this in the release notes. 
This issue appeared after to a recent arch update (which incidentally moved to a new kernel version).

**Comment by usatosi** [comment]
I have exact same problem with the following environment.

linux 5.7.4.arch1-1
open-vm-tools 6:11.0.1-2
VMware: 15.5.6

But I upgraded open-vm-tools from 6:11.0.1-1 on 5 months ago and the problem occurred today,just after upgraded vmware player to 15.5.6(I couldn't find out the detail version number before upgrade).

**Comment by zeretar** [comment]
I was experiencing the same, reverting back to kernel 5.6.19 fixed it hinting at a kernel/open-vm-tools compatibility issue.

Linux 5.6.19-2-MANJARO (was Linux 5.7.5-1-MANJARO, same problem with 5.8rc1)
open-vm-tools 6:11.0.1-2
VMWare Workstation: 15.5.6

**Comment by usatosi** [comment]
zeretar,
Thank you for your advice! Downgrading to 5.6.15 fixed the problem for me too.

**Comment by blueForestIcarus** [comment]
Updating both kernel and vmware worked for me.
Kernel = 5.7.4-arch1-1
VMWare 15.5.6

**Comment by LuakPL** [comment]
For me helped full-upgrade with open-vm-tools-desktop using kali tutorial:

https://www.kali.org/docs/virtualization/install-vmware-tools-kali-guest/
