### ISSUE TITLE
CentOS8, build error with xml-security on CentOS 8

### ISSUE THREAD

**Issue by battulgag** [vmware/open-vm-tools#441]
open-vm-tools with xml-security building error on CentOS 8.2 (4.18.0-193.6.3.el8_2.x86_64).

install xml-security-c from https://downloads.apache.org/santuario/c-library
fix XSECDOMUtils.hpp missing issue following https://issues.apache.org/jira/browse/SANTUARIO-506
+++ ./xsec/Makefile.am
`@ -316,6 +316,8 @@ utilsinclude_HEADERS = \`
`  utils/XSECXPathNodeList.hpp \`
`   utils/XSECSafeBufferFormatter.hpp \`
`   utils/XSECBinTXFMInputStream.hpp \`
`+  utils/XSECAlgorithmSupport.hpp \`
`+  utils/XSECDOMUtils.hpp \`
`   utils/XSECPlatformUtils.hpp`

autoreconf -ifv
./configure \
 --prefix=/usr/local \
 --libdir=/usr/local/lib64 \
 --enable-shared \
 --enable-static \
 --enable-xmlsecurity \
 --without-icu \
 --with-x

make -j 8
...

mv -f .deps/VGAuthService-VGAuthLog.Tpo .deps/VGAuthService-VGAuthLog.Po
mv -f .deps/VGAuthService-VGAuthUtil.Tpo .deps/VGAuthService-VGAuthUtil.Po
mv -f .deps/VGAuthService-random.Tpo .deps/VGAuthService-random.Po
mv -f .deps/VGAuthService-main.Tpo .deps/VGAuthService-main.Po
mv -f .deps/VGAuthService-netPosix.Tpo .deps/VGAuthService-netPosix.Po
mv -f .deps/VGAuthService-usercheck.Tpo .deps/VGAuthService-usercheck.Po
mv -f .deps/VGAuthService-log.Tpo .deps/VGAuthService-log.Po
mv -f .deps/VGAuthService-signalSource.Tpo .deps/VGAuthService-signalSource.Po
mv -f .deps/VGAuthService-gio.Tpo .deps/VGAuthService-gio.Po
mv -f .deps/VGAuthService-prefs.Tpo .deps/VGAuthService-prefs.Po
mv -f .deps/VGAuthService-filePosix.Tpo .deps/VGAuthService-filePosix.Po
mv -f .deps/VGAuthService-ticket.Tpo .deps/VGAuthService-ticket.Po
mv -f .deps/VGAuthService-fileLogger.Tpo .deps/VGAuthService-fileLogger.Po
mv -f .deps/VGAuthService-service.Tpo .deps/VGAuthService-service.Po
mv -f .deps/VGAuthService-i18n.Tpo .deps/VGAuthService-i18n.Po
mv -f .deps/VGAuthService-verify.Tpo .deps/VGAuthService-verify.Po
mv -f .deps/VGAuthService-vmxlog.Tpo .deps/VGAuthService-vmxlog.Po
mv -f .deps/VGAuthService-servicePosix.Tpo .deps/VGAuthService-servicePosix.Po
mv -f .deps/VGAuthService-certverify.Tpo .deps/VGAuthService-certverify.Po
mv -f .deps/VGAuthService-proto.Tpo .deps/VGAuthService-proto.Po
mv -f .deps/VGAuthService-alias.Tpo .deps/VGAuthService-alias.Po
In file included from ../serviceImpl/saml-xml-security-c.cpp:91:
../serviceImpl/samlInt.hpp:136:1: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
 auto_ptr<XMLGrammarPool> SAMLCreateAndPopulateGrammarPool();
 ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp:219:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
 static auto_ptr<DSIGKeyInfoX509> SAMLFindKey(const XSECEnv &secEnv,
        ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp: In function 'VGAuthError SAML_Init()':
../serviceImpl/saml-xml-security-c.cpp:241:7: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
       auto_ptr<XMLGrammarPool> myPool = SAMLCreateAndPopulateGrammarPool();
       ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp: At global scope:
../serviceImpl/saml-xml-security-c.cpp:281:1: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
 auto_ptr<XMLGrammarPool>
 ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp: In function 'std::auto_ptr<xercesc_3_2::XMLGrammarPool> SAMLCreateAndPopulateGrammarPool()':
../serviceImpl/saml-xml-security-c.cpp:284:4: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
    auto_ptr<XMLGrammarPool> newPool(new XMLGrammarPoolImpl(XMLPlatformUtils::fgMemoryManager));
    ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp:329:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
          return auto_ptr<XMLGrammarPool>(NULL);
                 ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp: In function 'void SAML_Reload()':
../serviceImpl/saml-xml-security-c.cpp:375:4: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
    auto_ptr<XMLGrammarPool> myPool = SAMLCreateAndPopulateGrammarPool();
    ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp: In function 'xercesc_3_2::DOMDocument* SAMLValidateSchemaAndParse(xercesc_3_2::XercesDOMParser&, const char*)':
**../serviceImpl/saml-xml-security-c.cpp:698:4: error: 'xsecsize_t' was not declared in this scope**
    **xsecsize_t errorCount = parser.getErrorCount();**
    ^~~~~~~~~~
../serviceImpl/saml-xml-security-c.cpp:698:4: note: suggested alternative: 'ssize_t'
    xsecsize_t errorCount = parser.getErrorCount();
    ^~~~~~~~~~
    ssize_t
../serviceImpl/saml-xml-security-c.cpp:699:8: error: 'errorCount' was not declared in this scope
    if (errorCount > 0) {
        ^~~~~~~~~~
../serviceImpl/saml-xml-security-c.cpp:699:8: note: suggested alternative: 'error_t'
    if (errorCount > 0) {
        ^~~~~~~~~~
        error_t
../serviceImpl/saml-xml-security-c.cpp: In function 'bool SAMLCheckSignature(xercesc_3_2::DOMDocument*, std::vector<std::__cxx11::basic_string<char> >&)':
../serviceImpl/saml-xml-security-c.cpp:1079:4: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
    auto_ptr<DSIGKeyInfoX509> keyInfo = SAMLFindKey(secEnv, sigElem);
    ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp: At global scope:
../serviceImpl/saml-xml-security-c.cpp:1246:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
 static auto_ptr<DSIGKeyInfoX509>
        ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp: In function 'std::auto_ptr<DSIGKeyInfoX509> SAMLFindKey(const XSECEnv&, const xercesc_3_2::DOMElement*)':
../serviceImpl/saml-xml-security-c.cpp:1254:14: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
       return auto_ptr<DSIGKeyInfoX509>(NULL);
              ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
../serviceImpl/saml-xml-security-c.cpp:1257:4: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
    auto_ptr<DSIGKeyInfoX509> keyInfo(new DSIGKeyInfoX509(&secEnv,
    ^~~~~~~~
In file included from /usr/include/c++/8/memory:80,
                 from ../serviceImpl/saml-xml-security-c.cpp:26:
/usr/include/c++/8/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;

**Comment by oliverkurth** [comment]
Is there a specific reason you need to build with xml-security? You can build with xmlsec1 (the default), with the same functionality.

**Comment by battulgag** [comment]
Thanks.
Yes. Reason is xml-security. Building success using xmlsec1 on CentOS 8.
Bulding success using xml-security-c-1.7.3 on CentOS 7.
Maybe later will be support xml-security-c-2.0.2 ?

**Comment by oliverkurth** [comment]
No, we are very likely to drop support for xml-security-c in the future.

**Comment by stanguturi** [comment]
> No, we are very likely to drop support for xml-security-c in the future.

Thanks Oliver for the update. Closing this issue.
