### ISSUE TITLE
Open-VM-Tools crash leading to a black screen in the VMware Horizon Seession

### ISSUE THREAD

**Issue by lenzker** [vmware/open-vm-tools#448]
Hallo,

We are currently faced with an issue that out-of a sudden VMware Horizon Virtual Desktop Sessions (with NVIDIA Grid vGPU) on Red Hat 7.5 fail with a black screen. During the investigation we figured  out that a certain point in time the open-vm-tools fail (open-vm-tool 12.5).

Since the Horizon Agent depends on a functional vmware-tools we need to fix the root cause causing this crash. Any idea what causes and how to fix that issue?

/var/log/messages

// Jul  7 10:21:25 vmcae10546 kernel: NMI watchdog: BUG: soft lockup - CPU#6 stuck for 22s! [VMwareBlastServ:3265]
Jul  7 10:21:25 vmcae10546 kernel: Modules linked in: fuse nvidia_uvm(OE) ipt_REJECT nf_reject_ipv4 iptable_filter nfsv3 nfs fscache vmw_vsock_vmci_transport vsock nvidia_drm(POE) nvidia_modeset(POE) nvidia(POE) iosf_mbi ppdev crc32_pclmul vmw_balloon ghash_clmulni_intel aesni_intel lrw gf128mul glue_helper ablk_helper cryptd pcspkr joydev ipmi_devintf ipmi_msghandler sg vmw_vmci nfit i2c_piix4 libnvdimm parport_pc shpchp parport nfsd nfs_acl lockd grace auth_rpcgss sunrpc binfmt_misc ip_tables ext4 mbcache jbd2 sr_mod cdrom ata_generic pata_acpi vmwgfx drm_kms_helper sd_mod crc_t10dif crct10dif_generic syscopyarea sysfillrect sysimgblt fb_sys_fops ttm drm ahci libahci ata_piix crct10dif_pclmul crct10dif_common crc32c_intel libata serio_raw i2c_core vmw_pvscsi vmxnet3 dm_mirror dm_region_hash dm_log dm_mod
Jul  7 10:21:25 vmcae10546 kernel: CPU: 6 PID: 3265 Comm: VMwareBlastServ Kdump: loaded Tainted: P           OE  ------------   3.10.0-862.9.1.el7.x86_64 #1
Jul  7 10:21:25 vmcae10546 kernel: Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 12/12/2018
Jul  7 10:21:25 vmcae10546 kernel: task: ffff94e6072c0fd0 ti: ffff94d6f951c000 task.ti: ffff94d6f951c000
Jul  7 10:21:25 vmcae10546 kernel: RIP: 0010:[<ffffffffc076730b>]  [<ffffffffc076730b>] _nv010249rm+0x11b/0x330 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: RSP: 0018:ffff94d6f951fb48  EFLAGS: 00000286
Jul  7 10:21:25 vmcae10546 kernel: RAX: ffff94e630b2ca90 RBX: 0000000000000282 RCX: ffff94e6272d9290
Jul  7 10:21:25 vmcae10546 kernel: RDX: ffff94e5c16c0690 RSI: 0000000000000000 RDI: ffff94e5c16c0690
Jul  7 10:21:25 vmcae10546 kernel: RBP: ffff94e63d59ab00 R08: ffff94d9f67fcec0 R09: 0000000180400037
Jul  7 10:21:25 vmcae10546 kernel: R10: 00000000f67fc101 R11: ffffec750ed9ff00 R12: ffff94d6f951fb70
Jul  7 10:21:25 vmcae10546 kernel: R13: ffffec753ef7dc00 R14: ffff94d6f951fb60 R15: ffffec753fd09b40
Jul  7 10:21:25 vmcae10546 kernel: FS:  00007f601b6017c0(0000) GS:ffff94e67fd80000(0000) knlGS:0000000000000000
Jul  7 10:21:25 vmcae10546 kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jul  7 10:21:25 vmcae10546 kernel: CR2: 00007f5ff76a5007 CR3: 0000000f9f7d6000 CR4: 00000000007607e0
Jul  7 10:21:25 vmcae10546 kernel: PKRU: 55555554
Jul  7 10:21:25 vmcae10546 kernel: Call Trace:
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc06eb4f6>] ? _nv027245rm+0x746/0x880 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc06e979b>] ? _nv027246rm+0x19b/0x840 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0d36909>] ? _nv003594rm+0x9/0x20 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0d3401b>] ? _nv004345rm+0x1b/0x80 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0d31047>] ? _nv011180rm+0x2d7/0x350 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0d2e5a9>] ? _nv035355rm+0x89/0x120 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0d2f4b2>] ? _nv035354rm+0x332/0x500 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0721314>] ? _nv034146rm+0xf4/0x1e0 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0721442>] ? _nv034147rm+0x42/0x70 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc072d29b>] ? _nv007464rm+0x4b/0x90 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0663f42>] ? os_acquire_spinlock+0x12/0x20 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0da7ef1>] ? _nv000909rm+0x601/0x940 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0db2544>] ? rm_ioctl+0x54/0xb0 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0658100>] ? nvidia_ioctl+0xa0/0x7a0 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0658629>] ? nvidia_ioctl+0x5c9/0x7a0 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffc0654083>] ? nvidia_frontend_unlocked_ioctl+0x43/0x50 [nvidia]
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffa7c30350>] ? do_vfs_ioctl+0x350/0x560
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffa7c3dde4>] ? mntput+0x24/0x40
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffa7c1d7e6>] ? __fput+0x186/0x260
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffa7c30601>] ? SyS_ioctl+0xa1/0xc0
Jul  7 10:21:25 vmcae10546 kernel: [<ffffffffa8120795>] ? system_call_fastpath+0x1c/0x21
Jul  7 10:21:25 vmcae10546 kernel: Code: ff ff 66 0f 1f 44 00 00 48 89 41 28 e9 49 ff ff ff 0f 1f 80 00 00 00 00 49 39 04 24 0f 84 90 00 00 00 48 85 c0 0f 84 ce 00 00 00 <80> 78 18 00 0f 85 86 00 00 00 48 85 db 0f 84 a8 00 00 00 48 8b

**Comment by johnwvmw** [comment]
There is no tools 12.5 release, please provide the correct version of open-vm-tools being used on your Red Hat 7.5 guest?

How did you determine that the open-vm-tools failed?

The trace shows the  spinlock in the Nvidia driver which is supplsystem?ied through Red Hat or Nividia.   It is not supplied in the open-vm-tools packages supplied by Red Hat.   Where there any recent driver updates applied to this Red Hat

**Comment by lenzker** [comment]
Sorry.. I meant 10.2.5.. After digging deep into the topic we have in-deed opened a ticket with Nvidia which driver current vGPU driver  is used within the system. Our first indicator has been a crash of the open-vm-tools but it seems to be some different component that is causing all the pain :). Thanks for helping!

**Comment by stanguturi** [comment]
> Sorry.. I meant 10.2.5.. After digging deep into the topic we have in-deed opened a ticket with Nvidia which driver current vGPU driver is used within the system. Our first indicator has been a crash of the open-vm-tools but it seems to be some different component that is causing all the pain :). Thanks for helping!

Thanks for the update. Closing this issue, since this is not an OVT issue.
