### ISSUE TITLE
make install successful but there is not vmtoolsd.service

### ISSUE THREAD

**Issue by songdongping** [vmware/open-vm-tools#449]
In my centos-7.8，I try to compile and install open-vm-tools by the source code. But when i make install successfully, i cannot find any vmtoolsd.service in my OS. I want to ask for the reason why be this.

**Comment by johnwvmw** [comment]
Unfortunately there is no startup script in the open-vm-tools.  Different Linux distributions use different init systems and init scripts.  Each Linux vendor adds the needed files and scripts to their open-vm-tools packages.

The simplest approach might be to use the existing systemd files from the open-vm-tools packages for CentOS 7

open-vm-tools
==========
./usr/lib/modules-load.d/open-vm-tools.conf
./usr/lib/systemd/system/mnt-hgfs.mount
./usr/lib/systemd/system/vgauthd.service
./usr/lib/systemd/system/vmtoolsd.service

open-vm-tools-desktop
================
./usr/lib/systemd/system/run-vmblock\x2dfuse.mount

**Comment by songdongping** [comment]
Thanks for your explanation, but in my system, I cannot find the file named open-vm-tools.conf. My install steps are as follows:
1、aclocal
2、autoreconf -i
3、autoconf
4、automake --add-missing
5、./configure
6、make
7、make install
There are some warnings but no error, but i can make install.  But there is no open-vm-tools.conf，why? Should i write a file named open-vm-tools.conf?

**Comment by songdongping** [comment]
> Unfortunately there is no startup script in the open-vm-tools. Different Linux distributions use different init systems and init scripts. Each Linux vendor adds the needed files and scripts to their open-vm-tools packages.
> 
> The simplest approach might be to use the existing systemd files from the open-vm-tools packages for CentOS 7
> 
> # open-vm-tools
> ./usr/lib/modules-load.d/open-vm-tools.conf
> ./usr/lib/systemd/system/mnt-hgfs.mount
> ./usr/lib/systemd/system/vgauthd.service
> ./usr/lib/systemd/system/vmtoolsd.service
> 
> # open-vm-tools-desktop
> ./usr/lib/systemd/system/run-vmblock\x2dfuse.mount

Thanks for your explanation, but in my system, I cannot find the file named open-vm-tools.conf. My install steps are as follows:
1、aclocal
2、autoreconf -i
3、autoconf
4、automake --add-missing
5、./configure
6、make
7、make install
There are some warnings but no error, but i can make install. But there is no open-vm-tools.conf，why? Should i write a file named open-vm-tools.conf?

**Comment by stanguturi** [comment]
> There are some warnings but no error, but i can make install. But there is no open-vm-tools.conf，why? Should i write a file named open-vm-tools.conf?

You need to create a new open-vm-tools.conf (if not present already) in the guest VM. Check https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/tools.conf for a reference to sample tools.conf file. As a part of the installation, this file is installed as 'tools.conf.example'.
