### ISSUE TITLE
Cannot compile on Debian testing/stretch with gtkmm

### ISSUE THREAD

**Issue by fernandodeperto** [vmware/open-vm-tools#45]
While trying to compile the code using the configure options:

```
./configure --disable-deploypkg
```

the compilation fails, with the first error being:

```
In file included from /usr/include/c++/5/type_traits:35:0,
                 from /usr/include/sigc++-2.0/sigc++/visit_each.h:22,
                 from /usr/include/sigc++-2.0/sigc++/functors/slot.h:6,
                 from /usr/include/sigc++-2.0/sigc++/signal_base.h:27,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:8,
                 from /usr/include/sigc++-2.0/sigc++/connection.h:22,
                 from ../../../../services/plugins/dndcp/dnd/copyPasteRpc.hh:28,
                 from ../../../../services/plugins/dndcp/dndGuest/copyPasteRpcV3.hh:29,
                 from ../../../../services/plugins/dndcp/dndGuest/copyPasteRpcV3.cc:26:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options
```

If I use the configure options:

```
    ./configure --disable-deploypkg --disable-gtkmm
```

the compilation succeed but then copy and paste doesn't work anymore, which is quite important to me. 

Is thre any workaround? If you need more information about my environment, feel free to ask. Basically, it's a freshly installed Debian Stretch.

**Comment by ravindravmw** [comment]
Please try this:

$ CXXFLAGS=-std=gnu++11 ./configure <your_options>

**Comment by fernandodeperto** [comment]
Hi. It worked, thank you for the suggestion. When I saw the error I thought about changing the standard, but in my experience it has never been a good idea so I didn't give it a try.

Just one more question, it could be related. When I execute ```vmware-user-suid-wrapper```, I see the error ```vmware-user: could not open /proc/fs/vmblock/dev``` but it works. I mean, I can change the resolution based on the window size. Is there something missing from my compilation?

**Comment by fernandodeperto** [comment]
For future reference to anyone that wants to compile version 10.0 on Debian Stretch, I had to add the following packages:

    sudo apt-get install libgtkmm-2.4-dev libgtk2.0-dev libxtst-dev libxrandr-dev libxrender-dev libxi-dev libxinerama-dev libxext-dev libx11-dev libtool libdumbnet-dev libprocps4-dev libxml-security-c-dev libxerces-c-dev libssl-dev libpam0g-dev libglib2.0-dev

and used the configure options:

    CXXFLAGS=-std=gnu++11 ../configure --disable-deploypkg --disable-docs

**Comment by bzed** [comment]
You could just use the package in debian, which comes with deploypg support and docs....

**Comment by stanguturi** [comment]
> and used the configure options:
> 
> ```
> CXXFLAGS=-std=gnu++11 ./configure --disable-deploypkg --disable-docs
> ```

Thanks for confirming that CXXFLAGS option worked.
