### ISSUE TITLE
Missing Error Check of function HgfsRemoveFromCacheInternal()

### ISSUE THREAD

**Issue by lc3412** [vmware/open-vm-tools#450]
Hi, 

From the usage pattern of function HgfsRemoveFromCacheInternal(),  I notice that the function should check the error condition and then do some handling actions, shown in the following code.

https://github.com/vmware/open-vm-tools/blob/f72e314e8b0df4e80c6b5f9b0c66ad2e9ce02e19/open-vm-tools/lib/hgfsServer/hgfsServer.c#L6270-L6273

https://github.com/vmware/open-vm-tools/blob/f72e314e8b0df4e80c6b5f9b0c66ad2e9ce02e19/open-vm-tools/lib/hgfsServer/hgfsServer.c#L5286-L5289
====================================================================

However, there exists a missing check in the same file. See the following code:

https://github.com/vmware/open-vm-tools/blob/f72e314e8b0df4e80c6b5f9b0c66ad2e9ce02e19/open-vm-tools/lib/hgfsServer/hgfsServer.c#L4963-L4964

**Comment by jonathanvmw** [comment]
@lc3412 

Thanks for the question.

The return value can be ignored at line 4964.  In that instance, HgfsRemoveFromCacheInternal is called from HgfsServerExitSessionInternal, which tears down and destroys an HGFS session.  If HgfsRemoveFrom CacheInternal fails in this context, it would indicate either (1) the file node doesn't exist, which means the file has been closed and the handle is stale, or (2) the close of the file referenced by the handle failed.  Either way, the session teardown is still able to complete successfully.

**Comment by lc3412** [comment]
Thanks for your explanation!
