### ISSUE TITLE
Failed to build open-vm-tools on Linux From Scratch

### ISSUE THREAD

**Issue by zhanghua000** [vmware/open-vm-tools#451]
I am working with devel branch and trying to compile this tool for LFS on VMware, but ld returns an error at last. It shows that `multiple definition of 'GDK_SELECTION_TYPE_TIMESTAMP'` and `multiple definition of 'GDK_SELECTION_TYPE_UTF8_STRING'`. The error message part of full output are listed below:
```
/usr/bin/ld: .libs/libdndcp_la-copyPasteUIX11.o:/sources/open-vm-tools/open-vm-tools/services/plugins/dndcp/copyPasteUIX11.cpp:105: multiple definition of `GDK_SELECTION_TYPE_UTF8_STRING'; .libs/libdndcp_la-copyPasteCompatX11.o:/sources/open-vm-tools/open-vm-tools/services/plugins/dndcp/copyPasteCompatX11.c:80: first defined here
/usr/bin/ld: .libs/libdndcp_la-copyPasteUIX11.o:/sources/open-vm-tools/open-vm-tools/services/plugins/dndcp/copyPasteUIX11.cpp:101: multiple definition of `GDK_SELECTION_TYPE_TIMESTAMP'; .libs/libdndcp_la-copyPasteCompatX11.o:/sources/open-vm-tools/open-vm-tools/services/plugins/dndcp/copyPasteCompatX11.c:76: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by johnwvmw** [comment]
The fix has recently been made in house and will probably appear in the "devel" changes later this week.

In the mean time, you can proceed by removing the following lines from *services/plugins/dndcp/copyPasteUIX11.cpp*

> -#ifndef GDK_SELECTION_TYPE_TIMESTAMP
> -GdkAtom GDK_SELECTION_TYPE_TIMESTAMP;
> -#endif
> -
> -#ifndef GDK_SELECTION_TYPE_UTF8_STRING
> -GdkAtom GDK_SELECTION_TYPE_UTF8_STRING;
> -#endif
> -

This issue should be updated when the change is committed to the "devel" branch.

**Comment by johnwvmw** [comment]
The change has been committed to the "devel" branch.   Closing this issue.
