### ISSUE TITLE
vmware_guest_network module not working as expected, it is not able to change a Live vm Network adapter settings

### ISSUE THREAD

**Issue by vivekanand552** [vmware/open-vm-tools#455]
Hello Team,

I am trying to automate the OVA/VM Template deployment using ansible and I have a use case to change the network adapter settings of a live vm from one VM Portgroup to another VM portgroup.

I am using "vmware_guest_network" module to achieve the same but somehow the network adapter is not getting changed as expected.

Ansible version: 2.9.5.

the module code is as below

 - name: setting the guest network
    vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: Watford
      validate_certs: no
   #   name: test_vm_rhel_0001
      moid: vm-18320
      gather_network_info: false
      networks:
        - name: "vlan_144_vivek"
          vlan: 144
          state: present
          connected: true
          device_type: vmxnet3
          label: "Network adapter 1"
          mac_addr: "00:50:56:b3:6c:e0"
         # name: DVSwitch: de f8 33 50 8f 55 dc 92-58 82 62 f1 cb ff 41 5e
          dvswitch_name: hcs-iww-nxsw-1-n1kv-VDS
          start_connected: true
          wake_onlan: true

When i run the playbook, the "vmware_guest_network module" shows something has changed but when i go into the GUI and the vm portgroup mapped to the network adapter its still not changed and the same portgroup previously mapped is still there

result as below

TASK [setting the guest network] ******************************************************************************************************************************************************************
task path: /root/viv_vmware_ucs_latest.yaml:202
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1596636333.41-205840345625537 `" && echo ansible-tmp-1596636333.41-205840345625537="` echo /root/.ansible/tmp/ansible-tmp-1596636333.41-205840345625537 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest_network.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-29658S_2c2N/tmpKWWpVm TO /root/.ansible/tmp/ansible-tmp-1596636333.41-205840345625537/AnsiballZ_vmware_guest_network.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1596636333.41-205840345625537/ /root/.ansible/tmp/ansible-tmp-1596636333.41-205840345625537/AnsiballZ_vmware_guest_network.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1596636333.41-205840345625537/AnsiballZ_vmware_guest_network.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1596636333.41-205840345625537/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "cluster": null,
            "datacenter": "Watford",
            "esxi_hostname": null,
            "folder": null,
            "gather_network_info": false,
            "hostname": "hcs-iww-vcent01.wahp.cww-hcs.com",
            "moid": "vm-18320",
            "name": null,
            "networks": [
                {
                    "connected": true,
                    "device_type": "vmxnet3",
                    "dvswitch_name": "hcs-iww-nxsw-1-n1kv-VDS",
                    "label": "Network adapter 1",
                    "mac_addr": "00:50:56:b3:6c:e0",
                    "name": "vlan_144_vivek",
                    "start_connected": true,
                    "state": "present",
                    "unit_number": 7,
                    "vlan": 144,
                    "wake_onlan": true
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false
        }
    },
    "network_data": {
        "0": {
            "allow_guest_ctl": true,
            "connected": true,
            "device_type": "VMXNET3",
            "label": "Network adapter 1",
            "mac_addr": "00:50:56:b3:6c:e0",
            "name": "DVSwitch: de f8 33 50 8f 55 dc 92-58 82 62 f1 cb ff 41 5e",
            "start_connected": true,
            "unit_number": 7,
            "wake_onlan": true
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=10   changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

But still in vm the previous portgroup is mapped
![vm portgroup issue ansible](https://user-images.githubusercontent.com/66349683/89422872-7e555380-d753-11ea-8127-a2901eae5f42.png)

 as shown in attcahment.

Request kind help in resolving this issue.

Thanks in advance!

Regards
Vivekanand

**Comment by dsouders** [comment]
@vivekanand552

This doesn't sound like a problem with open-vm-tools.
I'm checking internally for any ansible experts who might have suggestions for you.
Meanwhile, have you tried the GitHub ansible forum?  https://github.com/ansible

**Comment by dsouders** [comment]
@vivekanand552

One of our internal experts suggested this forum:  https://github.com/ansible-collections/vmware
And also this website: https://galaxy.ansible.com/community/vmware

**Comment by stanguturi** [comment]
> @vivekanand552
> 
> One of our internal experts suggested this forum: https://github.com/ansible-collections/vmware
> And also this website: https://galaxy.ansible.com/community/vmware

Not a open-vm-tools issue. As @dsouders mentioned, please post the question in the other forums. Closing. Thanks.
