### ISSUE TITLE
Any file copy from Ubuntu guest to Windows host share fails if I/O size >= 64KB

### ISSUE THREAD

**Issue by horshack-dpreview** [vmware/open-vm-tools#456]
This configuration has worked for years but suddenly all my file copies from my Ubuntu guest VM to my share on my Windows host OS fails with an I/O error. After some trial and error I determined the error only occurs if the I/O size for the copy is >= 64KB, which the GNOME UI shell uses, along with apps such as Firefox (downloading files into the share) and shell utilities such as cp. The only way I've been able to work around it is by using dd and specifying a block size less than 64K, such as:

dd if='/home/user/Pictures/screenshot.png' of=/mnt/hgfs/myshare/screenshot.png bs=63k

If I specify 64k in the above command line I get a generic "Input/output error".

I don't see the error when copying in the other direction, ie from my Windows host share to my Ubuntu guest from within the Ubuntu guest.

I'm running Ubuntu 20.04, open-vm-tools 2:11.1.0-2~ubuntu20.04.1 on the guest VM and Windows 10 on the host. I see the error for every share I've tried to copy to.

**Comment by horshack-dpreview** [comment]
Oops, looks like this has been reported here: https://github.com/vmware/open-vm-tools/issues/437

**Comment by sebma** [comment]
Hi, is there a workaround that actually works ?

**Comment by lousybrit** [comment]
> Hi, is there a workaround that actually works ?

Did you try the max_write option on the mount?
.host:/ /mnt/hgfs fuse.vmhgfs-fuse noauto,allow_other,max_write=61440 0 0
