### ISSUE TITLE
Give a nice man-page/elaborate help message for vmware-toolbox-cmd & vmware-rpctool

### ISSUE THREAD

**Issue by sshedi** [vmware/open-vm-tools#459]
Hi,

Please provide a man-page/elaborate help message for vmware-rpctool & vmware-toolbox-cmd with and please cover all possible options, will be much better with examples. Or if there is something available already, please give more info on it.

Thanks,
Shedi

**Comment by sshedi** [comment]
Any updates on this request? If not feasible please close this issue.

**Comment by stanguturi** [comment]
> Thanks for the response @lemke1458 but this user-guide doesn't give an extensive information on available options in rpctool and toolboxcmd. Can you please take this as a feature request?

Please check https://docs.vmware.com/en/VMware-Tools/11.3.0/com.vmware.vsphere.vmwaretools.doc/GUID-009A09B7-60F0-4B38-8908-C7D712E7E63E.html for the detailed information (usage and various other sub commands available) about 'toolboxcmd' utility. 

For 'rpctool', the help message printed with '-h' option is sufficient. Please check https://github.com/vmware/open-vm-tools/blob/677ddf97a85f8b96b95ac60f54b59df264d5c4d5/open-vm-tools/rpctool/rpctool.c#L54

Closing this issue. Thanks.
