### ISSUE TITLE
Getting source IP from a VMWork Workstation VM

### ISSUE THREAD

**Issue by flamecopper** [vmware/open-vm-tools#463]
Hi there,

I heard from one of my co-worker that:

- VM has Cisco AnyConnect VPN installed and can get IP xx.xx.xx.xx
- I want my base machine linux to be able to get xx.xx.xx.xx 

Can anyone tell me how the following can be done?

**Comment by vmwzhangv** [comment]
I don't understand your question ? You said you VM has VPN and is already getting IP. When you say "base machine linux",  do you actually mean "host machine" where your VMs are running ?

**Comment by stanguturi** [comment]
I don't think this issue is anyway related to open-vm-tools. Please post the question in [VMware Workstation community](https://communities.vmware.com/t5/VMware-Workstation/ct-p/3019-home) and see if anyone can provide help. Closing the issue.
