### ISSUE TITLE
open vm tools for freebsd?

### ISSUE THREAD

**Issue by mintchoco0122** [vmware/open-vm-tools#465]
does it work for freebsd, not just for linux? If not, is there any development for freebsd?

**Comment by johnwvmw** [comment]
Yes,  open-vm-tools is part of the FreeBSD /usr/ports which contains over 23,000 OSS projects that can be built for FreeBSD.

But the easiest solution is to install pre-built packages from the FreeBSD package repositories.

   pkg install open-vm-tools   - onto a FBSD system with a graphical desktop such as Gnome 3

   pkg install open-vm-tools-nox11   -  onto a FreeBSD server system - w/o a graphical desktop

FreeBSD also provides a community version of the vmxnet3 NIC driver.

**Comment by mintchoco0122** [comment]
But its version is 11.1.0.2 and the newest version of VMware workstation is 16. Is there version 16 or versions between open-vm-tools and vmware workstation is not related?

**Comment by mintchoco0122** [comment]
Well, I found out that 11.1.0 is the newest version for open-vm-tools. Thanks for all your help!

**Comment by johnwvmw** [comment]
They are separate products.  WorkStation  is a VMware hypervisor that is able to run Windows, Linux, FreeBSD guest - virtual machines.   WS is only available for installation on Linux and Windows.  

VMware Tools (Windows) and open-vm-tools (Linux and FreeBSD) install in the various guest OS's and consists of a suite of virtualization utilities that improves the functionality, administration, and management of virtual machines within a VMware environment.
