### ISSUE TITLE
glibc 2.32 causes tirpc related build errors

### ISSUE THREAD

**Issue by cpaelzer** [vmware/open-vm-tools#468]
Looks like:
`fatal error: rpc/types.h: No such file or directory`

open-vm-tools already detects libtripc in configure:
```
      checking for libtirpc (via pkg-config)... yes
      configure: tirpc is needed: yes
      configure: building with libtirpc
```

And build uses it most of the time:
```
      ... -DUSE_TIRPC -I/usr/include/tirpc ...
      ... -ltirpc ...
```

Yet with glibc2.32 finally dropping --enable-obsolete-rpc that finally
removes /usr/include/rpc/rpc.h and such and only leaves the proper
/usr/include/tirpc/rpc/rpc.h around.

These are broken by libc6-dev dropping rpc.h being taken over by libtirpc-dev
oaths changed:
Before:
```
# dpkg -S rpc/types.h rpc/rpc.h
libc6-dev:amd64: /usr/include/rpc/types.h
libc6-dev:amd64: /usr/include/rpc/rpc.h
```
After:
```
# dpkg -S rpc/types.h rpc/rpc.h
libtirpc-dev:amd64: /usr/include/tirpc/rpc/types.h
libtirpc-dev:amd64: /usr/include/tirpc/rpc/rpc.h
```

This causes several build issues as the libtripc flags are in XDR_
variables which are not present in all places where XDR related headers
are includes.
    
Add some more of these flags in the places that got flagged by build
fails to fix compilation with glibc >=2.32.

**Comment by cpaelzer** [comment]
See #469 for a proposed fix

**Comment by dsouders** [comment]
Thank you for reporting this issue and also for providing your fix!
An internal bug as been filed to address the problem.

**Comment by johnwvmw** [comment]
Fixed committed  to both the "devel" (e82101b) and "stable-11.2.x" (aa02477) branch for the next scheduled 11.2.x update release.

Closing this issue as fixed.

**Comment by cpaelzer** [comment]
Thank you @johnwvmw

**Comment by oyekan97** [comment]
I encountered this error when trying to install Seismic Unix on my window. Please help


![Screenshot_20230208_064447](https://user-images.githubusercontent.com/49397747/217630937-8d25af21-60d3-4da7-adc9-6a22d44b4c7a.png)

**Comment by lemke1458** [comment]
> I encountered this error when trying to install Seismic Unix on my window. Please help
> 
> ![Screenshot_20230208_064447](https://user-images.githubusercontent.com/49397747/217630937-8d25af21-60d3-4da7-adc9-6a22d44b4c7a.png)

Your issue appears to have nothing to with with open-vm-tools, since those files are not part of open-vm-tools.
Try the discussion board for whatever it is you're trying to build.

**Comment by johnwvmw** [comment]
@oyekan97    I think that the open-source project that you are looking for is https://github.com/JohnWStockwellJr/SeisUnix.

I see sever issues raised there that look quite similar to yours.
