### ISSUE TITLE
SCSI timer timeout value increase missing in open-vm-tools

### ISSUE THREAD

**Issue by acjohnson** [vmware/open-vm-tools#47]
In various releases of VMWare Tools a udev rule stored in `/etc/udev/rules.d/99-vmware-scsi-udev.rules` was created by the OSP packages to prevent SCSI subsystem intervention during storage head failovers and storage vMotions, etc. The following KB article describes this behavior:

http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1009465

The `open-vm-tools` packages should also incorporate the same udev rule.

**Comment by bernhardschmidt** [comment]
As far as I can tell this has been solved with https://github.com/vmware/open-vm-tools/commit/41c0f0812fd02bf9db2c276c675549ce9685af8b

**Comment by oliverkurth** [comment]
That's right. Thanks @bernhardschmidt!
