### ISSUE TITLE
Support OpenGL 4.1 for Workstation Pro 16.0

### ISSUE THREAD

**Issue by RoanBrand** [vmware/open-vm-tools#476]
OpenGL 4.1 now supported with workstation v16, but still only OpenGL 3.3 available in guest.

https://blogs.vmware.com/workstation/2020/09/workstation-16-now-available.html

https://docs.vmware.com/en/VMware-Workstation-Pro/16.0/com.vmware.ws.using.doc/GUID-EA588485-718A-4FD8-81F5-B6E1F04C5788.html

As far as I can tell the next step is to support it here for it to work? Might be wrong about that.
Any ideas on effort and ETA?

**Comment by johnwvmw** [comment]
@RoanBrand   Hi Roan,

You haven't indicated which guest OS and release version you are using here so my responses may be somewhat broad.

- You may need to upgrade the VMware hardware version of the guest VM.
- I trust that you have done any necessary display configuration changes needed per the preceding doc section - Configure Display Settings for a Virtual Machine.
- For Windows guests, the OpenGL 4.1 driver is part of the VMware Tools 11.1.5 that is available in WS 16.  A tools upgrade to 11.1.5 will be needed.
- For Linux guests, I am told that you will need Mesa 20.2.0 and Linux kernel version 5.7.

I hope that helps.

**Comment by RoanBrand** [comment]
Hi,

I was using ubuntu 20.04 as guest. I just saw 20.10 beta was out with kernel 5.8 and tried it.

Confirmed working !

Thanks
