### ISSUE TITLE
configure.ac:133: error: possibly undefined macro: AC_MSG_WARN (Ubuntu 20.04 ARM)

### ISSUE THREAD

**Issue by DennisFaucher** [vmware/open-vm-tools#478]
Hi,

Does this build on Ubuntu ARM? TIA

$ autoreconf -i
configure.ac:133: error: possibly undefined macro: AC_MSG_WARN
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:371: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Comment by DennisFaucher** [comment]
Found the instructions to overcome this:

apt update
apt install -y automake-1.15 pkg-config libtool libmspack-dev libglib2.0-dev libpam0g-dev libssl-dev libxml2-
dev libxmlsec1-dev libx11-dev libxext-dev libxinerama-dev libxi-dev libxrender-dev libxrandr-dev libgtk2.0-dev
libgtk-3-dev libgtkmm-3.0-dev

git clone https://github.com/vmware/open-vm-tools.git
cd open-vm-tools/open-vm-tools/

autoreconf -i
./configure
sudo make
sudo make install
sudo ldconfig

**Comment by eegull** [comment]
I believe the magic here is installing "pkg-config".  This is all I needed to do on Ubuntu 20.04 to fix a similar problem.
