### ISSUE TITLE
Anyplan for vm hardware 17 support, specifically watchdog timer?

### ISSUE THREAD

**Issue by ecrode** [vmware/open-vm-tools#489]
Esxi 7 was out since April 2020, yet I cannot find official support for additional features (specifically WG timer) that HW v 17 brought with it's release.

Is there a scripted workaround available to whack the dog (so to speak) and allow watch dog timer be used with machines running open-vm-tools?

Thank you

**Comment by dsouders** [comment]
Please refer to:  https://blogs.vmware.com/vsphere/2020/05/vsphere-7-virtual-watchdog.html

No open-vm-tools support should be required.  What specifically do you need?

**Comment by ecrode** [comment]
Thanks @dsouders, I've been trying to get watchdog support up and running on official photon os vm and can't find any info on how to go about doing that. I have a reverse proxy running (via docker) on it and once in a blue moon nginx locks up, makes the system unresponcive (to ssh / console) and uses 100% of the harddrive IO to read who knows what. 

Haven't gotten to the bottom of the issue yet (not sure were the fault lies: nginx (most likely), docker or photon itself), but it happens seldom enough that it's not really an issue. The problem is I need to manually restart the vm and would love for watchdog to take care of that for me.

**Comment by dsouders** [comment]
I've sent a message to the Photon dev team asking what is needed to enable a virtual watchdog timer.  Please stay tuned.  Thanks!

**Comment by dsouders** [comment]
The Photon team responded to your question: https://github.com/vmware/photon/issues/1091

While that's not the answer you want, they are aware that watchdog support is desired.  Thanks!

**Comment by ecrode** [comment]
Thank you @dsouders, you've helped identify where this issue belongs to. Would be great if functionality could be handled by the vmtools, as then support would be available on platforms otherwise not updated to support the watchdog timer, but for now I'm content on letting the OS handle the support.
