### ISSUE TITLE
Freebsd Compile Error

### ISSUE THREAD

**Issue by t1n1wall** [vmware/open-vm-tools#49]
libDeployPkg/processPosix.c needs
# include <signal.h>

or compile will fail with

processPosix.c: In function 'Process_RunToComplete':
processPosix.c:180:13: error: implicit declaration of function 'kill' [-Werror=implicit-function-declaration]

**Comment by ravindravmw** [comment]
You should always disable deployPkg on FreeBSD because that is not supported combo anyway.

Try configure with "--disable-deploypkg".

**Comment by t1n1wall** [comment]
that fixes it , thanks .... don't need to add include signal.h

**Comment by stanguturi** [comment]
> that fixes it , thanks .... don't need to add include signal.h

--disable-deploypkg option worked for FreeBSD. Closing this issue.
