### ISSUE TITLE
debian version detection broken

### ISSUE THREAD

**Issue by bzed** [vmware/open-vm-tools#5]
hi,

as we are having point-releases in debian every other month, version detection in the current code is rather broken. for now i've patched it in Debian (yes, I'm the open-vm-tools maintainer in debian, just mail me if you want to get in contact!) with this patch: https://github.com/bzed/pkg-open-vm-tools/blob/master/debian/patches/debian/fix_debian_verison_recognition

the better fix for version >= 7.X would be to strip the .X part from the number and just use that one. I know that some longish time ago we had things like 3.0 and 3.1 being completely different releases, but that time is gone.

cheers,

Bernd

p.s. it would be really nice to have public access to new code and patches again!

**Comment by ravindravmw** [comment]
Bernd, thanks for fixing it. We already have a fix for this in the upcoming release of open-vm-tools.

**Comment by ravindravmw** [comment]
> it would be really nice to have public access to new code and patches again!

Bernd, FYI we are working on making open-vm-tools releases faster than current schedules.

**Comment by bzed** [comment]
fixed in 9.10.0
