### ISSUE TITLE
compiling with --without-icu still links libicu

### ISSUE THREAD

**Issue by t1n1wall** [vmware/open-vm-tools#50]
compiled with --without-kernel-modules --without-gtk2 --without-gtkmm --without-ssl --without-xmlsecurity --without-xerces --without-icu --without-x --disable-vgauth

still links icu libraries, which are huge (~30MB)

```
libvmtools.so.0 => /lib/libvmtools.so.0 (0x28074000)
libdnet.so.1 => /usr/local/lib/libdnet.so.1 (0x280e9000)
libkvm.so.6 => /lib/libkvm.so.6 (0x280f5000)
libcrypt.so.5 => /lib/libcrypt.so.5 (0x280fe000)
libthr.so.3 => /lib/libthr.so.3 (0x28122000)
libgmodule-2.0.so.0 => /usr/local/lib/libgmodule-2.0.so.0 (0x28143000)
libgobject-2.0.so.0 => /usr/local/lib/libgobject-2.0.so.0 (0x28146000)
libgthread-2.0.so.0 => /usr/local/lib/libgthread-2.0.so.0 (0x28185000)
libglib-2.0.so.0 => /usr/local/lib/libglib-2.0.so.0 (0x28190000)
libintl.so.8 => /usr/local/lib/libintl.so.8 (0x28284000)
libc.so.7 => /lib/libc.so.7 (0x2828d000)
libicui18n.so.55 => /usr/local/lib/libicui18n.so.55 (0x28402000)
libicuuc.so.55 => /usr/local/lib/libicuuc.so.55 (0x2867a000)
libicudata.so.55 => /usr/local/lib/libicudata.so.55 (0x28800000)
libiconv.so.2 => /usr/local/lib/libiconv.so.2 (0x2a0b7000)
libpcre.so.1 => /usr/local/lib/libpcre.so.1 (0x2a1ab000)
libffi.so.6 => /usr/local/lib/libffi.so.6 (0x287f6000)
libm.so.5 => /lib/libm.so.5 (0x2a222000)
libc++.so.1 => /usr/lib/libc++.so.1 (0x2a249000)
libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x2a2f7000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x2a310000)
```

**Comment by oliverkurth** [comment]
Thanks. Is this on FreeBSD like issue #49 as well?

**Comment by t1n1wall** [comment]
yes, freebsd 10.2 , just noticed this error when running configure  (automake-1.15)

checking build system type... i386-unknown-freebsd10.2
checking host system type... i386-unknown-freebsd10.2
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/tmp/open-vm-tools/config/missing: Unknown `--is-lightweight' option
Try `/tmp/open-vm-tools/config/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... config/install-sh -c -d

**Comment by oliverkurth** [comment]
Did you use autoreconf? Building open-vm-tools for FreeBSD has some issues. It should be built with these instructions:

autoreconf -i --force
env CC=gcc48 CFLAGS=-Wl,-rpath=/usr/local/lib/gcc48 CPPFLAGS="-I/usr/local/include/" LIBS="-L/usr/local/lib" ./configure --without-kernel-modules --without-xmlsecurity --without-x --without-icu --disable-vgauth --disable-grabbitmqproxy --disable-deploypkg
make

**Comment by t1n1wall** [comment]
it builds fine, but putting it into a small freebsd image, increases the image from 12MB to 50MB, which is more than I would wish for.

 I have built as per your command line , still links icu files .  

# ldd services/vmtoolsd/.libs/vmtoolsd | grep libicu | cut -d ' ' -f3 | xargs -I zz ls -lh zz.1
-r-xr-xr-x  1 root  wheel   2.5M Oct 27 01:36 /usr/local/lib/libicui18n.so.55.1
-r-xr-xr-x  1 root  wheel   1.5M Oct 27 01:36 /usr/local/lib/libicuuc.so.55.1
-rwxr-xr-x  1 root  wheel    25M Nov 30 15:34 /usr/local/lib/libicudata.so.55.1

**Comment by oliverkurth** [comment]
Thanks for reporting. I created an internal bug for investigation.

**Comment by johnwvmw** [comment]
Actually, I believe that the --without-icu option worked as desired.  Since the 'ldd' command will report all needed runtime used by and ELF shared object or a.out, it uses the system RPATH or LD_LIBRARY_PATH to locate those NEEDED shared objects referenced without an absolute path name.

I have built the open-vm-tools source from the github repo.with the instructions provided by oliverkurth above.  And as you reported "ldd services/vmtoolsd/.libs/vmtoolsd seems to indicate that the ICU runtime is needed.  However, using 'readelf -d' to examine the .dynamic section of the ELF objects being created by the build:

> $ readelf -d ./services/vmtoolsd/.libs/vmtoolsd
> 
> Dynamic section at offset 0xa558 contains 28 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libvmtools.so.0]
>  0x0000000000000001 (NEEDED)             Shared library: [libdnet.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libkvm.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libcrypt.so.5]
>  0x0000000000000001 (NEEDED)             Shared library: [libthr.so.3]
>  0x0000000000000001 (NEEDED)             Shared library: [libgmodule-2.0.so.0]
>  0x0000000000000001 (NEEDED)             Shared library: [libgobject-2.0.so.0]
>  0x0000000000000001 (NEEDED)             Shared library: [libgthread-2.0.so.0]
>  0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
>  0x0000000000000001 (NEEDED)             Shared library: [libintl.so.8]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.7]
>  0x000000000000000f (RPATH)              Library rpath: [/usr/local/lib/gcc48:/usr/local/lib]

> $ readelf -d libvmtools/.libs/libvmtools.so.0
> 
> Dynamic section at offset 0x7f5f0 contains 33 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libdnet.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libkvm.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libcrypt.so.5]
>  0x0000000000000001 (NEEDED)             Shared library: [libthr.so.3]
>  0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
>  0x0000000000000001 (NEEDED)             Shared library: [libintl.so.8]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.7]
>  0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
>  0x000000000000000e (SONAME)             Library soname: [libvmtools.so.0]
>  0x000000000000000f (RPATH)              Library rpath: [/usr/local/lib/gcc48]

So neither the vmtoolsd daemon nor the library that it will use once installed need/use the ICU libraries.

Look at the path of the libvmtools.so.0 in the ldd output you reported.   It is the path of a previously installed libvmtools.so.0 that I believe was compiled without the configure option "--without-icu".

**Comment by stanguturi** [comment]
> Actually, I believe that the --without-icu option worked as desired. Since the 'ldd' command will report all needed runtime used by and ELF shared object or a.out, it uses the system RPATH or LD_LIBRARY_PATH to locate those NEEDED shared objects referenced without an absolute path name.

Thanks a lot John. This really not a bug. Closing.
