### ISSUE TITLE
FTFBS with glib2.0 >=2.66.3

### ISSUE THREAD

**Issue by cpaelzer** [vmware/open-vm-tools#500]
FTFBS due to new glib2.0 >=2.66.3

Example:
```
In file included from /usr/include/glib-2.0/glib/gmacros.h:241,
                 from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /<<PKGBUILDDIR>>/open-vm-tools/lib/include/vmware/tools/plugin.h:32,
                 from dndcp.cpp:36:
/usr/include/c++/10/type_traits:56:3: error: template with C linkage
   56 |   template<typename _Tp, _Tp __v>
      |   ^~~~~~~~
dndcp.cpp:34:1: note: ‘extern "C"’ linkage started here
   34 | extern "C" {
      | ^~~~~~~~~~
```

Full log:
https://launchpadlibrarian.net/525172798/buildlog_ubuntu-hirsute-amd64.open-vm-tools_2%3A11.2.5-2_BUILDING.txt.gz

On the glib side this is due to:
https://gitlab.gnome.org/GNOME/glib/-/issues/2331
Also related:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1935
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/J3P4TRHLWNDIKXF76OLYZNAPTABCZ3U5/#7LXFUDBBBIT23FE44QJYWX3I7U4EHW6M

There is a temporary workaround by hard setting the GLIB versions requested.
This I'll use to un-break the build in Ubuntu for now.
=> http://launchpadlibrarian.net/526861180/open-vm-tools_2%3A11.2.5-2_2%3A11.2.5-2ubuntu1.diff.gz

But mid term I guess you'll need to sort out the inclusion of such headers from CPP context more in general.

**Comment by cpaelzer** [comment]
@bzed - FYI in case you want/need to build for the glib2.0 in debian/experimental

**Comment by iainlane** [comment]
Hey just to say that I wouldn't call this a temporary workaround. I think you should apply a patch like this one as general good practice to guard against future deprecations or behaviour changes affecting you until you opt in to them. (In the absence of having it defined you always get the latest stuff available at build time, which might sometimes include breakage like this.)

https://developer.gnome.org/glib/stable/glib-Version-Information.html#GLIB-VERSION-MIN-REQUIRED:CAPS

But if you ever want to be able to lift this requirement to a higher version, to use newer APIs for example, then you'll need to fix the `extern`s, that is true to say.

Cheers!

**Comment by cpaelzer** [comment]
> Hey just to say that I wouldn't call this a temporary workaround. 

Thanks for the clarifications @iainlane !

**Comment by dsouders** [comment]
@cpaelzer Thank you for reporting this issue, an internal bug has been filed to track it.

**Comment by Conan-Kudo** [comment]
This is causes open-vm-tools to FTBFS on Fedora 34 now as well. ☹️

**Comment by johnwvmw** [comment]
We are working and validating the fix on Fedora 34 that addresses this and also addresses use of a deprecated function in a newer GTK3.   Stay tuned.

**Comment by Conan-Kudo** [comment]
Excellent!

Just FYI, I've filed a bug in RHBZ as well, please make sure once this is fixed that this is addressed: https://bugzilla.redhat.com/show_bug.cgi?id=1939718

**Comment by johnwvmw** [comment]
@cpaelzer ,
@bzed,
This issues has been fixed with change https://github.com/vmware/open-vm-tools/commit/82931a1bcb39d5132910c7fb2ddc086c51d06662 on the "devel" branch.   This will be part of the next major open-vm-tools release, but the change can be applied to the 11.2.5 open-vm-tools source release.

Closing this issue; please reopen if you have any concerns or problems.
