### ISSUE TITLE
GNOME and Plasma Wayland sessions don't have functioning auto-resize/maximize on Fedora 34

### ISSUE THREAD

**Issue by Conan-Kudo** [vmware/open-vm-tools#501]
On Fedora 34 Workstation and KDE Plasma beta RCs, the desktop is stuck at 800x600 resolution and doesn't resize properly when I resize the VM window in VMware Workstation 16, VMware Fusion 11.5, or VMware Fusion 12.

This seems to be caused by resolutionKMS not activating in non-X11 graphical sessions, based on the fact manually forcing it enabled fixes the problem.

(Downstream report: [RHBZ#1890815](https://bugzilla.redhat.com/show_bug.cgi?id=1890815))

**Comment by shoffmeister** [comment]
#382 is related in so far as ResolutionKMS is also concerned - but there for X

**Comment by shoffmeister** [comment]
Also #491 suggests a work-around

**Comment by johnwvmw** [comment]
Also, see the comment in https://github.com/vmware/open-vm-tools/issues/493#issuecomment-775450550 which discusses what appears to be a bug in some version of KDE Plasma.

**Comment by johnwvmw** [comment]
Issue #491 has been closed.   The change for "resolution: Fix kms autodetection" was available in open-vm-tools 11.3.0 and later releases.
