### ISSUE TITLE
vmware-vmtoolsd-root.log created on vmtoolsd start/restart

### ISSUE THREAD

**Issue by OzTechGeek** [vmware/open-vm-tools#503]
OS Version: Ubuntu 20.04.2 LTS
Tools Version: VMware Tools daemon, version 11.1.5.22735 (build-16724464)

Not sure where this is set/getting set but I have an issue with when vmtoolsd starts/restarts it creates a "vmware-vmtoolsd-root.log" even though my tools.cfg has a specific log path/location for each daemon in *..data, if I delete the log file and null out my specific vmware-tools.log file and restart the vmtoolsd service the "vmware-vmtoolsd-root.log" gets created again with just 2 entries then the vmtoolsd daemon starts logging to the correct "vmware-tools.log" file.

Is there something I could change in the systemd unit file to delay the start or start vmtoolsd later that would prevent this log from being created, or anyone know why it is created even with the settings configured in tools.cfg? (Configuration/Logs Attached)

Thoughts/Ideas?

Thanks All

```
/etc/vmware-tools/tools.conf
[logging]
log = true
enableCoreDump = false
maxCacheEntries = 4096

vmresset.handler = file+
vmresset.level = info
vmresset.data = /var/log/vmware-tools.log

vmsvc.handler = file+
vmsvc.level = info
vmsvc.data = /var/log/vmware-tools.log

toolboxcmd.handler = file+
toolboxcmd.level = info
toolboxcmd.data = /var/log/vmware-tools.log

vmtoolsd.handler = file+
vmtoolsd.level = info
vmtoolsd.data = /var/log/vmware-tools.log

vmusr.handler = file+
vmusr.level = info
vmusr.data = /var/log/vmware-tools.log

```
```
/var/log/vmware-vmtoolsd-root.log
[ message] [vmtoolsd] Log caching is enabled with maxCacheEntries=4096.
[ message] [vmtoolsd] Core dump limit set to -1

```
```
/var/log/vmware-tools.log
[ message] [vmsvc] Log caching is enabled with maxCacheEntries=4096.
[    info] [vmsvc] Configuration logging.useLogTextRpc is FALSE
[    info] [vmtoolsd] CmdLine: "/usr/bin/vmtoolsd"
[ message] [vmtoolsd] Tools Version: 11.1.5.22735 (build-16724464)
[    info] [vmtoolsd] Skipping environment initialization for vmsvc from unsetenvironment config.
[    info] [vmtoolsd] Skipping environment initialization for vmsvc from setenvironment config.
[    info] [vmsvc] SOCKET creating new socket, connecting to 0:975
[ message] [vmtoolsd] Plugin 'hgfsServer' initialized.
[ message] [vix] QueryVGAuthConfig: vgauth usage is: 1
[ message] [vmtoolsd] Plugin 'vix' initialized.
[    info] [appInfo] TweakGatherLoopEx: New value for poll-interval is 21600s.
[ message] [vmtoolsd] Plugin 'appInfo' initialized.
[ message] [vmtoolsd] Plugin 'deployPkg' initialized.
[    info] [guestinfo] New value for stats-interval is 20s.
[    info] [guestinfo] New value for poll-interval is 30s.
[ message] [vmtoolsd] Plugin 'guestInfo' initialized.
[ message] [vmtoolsd] Plugin 'powerops' initialized.
[    info] [vmtoolsd] Plugin 'libresolutionKMS.so' didn't provide deployment data, unloading.
[ message] [vmtoolsd] Plugin 'timeSync' initialized.
[ message] [vmtoolsd] Plugin 'vmbackup' initialized.
[    info] [vmtoolsd] Successfully started tools hang detector
[    info] [vmsvc] RpcChannel: Channel was reset successfully.
[    info] [appInfo] AppInfoServerReset: Using poll interval: 15202.
[    info] [appInfo] TweakGatherLoopEx: New value for poll-interval is 15202s.
[    info] [vmtoolsd] Reinitialize the Vmx Guest Logger with a new RPC channel.
[    info] [vmsvc] Configuration logging.useLogTextRpc is FALSE
[    info] [vmtoolsd] Clear out the tools hang detector RPC cache state
[ message] [vix] VixTools_ProcessVixCommand: command 62

```

**Comment by johnwvmw** [comment]
That couple of lines logging into the default log file for the vmtoolsd process is as expected.  

It covers the period of time between the vmtoolsd process start/initialization and when the tools.conf file can be read.

Note: As you currently have the logging configured, the logs for the vmtoolsd system service process and the desktop user will end up in the same file.   It will difficult, if not impossible, to use the log for triaging a problem with either process.  If you do not have a graphical desktop configured on your system, it should not be a problem.

It is strongly recommended that you differentiate by adding $(USER) to the names of the vmtoolsd and vmusr log file names.

    /var/log/vmware-tools.$(USER).log

**Comment by stanguturi** [comment]
> That couple of lines logging into the default log file for the vmtoolsd process is as expected.
> It covers the period of time between the vmtoolsd process start/initialization and when the tools.conf file can be read.
> It is strongly recommended that you differentiate by adding $(USER) to the names of the vmtoolsd and vmusr log file names.

Please check the valuable inputs and suggestions provided by @johnwvmw in the previous update. Thanks a lot @johnwvmw. Resolving this issue.
