### ISSUE TITLE
Problems with tightvncserver package.

### ISSUE THREAD

**Issue by a93h** [vmware/open-vm-tools#504]
Hello,
I'm running into a problem where if I disable my local VNC server copy/paste and drag/drop starts to work again
```shell
uname -a
Linux ubuntu 5.8.0-45-generic #51-Ubuntu SMP Fri Feb 19 13:24:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
I currently have three windows managers installed gnome, xfce4 and wayland.
I use gnome by default when logging into the virtual machine locally and xfce4 when logging in remotely.
Unfortunately when my vncserver.service is enabled I cannot login and use copy/paste drag/drop locally.
As soon as it's disabled and I logout/login the session reverts to working with copy/paste drag/drop.

I am familiar with the problem but not knowing what exactly is causing it or the remedy.
Any help or suggestions would be much appreciated.

**Comment by johnwvmw** [comment]
I believe that what you are experiencing is that only a single "vmtoolsd -n vmusr" process is allowed to be running at the same time. 

The restriction/limitation was put in place to address a security concern where desktop user A could continually monitor the contents of the host's clipboard and see the contents copied to the host's clipboard by user "B" on that same VM.

**Comment by a93h** [comment]
Thanks so much.
I switched to the x11vnc package.
It seems to resolve this problem.
