### ISSUE TITLE
Guest customization failing with Ubuntu 20.04

### ISSUE THREAD

**Issue by jmgilman** [vmware/open-vm-tools#508]
* vCenter: 7.0.2.00000
* ESXi: 7.0 Update 2
* VMWare Tools: 11.2.5-2ubuntu1~ubuntu20.04.1
* Cloud-init: 20.4.1-0ubuntu1~20.04.1

Process:
1. Fresh installation of Ubuntu 20.04 using the live CD with Packer
2. Packer does some initial provisioning of the machine:
```
#!/usr/bin/env bash

# Disable sudo password
sed -i 's/^%sudo.*/%sudo   ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers

# Change password
echo "administrator:$ADMIN_PASSWORD" | chpasswd

# Upgrade
apt-get update
apt-get upgrade -y

# Prepare for cloning
rm -rf /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
rm -rf /etc/cloud/cloud.cfg.d/99-installer.cfg
echo 'disable_vmware_customization: false' >> /etc/cloud/cloud.cfg
```
3. Machine is shut down and converted to a template
4. Clone process is initiated with guest customization set to only change the hostname
5. Machine comes up with network adapter disconnected (signaling customization failure)

It's important to note that if I manually enable the adapter the machine gets an IP address over DHCP and appears to work as expected. Additionally, disabling customization altogether removes the issue entirely. Looking through the logs I see no indication of why the guest customization is failing - the hostname is never changed which is an indicator it is indeed failing somewhere.

[Here are the logs for VMWare tools and cloud-init.](https://gist.github.com/jmgilman/d4b8825a240af4cc64c730e33c1e21ce)

The current workaround is to disable customization and configure the hostname after the cloning process.

**Comment by jmgilman** [comment]
This does seem similar to #483, however, I am not providing any customization scripts and none of the log indicators present in that issue are present in my own logs. So it appears to be a different issue.

**Comment by PengpengSun** [comment]
Hi @jmgilman 

From the cloud-init.log
2021-04-13 15:30:49,965 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: found local data from DataSourceNoCloud

It loaded the local seed DataSourceNoCloud but DataSourceOVF from /var/lib/cloud/seed/nocloud and /var/lib/cloud/seed/nocloud-net, I suggest you delete these 2 folders and have a retry.

**Comment by jmgilman** [comment]
Hi @PengpengSun,

[I've updated the logs here.](https://gist.github.com/jmgilman/d4b8825a240af4cc64c730e33c1e21ce)

It appears the recommended change did not resolve the issue - the network adapter is still disabled after cloning. 

```
administrator@ub2004:~$ stat /var/lib/cloud/seed/nocloud
stat: cannot stat '/var/lib/cloud/seed/nocloud': No such file or directory
administrator@ub2004:~$ stat /var/lib/cloud/seed/nocloud-net
stat: cannot stat '/var/lib/cloud/seed/nocloud-net': No such file or directory
```

**Comment by PengpengSun** [comment]
Hi @jmgilman 

> 2021-04-13 17:08:22,186 - stages.py[INFO]: Loaded datasource DataSourceNoCloud - DataSourceNoCloud [seed=cmdline][dsmode=net]

It turns out the seed=cmdline, so actually the DataSourceNoCloud is enabled in the kernel command line, could you please check file /proc/cmdline if a string looks like "ds=nocloud" can be found.

If yes, you can either remove the "ds=nocloud" from /proc/cmdline or explicitly set to DataSourceOVF by creating a file /etc/cloud/cloud.cfg.d/99-DataSourceOVF.cfg with content as below
`datasource_list: [ "DataSourceOVF" ]`

Please let me know if neither of them can fix the issue.

**Comment by jmgilman** [comment]
Hi @PengpengSun,

Adding the following to my bootstrap script solved the issue:

```
echo 'datasource_list: [ "DataSourceOVF" ]' > /etc/cloud/cloud.cfg.d/99-DataSourceOVF.cfg
```

Thanks for the help!
