### ISSUE TITLE
Centos 7

### ISSUE THREAD

**Issue by hrace009** [vmware/open-vm-tools#51]
got this problem, any help?

configure: error: Can't find include dir under /lib/modules/3.10.0-229.el7.x86_64

**Comment by dyno** [comment]
install kernel-devel package then retry.



On Sat, Dec 5, 2015 at 6:53 AM, Harris Marfel <notifications@github.com>
wrote:

> got this problem, any help?
>
> configure: error: Can't find include dir under
> /lib/modules/3.10.0-229.el7.x86_64
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vmware/open-vm-tools/issues/51>.
>



-- 
reality, with all its ambiguities, does the job just fine.

**Comment by dyno** [comment]
i assume it solved the problem.

**Comment by xentar1976** [comment]
This did not work for me.

**Comment by MaloneQQ** [comment]
I have the same issue.

**Comment by Jackpoto** [comment]
I think you just have to upgrade your kernel version.

**Comment by khaije1** [comment]
This problem can occur during the provision phase while building VM images using Packer. 

Note: the headers/sources provided in the latest kernel-devel package match the version of the kernel provided by the kernel package. 

For best results, `yum install kernel kernel-devel`, then reboot, then build and install the open-vm-tools.

**Comment by m00zi** [comment]
for me after reboot it worked, but now I am getting this err:

`configure: error: mspack >= 0.0.20040308alpha is required.`

**Comment by oliverkurth** [comment]
You need to install this package: libmspack-devel

You may get other errors after installing. Here is a list of required packages in CentOS7/RHEL7:

autoconf \
automake \
libtool \
gcc-c++ \
doxygen \
fuse-devel \
glib2-devel \
gtk2-devel \
gtkmm24-devel \
libdnet-devel \
libicu-devel \
libmspack-devel \
libX11-devel \
libXext-devel \
libXi-devel \
libXinerama-devel \
libXrandr-devel \
libXrender-devel \
libXtst-devel \
openssl-devel \
pam-devel \
procps-devel \
xerces-c-devel \
xml-security-c-devel \
make
