### ISSUE TITLE
open-vm-tools.service

### ISSUE THREAD

**Issue by Cessaa** [vmware/open-vm-tools#515]
My OS information is below

```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
```

If I install the open-vm-tools package with apt, open-vm-tools.service starts automatically.

`sudo apt install open-vm-tools`

![Screenshot from 2021-05-12 13-05-22](https://user-images.githubusercontent.com/57228637/117957461-c593f480-b322-11eb-9465-1c3b0ab98f0a.png)

![Screenshot from 2021-05-12 13-03-30](https://user-images.githubusercontent.com/57228637/117957474-c88ee500-b322-11eb-814f-69c5c6af9fa8.png)

But when i install it from the source code, the service does not come running.
The reason I'm saying this is that when vmtoolsd is not running, it shows NOT INSTALLED on the vm interface.

![Screenshot from 2021-05-12 12-40-19](https://user-images.githubusercontent.com/57228637/117954093-59fc5800-b31f-11eb-8d91-0fc07b13a30b.png)

If I manually create the service myself the version looks like this.

![Screenshot from 2021-05-12 12-44-05](https://user-images.githubusercontent.com/57228637/117954502-c1b2a300-b31f-11eb-88c0-c97cb991a090.png)

Now my wish is to have the service active while installing from the source code.
Is it possible ?
If possible, what am I missing?

Thanks in advance for your help.

**Comment by dbond007** [comment]
Not 100% sure if you are just asking why doesn't the source code come with an init script, the answer to that would be:
https://github.com/vmware/open-vm-tools/wiki/FAQ#how-can-i-start-open-vm-tools-on-boot

**Comment by stanguturi** [comment]
> Now my wish is to have the service active while installing from the source code.
> Is it possible ?

Thanks @dbond007 for the comments. When open-vm-tools is installed from the source code, the service file is not installed. Check https://github.com/vmware/open-vm-tools/wiki/FAQ#how-can-i-start-open-vm-tools-on-boot User needs to write the own init script specific to the distro. Please check https://src.fedoraproject.org/rpms/open-vm-tools/blob/master/f/vmtoolsd.service for the reference. Closing this issue.
