### ISSUE TITLE
Failed to start open-vm-tools.service: Unit vgauth.service not found.

### ISSUE THREAD

**Issue by raceolive** [vmware/open-vm-tools#525]
When I do "systemctl start open-vm-tools" it appears me the following message:

"Failed to start open-vm-tools.service: Unit vgauth.service not found."

I figure out the issue comes from i have installed a vm-tools new version without uninstall the previous one.

Can anybody help me?

**Comment by ajgringo619** [comment]
What OS/kernel version?

**Comment by raceolive** [comment]
Ubuntu 20.04 LTS

**Comment by ajgringo619** [comment]
When you say "the previous one", are you talking about the Ubuntu repo package or the one installed via VMware? To purge the Ubuntu package(s), run this:

`sudo apt-get purge open-vm-tools*`

**Comment by stanguturi** [comment]
Please follow the instructions mentioned by @ajgringo619 in https://github.com/vmware/open-vm-tools/issues/525#issuecomment-874946368 Purge the previous version of tools before installing a newer version.

Also, the service files are provided by the distro vendor. For any issues related to the service files, please contact the distro vendor and log a bug. Closing this issue. Thanks.
