### ISSUE TITLE
Add restart on failure in systemd service open-vm-tools.service

### ISSUE THREAD

**Issue by martintelco** [vmware/open-vm-tools#529]
Please add automatic service restart on failure , for systemd controller open-vm-tools.
in open-vm-tools.service  , in 
[Service]
...
Restart=on-failure

This will allow, if the open-vm-tool fails, systemd to restart it automatically.

**Comment by PaTHml** [comment]
As vmtoolsd service failure is not normal, would you give us some context on what you are observing that prompts the need for the setting?

Any specific Linux distro/vendors we should look at?

Thanks,

**Comment by martintelco** [comment]
Hi,
Os is ubuntu 18.04, I observed  open-vm-tools service failed, but could not retrieve any logs.

Thanks.


On 15 Jul 2021 19:02, PaTHml ***@***.***> wrote:

As vmtoolsd service failure is not normal, would you give us some context on what you are observing that prompts the need for the setting?

Any specific Linux distro/vendors we should look at?

Thanks,

**Comment by stanguturi** [comment]
> Please add automatic service restart on failure , for systemd controller open-vm-tools.
> in open-vm-tools.service , in

The service files are maintained by the distro vendors. Can you please report and log a bug with the distro vendor.

Closing this issue since it's really not an open-vm-tools issue.
