### ISSUE TITLE
@Claroquen, you must sign our contributor license agreement before your changes are merged. Click [here](https://cla.vmware.com/cla/4baf05793af149b2a583deb56881f935) to sign the agreement. If you are a VMware employee, read [this](https://cla.vmware.com/employee) for further instruction.

### ISSUE THREAD

**Issue by Portt56** [vmware/open-vm-tools#531]
@Claroquen, you must sign our contributor license agreement before your changes are merged. Click [here](https://cla.vmware.com/cla/4baf05793af149b2a583deb56881f935) to sign the agreement. If you are a VMware employee, read [this](https://cla.vmware.com/employee) for further instruction.

_Originally posted by @vmwclabot in https://github.com/vmware/open-vm-tools/issues/530#issuecomment-886155128_

**Comment by Claroquen** [comment]
Quiero abrir esto

**Comment by Claroquen** [comment]
git@gitlab.com:fdroid/wiki.wiki.git

**Comment by jonathanvmw** [comment]
@Claroquen - I'm not sure what you're asking, or whether it's related to open-vm-tools.  Please clarify your request and let us know how we can help you.  Thanks.
