### ISSUE TITLE
tools update from vm option 

### ISSUE THREAD

**Issue by xilmen** [vmware/open-vm-tools#537]
Hello 
I would like to know if the option "tools upgrades" in the VM options upgrades the open vm tools or upgrade only VMwaretools ?
Thank you
![image](https://user-images.githubusercontent.com/14809093/131093769-800d105d-a359-421c-848e-386e501a792a.png)

**Comment by zhoumgh** [comment]
Open-VM-Tools life cycle is managed by guest OS, it is not updated from vSphere side.

**Comment by xilmen** [comment]
Thanks ! :)
