### ISSUE TITLE
Shared folders lose mount points when exiting suspend mode

### ISSUE THREAD

**Issue by denji** [vmware/open-vm-tools#539]
If the machine is suspended and then resume again, the drives will be unmounted and need to be turned off and on again in "Settings" - "Options" ("Shared Folder" - "Disabled" and only then "Always enabled").

Host: 5.13.13-arch1-1

	  $ grep -E '(\S*NAME|VERSION|ID|ID_LIKE|\S*_CODENAME)=' /etc/os-release
	  NAME="Ubuntu"
	  VERSION="20.04.3 LTS (Focal Fossa)"
	  ID=ubuntu
	  ID_LIKE=debian
	  PRETTY_NAME="Ubuntu 20.04.3 LTS"
	  VERSION_ID="20.04"
	  VERSION_CODENAME=focal
	  UBUNTU_CODENAME=focal

**Comment by lousybrit** [comment]
> If the machine is suspended and then resumes again, the drives will be unmounted and need to be turned off and on again in "Settings" - "Options" ("Shared Folder" - "Disabled" and only then "Always enabled").
> 
Yes, any files opened in the VM after a suspend where the host (and server component) goes away all handles will be stale and will require opening again from the client.

One reason that the client does not make the open handles reconnect in the server is that the files could and are likely to have been modified while the VM was suspended. For these cases, it would be dangerous to have the client keep going with the prior handles and any content that it has read or needs to write out. This could entail losing updates on the files on the host and corrupting it.

With this in mind, the client will return stale handle errors to applications' next use of the filehandle after the resume.
This should cause the application to open the file anew.

Steve

**Comment by denji** [comment]
@lousybrit Another problem that occurs is that when the machine comes out of sleep it starts cyclically consuming host resources

	  hgfsWorkerThread| I005: VTHREAD ... "hgfsWorkerThread" tid ...
	  hgfsWorkerThread| I005: VTHREAD .... "hgfsWorkerThread" tid ...
	  vcpu-0| I005: HgfsThreadpool_Activate: count of worker threads: 10.
	  vcpu-0| I005: HgfsServerAllocateSession: init session ... id ...
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vmx| I005: TOOLS: appName=toolbox-dnd, oldStatus=1, status=2, guestInitiated=0.
	  vcpu-1| I005: TOOLS: appName=toolbox-dnd, oldStatus=2, status=1, guestInitiated=0.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vmx| I005: TOOLS: appName=toolbox-dnd, oldStatus=1, status=2, guestInitiated=0.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vcpu-1| I005: TOOLS: appName=toolbox-dnd, oldStatus=2, status=1, guestInitiated=0.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vmx| I005: TOOLS: appName=toolbox-dnd, oldStatus=1, status=2, guestInitiated=0.
	  vcpu-1| I005: TOOLS: appName=toolbox-dnd, oldStatus=2, status=1, guestInitiated=0.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vmx| I005: TOOLS: appName=toolbox-dnd, oldStatus=1, status=2, guestInitiated=0.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vcpu-1| I005: TOOLS: appName=toolbox-dnd, oldStatus=2, status=1, guestInitiated=0.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vmx| I005: TOOLS: appName=toolbox-dnd, oldStatus=1, status=2, guestInitiated=0.
	  vcpu-1| I005: TOOLS: appName=toolbox-dnd, oldStatus=2, status=1, guestInitiated=0.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox-dnd timed out.
	  vmx| I005: TOOLS: appName=toolbox-dnd, oldStatus=1, status=2, guestInitiated=0.
	  vmx| I005: GuestRpcSendTimedOut: message to toolbox timed out.
	  vmx| I005: Tools: [AppStatus] Last heartbeat value 205 (last received 13s ago)
	  vmx| I005: TOOLS: appName=toolbox, oldStatus=1, status=2, guestInitiated=0.
	  vcpu-0| I005: Tools: [AppStatus] Last heartbeat value 205 (last received 17s ago)
	  vcpu-0| I005: TOOLS: appName=toolbox, oldStatus=2, status=1, guestInitiated=0.
	  vcpu-0| I005: TOOLS: appName=toolbox-dnd, oldStatus=2, status=1, guestInitiated=0.
