### ISSUE TITLE
how to disable balloon module in open-VM-tools

### ISSUE THREAD

**Issue by harrezzebra** [vmware/open-vm-tools#541]
I want to disable the balloon module in open-VM-tools, but am unable to find documentation. whichever documentation I find are way old e.g. https://www.vmware.com/pdf/vmware-tools-cli.pdf.

Please help.

**Comment by johnwvmw** [comment]
Did you try the procedure in the KB article "Disabling the balloon driver"?
 https://kb.vmware.com/s/article/1002586

**Comment by harrezzebra** [comment]
Yes I know this method, but I want to do it in the operating system (RHEL), to avoid changes on the VMware infrastructure.

**Comment by harrezzebra** [comment]
balloon driver got disabled only by blacklisting vmw_balloon driver on the OS to prevent the loading of this module, but I have to rebuild grub and initramfs if I follow (https://access.redhat.com/solutions/41278#rhel7only).

**Comment by johnwvmw** [comment]
The balloon driver is not associated with open-vm-tools.

It is a Linux kernel driver supplied by your Linux vendor in the base OS and provides direct communication between the ESX server and the Linux OS.  If the the ESXi host is overloaded and available memory drops to approx. 4 % or less, the host will request each guest, through their balloon driver, to relinquish currently unused, free pages.   The Linux guest OS knows which memory pages are hot, which are unused but need to be written to disk and which do not need to be written to disk.    The ESX server does not have that level of information available.  If the ESX server must begin to swap out guest memory, the choice of mem pages swapped out may be less than optimum for a guest's performance.

Those are your 2 options:
  - disable the balloon driver in the VM's config spec as detailed in the KB
  - disable/remove the balloon driver in the Linux kernel.

Which ever method you choose, hopefully your server(s) will not become overloaded.

**Comment by stanguturi** [comment]
Thanks a lot, @johnwvmw for the comments in https://github.com/vmware/open-vm-tools/issues/541#issuecomment-915384288 Resolving this issue as fixed.
