### ISSUE TITLE
vmtoolsd.service not found

### ISSUE THREAD

**Issue by Rudasyy579** [vmware/open-vm-tools#553]
I have installed all the packages i need and when i try to start it is says `Unit file vmtoolsd.service does not exist`
It is on arch linux

**Comment by dsouders** [comment]
It would be helpful to know the specific guest operating system and version you are running, and how you are invoking
open-vm-tools.  The error message matches this:  https://github.com/chef/bento/issues/1267

> packer_templates/ubuntu/scripts/vmware.sh is attempting to start the service name that the "official" vmware tools uses,
> not the service name that comes with open-vm-tools.
>
> Change vmtoolsd to open-vm-tools in that script to fix.
