### ISSUE TITLE
Usage of LGPL headers in the MIT licensed project 

### ISSUE THREAD

**Issue by volo-droid** [vmware/open-vm-tools#560]
I'm a contributor to the https://github.com/HaikuArchives/VMwareAddons project which is licensed with MIT license.
I would like to use there a few header files from the open-vm-tools project (structures and macros related to HGFS). Can I include those headers into the project without changing the project license from MIT to LGPL? (while keeping the LGPL for included headers, of course).

Looking at the following paragraphs in the LGPLv2.1 it seems to be fine. But, it will be great if someone from the open-vm-tools project maintainers can confirm it.

> When a "work that uses the Library" uses material from a header file that is part of the Library, the object code for the work may be a derivative work of the Library even though the source code is not. Whether this is true is especially significant if the work can be linked without the Library, or if the work is itself a library. The threshold for this to be true is not precisely defined by law.
>
> If such an object file uses only numerical parameters, data structure layouts and accessors, and small macros and small inline functions (ten lines or less in length), then the use of the object file is unrestricted, regardless of whether it is legally a derivative work.

**Comment by dsouders** [comment]
Thank you for your question.  I sent it to the VMware Legal department.  This is their response:

“Assuming you are only using numerical parameters, data structure layouts and accessors, and small macros and small inline functions (ten lines or less in length), then we do not believe you would need to license your entire project under the LGPL.”

**Comment by volo-droid** [comment]
Sounds good! Thanks for the quick answer.
