### ISSUE TITLE
vmware-checkvm on Arm64 shows wrong version

### ISSUE THREAD

**Issue by dcasota** [vmware/open-vm-tools#569]
### Describe the bug

On Arm64 ```vmware-checkvm``` detects a wrong version.

```/usr/bin/vmware-checkvm
VMware software version 6 (good)

vmware-checkvm -p
ESX Server
```
Inside the .vmx file  the version is ```virtualHW.version="14"```.

### Reproduction steps

```bash
1. ESXiOnArm v1.8 installed on a RPi4B (fw 1.31), virtual machine created with Photon 4 rev2 .ova
2. (open-vm-tools 11.3.5 already installed)
3. run /usr/bin/vmware-checkvm
```

### Expected behavior

~Matching version with  ```virtualHW.version=``` inside .vmx file.~

### Additional context

This issue might already have been discussed quite a while ago, eg. https://kb.vmware.com/s/article/2020027

**Comment by rprabhud** [comment]
Hi,
vmware-checkvm is not supposed to report virtual hardware version.
It is used by scripts to check if the system is running inside a VM and to determine which product the VM is running under. 
Use the Summary tab of the VM or the virtualHW.version line of the VM's .vmx file for virtual hardware version.
Same thing is documented in above kb article.

**Comment by dcasota** [comment]
Hi @rprabhud, the correlation to the ESX server version makes sense. Thanks for the clarification.
vmware-vmcheck detects the ESX version as version 6. Shouldn't it be detected as version 7? Arm64 ESXi On Arm v1.8 shows up as version 7.0.0 Build 19076756.

**Comment by rprabhud** [comment]
No, it is not an ESX version either.
This command is part of tools and it does not give host version. However, 'vmware-checkvm -p' can tell you if its running on ESX or Workstation. 
Please note that this command output should not be used to get any version. The output "version 6 (good)" is left untouched so that it does not break the existing apps using checkvm output.

**Comment by dcasota** [comment]
thanks !
