### ISSUE TITLE
Debian 8 is shown as OtherGuestOS

### ISSUE THREAD

**Issue by ouafnico** [vmware/open-vm-tools#57]
Hello

Using open-vm-tools on Debian 8, when I ask with a script the type of OS, I get "OtherGuestOS", in place of "linuxGuest", with vmGuestOSType = vmObj.guest.guestFamily.

For Debian 7 or others distribution it's working well.

Is it a bug? Can I force th value somewhere?

Thanks

**Comment by ravindravmw** [comment]
What version of open-vm-tools are you using? And, what is the ESXi version?

**Comment by ouafnico** [comment]
Hello

It's the version 9.4.6-770165-8.

ESX is 5.5.

**Comment by ravindravmw** [comment]
You need at least ESX 6.0 and open-vm-tools 9.10.0 or later. All other (any old version) combinations do not recognize Debian 8.

**Comment by ouafnico** [comment]
Ok. I need to find a repo with newer version package.
Thanks,

**Comment by naujoitsc** [comment]
Hi,

I have the same issue.
On an existing Debian 8 VM on an ESXi 6.0 it works for me correct.
After updating to ESXi 6.5 on some not all Debian 8 VMs it will report "Other 3.x or later Linux (64-bit)"

`dpkg -l | grep open-vm-tools`
`ii  open-vm-tools                  2:9.4.6-1770165-8                  amd64        Open VMware Tools for virtual machines hosted on VMware (CLI)`

`cat /etc/debian_version`
`8.10`

But I think this version of open-vm-tools is fully supported.

I use this PowerCLI snippet to get the info from the vCenter Server:
`Get-VM Debian-8 | Get-View -Property @("Name", "Config.GuestFullName", "Guest.GuestFullName") | Select -Property Name, @{Label="Configured_OS";E={$_.Config.GuestFullName}}, @{Label="Running_OS";E={$_.Guest.GuestFullName}}`

Name     Configured_OS               Running_OS
Debian-8 Debian GNU/Linux 8 (64-bit) Other 3.x or later Linux (64-bit)

Here is an output of an other Debian 8 VM, which was installed on ESXi 6.0 and now running on ESXi 6.5:
Name            Configured_OS               Running_OS
Neuro_XNAT_DB01 Debian GNU/Linux 8 (64-bit) Debian GNU/Linux 8 (64-bit)

**Comment by naujoitsc** [comment]
I have fix it for me `apt-get install lsb-release`
