### ISSUE TITLE
Error finding the specified nic for mac address

### ISSUE THREAD

**Issue by dimakyriakov** [vmware/open-vm-tools#578]
Using terraform i am trying to create VM based on prepared ubuntu template. It's failing during "terraform apply" stage.

Error in cli:
`An error occurred while setting up network properties of the guest OS. See the log file /var/log/vmware-imc/toolsDeployPkg.log in the guest OS for details.`

Logs from VM
`ERROR: Fatal error occurred during customization !! Customization halted
ERROR: Error : Error finding the specified NIC for MAC address = xxx`

Terraform code:
```
resource "vsphere_virtual_machine" "control" {
    count = var.control-count
    name = "${var.vm-prefix}-controller-${count.index + 1}"
    resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
    datastore_id = data.vsphere_datastore.datastore.id
    host_system_id = data.vsphere_host.host.id
    
    num_cpus = var.vm-cpu
    memory = var.vm-ram
    guest_id = var.vm-guest-id

    
    network_interface {
        network_id = data.vsphere_network.network.id
        adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
    }

    disk {
        label = "${var.vm-prefix}-${count.index + 1}-disk"
        size  = 50
    }

    clone {
        template_uuid = data.vsphere_virtual_machine.template.id
        linked_clone  = false
        customize {
            
            linux_options {
            host_name = "${var.vm-prefix}-controller-${count.index + 1}"
            domain = var.vm-domain
            }
            
            network_interface {
            ipv4_address = "192.168.2.210" 
            ipv4_netmask = 24
            }

            ipv4_gateway = "192.168.2.254"
            dns_server_list = ["192.168.2.100","192.168.2.101"]
        }
    }
}
```

### Reproduction steps

```bash
1. terraform plan
2. terraform apply
```

### Expected behavior

VM creates with static ip and hostname

### Additional context
VM network is connected
Ubuntu 20.04
Hypervisor:	VMware ESXi, 6.7.0, 8169922

**Comment by rongz609** [comment]
Hi @dimakyriakov 
Can you post the whole toolsDeployPkg.log?

**Comment by xiaofengw-vmware** [comment]
@dimakyriakov , the error trace "Error finding the specified NIC for MAC address = xxx" means we couldn't find the NIC with mac address xxx, so we couldn't apply the network setting to the correct NIC.
Could you share us the toolsDeployPkg.log for further investigation?

**Comment by dimakyriakov** [comment]
Sorry, VM doesn't have ip to copy file with logs and web console doesn't allow me to copy text...
![image](https://user-images.githubusercontent.com/96116626/159689029-421e7b66-151d-49cd-99bd-7ea8886c0566.png)
![image](https://user-images.githubusercontent.com/96116626/159689084-e243c3e7-9c7a-4041-94fa-b288a637fd97.png)
![image](https://user-images.githubusercontent.com/96116626/159689131-5d0dde4e-ee22-43dd-89dd-1a5f68bfc4e0.png)
![image](https://user-images.githubusercontent.com/96116626/159689242-b675eed6-7cb2-455a-aa79-d1d4cd30d988.png)
![image](https://user-images.githubusercontent.com/96116626/159689259-71d8e666-e7c8-4c4d-9d5a-1a924f997586.png)

**Comment by xiaofengw-vmware** [comment]
From the log, guest customization is not supported for Ubuntu 20.04 LTS, so it call the wrong commands to fetch the interface information.
Please confirm what's your vSphere version? We support to customize Ubuntu 20.04 LTS from vSphere 6.7 U3g. It seems you are using vSphere 6.7.0, please upgrade if so. Thanks.
