### ISSUE TITLE
vmtoolsd auth denied

### ISSUE THREAD

**Issue by ouafnico** [vmware/open-vm-tools#58]
Hello

On Debian 7, 8 and Ubuntu 14.04, the authent through vmtoolsd is denied.

Dec 18 15:18:35 debian7 vmsvc[3866]: pam_unix(vmtoolsd:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root

Authent is working on ssh/direct access. 

It works well on centos/Redhat with same pam.d/vmtoolsd configuration.

I don't know who to resolv it :s If I can try something...

**Comment by oliverkurth** [comment]
What versions of open-vm-tools are you using, for all OSes that you tried? Also, can you please send the pam configuration files for vmtoolsd?

**Comment by ouafnico** [comment]
I'm using the last packaged version. On Debian 7 : 8.8.0+2012.05.21-724730-1.
On debian 8 9.4.6-770165-8.
On Ubuntu 14.04 LTS : 9.4.0-1280544-5ubuntu6.2.

For all, the /etc/pam.d/vmtoolsd is : 
#%PAM-1.0
auth       sufficient       pam_unix2.so nullok
auth       sufficient       pam_unix.so shadow nullok
auth       required         pam_unix_auth.so shadow nullok
account    sufficient       pam_unix2.so
account    sufficient       pam_unix.so
account    required         pam_unix_acct.so

On CentOS/Redhat, the pam conf is the same, but access works.

**Comment by bzed** [comment]
Please try the version from Wheezy or Jessie backports (!) and if it still does not work, open a bug in the Debian bugtracker (if you don't know how, install the tool 'reportbug' and run it).

**Comment by stanguturi** [comment]
> Please try the version from Wheezy or Jessie backports (!) and if it still does not work, open a bug in the Debian bugtracker (if you don't know how, install the tool 'reportbug' and run it).

Can you please try out the instructions provided by @bzed Closing the issue. Please reopen if the issue still exists with the latest version.
