### ISSUE TITLE
How to make a Debian package out of this

### ISSUE THREAD

**Issue by Melab** [vmware/open-vm-tools#59]
More of a question then an issue. On Ubuntu, there is a package for OVT, but I need to make an up-to-date one and it needs to be easy to uninstall. Does this project contain a way for making a Debian package for itself?

**Comment by ravindravmw** [comment]
It's not part of the project, but you should be able to use it from Debian packages, e.g. https://packages.debian.org/sid/open-vm-tools. Please contact Debian manintainer @bzed if you need further details.

**Comment by bzed** [comment]
You could use https://github.com/bzed/pkg-open-vm-tools as a start to build your own packages using git-buildpackage.

Please note that the Ubuntu packaging still differs from what we have in Debian - for whatever reasons. So backporting the latest packaging stuff from Ubuntu might make sense for you, too. Or just use Debian and receive backports for free :-)

**Comment by stanguturi** [comment]
This is really not an issue with this project. Valuable comments from @ravindravmw and @bzed should answer the question. Closing the issue.
