### ISSUE TITLE
please support dsm7

### ISSUE THREAD

**Issue by PrestarLin** [vmware/open-vm-tools#597]
### Describe the bug

the vmtools on dsm7 on esxi doesnot work,such poweroff ,restart ,just could display the network informations

### Reproduction steps

```bash
1.the vmtools on dsm7 on esxi doesnot work,such poweroff ,restart ,just could display the network informations
2.
3.
...
```

### Expected behavior

the vmtools on dsm7 on esxi doesnot work,such poweroff ,restart ,just could display the network informations

**Comment by johnwvmw** [comment]
@darescloud Can you please provide a little more context about your setup/configuration?

Is dsm7 DiskStation Manager, version 7.0?
It it Linux kernel based and if so what Linux kernel version?

ESXi configuration:    What version of ESXi?
  - How did you create the dsm7 VM on ESXi?
     - create a new VM ?
         - Guest Family?
         - Guest OS version ?
     - deploy an OVF template - obtained from where?
Open-vm- tools
   - what version?
   - how installed ?
      - self compilation - make build install?
      - obtained packages from an open-vm-tools provider ?
