### ISSUE TITLE
Sound not working anymore on latest pipewire - Windows 10 host Fedora 36 guest

### ISSUE THREAD

**Issue by hermidalc** [vmware/open-vm-tools#600]
### Describe the bug

No sounds anymore with `pipewire` 0.3.52. I've tried the troubleshooting on https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Troubleshooting. Recently, it used to only get stuttering/popping and only needed to do the Firefox websynth fixes to get sounds to work. But since a specific `pipewire` or other Fedora 36 update now I get no sound whatsoever.

### Reproduction steps

```bash
1. Update Fedora 36 VM to latest with pipewire 0.3.52
2. Test sound volume changes on desktop in upper righthand corner
3. No sound where sound worked before.
...
```

### Expected behavior

Sounds to play like normal

**Comment by hermidalc** [comment]
Hi @dsouders no it just doesn't work. Nothing like before with Firefox. Yeah pipewire just doesn't seem to play well with VMware, never had as many issues with sound as pulse audio before.

**Comment by hermidalc** [comment]
Btw should mention to help users, @dsouders and others, as expected updates to Fedora 36 pipewire and possibly other updates, but the sound started working again maybe two or three weeks ago. So it's likely always something with pipewire

**Comment by ValZapod** [comment]
Bug in pipewire. Install 

apt install pulseaudio

systemctl --user enable pulseaudio

Play with settings in gnome standard settings.
