### ISSUE TITLE
Not working on Ubuntu 22.04 as well as Kubuntu 22.04

### ISSUE THREAD

**Issue by ghost** [vmware/open-vm-tools#604]
### Describe the bug

My computer host: win10
VMware® Workstation 16 Pro：16.2.4 build-20089737
Never had this problem before (can't share clips with my host, copy paste files.

I installed 3 new systems today. (ubuntu 22.04, Kubuntu 22.04, Kali 2022.2 )
I have also tried various methods through the Internet, but it has not been solved.

question:
1. The clipboard cannot be shared with the host computer
2. Unable to copy and paste files with the host computer

I try to uninstall
`sudo apt-get --purge remove open-vm-tools`
`sudo apt-get --purge remove open-vm-tools-desktop`

and reinstall
`sudo open-vm-tools`
`sudo open-vm-tools-desktop`

I also re-added the boot
`systemctl enable open-vm-tools.service`
`systemctl enable vmtoolsd.service`

can't be solved, This is a very strange problem, I tried reinstalling the system again (eg Kubuntu 22.04)
Didn't experience any issues at first, I tried updating the system and after rebooting, the issue happened again.

In the system of the xfce desktop environment, this problem does not occur.

But I use KDE and Gnome desktop environment system. I can only solve my problem by running `vmware-user` after every boot now.

please help me to solve this problem
I even tried reinstalling VMware Workstation 16
The problem still exists, this is a fatal problem.
I've never come across this before..
thanks~

### Reproduction steps

```bash
*
```

### Expected behavior

*

**Comment by lemke1458** [comment]
It sounds like the auto-start of vmware-user is either failing or not properly configured.

An earlier thread has some details on how to verify if the user-mode Tools is probably configured.  See https://github.com/vmware/open-vm-tools/issues/319

**Comment by polarathene** [comment]
KDE will often fail to launch guest vmware service from Plasma 5.25 due to switch to systemd startup by default. There's an open issue that documents the problem and provides a fix that openSUSE ships.

Also pay attention to X11 vs Wayland. Gnome Wayland guests can share clipboard with host (at least X11 host), and have seamless mouse (not locked into the guest window requiring keyboard shortcut to release). KDE Wayland does not support either.

**Comment by offbrandmark** [comment]
Just wanted to say this fix still works with VMware workstation pro with Ubuntu 22.04. Thank you for the help
