### ISSUE TITLE
Rocky 9.0 network customization is lost right after applying.

### ISSUE THREAD

**Issue by shanduur-dell** [vmware/open-vm-tools#607]
### Describe the bug

After building the VM using Packer for vSphere, I am booting the test VM. It picks the Hostname (but not IP), and saves it in `/etc/sysconfig/network` and it is visible in the login panel, prompt and as a output of `hostname`. After few seconds, a reboot happens and rebooted OS no longer has proper hostname, nor valid IP. Displayed IP is IP of the VM used for building template.

Full log:
[toolsDeployPkg.log (corrected)](https://github.com/vmware/open-vm-tools/files/9401516/toolsDeployPkg.log)

### Reproduction steps

```bash
1. Prepare VM as template with Rocky Linux 9.0 given the following kickstart file:

cdrom
text
skipx
bootloader
firewall --disabled
selinux --disabled
firstboot --disabled
lang en_US.UTF-8
keyboard us
timezone America/New_York
zerombr
autopart --type=plain
rootpw toor
reboot

%packages --ignoremissing --excludedocs
openssh-clients
wget
curl
bzip2
dkms
patch
net-tools
sudo
sshpass
selinux-policy-devel
open-vm-tools
iproute-tc
-fprintd-pam
-intltool
-microcode_ctl
-irqbalance
-dracut-config-rescue
%end

%post
# perl is outside base image
dnf install -y perl
%end

2. Deploy VM from template using network configuration with static IP and name for VM in VSphere.
3. Observe
```

### Expected behavior

Network configuration is preserved after reboot.

**Comment by rongz609** [comment]
Hi @shanduur-dell 
Please try the work around method in https://kb.vmware.com/s/article/88199
Or you can update your vCenter to vSphere 6.7 P07/U3r or vSphere 7.0 P05/U3f releases according to the KB article.
Please let me know if the problem still exists.
Thanks.

**Comment by shanduur-dell** [comment]
@rongz609 unfortunately, the work around does not seem to work. I modified `NetworkManager.conf` to include:

```ini
[main]
plugins=ifcfg-rh,keyfile
```

And followed the instruction to modify the `abc123.nmconnection` to look like:

```ini
[connection]
autoconnect-priority=-999
```

Unfortunately, this did not solved the issue. The ifcfg-rh file created by customization engine is called `ifcfg-ether` instead of `ifcfg-ens192`, but renaming it and rebooting deployed VM does not help. 

---

```
vSphere Client version 6.7.0.48000
```

```
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.7.0
Build:        18010599
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.7.3
```

**Comment by rongz609** [comment]
Hi @shanduur-dell 

The KB says "Edit /etc/NetworkManager/system-connections/{NAME}.connection file(s)."

I saw you modified abc123.nmconnection. 
Seems that you modified the wrong file.
Can you confirm it?
Thanks.

**Comment by rongz609** [comment]
According to your attached toolsDeployPkg.log, I saw you have four NICs in your VM, eth0, eth1, eth2 and eth3
then you may need to edit below files:
/etc/NetworkManager/system-connections/eth0.connection
/etc/NetworkManager/system-connections/eth1.connection
/etc/NetworkManager/system-connections/eth2.connection
/etc/NetworkManager/system-connections/eth3.connection

The "NAME" in /etc/Ne†workManager/system-connections/{NAME}.connection means your NIC interface name.

**Comment by shanduur-dell** [comment]
I do not have any `*.connection` files in this location. And I do not have any `*.connection` files anywhere in the system!

**Comment by rongz609** [comment]
OK, can you run command "(sudo) nmcli -f ALL connection show"
to check which configure file is active in your VM.

**Comment by rongz609** [comment]
Hi @shanduur-dell 

In your toolsDeployPkg.log, I found:
DEBUG: Command: 'cat /etc/redhat-release' 
DEBUG: Result: Red Hat Enterprise Linux Server release 7.6 (Maipo)

Seems that you are using Red Hat 7.6.
Can you confirm it?
Thanks.

**Comment by shanduur-dell** [comment]
No, I am using Rocky Linux 9.0 (ISO: `Rocky-9.0-x86_64-minimal.iso`, Checksum: `dbe7ee3000baa22ebfc7d66611597081c6b3e792a8c0c86a5a9d58e14650d874`).

```
[root@myhost ~]# cat /etc/redhat-release
Rocky Linux release 9.0 (Blue Onyx)
[root@myhost ~]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.0 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.0 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.0"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"
```

**Comment by shanduur-dell** [comment]
Looks like I uploaded wrong Log file, here is correct one: 
[toolsDeployPkg.log](https://github.com/vmware/open-vm-tools/files/9401516/toolsDeployPkg.log)

**Comment by shanduur-dell** [comment]
```
[root@myhost ~]# ls -al /etc/sysconfig/network-scripts
total 12
drwxr-xr-x. 2 root root   64 Aug 23 09:45 .
drwxr-xr-x. 3 root root 4096 Aug 23 05:42 ..
-rw-r--r--  1 root root  185 Aug 23 09:45 ifcfg-ether
-rw-r--r--  1 root root    0 Aug 23 09:45 route6-ether
-rw-r--r--  1 root root   24 Aug 23 09:45 route-ether
[root@myhost ~]# cat /etc/sysconfig/network-scripts/ifcfg-ether
# Generated by VMWare customization engine.
DEVICE=ether
ONBOOT=yes
USERCTL=no
BOOTPROTO=static
NETMASK=255.255.248.0
IPADDR=10.247.97.127
PEERDNS=no

check_link_down() {
 return 1;
}
[root@myhost ~]# cat /etc/sysconfig/network-scripts/route-ether
default via 10.247.96.1
[root@myhost ~]# cat /etc/sysconfig/network-scripts/route6-ether
```

**Comment by rongz609** [comment]
OK, your vCenter is too old.
You need to follow two KB to solve your issue.
https://kb.vmware.com/s/article/86163
https://kb.vmware.com/s/article/88199

Let me summarize the steps:
1. Power-on Virtual Machine.
2. In Guest OS, update /etc/redhat-release, replace "Rocky" with "CentOS". Save and close the file.
3. Edit /etc/NetworkManager/system-connections/{NAME}.connection file(s).
4. Add 'autoconnect-priority=-999' under [Connection] section in the file(s).
5. Save and close the file(s).
6. Power-off the Virtual Machine (convert Virtual Machine back to template).


If you upgrade your vCenter to 6.7U3p, then you just need to follow https://kb.vmware.com/s/article/88199.
And if you upgrade your vCenter to 6.7 P07/U3r, then you don't need the walk around steps.

**Comment by shanduur-dell** [comment]
Thank you for your help @rongz609 !

**Comment by rongz609** [comment]
Glad to help:)
