### ISSUE TITLE
nicInfoPosix.c:344:5: error: #error GuestInfoGetPrimaryIP needed for this platform

### ISSUE THREAD

**Issue by Justinzobel** [vmware/open-vm-tools#61]
Making all in nicInfo
make[2]: Entering directory '/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/nicInfo'
/bin/sh ../../libtool  --tag=CC   --mode=compile x86_64-solus-linux-gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.5\" -DPACKAGE_STRING=\"open-vm-tools\ 10.0.5\" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_X11_SM_SMLIB_H=1 -DHAVE_X11_ICE_ICELIB_H=1 -DHAVE_X11_EXTENSIONS_XCOMPOSITE_H=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_DNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include  -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS  -D_REENTRANT    -I/usr/include  -DUSE_ICU -DHAVE_ICU_38 -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE  -DUSE_SLASH_PROC -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-but-set-variable -MT libNicInfo_la-compareNicInfo.lo -MD -MP -MF .deps/libNicInfo_la-compareNicInfo.Tpo -c -o libNicInfo_la-compareNicInfo.lo `test -f 'compareNicInfo.c' || echo './'`compareNicInfo.c
/bin/sh ../../libtool  --tag=CC   --mode=compile x86_64-solus-linux-gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.5\" -DPACKAGE_STRING=\"open-vm-tools\ 10.0.5\" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_X11_SM_SMLIB_H=1 -DHAVE_X11_ICE_ICELIB_H=1 -DHAVE_X11_EXTENSIONS_XCOMPOSITE_H=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_DNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include  -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS  -D_REENTRANT    -I/usr/include  -DUSE_ICU -DHAVE_ICU_38 -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE  -DUSE_SLASH_PROC -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-but-set-variable -MT libNicInfo_la-util.lo -MD -MP -MF .deps/libNicInfo_la-util.Tpo -c -o libNicInfo_la-util.lo `test -f 'util.c' || echo './'`util.c
/bin/sh ../../libtool  --tag=CC   --mode=compile x86_64-solus-linux-gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.5\" -DPACKAGE_STRING=\"open-vm-tools\ 10.0.5\" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_X11_SM_SMLIB_H=1 -DHAVE_X11_ICE_ICELIB_H=1 -DHAVE_X11_EXTENSIONS_XCOMPOSITE_H=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_DNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include  -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS  -D_REENTRANT    -I/usr/include  -DUSE_ICU -DHAVE_ICU_38 -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE  -DUSE_SLASH_PROC -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-but-set-variable -MT libNicInfo_la-nicInfo.lo -MD -MP -MF .deps/libNicInfo_la-nicInfo.Tpo -c -o libNicInfo_la-nicInfo.lo `test -f 'nicInfo.c' || echo './'`nicInfo.c
/bin/sh ../../libtool  --tag=CC   --mode=compile x86_64-solus-linux-gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.5\" -DPACKAGE_STRING=\"open-vm-tools\ 10.0.5\" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_X11_SM_SMLIB_H=1 -DHAVE_X11_ICE_ICELIB_H=1 -DHAVE_X11_EXTENSIONS_XCOMPOSITE_H=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_DNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -I.  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include  -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS  -D_REENTRANT    -I/usr/include  -DUSE_ICU -DHAVE_ICU_38 -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE  -DUSE_SLASH_PROC -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-but-set-variable -MT libNicInfo_la-nicInfoPosix.lo -MD -MP -MF .deps/libNicInfo_la-nicInfoPosix.Tpo -c -o libNicInfo_la-nicInfoPosix.lo `test -f 'nicInfoPosix.c' || echo './'`nicInfoPosix.c
libtool: compile:  x86_64-solus-linux-gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.5\" "-DPACKAGE_STRING=\"open-vm-tools 10.0.5\"" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_X11_SM_SMLIB_H=1 -DHAVE_X11_ICE_ICELIB_H=1 -DHAVE_X11_EXTENSIONS_XCOMPOSITE_H=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_DNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -I. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -D_REENTRANT -I/usr/include -DUSE_ICU -DHAVE_ICU_38 -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE -DUSE_SLASH_PROC -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-but-set-variable -MT libNicInfo_la-compareNicInfo.lo -MD -MP -MF .deps/libNicInfo_la-compareNicInfo.Tpo -c compareNicInfo.c  -fPIC -DPIC -o .libs/libNicInfo_la-compareNicInfo.o
libtool: compile:  x86_64-solus-linux-gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.5\" "-DPACKAGE_STRING=\"open-vm-tools 10.0.5\"" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_X11_SM_SMLIB_H=1 -DHAVE_X11_ICE_ICELIB_H=1 -DHAVE_X11_EXTENSIONS_XCOMPOSITE_H=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_DNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -I. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -D_REENTRANT -I/usr/include -DUSE_ICU -DHAVE_ICU_38 -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE -DUSE_SLASH_PROC -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-but-set-variable -MT libNicInfo_la-nicInfo.lo -MD -MP -MF .deps/libNicInfo_la-nicInfo.Tpo -c nicInfo.c  -fPIC -DPIC -o .libs/libNicInfo_la-nicInfo.o
libtool: compile:  x86_64-solus-linux-gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.5\" "-DPACKAGE_STRING=\"open-vm-tools 10.0.5\"" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_X11_SM_SMLIB_H=1 -DHAVE_X11_ICE_ICELIB_H=1 -DHAVE_X11_EXTENSIONS_XCOMPOSITE_H=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_DNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -I. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -D_REENTRANT -I/usr/include -DUSE_ICU -DHAVE_ICU_38 -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE -DUSE_SLASH_PROC -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-but-set-variable -MT libNicInfo_la-util.lo -MD -MP -MF .deps/libNicInfo_la-util.Tpo -c util.c  -fPIC -DPIC -o .libs/libNicInfo_la-util.o
libtool: compile:  x86_64-solus-linux-gcc -DPACKAGE_NAME=\"open-vm-tools\" -DPACKAGE_TARNAME=\"open-vm-tools\" -DPACKAGE_VERSION=\"10.0.5\" "-DPACKAGE_STRING=\"open-vm-tools 10.0.5\"" -DPACKAGE_BUGREPORT=\"open-vm-tools-devel@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"open-vm-tools\" -DVERSION=\"10.0.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_X11_SM_SMLIB_H=1 -DHAVE_X11_ICE_ICELIB_H=1 -DHAVE_X11_EXTENSIONS_XCOMPOSITE_H=1 -DHAVE_ECVT=1 -DHAVE_FCVT=1 -DNO_DNET=1 -DHAVE_CRYPT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_WCHAR_H=1 -DHAVE_SYS_IO_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SYSINFO_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_USER_H=1 -DHAVE_SYS_VFS_H=1 -DHAVE_UNWIND_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DTIME_WITH_SYS_TIME=1 -I. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -I/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/include -DUSING_AUTOCONF=1 -DOPEN_VM_TOOLS -D_REENTRANT -I/usr/include -DUSE_ICU -DHAVE_ICU_38 -DVMX86_TOOLS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE -DUSE_SLASH_PROC -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wall -Werror -Wno-pointer-sign -Wno-unused-value -fno-strict-aliasing -Wno-unknown-pragmas -Wno-uninitialized -Wno-deprecated-declarations -Wno-unused-but-set-variable -MT libNicInfo_la-nicInfoPosix.lo -MD -MP -MF .deps/libNicInfo_la-nicInfoPosix.Tpo -c nicInfoPosix.c  -fPIC -DPIC -o .libs/libNicInfo_la-nicInfoPosix.o
mv -f .deps/libNicInfo_la-util.Tpo .deps/libNicInfo_la-util.Plo
mv -f .deps/libNicInfo_la-nicInfo.Tpo .deps/libNicInfo_la-nicInfo.Plo
nicInfoPosix.c:344:5: error: #error GuestInfoGetPrimaryIP needed for this platform
 #   error GuestInfoGetPrimaryIP needed for this platform
     ^
nicInfoPosix.c:910:1: error: 'ValidateConvertAddress' defined but not used [-Werror=unused-function]
 ValidateConvertAddress(const struct sockaddr _addr)  // IN:
 ^
cc1: all warnings being treated as errors
Makefile:491: recipe for target 'libNicInfo_la-nicInfoPosix.lo' failed
make[2]: *_\* [libNicInfo_la-nicInfoPosix.lo] Error 1
make[2]: **\* Waiting for unfinished jobs....
mv -f .deps/libNicInfo_la-compareNicInfo.Tpo .deps/libNicInfo_la-compareNicInfo.Plo
make[2]: Leaving directory '/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib/nicInfo'
Makefile:453: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/justin/YPKG/build/open-vm-tools/open-vm-tools-stable-10.0.5/open-vm-tools/lib'
Makefile:496: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

**Comment by oliverkurth** [comment]
It looks like you are missing libdnet. You can try giving '--without-dnet' to ./configure, or install libdnet. Which Linux distribution or OS are you using?

**Comment by Justinzobel** [comment]
Yeah I passed --without-dnet and this still happens, trying to compile for
Solus (https://solus-project.com)

**Comment by ravindravmw** [comment]
This looks like another Linux distro.

You can't build without libdnet. Drop '--without-dnet' switch and have libdnet configured. If solus-project does not provide libdnet, you will have to build it yourself.

**Comment by Justinzobel** [comment]
Umm if you can't build without dnet why is it a configure option... That seems a bit of a contradiction.

**Comment by ravindravmw** [comment]
Yes, it needs to be improved.

**Comment by oliverkurth** [comment]
That option used to work though, it just limited functionality.

**Comment by Jackpoto** [comment]
I have the same problem on a redhat 7.2 VM.
We have a problem to use VIX with the open-vm-tools 9.10.2-4 so we open a support ticket with VMware. They ask me to try with the latest version of open-vm-tools.
So I clone the source with git clone, and launch the following commands 
autoreconf
./configure --without-pam --without-ssl --without-x --without-procps --without-dnet --without-icu
make 

but I have the same error
nicInfoPosix.c:344:5: error: #error GuestInfoGetPrimaryIP needed for this platform
 #   error GuestInfoGetPrimaryIP needed for this platform
     ^
nicInfoPosix.c:910:1: error: 'ValidateConvertAddress' defined but not used [-Werror=unused-function]
 ValidateConvertAddress(const struct sockaddr *addr)  // IN:
 ^
cc1: all warnings being treated as errors

What can I do ?

**Comment by yusong555** [comment]
Hi, 

I have also seen a same problem on RedHat 7.2 VM.   I ran

autoreconf -i
./configure --enable-deploypkg=no --without-ssl --without-icu --without-procps --without-dnet
make

and getting the below errors. 

nicInfoPosix.c:344:5: error: #error GuestInfoGetPrimaryIP needed for this platform
 #   error GuestInfoGetPrimaryIP needed for this platform
     ^
nicInfoPosix.c:910:1: error: 'ValidateConvertAddress' defined but not used [-Werror=unused-function]
 ValidateConvertAddress(const struct sockaddr *addr)  // IN:
 ^

Please assist to fix this?

**Comment by ravindravmw** [comment]
You have to have dnet and remove "--without-dnet" option from configure command line. Please see my previous response on this issue.

**Comment by yusong555** [comment]
hi Ravin

Is this package for dnet? I have it installed already. 

libdnet-1.12-13.1.el7.x86_64

**Comment by oliverkurth** [comment]
For building, you also need the -devel package: libdnet-devel . The -devel packages contain additional files, for example header files, that are required to build. For RHEL 7, this should be the complete list of required packages, without having to disable any options:

  autoconf \
  automake \
  libtool \
  gcc-c++ \
  doxygen \
  fuse-devel \
  glib2-devel \
  gtk2-devel \
  gtkmm24-devel \
  libdnet-devel \
  libicu-devel \
  libmspack-devel \
  libX11-devel \
  libXext-devel \
  libXi-devel \
  libXinerama-devel \
  libXrandr-devel \
  libXrender-devel \
  libXtst-devel \
  openssl-devel \
  pam-devel \
  procps-devel \
  xerces-c-devel \
  xml-security-c-devel \
 make

**Comment by yusong555** [comment]
thanks very much, Gents! compile is working now.  :+1:
