### ISSUE TITLE
vmware-toolbox-cmd shrink causes reboot into emergency mode with inode filesystem corruption

### ISSUE THREAD

**Issue by hermidalc** [vmware/open-vm-tools#613]
### Describe the bug

After performing `vmware-toolbox-cmd shrink /` on Fedora 36 guest with ext4 filesystems (not btrfs because it can't shrink this) and the standard LVM based layout, when rebooting after the shrink the system boots into emergency mode and there are inode (and possibly other I forget right now) filesystem issues that require and `fsck -f` of mounts to fix them and reboot successfully back into Fedora. This didn't use to happen so I believe is a new bug.

### Reproduction steps

1. Create Fedora 36 guest with ext4 filesystems (except /boot/efi) and the standard LVM layout (with the entire root / mounted to /dev/mapper/fedora_<hostname>-root)
2. Perform `sudo vmware-toolbox-cmd shrink /`
3. Reboot and system will go into emergency mode with filesystem corruption that requires `fsck -f` of root filesystem to fix inode and other issues

### Expected behavior

Shrink not causing filesystem corruption

**Comment by hermidalc** [comment]
Latest WS Pro for Windows (10) 16.2.4

**Comment by lemke1458** [comment]
Thanks, internal bug filed.

**Comment by lemke1458** [comment]
The disk team has asked for a Workstation support bundle collected after the shrink but before the reboot.

Can you please gather one and attach?

**Comment by hermidalc** [comment]
Sorry took me a sec to get to this, when create a fresh Fedora 36 VM with the same LVM ext4 layout and do the shrink it doesn't have this problem. So it's something with my VM, will trash it and create a new one and move all my stuff over.

**Comment by hermidalc** [comment]
And honestly I have no idea how this started happening, I'm a heavy VMware Workstation user with Fedora VMs and this never happened before. I've gone back to using standard ext4 partitions in the Fedora setup instead of the default LVM layout

**Comment by lemke1458** [comment]
Thanks for the update, I'll close the internal bug.
