### ISSUE TITLE
Fedora guests fully supports UEFI and Secure Boot but VMware doesn't allow selecting these options

### ISSUE THREAD

**Issue by hermidalc** [vmware/open-vm-tools#615]
### Is your feature request related to a problem? Please describe.

Sorry I know this isn't a open-vm-tools issue, please report this to the main VMware team.

Fedora guests fully support UEFI and Secure Boot. I don't know why VMware Workstation doesn't allow selecting these options when you pick `Fedora 64-bit`. I've been going around it by creating the VM and then manually editing the vmx file adding the UEFI config. VMware UEFI and Secure Boot have always worked for Fedora guests for as long as I can remember. It's a bit annoying too in the most recent VMware Workstation it gives me popup messages that I can't have these options selected when I try to change other options on that tab in the Edit VM Settings window.

### Describe the solution you'd like

Please make `Fedora 64-bit` as supported guest for VMware UEFI and Secure Boot! It's always worked without any issues.

### Describe alternatives you've considered

Manually editing vmx file and adding the settings.

**Comment by dsouders** [comment]
@hermidalc 

There is already an internal bug for this issue.  I have added this report to that bug.

In the future, please use communities.vmware.com for reporting issues that are unrelated to open-vm-tools.  Here's the URL for Workstation: https://communities.vmware.com/t5/VMware-Workstation/ct-p/3019-home

**Comment by hermidalc** [comment]
@dsouders sorry about that and thank you!

**Comment by dsouders** [comment]
@hermidalc

No problem!  Thank you for all of your contributions to this list!
