### ISSUE TITLE
VGAuthService: symbol lookup error: /lib64/libxmlsec1.so.1: undefined symbol: xmlIOFTPRead

### ISSUE THREAD

**Issue by fifofonix** [vmware/open-vm-tools#621]
### Describe the bug

Open-vm-tools vgauthd.service has started to fail on the `next` FedoraCoreOS stream (37.20221031.1.0 (2022-11-02T09:38:17Z)) with an error in the journal referencing an undefined symbol, e.g:

```
Nov 03 05:42:55 host systemd[1]: Started vgauthd.service - VGAuth Service for open-vm-tools.
Nov 03 05:42:55 host VGAuthService[894]: /usr/bin/VGAuthService: symbol lookup error: /lib64/libxmlsec1.so.1: undefined symbol: xmlIOF>
Nov 03 05:42:55 host systemd[1]: vgauthd.service: Main process exited, code=exited, status=127/n/a
Nov 03 05:42:55 host systemd[1]: vgauthd.service: Failed with result 'exit-code'.
```

### Reproduction steps

This issue does not occur on recent *prior* versions of FedoraCoreOS.

Reproduction is simply by installing the open-vm-tools package on a new `next` stream FedoraCoreOS VM which can be done with `rpm-ostree install open-vm-tools`.  A reboot to activate the change will yield a failed vgauthd.service systemd unit.

Examining dependent rpm package identifiers installed on latest FedoraCoreOS vs most recent prior working version there is no change shown.

It is also possible to reproduce this issue by running the latest version of FedoraCoreOS in a container `docker run --rm -ti quay.io/fedora/fedora-coreos:next-devel` as follows:
```
bash-5.2# rpm-ostree install open-vm-tools
bash-5.2# /usr/bin/VGAuthService -s
/usr/bin/VGAuthService: symbol lookup error: /lib64/libxmlsec1.so.1: undefined symbol: xmlIOFTPRead, version LIBXML2_2.4.30
```

### Expected behavior

Service runs without issue as it does on prior FedoraCoreOS versions

### Additional context

```
% uname
Linux host 6.0.5-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 26 17:24:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dustymabe** [comment]
Yep this can be closed. It's a packaging issue downstream. See https://bugzilla.redhat.com/show_bug.cgi?id=2139849
