### ISSUE TITLE
RecordRoutingInfoIPv6 - not parsing /proc/net/ipv6_route properly

### ISSUE THREAD

**Issue by bzed** [vmware/open-vm-tools#63]
We have a system with a lot of entries in /proc/net/ipv6_route:

```
# wc -l /proc/net/ipv6_route 
187 /proc/net/ipv6_route
```

Which results in this:

```
# tail /var/log/vmware-vmsvc.log 
[Jan 01 19:04:09.451] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
[Jan 01 19:04:39.453] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
[Jan 01 19:05:09.453] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
[Jan 01 19:05:39.454] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
[Jan 01 19:06:09.455] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
[Jan 01 19:06:39.455] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
[Jan 01 19:07:09.455] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
[Jan 01 19:07:39.456] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
[Jan 01 19:08:09.457] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
[Jan 01 19:08:39.458] [ message] [vmsvc] RecordRoutingInfoIPv6: route limit (100) reached, skipping overflow.
```

Reason for that seems to be that your code doesn't parse /proc/net/ipv6_route properly as it doesn't ignore RTF_CACHE and other uninteresting routes. The number of routes is very low in reality:

```
# netstat -nr -A inet6 
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref Use If
aaaa:bbbb:cccc:ddd::/64        ::                         U    256 0     1 eth0
fe80::/64                      ::                         U    256 0     0 eth0
::/0                           aaaa:bbbb:cccc:ddd::def    UG   1024 0     0 eth0
::/0                           ::                         !n   -1  144584362 lo
::1/128                        ::                         Un   0   1 11102 lo
aaaa:bbbb:cccc:ddd::130/128    ::                         Un   0   169480472 lo
aaaa:bbbb:cccc:ddd::131/128    ::                         Un   0   11655120 lo
fe80::250:56ff:fe96:2de4/128   ::                         Un   0   11192401 lo
ff00::/8                       ::                         U    256 0     0 eth0
::/0                           ::                         !n   -1  144584362 lo
```

or from the modern ip tool:

```
# ip -6 ro sh
aaaa:bbbb:cccc:ddd::/64 dev eth0  proto kernel  metric 256 
fe80::/64 dev eth0  proto kernel  metric 256 
default via aaaa:bbbb:cccc:ddd::def dev eth0  metric 1024 
```

You could have a look at the netstat or iproute source to figure out how to parse the file properly so the error doesn't happen on systems with a lot of ipv6 traffic.

**Comment by mkubecek** [comment]
The idea of parsing files in /proc/net to get routes is rather unfortunate, netlink should be used instead. But one would need to know what purpose the list serves to tell which routes should be collected and which not.

**Comment by stanguturi** [comment]
Please check 065f09b94e09f1127901db29e73cc9b9f36df4fc We have made changes to how the SlashProcNet_GetRoute[4|6] function(s) works. Only routes with RTF_UP bit set are captured. Try out the latest version of open-vm-ttools and see if the issue still happens.

**Comment by stanguturi** [comment]
> Please check [065f09b](https://github.com/vmware/open-vm-tools/commit/065f09b94e09f1127901db29e73cc9b9f36df4fc) We have made changes to how the SlashProcNet_GetRoute[4|6] function(s) works. Only routes with RTF_UP bit set are captured. Try out the latest version of open-vm-ttools and see if the issue still happens.

Closing this issue. Please reopen if you still find the issue with the latest version of open-vm-tools. Thanks.
