### ISSUE TITLE
Exclude popular CNI interface in GUESTINFO_DEFAULT_IFACE_EXCLUDES

### ISSUE THREAD

**Issue by lubronzhan** [vmware/open-vm-tools#638]
### Is your feature request related to a problem? Please describe.

`GUESTINFO_DEFAULT_IFACE_EXCLUDES` is defined.
Since k8s are more popular nowadays and their CNI also has IPs for pods, we should also exclude the IP assigned by popular CNI.
For example
```
antrea-*,cali*
```

### Describe the solution you'd like

```
GUESTINFO_DEFAULT_IFACE_EXCLUDES="docker*,veth*,virbr*,antrea-*,cali*"
```

**Comment by johnwvmw** [comment]
Late house keeping.   This issue and pull request #639 were addressed in open-vm-tools 12.3.0
