### ISSUE TITLE
hostinfoPosix.c - lsb_release not always installed - RHEL9 will not even ship it

### ISSUE THREAD

**Issue by PeterPitterling** [vmware/open-vm-tools#647]
### Describe the bug

https://github.com/vmware/open-vm-tools/blob/ed34acd62f67aceace5f28d214dc8e47b6e35691/open-vm-tools/lib/misc/hostinfoPosix.c#L1799

seems like "lsb_release" is always called even not available ...

Not all distros have lsb_release installed by default. 
RHEL9 will not even provide lsb_release 

### Reproduction steps

1. just run vmtoolsd - systemctl start vmtoolsd.service
2.
3.
...

### Expected behavior

check for existence of lsb_release or remove this kind of extraction

**Comment by pengzhencao** [comment]
Check a few lines bellow:
https://github.com/vmware/open-vm-tools/blob/ed34acd62f67aceace5f28d214dc8e47b6e35691/open-vm-tools/lib/misc/hostinfoPosix.c#L1801

If the output for "/usr/bin/lsb_release" is null then the open-vm-tools will use other files to check the OS release.

We should not remove this as this is useful for linux distros like ubuntu.

**Comment by Pitterling** [comment]
Ubuntu has os-release support at least since 16.04 LTS which is already out of support !
Again, in case of finding os-release you can stop extracting all other files+lsb_release

> lsb_release is not always installed on a system, and requires running a subprocess in order to get information from it. The /etc/os-release file is required by any system booting with systemd, and encouraged as a distro-neutral and init-neutral identification method used by a number of non-systemd distros too. It's purpose is to replace the multitude of distro-specific foo-release files, as well as to provide something documented to be readable by any programming language without, say, depending on the implementation of a CLI command like lsb_release.
> 
> See for details:
> http://0pointer.de/blog/projects/os-release
> https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by johnwvmw** [comment]
Responding to issues #647 and #648

Thanks for raising these two issues.

While many Linux distros do not provide LSB information and rely exclusively on the os-release standard information, the open-vm-tools releases must remain compatible with older Linux releases.  We cannot rely solely on the os-release data.  Some older Linux releases provide both LSB and os-release data with better data in one over the other.

Removing the check for both, could affect the recognition of the older Linux releases.  Retesting hundreds of older distros and their many releases would be prohibitive for the small performance gain in this only happens once at vmtoolsd start/restart OS identification check.

A quick check for LSB availability is being introduced and the result used to avoid attempting expensive LSB operations.  This solves the performance issue on newer Linux releases without jeopardizing compatibility.

**Comment by johnwvmw** [comment]
Fix was part of the open-vm-tools 10.3.0 release.
