### ISSUE TITLE
hostinfoPosix.c - read OsRelease before lsbDate, no need to try all: os-release,lsb_release,/etc/*-release files

### ISSUE THREAD

**Issue by PeterPitterling** [vmware/open-vm-tools#648]
### Describe the bug

currently lsb_release is called, if failing a long list of files is tested .. in addition os-release is tried ..
later on lsb is compared to os-release .. 

flip .. get HostinfoOsRelease first and if score > 0 skip HostinfoLsb

https://github.com/vmware/open-vm-tools/blob/ed34acd62f67aceace5f28d214dc8e47b6e35691/open-vm-tools/lib/misc/hostinfoPosix.c#L1980-L1981

### Reproduction steps

1. always active 
2.
3.
...

### Expected behavior

just extract once Hostinfo data, but not multiple times

**Comment by pengzhencao** [comment]
Thanks for trying to improve the efficiency to detect OS distros for open-vm-tools. However,  the open-vm-tools needs to supports a variety of Linux distros some are with lsb-release while some don't and some may even have both lsb-release and os-release info. We could  not know in advance which distro it is running so we have to collect release/distro info with various methods and then make a final conclusion.

**Comment by Pitterling** [comment]
> lsb_release is not always installed on a system, and requires running a subprocess in order to get information from it. The /etc/os-release file is required by any system booting with systemd, and encouraged as a distro-neutral and init-neutral identification method used by a number of non-systemd distros too. It's purpose is to replace the multitude of distro-specific foo-release files, as well as to provide something documented to be readable by any programming language without, say, depending on the implementation of a CLI command like lsb_release.
> 
> See for details:
> http://0pointer.de/blog/projects/os-release
> https://www.freedesktop.org/software/systemd/man/os-release.html

In case of finding /etc/os-release you can stop trying to extract data from lsb_release/*other-release files.

**Comment by johnwvmw** [comment]
Responding to issues #647 and #648

Thanks for raising these two issues.

While many Linux distros do not provide LSB information and rely exclusively on the os-release standard information, the open-vm-tools releases must remain compatible with older Linux releases.  We cannot rely solely on the os-release data.  Some older Linux releases provide both LSB and os-release data with better data in one over the other.

Removing the check for both, could affect the recognition of the older Linux releases.  Retesting hundreds of older distros and their many releases would be prohibitive for the small performance gain in this only happens once at vmtoolsd start/restart OS identification check.

A quick check for LSB availability is being introduced and the result used to avoid attempting expensive LSB operations.  This solves the performance issue on newer Linux releases without jeopardizing compatibility.
