### ISSUE TITLE
Customization not working on CentOS 7.2

### ISSUE THREAD

**Issue by rikatz** [vmware/open-vm-tools#65]
So, here is the problem:

I have a CentOS 7.2 machine. It has perl installed, as kernel-devel and open-vm-tools 9.10.2-4.el7.

While trying to customize this machine, the log '/var/log/vmware-imc/toolsDeployPkg.log' says that everything went fine.

But while taking a look inside the VM, I've figured out that Open VM Tools is customizing the wrong files:

- hostname - customizing /etc/sysconfig/network instead of /etc/hostname
- Network - customizing /etc/sysconfig/network/ifcfg-ether instead of the right interface.

Is this a bug or am I doing something wrong?

Thanks in advice!

**Comment by rikatz** [comment]
An update: If I change the '/etc/redhat-release' to 'Red Hat Enterprise Linux Server release 7.2 (Maipo)' this works fine.

Trying to find on the code where is this, to maybe help with something :D

**Comment by rikatz** [comment]
Compiled and tested with the 'master branch' version (10.0.0.5) and the same issue occur :(

**Comment by dyno** [comment]
the problem probably related to https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/lib/misc/hostinfoPosix.c

**Comment by rikatz** [comment]
Yes, as CentOS is almost the same as Red Hat, I'm doing some tests copying the block of Red Hat to CentOS (and supressing the 'enterprise if', to see if this works.

If it does, I'm going toopen an merge request with the correction ;)

**Comment by rikatz** [comment]
OK, so this changes something, but still doesn't work. 

VMWare is recognizing now the machine as RHEL 7 (and not CentOS 4/5/6/7) but the customization still doesn't work.

Going to check other stuffs :D

**Comment by aneverov4vmw** [comment]
Guest Customization feature as such is not part of the Tools. Only the deployPkg transport mechanism is.

The way we determine how to customize is based on the OS identification strings. In http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf you can see that on 5.5.x line CentOS7 support has been added one update release later than RHEL7. The only actual issue was that the id string didn't make it on time, that's why the workaround works.

**Comment by rikatz** [comment]
Ok, so the resolution for this issue is to update my vCenter to the latest release?

I'm using vSphere 5.5 2646489 (probably Update 2), upgrading this to U3 solves the issue?

Thanks!

**Comment by aneverov4vmw** [comment]
Yes, build 2646489 corresponds to VC 5.5 U2e. Upgrading to U3 should remove the need to apply id string workaround.

**Comment by rikatz** [comment]
OK, so upgraded to U3 and the issue is solved.

Thanks guys, closing this issue.
