### ISSUE TITLE
Possible typo in VMware Contributor Agreement

### ISSUE THREAD

**Issue by kernelsmith** [vmware/open-vm-tools#656]
### Describe the bug

When reading the VMware contributor agreement, the first sentence (I believe) of section 2 says "With respect to any worldwide copyrights, copyright applications and registrations in your Contribution, you irrevocably assign to us join copyright ownership". Should that be "With respect to any worldwide copyrights, copyright applications and registrations in your Contribution, you irrevocably assign to us join**t** copyright ownership"?

### Reproduction steps

1. Read the VMware Contributor Agreement and evaluate

### Expected behavior

That `join` be `joint` I believe.

**Comment by johnwvmw** [comment]
@kernelsmith 

Josh, Thanks for pointing out several typo's in the code and the Contributor Agreement.   The tools team typically does not get to see that license agreement, but I will pass this along to the legal department to correct their verbage.

Thanks again.

**Comment by kernelsmith** [comment]
No problem. Yeah, I figured as much, but I couldn't think of another way to communicate it to anyone who might know what to do with the info ;) As for the PR, it's not exactly a bug fix obviously, but for better or worse finding typos is my one super power especially when I'm NOT looking for them lol

**Comment by kernelsmith** [comment]
I'll close this issue so it's not making noise

**Comment by kernelsmith** [comment]
FTR, my PR was rejected, for a VMware Contributor Agreement reason that makes no sense. I am not a VMware employee
