### ISSUE TITLE
gdk-pixbuf-xlib is deprecated

### ISSUE THREAD

**Issue by ozbenh** [vmware/open-vm-tools#658]
### Is your feature request related to a problem? Please describe.

open-vm-tools currently requires `gdk-pixbuf-xlib` which is a deprecated library and might  be removed from some distribution.

A quick look seems to indicate that it's solely used for `gdk_pixbuf_xlib_get_from_drawable()` to retreive pixels from an X11 drawable to a GdkPixbuf.

Unfortunately I'm not familiar with what is the new recomended approach for this (whoever deprecated this never provided any pointer or recommendations about how to replace it) but I *assume* it's via Cairo...

### Describe the solution you'd like

open-vm-tools no longer relies on gdk-pixbuf-xlib

**Comment by johnwvmw** [comment]
Fix was delivered with the open-vm-tools 12.3.0 release.
