### ISSUE TITLE
autoreconf failed on FreeBSD 12

### ISSUE THREAD

**Issue by tbswork1** [vmware/open-vm-tools#665]
### Describe the bug

```
> autoreconf -i
autom4te2.71: error: need GNU m4 1.4 or later: /usr/local/bin/gm4
aclocal: error: /usr/local/bin/autom4te2.71 failed with exit status: 1
autoreconf2.71: error: aclocal failed with exit status: 1
```

### Reproduction steps

1. git clone the repo
2. cd open-vm-tools/open-vm-tools
3. autoreconf -i
...

### Expected behavior

no error

### Additional context

```
pkg info m4
m4-1.4.19,1
Name           : m4
Version        : 1.4.19,1
Installed on   : Mon May  8 17:42:26 2023 PDT
Origin         : devel/m4
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : devel
Licenses       : GPLv3
Maintainer     : sunpoet@FreeBSD.org
WWW            : https://www.gnu.org/software/m4/m4.html
Comment        : GNU M4
Options        :

```

**Comment by johnwvmw** [comment]
@tbswork1 

I have been unable to reproduce your failure.   On a FBSD 12.4 system, I was able to run through the following sequence:
- autoreconf -i
- ./configure --disable-vgauth  --enable-containerinfo=no  --without-icu
- make

My FBSD 12.4 system has:
   m4:      Version        : 1.4.19,1
   automake:     Version        : 1.16.5
   autoconf:      Version        : 2.71
   
My packages were installed back in Dec. 2022.  It appears that at least your "m4" packages was installed yesterday.

Are you certain that all needed build packages are correctly installed?

What FBSD 12 release are you using?

By the way open-vm-tools-nox11 and open-vm-tools 12.2.0 pacjages are available fro the FBSD repository.

**Comment by tbswork1** [comment]
after upgrading to FreeBSD 12.4 it can start to build but at the end, there is an error related GTK:

```
open-vm-tools/open-vm-tools/services/plugins/dndcp/dndUIX11.cpp:306: undefined reference to `Gtk::Widget::drag_dest_set(std::vector<Gtk::TargetEntry, std::allocator<Gtk::TargetEntry> > const&, Gtk::DestDefaults, Gdk::DragAction)'
collect2: error: ld returned 1 exit status
*** Error code 1
```

I am installing the the package on a headless server in VMWare hoping to improve the disk IO performance. With the ` --without-gtk3` I got similar build errors.

**Comment by johnwvmw** [comment]
This is the first mention of building on/for a headless system...

Please take a look at the output of ./configure --help

For a headless system you will want to suppress any attempt to build the desktop plugins.

Try "--without-x"

**Comment by tbswork1** [comment]
@johnwvmw 
Thanks it works. However after installing the latest of open-vm-tools , FreeBSD access to mounted Windows host share is still slow as before. I am using VMWare 17 Pro.
