### ISSUE TITLE
Getting shared folders to work on a linux guest

### ISSUE THREAD

**Issue by nemumaru** [vmware/open-vm-tools#679]
### Describe the bug

 - VMWare Workstation Pro Version 17.0.2 build-21581411
 - Host System: Win 10 Pro most recent version
 - Guest OS: Zorin OS 16 Core most recent version

I want to setup a shared folder between my windows host and my zorinOS(Ubuntu) guest that runs as a VM. In workstation I enabled "Shared Folders" and configured a folder with my host system. The guest has the most recent version of open-vm-tools-desktop installed and is in general everything is up to date.
Following the [docs][1] I run the following on the guest machine
`/usr/bin/vmhgfs-fuse .host:/ /home/user1/shares -o subtype=vmhgfs-fuse,allow_other`
and get faced with ```/usr/bin/vmhgfs-fuse: File or folder not found```
If I run `vmhgfs-fuse` I'm getting the info that the command `vmhgfs-fuse` could not be found but can be installed with `sudo apt install open-vm-tools` .
Despite the fact that I already got it installed, I now run `sudo apt install open-vm-tools`
and ofcourse get the info that nothing happened because I already got the most recent version of open-vm-tools installed.

  [1]: https://docs.vmware.com/en/VMware-Workstation-Pro/17/com.vmware.ws.using.doc/GUID-AB5C80FE-9B8A-4899-8186-3DB8201B1758.html

### Reproduction steps

1.Install VMWare Workstation Pro
2.Setup ZorinOS 16 Core via official ISO
3.Enable "Shared Folders"
4.Create shared folder on host
5.Install open-vm-tools-desktop

### Expected behavior

The shared folder is being mounted in the guest system.

**Comment by johnwvmw** [comment]
How was the "most recent version of open-vm-tools-desktop" installed on your VM?

Assumption: that you also have base open-vm-tools package installed.  

There is a dependency of open-vm-tools-desktop on open-vm-tools.   That dependency is built into the packaging by the open-vm-tools maintainer for your Linux and for Ubuntu systems, installing open-vm-tools-desktop should also install the open-vm-tools package at the same time.

The vmhgfs-fuse command is in the open-vm-tools package.

What version of OVT do you have installed; what is reported by the "vmtoolsd -v" command?

**Comment by nemumaru** [comment]
I installed it through apt and also did a clean reinstall of the machine. It now seems to work for some reason, eventhough I followed my own docs to ensure reproducability. I unfortunately have absolutely no idea what has been the issue, nor what fixed it now...

**Comment by johnwvmw** [comment]
I am glad to hear that things are working for you now.

**Comment by johnwvmw** [comment]
Please reopen this issue if you experience any addition problems with your shared folders
