### ISSUE TITLE
open-vm-tools fails to build on ubuntu 15.10

### ISSUE THREAD

**Issue by superbonaci** [vmware/open-vm-tools#68]
user@ubuntu:~/open-vm-tools/open-vm-tools$ ./configure --without-x --without-pam --without-ssl --without-icu

checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking build system type... (cached) x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /bin/sed
checking whether ln -s works... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for a sed that does not truncate output... (cached) /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking how to run the C++ preprocessor... g++ -E
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for pkg-config... yes
checking for X... disabled
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for libmspack >= 0.0.20040308alpha (via pkg-config)... yes
checking for glib-2.0 >= 2.14.0 (via pkg-config)... yes
checking for gmodule-2.0 >= 2.14.0 (via pkg-config)... yes
checking for gobject-2.0 >= 2.14.0 (via pkg-config)... yes
checking for gthread-2.0 >= 2.14.0 (via pkg-config)... yes
checking for glib-genmarshal... yes
checking for fuse (via pkg-config)... yes
checking CUnit/CUnit.h usability... no
checking CUnit/CUnit.h presence... no
checking for CUnit/CUnit.h... no
configure: WARNING: CUnit not found, tests won't be compiled.
checking for crypt in -lcrypt... yes
checking for dlopen... no
checking for dlopen in -ldl... yes
checking for ecvt... yes
checking for fcvt... yes
checking for pthread_mutex_init in -lpthread... yes
checking for libprocps (via pkg-config)... yes
checking for dumbnet-config... /usr/bin/dumbnet-config
checking for rpcgen... /usr/bin/rpcgen
checking crypt.h usability... yes
checking crypt.h presence... yes
checking for crypt.h... yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking sys/inttypes.h usability... no
checking sys/inttypes.h presence... no
checking for sys/inttypes.h... no
checking sys/io.h usability... yes
checking sys/io.h presence... yes
checking for sys/io.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/sysinfo.h usability... yes
checking sys/sysinfo.h presence... yes
checking for sys/sysinfo.h... yes
checking for sys/types.h... (cached) yes
checking for sys/user.h... yes
checking sys/vfs.h usability... yes
checking sys/vfs.h presence... yes
checking for sys/vfs.h... yes
checking syslimits.h usability... no
checking syslimits.h presence... no
checking for syslimits.h... no
checking unwind.h usability... yes
checking unwind.h presence... yes
checking for unwind.h... yes
checking for wchar.h... (cached) yes
checking linux/unistd.h usability... yes
checking linux/unistd.h presence... yes
checking for linux/unistd.h... yes
checking for ecvt in -lc... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for an ANSI C-conforming const... yes
checking for uid_t in sys/types.h... yes
checking for inline... inline
checking for mode_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for struct stat.st_rdev... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for working volatile... yes
checking for GCC flag -Wno-pointer-sign... yes
checking for GCC flag -Wno-unused-value... yes
checking for GCC flag -fno-strict-aliasing... yes
checking for GCC flag -Wno-unknown-pragmas... yes
checking for GCC flag -Wno-uninitialized... yes
checking for GCC flag -Wno-deprecated-declarations... yes
checking for GCC flag -fvisibility... yes
checking for GCC flag -Wno-unused-but-set-variable... yes
checking for doxygen... yes
checking for dot... no
checking for mscgen... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating lib/appUtil/Makefile
config.status: creating lib/auth/Makefile
config.status: creating lib/backdoor/Makefile
config.status: creating lib/asyncsocket/Makefile
config.status: creating lib/sslDirect/Makefile
config.status: creating lib/pollGtk/Makefile
config.status: creating lib/poll/Makefile
config.status: creating lib/dataMap/Makefile
config.status: creating lib/hashMap/Makefile
config.status: creating lib/dict/Makefile
config.status: creating lib/dynxdr/Makefile
config.status: creating lib/err/Makefile
config.status: creating lib/file/Makefile
config.status: creating lib/foundryMsg/Makefile
config.status: creating lib/glibUtils/Makefile
config.status: creating lib/guestApp/Makefile
config.status: creating lib/guestRpc/Makefile
config.status: creating lib/hgfs/Makefile
config.status: creating lib/hgfsBd/Makefile
config.status: creating lib/hgfsHelper/Makefile
config.status: creating lib/hgfsServer/Makefile
config.status: creating lib/hgfsServerManagerGuest/Makefile
config.status: creating lib/hgfsServerPolicyGuest/Makefile
config.status: error: cannot find input file: lib/hgfsUri/Makefile.in

**Comment by ravindravmw** [comment]
Looks same as issue #42.

Try running 'autoreconf -i' before 'configure'.

**Comment by superbonaci** [comment]
Autoconf* is missing. There are two versions of autoconf:

* autoconf
* autoconf2.13

Finally I've installed autoconf2.13

sudo apt-get install build-essential libtool autoconf2.13
sudo autoreconf -i

**Comment by superbonaci** [comment]
sudo insmod modules/linux/vmhgfs/vmhgfs.ko
sudo  mount -t vmhgfs .host:/ /mnt
Error: cannot mount filesystem: Input/output error

**Comment by dyno** [comment]
what does `mount` show? is there anything already mounted in `/mnt`? have you enabled shared folder in Workstation or Fusion? have you tried `reboot`?

**Comment by superbonaci** [comment]
Yes, there are already folders under /mnt/ which I used to mount loopback devices and bitlocker raw images. The problem was I had sharing folder disabled in Workstation. Not works:

sudo insmod modules/linux/vmhgfs/vmhgfs.ko
sudo mkdir -p /mnt/hgfs
sudo mount -t vmhgfs .host:/ /mnt/hgfs
Could not add entry to mtab, continuing

Now, how can I install the module and set it to autoload and automount?

**Comment by dyno** [comment]
auto load vmhgfs.ko,
```
cp vmhgfs.ko /lib/modules/$(uname -r)/vmware/vmhgfs.ko
dpmod -a
modinfo vmhgfs
## edit /etc/modules and add vmhgfs to the end
```

auto mount: 
```
cp hgfsmounter/mount.vmhgfs /sbin/
 ## edit /etc/fstab and add
.host:/ /mnt/hgfs vmhgfs  defaults 0 0
```

**Comment by superbonaci** [comment]
For ubuntu:

auto load vmhgfs.ko:

```
sudo su

mkdir -p /lib/modules/$(uname -r)/vmware/

cp modules/linux/vmhgfs/vmhgfs.ko /lib/modules/$(uname -r)/vmware/vmhgfs.ko

depmod -a

modinfo vmhgfs

grep -q -F 'vmhgfs' /etc/modules || echo 'vmhgfs' >> /etc/modules
```

auto mount:

```
sudo su

cp hgfsmounter/mount.vmhgfs /sbin/

(grep -q 'vmhgfs' /etc/fstab && echo 'vmhgfs already exists, skipping') || echo '.host:/ /mnt/hgfs vmhgfs  defaults 0 0' >> /etc/fstab
```

Check if vmware shared folders is mounted after reboot:

`(mount | grep -q '.host:/ on /mnt/hgfs' && echo 'VMWare Shared Folders mounted!') || echo 'VMWare Shared Folders NOT mounted!'`

**Comment by pitaj** [comment]
I've built `open-vm-tools` on Ubunto 15.10 using the following commands in the main directory, all of which seemed successful:

```bash
sudo apt-get install libpam0g-dev libgtk2.0-dev openssl libmspack-dev libxml-security-c-dev libxerces-c-dev libssl-dev libxtst-dev libgtkmm-2.4-dev libprocps3-dev libdnet-dev libdumbnet-dev libtool
autoreconf -i
./configure
make
```

However, it seems that they are not installed. I've tried `sudo make install`, but that seems to have no effect.

**Comment by johnkw2275** [comment]
pitaj,

I don't know if this will help you but I ran it with
sudo ./configure --disable-multimon
sudo make MODULES=vmhgfs
sudo insmod modules/linux/vmhgfs/vmhgfs.ko
sudo mount -t vmhgfs .host:/ /mnt
ls /mnt

**Comment by pitaj** [comment]
@johnkw2275 it's not really the vmhgfs that I'm having an issue with. I'm trying to get 3d hardware acceleration to work and other stuff as well

**Comment by superbonaci** [comment]
@pitaj install open-vm-tools and open-vm-tools-desktop with apt-get and them compile and install vmhgfs.ko as stated.

**Comment by pitaj** [comment]
@superbonaci `open-vm-tools-dkms` fails to install correctly

Will this allow for 3d acceleration

**Comment by superbonaci** [comment]
@pitaj `open-vm-tools*` is much more than shared directories. Sure it will allow you for faster graphics performance. If you can't install kernel modules for open-vm-tools you should check why it happens, or build and install them manually.

**Comment by pitaj** [comment]
> or build and install them manually

Yes, this is exactly what I want to do. This was my whole purpose of commenting on this issue: I can't fit the life of me figure out how to build and install the modules from this repository. 

I want to figure out what modules exist, how to specify to build all modules (if possible), what modules are parts of the repository shipped packages (open-vm-tools, -desktop, -dkms), and what modules are required to enable 3d graphics hardware acceleration. 

The documentation, even in the VMWare KB, is very sparse and difficult to navigate. 

I've figured out, from observing the issues on this repo, that most people use the open-vm-tools to use shared directories between the host and guest. 

If I don't need this functionality, should I just use the proprietary tools provided by the VMware client, since the latest open tools available in the repositories do not support my OS version? Will this allow me to have the features I want?

**Comment by ravindravmw** [comment]
@pitaj I think your issue is more like issue #53. Could you please add your problem there?

> I want to figure out what modules exist

You can see the modules listed under https://github.com/vmware/open-vm-tools/tree/master/open-vm-tools/modules/linux. All the directories except 'shared' are the modules.

> how to specify to build all modules (if possible)

By default all modules are built if your Linux kernel is old enough. Here are the Linux version based driver selections for the the build: https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/configure.ac#L1036.

> what modules are parts of the repository shipped packages (open-vm-tools, -desktop, -dkms),

You should be able to check that from the contents of the respective packages.

> and what modules are required to enable 3d graphics hardware acceleration.

Let's take this up in issue #53.

> I've figured out, from observing the issues on this repo, that most people use the open-vm-tools to use shared directories between the host and guest.

open-vm-tools is pretty much as useful as VMware Tools.

> If I don't need this functionality, should I just use the proprietary tools provided by the VMware client, since the latest open tools available in the repositories do not support my OS version? Will this allow me to have the features I want?

I don't think that will help, but you can try that and update issue #53 with your findings. open-vm-tools do support Ubuntu 15.10. The only problem to be solved is  3D acceleration.

**Comment by superbonaci** [comment]
Solved for now.
