### ISSUE TITLE
update Guest Tools (v12.3.25) to Version 

### ISSUE THREAD

**Issue by hamzaouichaker** [vmware/open-vm-tools#687]
### Describe the bug

I know its not a bug but i dont know how to ask this question.
We run Ubuntu 22.04.3 LTS and if we do a apt-get update and apt-get upgrade the open-vm-tools are not updated.
I got the message that we run the newest version.

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
open-vm-tools is already the newest version (2:12.1.5-3~ubuntu0.22.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

### Reproduction steps

1. access to Ubuntu 22.04.3 LTS
2.  run sudo apt-get install open-vm-tools
3. 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
...

### Expected behavior

Version should be updated to 12.3.25

**Comment by johnwvmw** [comment]
This question should be directed to Ubuntu.

The open-vm-tools packages are provided by the Linux vendors.   At least 1 week prior to any VMware Security Announcement (VMSA), Linux vendors are provided with advanced warning and patch(es) to address the security problems in each open-vm-tools version that they may be actively supporting.  Your currently installed OVT package (2:12.1.5-3~ubuntu0.22.04.2) was for an earlier announced VMSA.   I would expect that a security update for OVT 12.1.5 for Ubuntu  22.04 may be underway.

I believe that for new OVT releases, Ubuntu initially targets those packages for the next up coming release - 23.10 (mantic).  Once in that next release, the OVT version may be considered for back port to supported LTS Ubuntu releases.
Whether or when that might happen, I cannot say.

UB 22.04 was initially released with OVT 11.3.5 (2:11.3.5-1ubuntu4 [ports]: arm64)  and later upgraded to OVT 12.1.5  (2:12.1.5-3~ubuntu0.22.04.2 [security]: amd64).
