### ISSUE TITLE
DKMS does not build 

### ISSUE THREAD

**Issue by LethalManBoob** [vmware/open-vm-tools#688]
### Describe the bug

THIN LTO cachyos kernels will not build dkms

### Reproduction steps

install cachyos-rt or lto
try to launch vmware

### Expected behavior

supposed to open

### Additional context

_No response

**Comment by LethalManBoob** [comment]
![image](https://github.com/vmware/open-vm-tools/assets/30273211/e4e4f75b-2aa6-4d24-b27a-0e7a085257a6)

**Comment by johnwvmw** [comment]
It appears that you may be trying to install Workstation 17.0.2 for Linux onto your Arch Linux.

This is clearly not an open-vm-tools issue.   I have pinged the Workstation team for any guidance that they may be able to provide or possibly another contact point.   

In the mean time, you may wish to post you issue and questions on the VMware Community site at https://communities.vmware.com/t5/VMware-Workstation/ct-p/3019-home

**Comment by johnwvmw** [comment]
Not an open-vm-tools issue.
