### ISSUE TITLE
vmware-rpctool Permission denied with guest_rpc.rpci.auth.cmd.info-get

### ISSUE THREAD

**Issue by playerla** [vmware/open-vm-tools#690]
### Describe the bug

Hi, 

Following  #288 non-root user can change the VM's configuration by vmtoolsd. I set up 
```
guest_rpc.rpci.auth.cmd.info-set = "TRUE"
guest_rpc.rpci.auth.cmd.info-get = "TRUE"
```
and get expected behaviour for vmtoolsd as described in #288
(`vmtoolsd --cmd 'info-get guestinfo.userdata'` as root return what we want for cloud-init)

But cloud-init use vmware-rpctool with equivalent command still as root. Here the bug :
```
vmware-rpctool  'info-get guestinfo.userdata'
Permission denied
```

Why this different between vmware-rpctool "a utility provided by open-vm-tools to set metadata, userdata and vendordata" and the Linux daemon vmtoolsd ?

What am I missing ?

From #288 :

> How does open-vm-tools identify “privileged users”?
> The verification is based on the usage of privileged port (< 1024) which is not allowed by the guest for non-privileged users.

### Reproduction steps

1. Deploy a Linux (test on Debian11 VMWare Tools daemon 11.2.5.26209 build-17337674 from apt - https://packages.debian.org/bullseye/open-vm-tools)
2. Set VMX guestinfo.userdata
3. Run vmware-rpctool  'info-get guestinfo.userdata'

### Expected behavior

Authorized to read guestinfo from root user with vmware-rpctool

**Comment by lemke1458** [comment]
rpctool does not support secure RPCs, and we'd like to deprecate it.

'vmtoolsd --cmd' does support secure RPCs, and is the preferred way to execute RPCs.

**Comment by playerla** [comment]
Thank you, I open an issue there https://github.com/canonical/cloud-init/issues/4436

**Comment by playerla** [comment]
Hi @lemke1458 

Is rpctool for Linux distributed outside open-vms-tools (this repository) ?

Would it be relatively safe to assume we could replace vmware-rpctool by vmstoold ?

Thanks

**Comment by lemke1458** [comment]
rpctool isn't distributed by VMware outside of open-vm-tools.

I think it depends on who 'we' is and how its being used.

'vmtoolsd --cmd' won't work in sufficiently old version of VMware Tools.  

Secure RPCs also depend on having vmci and vsocket kernel drivers installed, which may not be true, either by administrator choice or because the OS is one that doesn't have it (eg, some Unix variant like a real time OS).

**Comment by lemke1458** [comment]
See https://github.com/canonical/cloud-init/pull/4444
