### ISSUE TITLE
clean install of rhel 9.2 on esxi 8u2 goes as expected, until reboot, afterwards keyboard doesn't work

### ISSUE THREAD

**Issue by lknite** [vmware/open-vm-tools#695]
### Describe the bug

I can see that open-vm-tools was installed automatically, could this issue be related to open-vm-tools?
``` Running, version:12325 (Guest Managed) ```

I have 19 new rhel vms all exhibiting the same behavior.

### Reproduction steps
VM Hardware
* ESXi 8.0 U2 and later (VM version 21)

1. boot off the rhel 9.2 dvd iso
2. install 'minimal' or 'linux server'
3. after everything completes and the system reboots, keyboard no longer works via 'web console' or 'remote console'

### Expected behavior

Since the keyboard works during installation I was surprised to see it not work after the install finished.

**Comment by rprabhud** [comment]
Hi, Thank you for reporting the problem.
We tried to reproduce the problem but could not reproduce.
Were all 19 VMs installed separately from ISO or were the 18 clones or deploys from a template made from the original faulty VM?
Are the VMs responsive, powered on and are you able to ssh into the VMs?
Can you disconnect from the web console and then open a new web-console and try?

**Comment by lknite** [comment]
This looks to have been a learning curve on my side. Though I deleted and recreated Standard vSwitches via the esxi hosts, and deleted and recreated the distributed switch via vcenter, as well as many distributed switch ports, it wasn't until I asked someone more senior and we started over creating a standard switch then 'migrated the switch to the distributed switch' that the keyboard began working. So, I can't be sure of the exact fix, other than to say I saw a very old similar posting speaking about network connectivity being involved in the keyboard not working via the web console and I think that probably captures the issue I was experiencing as well.

Marking this one as resolved.

**Comment by rprabhud** [comment]
Hi,
You can try below two workarounds if the issue happens again:
(1) Power off the VM, and add the config option:
keyboard.allowBothIRQs = FALSE
This might cause your Linux VM's input to hang if the Guest tries to Sleep/Hibernate, but it may work-around the problem.
(2) Power off the VM and make sure the VM has a USB controller, and add this config option to switch to the virtual USB keyboard:
keyboard.vusb.enable = TRUE
That will switch from using the PS/2 keyboard to the USB keyboard, but may make your key-repeat get stuck more often.
