### ISSUE TITLE
Kali running on VMWare freezes suddenly 

### ISSUE THREAD

**Issue by marcushabib** [vmware/open-vm-tools#697]
### Describe the bug

My Kali Linux, which is running on VMWare, freezes suddenly. The host is Windows 11.

Over six months I tried so many things, including starting from stopping the firewall and AV, changing the VMWare RAM, and processor, and deleting the virtual CD/DVD, reinstalling Windows to the extent that I requested DELL to exchange their "faulty" laptop. However the issue persisted, even though I downloaded a new VMWare and Kali Linux on the new laptop

### Reproduction steps

1. It just decides to freeze! There is no specific pattern, nevertheless, I noticed the freezing frequency increases when I RDP to another machine.
2. Sometimes the username and password fields do not accept keyboard entries, so I have to restart the machine several times.
3
...

### Expected behavior

I expect the machine not to freeze and run smoothly, same as it was when I used my older laptop (which ran Windows 10 and VMWare Pro too)

**Comment by jonathanvmw** [comment]
@marcushabib - Thank you for reporting the problem. Based on your description, this issue does not appear to be related to open-vm-tools. Please use VMTN (https://communities.vmware.com/) or VMware Support service for further updates on this issue or other product issues unrelated to open-vm-tools.

If further investigation points to a problem in open-vm-tools, please reopen the issue and provide further details.  Thank you.
