### ISSUE TITLE
Customize.pl support for ubuntu 22.04

### ISSUE THREAD

**Issue by wanfangli** [vmware/open-vm-tools#698]
### Describe the bug

Hi here, I meet a problem when setting the static IP using the vmware_guest. As we know, vmguest will call the vmtools to set static IP, and if we don't have the cloud-init, we will use the customize.pl to set the static IP, I found that the script can not find the correct version of ubuntu 22. It shows that the version is ubuntu, not ubuntu 22. And use the UbuntuCustomization customize instance, but we should use UbuntuNetplanCustomization instead which works on Ubuntu 22. I guess we need help to support ubuntu 22.04 in Customize.pl, make it find the correct version of ubuntu 22. 

### Reproduction steps

1. deploy a u22 vm on vsphere
2. use ansible.vmware_guest to set the static IP
3. find the log in /var/log/vmware-imc/tooolsDeployPkg.log

U22 log:
![Image 12-6-23 at 5 03 PM](https://github.com/vmware/open-vm-tools/assets/153144956/e003b58b-e32e-48ad-aa1b-ae5a3d4c1988)

U18 log (correct one):
![Image 12-6-23 at 5 04 PM](https://github.com/vmware/open-vm-tools/assets/153144956/7af38ff2-1678-4871-8e19-ece3b05796e5)

### Expected behavior

I guess we need help to support ubuntu 22.04 in Customize.pl, make it find the correct version of ubuntu 22.

**Comment by PengpengSun** [comment]
Hi @wanfangli, may I know your vCenter server version/build? Please check [https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf](https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf), Ubuntu 22.04 customization is supported since vSphere 7.0 Update 1 release.

**Comment by wanfangli** [comment]
Oh thanks..... I found we use the 6.7 which is not supported. Thanks for your info, I will let my colleagues know.
