### ISSUE TITLE
fails to quiesce running rsync and gluster

### ISSUE THREAD

**Issue by magicrobotmonkey** [vmware/open-vm-tools#7]
I have a host on ESX which I'm using to rsync on to gluster. When the nightly backups occur, I get hung_task_timeouts and the snapshot fails because of a failure to quiesce. The backup guy claims we cannot turn off quiesced backups because we are using a 3rd party backup solution. Is there I way I can disable quiescing from the machine itself?

**Comment by ravindravmw** [comment]
Yes, you can disable quiescing from the guest if you know for sure that's what you really want. Following are the steps:

1. Create /etc/vmware-tools/tools.conf file in the guest
2. Have following configuration in the file above:

# Start
[vmbackup]
enableSyncDriver=false
# End

This will make open-vm-tools lie about quiescing, so use this as a last resort when you absolutely don't want quiescing or when you want a temporary workaroud when the issues is being looked into. In most of the cases, you might need to get VMware support involved to figure out what is going on with your VM.

PS: github is not the right platform for discussing such questions, please consider using VMware Community forums for such questions and limit github for open-vm-tools project specific issues (e.g. download/build etc).

**Comment by ravindravmw** [comment]
I assumed you know how disabling guest quiescing will impact VM backups. If you don't know, please be aware that your VM backups will no longer be guaranteed to have file system consistency. This means your backups might have corrupt file system and/or application data, so when you restore such backups, it will be totally up to the file system and/or application to deal with inconsistencies. Even if file system and/or application recover from the inconsistencies, there will still be some amount of data loss in these backups (writes that have not made into disk yet will be lost).

**Comment by magicrobotmonkey** [comment]
Yes, I'm aware of the risks. This machine in particular is OK without backups as it doesn't hold important data and its configuration is safely stored in source control.

OTOH, I am going to be bringing up hosts with gluster drives mounted which will need backups. I suspect that the issue may be caused by vm-tools attempting to quiesce the gluster drive. Is it possible to tell the vm tools which drives don't need quiescing in order to take a snapshot?

**Comment by ravindravmw** [comment]
> Is it possible to tell the vm tools which drives don't need quiescing in order to take a snapshot?

Nope, unfortunately there is nothing in our code today. We expect Linux kernel to deal with unsupported filesystem and return proper error code (EOPNOTSUPP in this case) for FIFREEZE IOCTL.

**Comment by mgorbach** [comment]
I'm getting something very similar, in fact causing a whole system hang, with nfsv4: https://communities.vmware.com/thread/509368

**Comment by bzed** [comment]
Same here, even without special filesystems involved.
A Debian user also reported the same: http://bugs.debian.org/784398

**Comment by bzed** [comment]
@ravindravmw if github is not the right platform to discuss issues, why do you have the source code here at all? You might want to learn that having all commits in the public would actually help you, for example in fixing this bug. It would have been tracked down already for sure.

**Comment by bzed** [comment]
Also just to keep things tracked here, this happens with Debian Jessie, using the vmv_* kernel modules from the Debian kernel - and with Debian Wheezy, using the modules from open-vm-tools.

**Comment by ravindravmw** [comment]
bzed, I believe there are different issues here:

We fixed an issue with NFS mount locking up quiescing operation in open-vm-tools-9.4.6. You can compare and see the differences in lib/syncDriver/syncDriverPosix.c between version 9.4.0 and 9.4.6. We skip NFS mounts from quiescing now. The communities thread seems to be NFS related.

The debian issue seems different. It seems to be an outcome of communication failure between guest and host. Could you please start a separate issue for tracking this? I can advise with next steps once you create a new issue for this.

**Comment by ravindravmw** [comment]
I have raised a VMware internal bug to provide a way to skip quiescing specific paths in the guest.

**Comment by ravindravmw** [comment]
For the record, Debian issue reported by bzed was tracked as #16.

**Comment by stanguturi** [comment]
> I have raised a VMware internal bug to provide a way to skip quiescing specific paths in the guest.

Please check 477ed7490a0c8376b050b49af84a07e82490fbe6 Using a specific option in tools.conf, specific file system mounts can be skipped during 'quiesce snapshot' operation. Please take the latest version of open-vm-tools.

With that fix in place, I believe, we can close this issue. Thanks.
