### ISSUE TITLE
Stability issues on Debian Jessie 8 ("Failed to quiesce the virtual machine.")

### ISSUE THREAD

**Issue by patschi** [vmware/open-vm-tools#70]
Hello,

I'm running out of ideas and after some investigation and researching I *think* that the issue may rely on the open-vm-tools. If not, than I'm sorry for stealing your valuable time!

At the end of the github issue #16 someone was reporting debian hang-issues too. But finally I decided to open a new issue for that as I don't know if the problems have really something together.

The point is, that I'm experiencing heavy stability issues with Debian Jessie 8 (8.3 to be more specific) on ESXi 6.0 U1b build 3380124 with installed open-vm-tools. My Debian 8 VMs are crashing randomly with a kernel panic when trying to create snapshot with FS-quiescing enabled: When taking the snapshot the percentage is stuck at 0% and some seconds later the kernel panic occurs. About 15 minutes later the snapshot task finally times out.

![image](https://cloud.githubusercontent.com/assets/2029878/12747694/e0e9e5da-c9a5-11e5-8b42-84ddf06e1ac9.png)

Sometimes the snapshot works, sometimes the VM crashes completely. It seems to be completely randomly. Even when my Veeam instance is backupping up my homelab every night, the kernel "only" gets a panic every several days and not every day when the job runs.

A excerpt of hostd.log: (newly installed, only GitLab instance running)
```
2016-02-01T18:20:55.044Z verbose hostd[39940B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/549ae562-fad9a162-1e30-0cc47a0d187a/vsrvgit01/vsrvgit01.vmx opID=2bf0ae38-41-672e user=vpxuser:DOMAIN\sa-veeam] Create Snapshot: VEEAM BACKUP TEMPORARY SNAPSHOT, memory=false, quiescent=true state=4
2016-02-01T18:35:55.066Z verbose hostd[394CDB70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/549ae562-fad9a162-1e30-0cc47a0d187a/vsrvgit01/vsrvgit01.vmx] Handling vmx message 14208: Timed out while quiescing the virtual machine.
2016-02-01T18:35:55.066Z info hostd[394CDB70] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 44478 : Warning message on vsrvgit01 on esxi01.domain.tld in ha-datacenter: Timed out while quiescing the virtual machine.
2016-02-01T18:35:55.067Z verbose hostd[37D76B70] [Originator@6876 sub=Vigor.Vmsvc.vm:/vmfs/volumes/549ae562-fad9a162-1e30-0cc47a0d187a/vsrvgit01/vsrvgit01.vmx] Create Snapshot message: An error occurred while saving the snapshot: Failed to quiesce the virtual machine.
--> An error occurred while taking a snapshot: Failed to quiesce the virtual machine.
```

The reason why I think that it could be a issue with open-vm-tools is that the issue sounds similar to #16 and because my Debian Wheezy 7 (7.7 currently) VMs with open-vm-tools from the Debian repository (8.8.0+2012.05.21-724730-1+nmu2+deb7u1) are running quite stable. I experience the described issue only on Debian Jessie 8 VMs with open-vm-tools 9.4.6-1770165-8 so far. Multiple virtual machines with Deb8 are affected by this issue (even a fully fresh virtual machine with just open-vm-tools).

Thanks for your time and your help!

Best regards,
Patrik

**Comment by patschi** [comment]
Just some more observations in short:
- Windows systems are stable (Windows Server 2012 R2, Windows 10)
- Debian Wheezy 7 VMs are stable
- Other Linux distributions like SUSE Linux Enterprise are stable
- Debian Jessie 8 VMs are crashing when trying to make snapshots with FS-quiesce enabled
- Not happing on every snapshot
- It seems that it does not matter if a virtual machine has a "high" load (loadavg 5m 1.50) or is idling

**Comment by ravindravmw** [comment]
open-vm-tools is only involved in invoking FIFREEZE and FITHAW IOCTLs to quiesce and resume file system activity in the guest. If these calls crash the system, you will hit it every time.

Kernel crash is most likely a kernel bug in the way file system is reacting to the IOCTLs we invoke. You might want to raise this with Debian kernel maintainers with the kernel dump/panic details.

**Comment by patschi** [comment]
Thank you very much for the clarification! :)
I'm doing some more tests and will open a bug then on the Debian site.

**Comment by benasse** [comment]
@patschi 
Hello,
Did you find a solution ?
I have the same symptoms and have not found the mentioned bug on the debian bug tracker.

Regards,

**Comment by patschi** [comment]
Well, I decided for the more easier way: I switched to Ubuntu LTS and used vmware-tools on the affected Debian machines. Someday I upgraded my ESXi to a higher patch level and as far as I know this fixed it as well...

Can't remember all details anymore, it was more than 1,5 years ago :)

**Comment by benasse** [comment]
Thank you for the answer, I will see what it is possible to make in my context.
