### ISSUE TITLE
Slow SSD Disk Write Performance (VMWare Workstation Pro 17.5)

### ISSUE THREAD

**Issue by DanielEgenolf** [vmware/open-vm-tools#702]
### Describe the bug

Hello,

After the last upgrade of VMWare Workstation Pro 17.0.2 -> 17.5 I am having strange disk i/o write performance issues inside my VM. The Vmware software is installed on Windows 11 22H2 and the operating system of the VM is Ubuntu 22.04.

I use the following command to measure the disk write speed.
time dd if=/dev/zero of=test bs=1M count=8192

On windows (using Git Bash) the command finishes after a few seconds having a disk write speed of around 2,5 GB/sec. In my Ubuntu VM (on the same laptop) the disk write speed is only up to 30MB/sec.

The windows features Hyper-V, Windows Hypervisor, etc. are not enabled. Nevertheless, I tried to install Ubuntu on Hyper-V temporarily to test the command above. Inisde Hyper-V I am having a disk write speed of 2,5GB/sec too.

Why is the disk write speed so bad using VMWare 17.5? Is this related to the VMWare-Tools on Ubuntu?

Any help appreciated!

Thanks and kind regards
Daniel

### Reproduction steps

1. Install VMWare 17.5 on Windows 11 22H2
2. Install Ubuntu 22.04 as VM
3. Run the following command to test the disk write speed:
time dd if=/dev/zero of=test bs=1M count=8192

### Expected behavior

The disk write speed should be higher than 1GB/sec when using a SSD.

**Comment by lousybrit** [comment]
Hello
Thanks for reporting this.
Please can you confirm a couple of things.
I assume you are writing to the local disk in the Ubuntu 22.04 VM, is that correct?
What is the disk controller you are using for your disk e.g. SCSI and lsilogic.
If that is the configuration, then it is not directly Tools related. It would be a question for another group which I could file a request to handle.

Thanks.

**Comment by DanielEgenolf** [comment]
Hello @lousybrit,

thanks for your comment! Our team is using VMWare Workstation Pro since many years for our daily work. We all have the same setup:

- **Host OS:** Windows 11 Version 22H2 (OS Build 22621.2715)
- **Guest/VM OS:** Ubuntu 22.04 LTS
- **VMWare Workstation Pro:** 17.5.0 build-22583795
- **Disk Controller:** SCSI (lsilogic)
- **Local disk:** SSD
- **VMX Monitor Mode:** ULM

After the last upgrade of VMWare version to 17.5 the half of our team cannot use the VM anymore because it is so slow. The disk write speed is <= 30MB/sec. All versions and also the VMWare configuration file is identical for all of us. We are all using the same version of vmware-open-tools.

The only thing that is different is the laptop. Colleagues which are using the "Lenovo P1 G2 I9" do not have the disk write problem. All other colleagues are using the "Lenovo P1 G5 I7" and there the disk write speed is very slow.

Thanks in advance
Daniel

**Comment by lousybrit** [comment]
I have passed on the details to the relevant team to look into this.
I hope that they will be able to help and update here.

**Comment by witallwang** [comment]
Hi Daniel, please try to change the VM's controller from lsilogic to PVSCSI to see if the performance improves while we are trying to reproduce. This will help to confirm if the issue is lsilogic related. Thanks.

**Comment by DanielEgenolf** [comment]
Hello @witallwang,

this helped a little bit:

```
$ dd if=/dev/zero of=HUGO bs=1M count=8192
1140+0 records in
1140+0 records out
1195376640 bytes (1.2 GB, 1.1 GiB) copied, 12.7634 s, 93.7 MB/s
```
Now, the disk write speed is <= 100 MB/s. But still this is too slow. Normally, I had a disk write speed up to 2,5 GB/s on the same device.

Thanks for checking.

**Comment by lousybrit** [comment]
Hi Daniel.
For general issues related to Workstation you can try the VMware Community forums
 e.g. https://communities.vmware.com/t5/VMware-Workstation/ct-p/3019-home
It is also a good place to raise product issues or questions.

**Comment by witallwang** [comment]
Hi @DanielEgenolf,
I tried to repro in my local setup but it seems fine.

VMware® Workstation 17 Pro
17.5.0 build-22583795
matt@debian:~$ dd if=/dev/zero of=./a bs=1M count=8192
8192+0 records in
8192+0 records out
8589934592 bytes (8.6 GB, 8.0 GiB) copied, 11.4641 s, 749 MB/s

Could you file an SR to VMware and follow the steps described in https://kb.vmware.com/s/article/1346 to collect debug data? Thanks.

**Comment by witallwang** [comment]
I noticed that "Lenovo P1 G5 I7" has i7-12700H CPU, which has 6 P-cores and 8 E-cores.

Total Cores
14
# of Performance-cores
6
# of Efficient-cores
8

My setup was AMD-7500F, with no E-cores. It's a good idea to check if vmx process was running on E-cores, if so, please tie it to P-cores.

**Comment by DanielEgenolf** [comment]
Hi @witallwang,

thank you for checking this issue. Unfortunately, it is not possible to file an SR to VMware. I have to create an internal IT ticket for that in our company.

The hint regarding the P-cores and E-cores helped a little bit. Now, the vmx process is tied to P-cores only and the disk write speed is about 200-300MB/sec. This is much better than 30MB/sec :).

But still this disk write speed is far to slow. We cannot compile our projects anymore in that VMs because it takes far too long. We switched to Hyper-V solution. There, the disk write speed is 2,5 GB/sec again.

Thanks for your help! I am closing this issue as it is not related to the open-vm-tools.
