### ISSUE TITLE
systemd PrivateTmp breaks deployPkg functionality

### ISSUE THREAD

**Issue by divad** [vmware/open-vm-tools#72]
On systemd based systems (like RHEL7, and upcoming Debian/Ubuntu releases) there is a systemd function called PrivateTmp. The RHEL packaged version of open-vm-tools sets this on 'vmtoolsd'. This means that anything that open-vm-tools/vmtoolsd does in /tmp is hidden from the rest of the system and is wiped on reboot.

When using deployPkg guest customisation system (after a VM clone or SRM) a file is created in /tmp called '/tmp/.vmware-deploy.Done'. Many people, including me, check to see if that file exists to determine if the guest tools customisation has run successfully.

open-vm-tools arguably should not be doing this - it should not be storing this file in /tmp. Because it does, when combined with PrivateTmp in systemd, you can't determine if guest tools customisation is complete. This breaks our build system and renders creating that file useless.

Can you please change open-vm-tools so that it creates this marker file outside of any tmp directory so that PrivateTmp does not affect it, e.g. /var or /etc ? 

Thanks in advance,

David Bell
University of Southampton

**Comment by ravindravmw** [comment]
Thanks for reporting this issue. We have created an internal bug to track it.

**Comment by LIV2** [comment]
@ravindravmw is this still being looked at?

Thanks,
Matt

**Comment by ravindravmw** [comment]
Yes. There will be an alternative and supported solution provided in the next release of open-vm-tools.

FWIW, checking the guest customization status by looking at the presence of '/tmp/.vmware-deploy.Done' file is not officially supported.

**Comment by divad** [comment]
Thanks, we gave up using the VMware post-installation customisation and wrote our own solution because there was no way to determine if it had ever run (and sometimes it just didn't run at all!).

**Comment by stanguturi** [comment]
> Can you please change open-vm-tools so that it creates this marker file outside of any tmp directory so that PrivateTmp does not affect it, e.g. /var or /etc ?

Fixed in 640bd4f9c012b201ad1d45a131dad2e804f53766 Please check.

**Comment by stanguturi** [comment]
> > Can you please change open-vm-tools so that it creates this marker file outside of any tmp directory so that PrivateTmp does not affect it, e.g. /var or /etc ?
> 
> Fixed in [640bd4f](https://github.com/vmware/open-vm-tools/commit/640bd4f9c012b201ad1d45a131dad2e804f53766) Please check.

In 640bd4f commit, the alternate path /var/run (other than /tmp) is used only for extracting the package. Still, the hardcoded /tmp path is being used for storing the marker files. There is some work that still needs to be done. Re-opening the issue for tracking.

**Comment by stanguturi** [comment]
Fixed in commit 8fe54f5da07f5204c20448ad9a21ba0b62e32e3a Closing the issue.
