### ISSUE TITLE
`/etc/machine-id` not found during customization with RHEL 9 on vSphere 8

### ISSUE THREAD

**Issue by rbriancollins** [vmware/open-vm-tools#724]
### Describe the bug

While cloning from a RHEL 9 template on vSphere 8, customization fails and VM is created with no IP address and network adapter disconnected.
We do not have this issue with RHEL 8 in vSphere 8, nor does it occur with RHEL 9 in vSphere 7.

### Reproduction steps

1. Initiate clone of VM from a RHEL 9 template (in our case, via Ansible 2.15.3 using the `vmware_guest` module).
2. After VM is cloned in vCenter, VM has no network.
3. Login to VM console in vCenter, view `/var/log/vmware-imc/toolsDeployPkg.log` and see error.
...

### Expected behavior

VM is cloned and has network connectivity with assigned IP address.

### Additional context

This process has worked fine with previous versions of RHEL and vSphere.  The only thing that *seems* different here is that our Infrastructure team recently upgraded this particular vCenter to 8.0.2.  Since that time, clones of RHEL 9 fail to customize properly.
Template has `open-vm-tools-12.3.5-2.el9.x86_64`.

**Comment by rbriancollins** [comment]
Additional info: initiating clone directly from inside vCenter and applying a customization spec produces the same result and has the same error in the log file.

**Comment by ruishuangvmw** [comment]
Hi @rbriancollins,
Thank you for reporting,
And can you please provide the customization log details? It should be `/var/log/vmware-gosc/instant_clone_customization.log` when you clone VM and customization.
Please also check the following in your VM template:
1. Checking if there was `/etc/machine-id` in your template. If no such file the customization engine may skip renewing the machine-id after the VM clone.
2. Make sure your VM template has `dbus-uuidgen` .  If no such utility the customization engine can't generate the new machine-id for the cloned VM.

Thanks,

**Comment by rbriancollins** [comment]
Thanks!

1. Have verified template has `/etc/machine-id`
2. Aha!  `dbus-uuidgen` was not present because `dbus-tools` was not installed.  Some recent change in the RHEL ISO appears to have changed this.  We can install `dbus-tools` from the official repos but not from the RHEL 9.4 ISO.

After installing `dbus-tools` during Packer post-build, our RHEL 9 image issue is resolved.
Still not sure why this is not an issue in our other datacenter, where the image also did not include that package, but I am glad we got it sorted out.
Thank you for the help!
