### ISSUE TITLE
Preferred solution to mount Shared Folders at boot

### ISSUE THREAD

**Issue by lovette** [vmware/open-vm-tools#726]
### Is your feature request related to a problem? Please describe.

I'm standing up a new install of Rocky Linux 9.4 in a VMware Fusion Virtual Machine. 

For many years now, I've been installing *open-vm-tools* with *dnf* then using the method outlined in [KB article 316336](https://knowledge.broadcom.com/external/article/316336/enabling-hgfs-shared-folders-on-fusion-o.html) to mount Shared Folders to `/mnt/hgfs`.

This time however the mount unit failed with the error:

    mount: /mnt/hgfs: wrong fs type, bad option, bad superblock on vmhgfs-fuse, missing codepage or helper program, or other error.

After many hours of trial and error, I stumbled on the culprit: the *fuse* package is not installed, only *fuse3*.

### Describe the solution you'd like

Two solutions that resolve the issue:

1. `dnf install fuse`
2. Change the unit file `[Mount]` option `Type` from `fuse` to `fuse3`

I'm not a domain expert on FUSE, so am curious if one solution is preferable to the other.

### Additional context

Thanks!

**Comment by lousybrit** [comment]
Hi there,

Thanks for reporting.
Either method should be fine. Installing the fuse component has been the expected option. As you mention, the KB should be updated for newer releases with fuse3.

In a terminal window, you run the command :
vmhgfs-fuse --enabled
It should report "HGFS FUSE client needs FUSE environment" if the fuse component is missing from the environment.
If everything is good, it will report "HGFS FUSE client enabled". 

Steve

**Comment by lovette** [comment]
Thanks for the quick response. I'll make note of the `--enabled` environment check. Since *open-vm-tools* pulls in *fuse3* as a dependency it should be rare for FUSE to be missing altogether. Since fuse3 is the future, I'll set `Type=fuse3` going forward!
