### ISSUE TITLE
Clipboard not working on Ubuntu

### ISSUE THREAD

**Issue by kmcorbett** [vmware/open-vm-tools#733]
### Describe the bug

I run Ubuntu 22.04 (LTS) under VMware Fusion Pro on Mac OS Sonoma 14.5. I followed the instructions to install `open-vm-tools `and `open-vm-tools-desktop`. AFAICT the services are running, but copy & paste functionality between the host and guest OS is not working.

There are other issues for other OS, but I can't tell if what I'm seeing is related.

### Reproduction steps

1. Login to Ubuntu
2. Copy and paste any text from/to _eg_ terminal or Emacs within Ubuntu (using Ctrl-C / Ctrl-Y)
3. Attempt to paste in a Mac app _eg_ terminal or Emacs within Mac OS (using menu Paste, not Emacs kill-ring)
...
Host OS clipboard has not been updated. Paste does not reflect change in the clipboard from guest OS.

### Expected behavior

Copy and paste should work seamlessly with _open-vm-tools_. 

### Additional context

I have not tested other integration features (file-sharing or drag-and-drop) because I don't know what is expected. I do know that 1) the clipboard works seamlessly using Parallels Desktop (plus file sharing) and 2) this used to work in VMware Fusion (older versions of Fusion with VMware tools from them)

**Comment by kmcorbett** [comment]
This shows that the `open-vm-tools service` is running. Are there other services I need to enable? I did install `fuse` per a recommendation from another problem report.

<img width="836" alt="image" src="https://github.com/user-attachments/assets/edf14aca-9030-4811-8c1d-87e42d293dae">

**Comment by vmwkruti1111** [comment]
Hi, 
Can you please tell us, 
Which VMware Fusion version installed on the host ? and also open-vm-tools version running inside the guest?

**Comment by kmcorbett** [comment]
> Hi, Can you please tell us, Which VMware Fusion version installed on the host ? and also open-vm-tools version running inside the guest?

VMware Fusion Professional Version 13.5.2 (23775688)

<img width="836" alt="image" src="https://github.com/user-attachments/assets/ba85bd3f-604a-4aef-893b-cad98f19bb43">

**Comment by kmcorbett** [comment]
Copy & paste are working now! All I did was uninstall both packages, reinstall, and reboot. Now I see the packages,

I set up File Sharing / Shared Folders. I'm unsure where to look for the shared folder(s) in the guest OS.  I'll look that up and see if that's working.
