### ISSUE TITLE
Cannot cut/paste to/from VMWare Remote Console on RHEL Linux VM

### ISSUE THREAD

**Issue by stevestet** [vmware/open-vm-tools#745]
### Describe the bug

I have configured the required settings to enable cut/paste and even installed the "open-vm-tools-desktop" package but cut/paste does not work, version details below:-
VM OS is RHEL 7.9 (Maipo) Kernel 3.10.0-1160.123.1.el7.x86_64
VMWare Tools versions:-
open-vm-tools 11.0.5 Rel 3.el7_9.9
open-vm-tools-desktop 11.0.5 Rel 3.el7_9.9

### Reproduction steps

1. Configure VM settings as below:-
2. isolation.tools.copy.disable = FALSE
3. isolation.tools.paste.disable = FALSE
4. solation.tools.setGUIOptions.enable  = TRUE
5. Installed additional package open-vm-tools-desktop
6. Powered OFF/ON the VM
...

### Expected behavior

To be able to cut/paste to/from the VM VMWare VMRC Remote Console

**Comment by PaTHml** [comment]
Several things missing to help here:
  - ESXi or Workstation or Fusion version.
  - - - If Workstation or Fusion the host OS information.
  - When you say "installed additional package open-vm-tools-desktop", this raises the questions: Are you running a desktop? and what's the window manager in use?

We likely need to make sure the vmusr process started on user login.  That is also dependent if there are multiple user login on that vm.  The process is started only for the first user to login as only one instance of the process will be allowed to run.

Something like:
> ps -aux | grep vmusr

Should yield a single process like:
/usr/bin/vmtoolsd -n vmusr --blockFd 3 --uinputFd 4

For the logged in user.  If it's running for a different user or not running, that would be part of the issue seen.

**Comment by stevestet** [comment]
Hi there, thank you for the reply and also apologies I should have been more specific, this is a RHEL Linux ESXi hosted VM, I installed  open-vm-tools-desktop just in case (but quite unnecessarily) to see if that allowed us to cut/paste but it did not. I specifically wanted to be able to paste our very long passwords in at the VMRC login prompt but have today been advised by VMware that this is not possible in a VMRC Console as per the design, makes sense for Security reasons I suppose, thanks again for responding and I will close this issue now, btw we did have the vmtoolsd service running.

**Comment by PaTHml** [comment]
Thank you for the follow up.
