### ISSUE TITLE
Ubuntu Guest OS not show full version

### ISSUE THREAD

**Issue by mattyx0011** [vmware/open-vm-tools#749]
### Is your feature request related to a problem? Please describe.

The Ubuntu Guest OS does not display its full version (such as 16.04, 18.04, 20.04, etc.) on VMware ESXi 7.0.3 with VMware Tools version 10361. Currently, I need to gather statistics on the Ubuntu version counts across all VMs on the ESXi host.

Since using lsb_release on each VM one by one is too time-consuming, I’m wondering if there is a way to find the Ubuntu version via VMware Tools commands or by modifying some configuration, so I can obtain this information more efficiently.

If  have any information available, please don't hesitate to share. Thank you very much.

### Describe the solution you'd like

  display full version

**Comment by rprabhud** [comment]
Hi,
You will find the version and other information about the guest OS as part of guest variable "guestInfo.detailed.data" in VM Advanced Setting.

**Comment by mattyx0011** [comment]
> Hi, You will find the version and other information about the guest OS as part of guest variable "guestInfo.detailed.data" in VM Advanced Setting.

Thank you for your response.
![image](https://github.com/user-attachments/assets/1d451a5c-073b-40f4-b80d-a185655ee01f)
Based on the information you provided regarding the variable "guestInfo.detailed.data," it seems that support requires ESXi 8.0.2 and VMware Tools version 11.2.0 or higher.

Is upgrading the only solution? I did not see this parameter in ESXi 7.0.3 with VMware Tools 10.3. Thank you for your help!

**Comment by rprabhud** [comment]
Yes VMTools version 11.2.0 or higher is needed for "guestInfo.detailed.data".
I am able to see it on ESXi 7.0.3 for Ubuntu-20.04.2 with VMTools 11.3.0

**Comment by rprabhud** [comment]
Ubuntu versions such as 16.04, 18.04, 20.04, etc. should be running open-vm-tools. Are your Ubuntu guests running VMTools 10361 (10361 is 10.3.25 Tar Tools and not open-vm-tools)?

**Comment by mattyx0011** [comment]
> Ubuntu versions such as 16.04, 18.04, 20.04, etc. should be running open-vm-tools. Are your Ubuntu guests running VMTools 10361 (10361 is 10.3.25 Tar Tools and not open-vm-tools)?

Thank you for your explanation it has truly saved me as a beginner. I now understand where the issue lies. I have successfully upgraded to version 11.3 and can see the guestInfo.detailed.data. I am currently working towards manually installing it on each Ubuntu machine. Thank you once again.
