### ISSUE TITLE
/usr/lib64/libvmtools.so.0: undefined symbol: intf_open

### ISSUE THREAD

**Issue by ghidu** [vmware/open-vm-tools#75]
I've been installing open vm tools for a long time in RedHat. Lately I noticed in vcenter the warning "VMware Tools is not installed..." and trying to "Shutdown Down Guest OS" would throw "Cannot shut down the guest operating system. The virtual machine is not running VMware Tools.". I am now using RedHat 7.2 (I don't know if this happened in RedHat 7.1) with open-vm-tools-9.10.2-4.el7.x86_64.
Checking the status of vmtoolsd service I noticed the following:
 /usr/bin/vmtoolsd: symbol lookup error: /usr/lib64/libvmtools.so.0: undefined symbol: intf_open
vmtoolsd.service: main process exited, code=exited, status=127/n/a

**Comment by ravindravmw** [comment]
intf_open is provided by libdnet. Probably, your system does not have libdnet? Could you please run 'ldd' on libvmtools.so and share the output you get?

**Comment by ghidu** [comment]
$ldd /usr/lib64/libvmtools.so.0
	linux-vdso.so.1 =>  (0x00007ffc239a9000)
	libdnet.so.1 => /opt/dell/srvadmin/lib64/libdnet.so.1 (0x00007eff24f8e000)
	librt.so.1 => /lib64/librt.so.1 (0x00007eff24d86000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007eff24a4e000)
	libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007eff24650000)
	libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007eff242d7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007eff240ba000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007eff23eb6000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007eff23c49000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007eff23861000)
	libc.so.6 => /lib64/libc.so.6 (0x00007eff234a0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007eff2546e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007eff2328a000)
	libdsupt.so.1 => /opt/dell/srvadmin/lib64/libdsupt.so.1 (0x00007eff22ff9000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007eff22cf0000)
	libm.so.6 => /lib64/libm.so.6 (0x00007eff229ee000)
	libicudata.so.50 => /lib64/libicudata.so.50 (0x00007eff21419000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007eff211cd000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007eff20ee8000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007eff20ce3000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007eff20ab1000)
	libz.so.1 => /lib64/libz.so.1 (0x00007eff2089b000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007eff2068b000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007eff20487000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007eff2026d000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007eff20047000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007eff1fde6000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007eff1fbc0000)

$ldd /usr/lib64/libvmtools.so.0.0.0
	linux-vdso.so.1 =>  (0x00007ffe8d9ab000)
	libdnet.so.1 => /opt/dell/srvadmin/lib64/libdnet.so.1 (0x00007f7e20c95000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f7e20a8d000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f7e20755000)
	libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007f7e20357000)
	libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007f7e1ffde000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7e1fdc1000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7e1fbbd000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f7e1f950000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f7e1f568000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7e1f1a7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7e21175000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7e1ef91000)
	libdsupt.so.1 => /opt/dell/srvadmin/lib64/libdsupt.so.1 (0x00007f7e1ed00000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f7e1e9f7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7e1e6f5000)
	libicudata.so.50 => /lib64/libicudata.so.50 (0x00007f7e1d120000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f7e1ced4000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f7e1cbef000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f7e1c9ea000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f7e1c7b8000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f7e1c5a2000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f7e1c392000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f7e1c18e000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f7e1bf74000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f7e1bd4e000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f7e1baed000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f7e1b8c7000)

Thanks for you interest in my issue

**Comment by ravindravmw** [comment]
> libdnet.so.1 => /opt/dell/srvadmin/lib64/libdnet.so.1 (0x00007eff24f8e000)

Why this library is not under system path /lib64? I'm suspecting this path is not configured properly. What do you get from following commands?

$ ls /etc/ld.so.conf.d/
$ cat /etc/ld.so.conf.d/*
$ ldconfig -p | grep dnet

Even /opt/dell/srvadmin/lib64/libdsupt.so.1 has the same problem. Any reason why you are not using the libraries provided by Red Hat?

**Comment by ghidu** [comment]
We are using a modified (in house) Red Hat 7.2 ISO

**$ ls /etc/ld.so.conf.d/**
kernel-3.10.0-327.4.4.el7.x86_64.conf  
srvadmin-deng.conf         
srvadmin-idrac.conf            
srvadmin-omacore.conf   
srvadmin-rac5.conf     
srvadmin-storelib.conf
mariadb-x86_64.conf                    
srvadmin-hapi-x86_64.conf  
srvadmin-isvc.conf             
srvadmin-omcommon.conf  
srvadmin-realssd.conf  
wireshark.conf
raidcfg.conf                           
srvadmin-idrac7.conf       
srvadmin-itunnelprovider.conf  
srvadmin-rac4.conf      
srvadmin-storage.conf

**$cat /etc/ld.so.conf.d/***
Placeholder file, no vDSO hwcap entries used in this kernel.
/usr/lib64/mysql
/opt/dell/toolkit/bin
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64/openmanage
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64/srvadmin-idrac7
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64/srvadmin-idrac
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64/srvadmin-isvc
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64/openmanage
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64/openmanage
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64/openmanage
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64/openmanage
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64
/opt/dell/srvadmin/lib64/openmanage
/opt/dell/srvadmin/lib64/openmanage/smpop
/opt/dell/srvadmin/lib64
/usr/local/lib64

**$ ldconfig -p | grep dnet**
	libdnet.so.1 (libc6,x86-64) => /opt/dell/srvadmin/lib64/libdnet.so.1
	libdnet.so (libc6,x86-64) => /opt/dell/srvadmin/lib64/libdnet.so

**Comment by ravindravmw** [comment]
Could you please gather output of following command?

$ nm -D --defined-only /opt/dell/srvadmin/lib64/libdnet.so.1 | grep intf

**Comment by ghidu** [comment]
Hi Kumar,
No output for that command

**Comment by ravindravmw** [comment]
Thanks. So, you have a libdnet which is pretty useless.

I'm not sure if we can do anything here. You need to either get a good libdnet from your vendor (seems to be Dell?) or use the libdnet available from Red Hat. On RHEL system, using libdnet from Red Hat might make more sense, but it is up to you to choose whatever is better for your case.

**Comment by ghidu** [comment]
Hi Ravin,
I have a machine with the same OS installed and the same open vm tools, open-vm-tools-9.10.2-4.el7.x86_64 that doesn't show the same issue. There is a difference in the way these machines are installed (manually vs automatically). Here is something I noticed that is different:
# ldconfig -p | grep dnet
	libdnet.so.1 (libc6,x86-64) => /opt/dell/srvadmin/lib64/libdnet.so.1
	libdnet.so.1 (libc6,x86-64) => /lib64/libdnet.so.1
	libdnet.so (libc6,x86-64) => /opt/dell/srvadmin/lib64/libdnet.so

**Comment by ravindravmw** [comment]
You do have system library libdnet.so.1 on a working system. This is supposed to work. You need to figure out why don't have this library /lib64/libdnet.so.1 on non-working system. Who deleted it? You need to work through your VM setup/creation procedures to find this one.

My conclusion on this issue is, /opt/dell/srvadmin/lib64/libdnet.so.1 is not a useful version of libdnet because it does not expose the necessary APIs like intf_open. I think you have two ways to fix it, either get a good version of /opt/dell/srvadmin/lib64/libdnet.so.1 from someone who built it for you or get the Red Hat's version of libdnet in /lib64/libdnet.so.1 which is guaranteed to work.

There is nothing to be fixed in open-vm-tools for this.

**Comment by ghidu** [comment]
Thank you for the help Ravindra (apologies for writing your name wrong before)
I've added libdnet to the kickstart and it is working.

**Comment by stanguturi** [comment]
> Thank you for the help Ravindra (apologies for writing your name wrong before)
> I've added libdnet to the kickstart and it is working.

Thanks for trying out and confirming. Closing this issue.
