### ISSUE TITLE
Guest OS operation failed with Red Hat or CentOS VM

### ISSUE THREAD

**Issue by smartmaster** [vmware/open-vm-tools#78]
for example VMware vSphere PowerCLI "Copy-VMGuestFile" cmdlet failed as the attached screenshot.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**PowerCLI D:\> Copy-VMGuestFile -Source D:\text.txt -Destination /tmp/ -VM ############# -LocalToGuest -GuestUser root -GuestPassword ############
Copy-VMGuestFile : 3/24/2016 15:18:05    Copy-VMGuestFile        The remoteserver returned an error: (500) Internal Server Error.
At line:1 char:1
+ Copy-VMGuestFile -Source D:\text.txt -Destination /tmp/ -VM yanyu08-RHEL7
-Local ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-VMGuestFile], ViError
    + FullyQualifiedErrorId : Client20_VmGuestServiceImpl_UploadFileToGuest_Up
   loadError,VMware.VimAutomation.ViCore.Cmdlets.Commands.CopyVMGuestFile**

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

vCenter version 6.0.0
ESXi version: 5.5.0
VM: RHEL 7

**Comment by stanguturi** [comment]
The '(500) Internal Server Error' is returned by the 'Management agent' running in the ESX machine. Without the log files, we don't have any idea why the error is returned. Also, the HTTP error is not related to 'VMware Tools'. Please contact the VMware Technical Support team and provide the complete set of log files. They will provide more information.

Thanks.

**Comment by smartmaster** [comment]
Thanks for your reply. We will open a VMware Support Request ticket for the problem.

**Comment by smartmaster** [comment]
We tried ESX server 6.0 update 2, it can work with Red Hat or CentOS VM. it should be an ESX issue instead of a VMTools one. so close it.
