### ISSUE TITLE
bug in log.h

### ISSUE THREAD

**Issue by diablitozzz** [vmware/open-vm-tools#8]
You have bug in log.h
See diff - http://pkgs.fedoraproject.org/cgit/open-vm-tools.git/commit/?id=0225d0b56bab2860df28808f8541bf5f34ab6b62

**Comment by ravindravmw** [comment]
This has been fixed in the latest stable branch stable-9.10.x, https://github.com/vmware/open-vm-tools/blob/stable-9.10.x/open-vm-tools/lib/include/vmware/tools/log.h.

Master branch is not updated yet. We need to fix that too.
