### ISSUE TITLE
open-vm-tools does not resize the display on Kali 2016.1

### ISSUE THREAD

**Issue by NoahAndrews** [vmware/open-vm-tools#80]
I'm having the same problem as @Melab in #54, but on Kali Linux. In addition, `vmtoolsd -n vmusr` is running, and has loaded `libresolutionSet.so`.

**Comment by NoahAndrews** [comment]
Ah. For anyone else having a similar issue with VMWare Workstation, make sure you select "Autofit guest" under View -> Autosize.

**Comment by bleepblipbloop** [comment]
I'm having the same problem with Kali Linux 2016.1 as well, but selecting "Autofit guest" doesn't resolve it for me.  The OS is updated to current, I have open-vm-tools and open-vm-tools-desktop installed, I'm running `vmtoolsd -n vmusr --blockFd 3`, and it's loaded `libresolutionSet.so`.  I'm running on ESXi 6.0 and the Kali VM is a version 11 virtual machine.  Autofit window doesn't work for me.  If I attempt to click "Fit guest now", I can still see the mouse pointer on the screen but clicking no longer works.  Attempting to change the resolution manually from within the settings control panel locks up the screen entirely, in which case I no longer even have a mouse pointer.

**Comment by bleepblipbloop** [comment]
...And of course after two days of looking at resources to try to solve this problem, the VERY NEXT LINK that I click after making this post fixes it for me.  For anyone else who might be having this issue, upping the video memory from 4 MB to 32 MB in the VM settings fixed it for me, as detailed here:  https://forums.kali.org/showthread.php?30917-Resolution-change-fails-on-ESXi-6-0-VM

**Comment by move123456789** [comment]
Thanks for Saying this! IT WORKED :D

Ah. For anyone else having a similar issue with VMWare Workstation, make sure you select "Autofit guest" under View -> Autosize.
--

**Comment by codagus** [comment]
@bleepblipbloop hours and hours.. and the solution wasn't in any command whatsoever, UNBELIEVABLE! THXS!
