### ISSUE TITLE
Compilation failed on kernel >=4.5

### ISSUE THREAD

**Issue by Grief** [vmware/open-vm-tools#82]
This is the reason: https://github.com/torvalds/linux/commit/32fb378437a1d716e72a442237d7ead1f435ecf0

These are the errors:

```
/files/oss/open-vm-tools/open-vm-tools/modules/linux/vmhgfs/link.c:65:4: error: unknown field ‘follow_link’ specified in initializer
    .follow_link   = HgfsFollowlink,
    ^
/files/oss/open-vm-tools/open-vm-tools/modules/linux/vmhgfs/link.c:65:21: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    .follow_link   = HgfsFollowlink,
                     ^
/files/oss/open-vm-tools/open-vm-tools/modules/linux/vmhgfs/link.c:65:21: note: (near initialization for ‘HgfsLinkInodeOperations.lookup’)
/files/oss/open-vm-tools/open-vm-tools/modules/linux/vmhgfs/link.c:67:4: error: unknown field ‘put_link’ specified in initializer
    .put_link      = HgfsPutlink,
    ^
/files/oss/open-vm-tools/open-vm-tools/modules/linux/vmhgfs/link.c:67:21: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    .put_link      = HgfsPutlink,
                     ^
/files/oss/open-vm-tools/open-vm-tools/modules/linux/vmhgfs/link.c:67:21: note: (near initialization for ‘HgfsLinkInodeOperations.create’)
```

**Comment by ravindravmw** [comment]
vmhgfs is not supposed to be used for kernel 4.0.0 or later.

Please see https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/configure.ac#L1053.

How are you getting this built and is there any particular reason you are trying to build it for newer kernel?

**Comment by Grief** [comment]
I just would like to mount host directories in guest ubuntu 16.04 with kernel updated to 4.5.2 (but the same issue exists for kernel 4.4 which is default in ubuntu 16.04)

**Comment by ravindravmw** [comment]
You shouldn't need vmhgfs driver for kernel > 4.2. Distros with newer kernel versions should use the new implementation that is Fuse based instead of relying on vmhgfs driver.

Isn't mounting host directories working without this driver for you? If not, you will have to take this up with Ubuntu.

**Comment by Grief** [comment]
Got it. Thanks for the explanations

**Comment by jasonblewis** [comment]
the upshot of this is that to share folders between host and guest, you can use vmhgfs-fuse.

see https://gist.github.com/vadviktor/5aa034bbee6e53d26b70
and
https://wiki.archlinux.org/index.php/VMware/Installing_Arch_as_a_guest#Shared_Folders_with_vmhgfs-fuse_utility

**Comment by Grief** [comment]
I missed that issue in the list of the issues opened by me.
@jasonblewis I didn't say thanks, sorry for that. Your link to the gist was very helpful.
@ravindravmw I think the issue can be closed then.

**Comment by stanguturi** [comment]
> @ravindravmw I think the issue can be closed then.

Closing. Thanks.
