### ISSUE TITLE
open-vm-tools won't get installed on guest

### ISSUE THREAD

**Issue by ChazyTheBest** [vmware/open-vm-tools#84]
I'm using Manjaro (Arch Linux) and I always have had trouble getting the tools on the guest.

I don't remember the last time that vmware workstation (player) installed the tools without throwing any error. The typical "can't connect to server", that no matter how much you search for a solution, it's a dead end.

I've already tried opening vmplayer with permissions. In any case I get the following error:

```
There were one or more problems downloading components:

VMware Tools for Windows 95, 98, Me, and NT:
Could not find component on update server. Contact VMware Support or your system administrator.

VMware Tools for Windows 2000 or later:
Could not find component on update server. Contact VMware Support or your system administrator.

VMware Tools for Linux:
Could not find component on update server. Contact VMware Support or your system administrator.

VMware Tools for Solaris:
Could not find component on update server. Contact VMware Support or your system administrator.

VMware Tools for FreeBSD:
Could not find component on update server. Contact VMware Support or your system administrator.

VMware Tools for Netware:
Could not find component on update server. Contact VMware Support or your system administrator
```

I tried removing and readding the cd/dvd drive and the option is enabled but again the error.

I've installed all dependencies (fuse, gtkmm, linux-headers and ncurses5-compat-libs) and the tools: open-vm-tools and linux44-open-vm-tools-modules but vmplayer is not detecting them...

**Comment by stanguturi** [comment]
Need the workstation/player log files to figure out the root cause. Anyway, the error seems to be coming from Workstation/player product itself and not from 'VMware Tools'. You can post the question in the following VMTN communities for better suggestions.

https://communities.vmware.com/community/vmtn/workstation/
https://communities.vmware.com/community/vmtn/player/

Thanks
