### ISSUE TITLE
Disconnected NIC after guest customization

### ISSUE THREAD

**Issue by tmonning** [vmware/open-vm-tools#86]
Hi,

from time to time (about every 10th deployment on average) we experience a NIC being disconnected - in a Linux virtual machine with two NICs - after the guest customization took place. We were able to reproduce that behavior with several virtual machine templates with different open-vm-tools versions (although it happens randomly). The only thing that seemed to have helped (for now) is switching to another vcenter with different esx-hosts (2 esx hosts each, they are all configured exactly the same way). There is no error or anything suspicious in the logs (esx logs and vm logs). You just can see, that the NICs get disconnected during the customization phase and they usually come up again after the initial reboot, except for the failed ones of course.

The following table shows the tested configurations:
The left most column shows the used OS distribution.
**Failed** means, that there was at least one disconnected NIC, **guest tools** mentions the used repository for the installed open-vm-tools and **custom SW** means, that custom software has been installed (otherwise it's a plain image from the according distribution site). All NICs were using the _e1000_ adapter.
```
                   custom SW    guest tools          Failed
=========================================================                                                               
On VCSA-2
---------------------------------------------------------                                                               
openSuSE 13.2           x       SLES 11 SP3             x
openSuSE 13.2           x       SLES 11 SP4             x
openSuSE 13.2                   SLES 11 SP4             x
openSuSE 13.2                   openSuSE 13.2 (OSS)     x
openSuSE 13.2                   openSuSE 13.2           x
openSuSE 42.1                   openSuSE 42.1           x
Ubuntu Server 16.04             Ubuntu                  x
SLES 12 SP1                     SLES12 SP1              x

On VCSA-4
---------------------------------------------------------
SLES 12 SP1                     SLES12 SP1
openSuSE 42.1                   openSuSE 42.1
openSuSE 13.2           x       SLES 11 SP4

```
The esx hosts are all running on _VMware ESXi 6.0.0 build-3568940_.
Is there any known issue with the open-vm-tools, that would explain that behavior or does anyone know if this is even related to the open-vm-tools? Do we need to have a look somewhere else?

**Comment by aneverov4vmw** [comment]
Hi,

The fact that NICs are disconnected during guest customization is the normal behavior implemented to avoid IP conflicts. However, NICs should be normally enabled back at the end of customization unless there is some error. 

The in-guest logs are located in /var/log/vmware-imc/. Could you please share at least one set of log files (normally just a single one) for each of the cases of success and failure for the same VM (or at least the same OS distribution)? Feel free to remove any data you might find sensitive.

Are these VMs by any chance experiencing DRS or some other kind of vMotion?

**Comment by tmonning** [comment]
We solved the problem already. The reason why this occurred is still unknown but we found out, that we used portgroups with ephemeral port-binding, which - according to vmware's documentation - is not supported for productive environments. We now switched to static port-bindings and the disconnected NIC problem has never been seen again since.
