### ISSUE TITLE
Enable the hgfs shared for Ubuntu 16.04 LTS Xenial

### ISSUE THREAD

**Issue by suntong** [vmware/open-vm-tools#87]
In #44, it says

> With open-vm-tools 10.0, there is no need to build vmhgfs module anymore. This is not required because HGFS implementation is FUSE based in 10.0.

But having installed the official open-vm-tools under Ubuntu 16.04 LTS Xenial, I'm still unable to see the hgfs shared from the host. Anything that I've missed? 

    $ apt-cache policy open-vm-tools
    open-vm-tools:
      Installed: 2:10.0.7-3227872-2ubuntu2
      Candidate: 2:10.0.7-3227872-2ubuntu2
      Version table:
     *** 2:10.0.7-3227872-2ubuntu2 500
    ...
    
    $ apt-cache search hgfs | wc 
          0       0       0

    $ df
    Filesystem     1K-blocks    Used Available Use% Mounted on
    udev              481988       0    481988   0% /dev
    tmpfs              99852    4548     95304   5% /run
    /dev/sda1       31863728 1699600  28522504   6% /
    tmpfs             499248       0    499248   0% /dev/shm
    tmpfs               5120       0      5120   0% /run/lock
    tmpfs             499248       0    499248   0% /sys/fs/cgroup
    
    $ uname -a 
    Linux uname 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Thanks

**Comment by suntong** [comment]
Found out that I missed `open-vm-tools-desktop` (Ref https://bugs.launchpad.net/ubuntu/+source/open-vm-tools/+bug/1551558), but that doesn't install for Ubuntu 16.04 LTS Xenial -- https://bugs.launchpad.net/ubuntu/+source/open-vm-tools/+bug/1513531

**Comment by konfer** [comment]
After install the open-vm-tools-desktop, I still can't see the share folder,even can't see the hgfs in the   "mnt" ,so have you meet the same problem and how to solve it .Thank you
