### ISSUE TITLE
Poor performance on OS X Fusion host / Ubuntu 16.04 guest

### ISSUE THREAD

**Issue by marcosscriven** [vmware/open-vm-tools#89]
I'm having terrible trouble using an Ubuntu 16.04 guest, with open-vm-tools installed.
The whole guest desktop constantly hangs, with _kworker_ and _xorg_ threads maxing out, and the graphics card fan going crazy.

Would anyone be able to help me trace the issue here please? I've asked on the VMWare forum, to no avail.

**Comment by oliverkurth** [comment]
Thanks for reporting! A few question: which version of open-vm-tools  do you have installed - is it 10.0.7 ad shipped with Ubuntu? Do you have the open-vm-tools-desktop installed as well? And which version of Fusion are you using?

I will try to reproduce this issue here.

**Comment by oliverkurth** [comment]
Hm, for some reason I thought you were using Fusion, but now  see that you don't mention it. So what OS do you use, and which version of Workstation or Fusion?

**Comment by marcosscriven** [comment]
Hi @oliverkurth - yes I'm using Fusion (in the title of the issue). Full versions for the various components:

- Fusion: Version 8.1.1 (3771013)
- Host: OS X 10.11.4, with 
- Guest: Ubuntu 16.04 Linux albert 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- open-vm-tools-desktop: Version: 2:10.0.7-3227872-2ubuntu1

Examples of things I'm seeing:

- The search panel of Unity desktop opening up visibly in jerky steps
- Slow scrolling in Chrome
- The aforementioned freezing with _kwoker_ and _xorg_ thread issues

Thanks for looking into this

**Comment by marcosscriven** [comment]
@oliverkurth - any luck with this one?

**Comment by oliverkurth** [comment]
Hi Marcos,

do you see the same issue with 3D acceleration turned off?

**Comment by oliverkurth** [comment]
Hi Marcos,
another question: how much graphics memory did you allocate for the VM? One of our developers suggests to use 1GB minimum. Also, could you please give us the output of the command:

glxinfo | grep OpenGL

Thanks,
Oliver

**Comment by oliverkurth** [comment]
@marcosscriven , I'll close this issue for now. Feel free to reopen when you have more information (see my last questions).

**Comment by bartmcleod** [comment]
I have a similar experience with Ubuntu 17.10 guest in Fusion.

I must say it hasn't always been bad. I guess it depends on which vm tools are installed and if they are up to date. I am unclear whether I need to use the open vm tools or the VMware vm tools. I installed the latter.
