### ISSUE TITLE
[PATCH] ./configure can't find my C++ compiler but it's there

### ISSUE THREAD

**Issue by andy-js** [vmware/open-vm-tools#92]
This patch attempts to resolve two issues.  Firstly you're using AC_CHECK_TOOLS to check for CXX which is unnecessary because AC_PROG_CXX already looks for the prefixed version of the command. AC_CHECK_PROG is sufficient.   Secondly the check fails if the CXX is set to an absolute path (something AC_PROG_CXX handles fine).  This change also handles the case when CXX has some arguments appended to the end of it (again AC_PROG_CXX can deal with this too).

<pre>
diff --git a/open-vm-tools/configure.ac b/open-vm-tools/configure.ac
index fd2bdc7..7e1511a 100644
--- a/open-vm-tools/configure.ac
+++ b/open-vm-tools/configure.ac
@@ -811,7 +811,17 @@ AC_ARG_WITH([icu],
             [with_icu=yes])
 
 if test "$have_x" = "yes" -o "$with_icu" = "yes"; then
-   AC_CHECK_TOOL([have_cxx], [$CXX], [no])
+   # AC_CHECK_PROG fails to locate CXX if it's set to an absolute
+   # path and it includes arguments, which is often the case when
+   # cross compling.  Try to handle this case directly.
+   case "$CXX" in
+      [/*])
+         AS_IF(test -x ${CXX%% *}, [have_cxx=yes], [have_cxx=no])
+         ;;
+      [*])
+         AC_CHECK_PROG([have_cxx], [$CXX], [yes], [no])
+         ;;
+   esac
    if test "$have_cxx" = "no"; then
       AC_MSG_ERROR([C++ compiler not found. Make sure you have a C++ compiler installed or configure without X11 (using --without-x) and without ICU (using --without-icu).])
    fi
</pre>

**Comment by oliverkurth** [comment]
Thanks @andy-js for that patch.

Can you please create a pull request? You should then get a request to sign a CLA agreement.

Also, can you provide steps to reproduce the issue that is being fixed?

Thanks,
Oliver

**Comment by andy-js** [comment]
I'll see what I can do.  Setting CXX to something like this should be enough to recreate the issue:

<pre>
CXX="/usr/bin/g++ -m64"
</pre>

**Comment by oliverkurth** [comment]
Fixed with 6b1ef0ef99f34011da3f5383414eeedf81c59d3b . Thank you!
