### ISSUE TITLE
Fails to build with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by bzed** [vmware/open-vm-tools#96]
Forwarded from http://bugs.debian.org/828476

OpenSSL 1.1.0 is about to released.  During a rebuild of all packages using
OpenSSL this package fail to build.  A log of that build can be found at:
https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/open-vm-tools_10.0.7-3227872-2_amd64-20160529-1501

On https://wiki.openssl.org/index.php/1.1_API_Changes you can see various of the
reasons why it might fail.  There are also updated man pages at
https://www.openssl.org/docs/manmaster/ that should contain useful information.

**Comment by lousybrit** [comment]
I have filed a bug and we will address this issue.

Thanks

**Comment by bzed** [comment]
Hi @lousybrit! Are there any news on this? It would be nice to have a patch soon-ish.
Thanks!

**Comment by lousybrit** [comment]
The bug I filed was fixed internally on July 27th and also validated by our testing group.

It will be in the upcoming releases of the VMware tools which are due very very soon.
(Not allowed to give any dates unfortunately, so that is as specific as I can be.)

Thanks for your reporting and patience on this issue.
Steve

**Comment by bzed** [comment]
@oliverkurth @ravindravmw @lousybrit 
Well, you could just publich an appropriate patch. If you want to see open-vm-tools in the next Debian release, I need a fix within the next 3-4 weeks. I appreciated that you take care of my bug reports, but waiting for a new release is something that won't work in the long run. Also it would be nice to be able to fix bugs in the open-vm-tools version that was released with Debian - and for that we *need* a proper way to understand changes - which means proper commits.

**Comment by oliverkurth** [comment]
@bzed is this still an issue?

**Comment by bzed** [comment]
@oliverkurth builds perfectly fine with 1.1 and 1.0. As the migration kinda failed in Debian and 1.0 is still the default while 1.1 is available, I'll stick with 1.0 for the version in stretch and for backports I'll start to use 1.1
