### ISSUE TITLE
Support for Unity mode is dropped, right?

### ISSUE THREAD

**Issue by antitoxic** [vmware/open-vm-tools#97]
I'm going crazy running ton of searches and can't find a definitive answer on whether open-vm-tools has dropped support for Unity mode in linux guests. 

I know VMware dropped support in Workstation 12 **but** I'm using Player v7 **and** so far I successfully had unity mode with guest additions 9.9.3-2759765 (windows host, linux guest, test with both openbox and mutter) with minor things like having no preview in Alt-Tab on windows

Can anyone please clarifify is support for Unity mode dropped in open-vm-tools?

Tagging recent contributors: @dyno @ravindravmw

**Comment by ravindravmw** [comment]
AFAIK, Unity was never part of open-vm-tools. What am I missing?

**Comment by antitoxic** [comment]
I don't know. It was part of VMware guest tools but they have started deprecating them and displaying reccomending open-vm-tools instead.

Plus there are search results in the codebase matching "unity": https://github.com/vmware/open-vm-tools/search?utf8=%E2%9C%93&q=unity

**Comment by antitoxic** [comment]
I think this confirms it: https://github.com/vmware/open-vm-tools/issues/54#issuecomment-166232958
