### ISSUE TITLE
Build fails on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by g40** [vmware/open-vm-tools#98]
Autoconf is not quite my thing so I've no good idea where this is being set up.

```
-o .libs/libdndcp_la-dndClipboard.o
cc1: error: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [-Werror]
```

```
@ubuntu:~/src/open-vm-tools/open-vm-tools$ gcc --version
gcc (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413

@ubuntu:~/src/open-vm-tools/open-vm-tools$ uname -a
Linux ubuntu 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ravindravmw** [comment]
What is open-vm-tools version you are trying to build?

**Comment by g40** [comment]
master

**Comment by oliverkurth** [comment]
@g40, is his still an issue for you? Can you please try the current master, and try building?

If it still does not work for you, please describe the steps that you used. These steps should work fine on Ubuntu:

autoreconf -i
./configure --without-kernel-modules
make

For dependencies, you may need to install these packages:
apt-get install -y build-essential
apt-get build-dep -y open-vm-tools
apt-get install -y libmspack-dev libssl-dev libxerces-c-dev libxml-security-c-dev libprocps4-dev

**Comment by oliverkurth** [comment]
@g40, I am closing this issue because there is no response, and we had several releases since this was reported. Feel free to reopen if this is still an issue with current master or the latest release.
